### ISSUE TITLE
Issues compiling with OpenJDK 7 in FreeBSD 10.1

### ISSUE THREAD

**Issue by rayrapetyan** [apache/incubator-druid#1352]
You may get following errors compiling Druid with OpenJDK7:

```
-------------------------------------------------------------------------------
Test set: io.druid.server.router.JavaScriptTieredBrokerSelectorStrategyTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.01 sec <<< FAILURE! - in io.druid.server.router.JavaScriptTieredBrokerSelectorStrategyTest
testSerde(io.druid.server.router.JavaScriptTieredBrokerSelectorStrategyTest)  Time elapsed: 0.008 sec  <<< ERROR!
java.lang.NullPointerException: null
        at io.druid.server.router.JavaScriptTieredBrokerSelectorStrategy.<init>(JavaScriptTieredBrokerSelectorStrategy.java:50)
        at io.druid.server.router.JavaScriptTieredBrokerSelectorStrategyTest.<init>(JavaScriptTieredBrokerSelectorStrategyTest.java:37)

testGetBrokerServiceName(io.druid.server.router.JavaScriptTieredBrokerSelectorStrategyTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.NullPointerException: null
        at io.druid.server.router.JavaScriptTieredBrokerSelectorStrategy.<init>(JavaScriptTieredBrokerSelectorStrategy.java:50)
        at io.druid.server.router.JavaScriptTieredBrokerSelectorStrategyTest.<init>(JavaScriptTieredBrokerSelectorStrategyTest.java:37)
```

This is a known bug which seems has been fixed in Ubuntu (https://bugs.launchpad.net/ubuntu/+source/openjdk-7/+bug/982501).

However, in FreeBSD you have to use OpenJDK 8:

```
setenv JAVA_HOME /usr/local/openjdk8/
mvn clean package
```

Then compilation will succeed.

**Comment by xvrl** [comment]
thank you @rayrapetyan, we don't currently run or test on OpenJDK, and we only have limited experience with it. It seems OpenJDK does not include a javascript engine by default like Oracle JDK does. Glad to know it works with OpenJDK 8 though.

**Comment by xvrl** [comment]
@rayrapetyan given that openjdk 7 doesn't provide a javascript scriptengine, I think we should simply document that when running OpenJDK, at least version 8 is required, but that we have not tested this extensively.

**Comment by rayrapetyan** [comment]
Thanks for a quick response! Yes, that's the best thing to do here - just add a note into doc.

**Comment by rayrapetyan** [comment]
Btw I may also add here that "wikipedia" example is up and running on my home PC for last 5 days with no issues, so at least a basic functionality is fine on FreeBSD 10.1 + OpenJDK 8.
From time to time I'm getting:
```
2015-05-13T17:53:06,686 ERROR [ApiDaemon] com.ircclouds.irc.api.AbstractMessageReader - Error reading from connection
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:1.7.0_80]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:1.7.0_80]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.7.0_80]
	at sun.nio.ch.IOUtil.read(IOUtil.java:197) ~[?:1.7.0_80]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:384) ~[?:1.7.0_80]
	at com.ircclouds.irc.api.comms.SocketChannelConnection.read(SocketChannelConnection.java:36) ~[irc-api-1.0-0011.jar:?]
	at com.ircclouds.irc.api.AbstractMessageReader.available(AbstractMessageReader.java:47) [irc-api-1.0-0011.jar:?]
	at com.ircclouds.irc.api.AbstractApiDaemon.run(AbstractApiDaemon.java:28) [irc-api-1.0-0011.jar:?]
```
exceptions in a RT node logs, but it's a connection issue not related to the software part. I'll do much more extensive tests with a high-load in the future on this configuration.

**Comment by drcrallen** [comment]
Is this PC connected via wireless or direct ethernet cable?

**Comment by rayrapetyan** [comment]
Direct ethernet through a router + cable modem
