### ISSUE TITLE
Transient error - Unable to push events to task / NoBrokersAvailableException

### ISSUE THREAD

**Issue by mark1900** [apache/incubator-druid#1448]
I continue to get the following exceptions similar to below and I believe it is more than my server configuration.

```
2015-06-17T12:20:05.365-0400 c.m.t.f.FutureRetry$ [WARN] Transient error, will try again in 285 ms
java.io.IOException: Unable to push events to task: index_realtime_kafka-storm-tranquility-druid-topology-test-datasource_2015-06-17T16:00:00.000Z_0_0 (status = TaskRunning)
...
com.twitter.finagle.NoBrokersAvailableException: No hosts are available for druid:firehose:kafka-storm-tranquility-druid-topology-test-datasource-16-0000-0000
        at com.twitter.finagle.NoStacktrace(Unknown Source) ~[na:na]
```

Please see the following forum threads:
- [Tranquility DruidBeam - NoBrokersAvailableException: No hosts are available](https://groups.google.com/forum/#!topic/druid-user/UT5JNSZqAuk)
- [Transient errors during creating new tasks](https://groups.google.com/forum/#!topic/druid-user/LKqvur7wWmo)

My current server configuration is outlined here:

 [https://github.com/mark1900/druid-sandbox/tree/master/kafka-storm-tranquility-druid-topology-test](https://github.com/mark1900/druid-sandbox/tree/master/kafka-storm-tranquility-druid-topology-test)

**Comment by skilledmonster** [comment]
This is exactly I am seeing as well? Is there a resolution on this one?

**Comment by bohemia420** [comment]
@skilledmonster  hahaha and How did you solve this one now ? well I found that the overlord and service names must match. but not working as of now.

**Comment by skilledmonster** [comment]
@bohemia420  - In my case, I noticed the exception has nothing to do with the underlying issue. It was simply a mis-configured spec in my case.

**Comment by bauerctu** [comment]
I have the same problem too:

[WARN] 2016-07-25 16:18:04,735 com.metamx.tranquility.finagle.FutureRetry$ ? - Transient error, will try again in 206 ms
java.io.IOException: Unable to push events to task: index_realtime_MiddletiersBillingProd_2016-07-25T16:00:00.000+08:00_3_0 (status = TaskRunning)
	at com.metamx.tranquility.druid.DruidBeam$$anonfun$4$$anonfun$apply$4$$anonfun$apply$6$$anonfun$apply$7$$anonfun$apply$3$$anonfun$applyOrElse$2.apply(DruidBeam.scala:160)
	at com.metamx.tranquility.druid.DruidBeam$$anonfun$4$$anonfun$apply$4$$anonfun$apply$6$$anonfun$apply$7$$anonfun$apply$3$$anonfun$applyOrElse$2.apply(DruidBeam.scala:146)
	at com.twitter.util.Future$$anonfun$map$1$$anonfun$apply$6.apply(Future.scala:863)
	at com.twitter.util.Try$.apply(Try.scala:13)
	at com.twitter.util.Future$.apply(Future.scala:90)
	at com.twitter.util.Future$$anonfun$map$1.apply(Future.scala:863)
	at com.twitter.util.Future$$anonfun$map$1.apply(Future.scala:863)
	at com.twitter.util.Future$$anonfun$flatMap$1.apply(Future.scala:824)
	at com.twitter.util.Future$$anonfun$flatMap$1.apply(Future.scala:823)
	at com.twitter.util.Promise$Transformer.liftedTree1$1(Promise.scala:100)
	at com.twitter.util.Promise$Transformer.k(Promise.scala:100)
	at com.twitter.util.Promise$Transformer.apply(Promise.scala:110)
	at com.twitter.util.Promise$Transformer.apply(Promise.scala:91)
	at com.twitter.util.Promise$$anon$2.run(Promise.scala:345)
	at com.twitter.concurrent.LocalScheduler$Activation.run(Scheduler.scala:186)
	at com.twitter.concurrent.LocalScheduler$Activation.submit(Scheduler.scala:157)
	at com.twitter.concurrent.LocalScheduler.submit(Scheduler.scala:212)
	at com.twitter.concurrent.Scheduler$.submit(Scheduler.scala:86)
	at com.twitter.util.Promise.runq(Promise.scala:331)
	at com.twitter.util.Promise.updateIfEmpty(Promise.scala:642)
	at com.twitter.util.Promise.update(Promise.scala:615)
	at com.twitter.util.Promise.setValue(Promise.scala:591)
	at com.twitter.concurrent.AsyncQueue.offer(AsyncQueue.scala:76)
	at com.twitter.finagle.transport.ChannelTransport.handleUpstream(ChannelTransport.scala:45)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:108)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:194)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.handler.codec.http.HttpClientCodec.handleUpstream(HttpClientCodec.java:92)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142)
	at com.twitter.finagle.channel.ChannelStatsHandler.messageReceived(ChannelStatsHandler.scala:86)
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142)
	at com.twitter.finagle.channel.ChannelRequestStatsHandler.messageReceived(ChannelRequestStatsHandler.scala:35)
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.twitter.finagle.NoBrokersAvailableException: No hosts are available for druid:firehose:MiddletiersBillingProd-08-0003-0000
	at com.twitter.finagle.NoStacktrace(Unknown Source)

**Comment by cheleb** [comment]
You should take a look at overlord logs, you have some indexes tasks running ?

**Comment by dijingran** [comment]
@cheleb I've got the same error , and yes i have a index task running.  I looked at overlord logs, and there was nothing relavent. 

This error only  occured after restart the tranquility.

**Comment by cheleb** [comment]
Look like your middlemanager (data node) are exhausted (no more index slot available)

**Comment by narendrasfo** [comment]
I am also  getting same error after restarting tranquility 

Sep 12, 2016 9:22:18 PM com.twitter.finagle.Init$$anonfun$1 apply$mcV$sp
INFO: Finagle version 6.31.0 (rev=50d3bb0eea5ad3ed332111d707184c80fed6a506) built at 20151203-164135
2016-09-12 21:22:19,161 [ClusteredBeam-ZkFuturePool-ae2959c9-8f0c-4379-88d3-c4841aeaa647] INFO  c.m.c.s.net.finagle.DiscoResolver - Updating instances for service[druid:overlord] to Set()
2016-09-12 21:22:19,278 [ClusteredBeam-ZkFuturePool-ae2959c9-8f0c-4379-88d3-c4841aeaa647] INFO  c.m.t.finagle.FinagleRegistry - Created client for service: disco!druid:overlord
2016-09-12 21:22:19,359 [ClusteredBeam-ZkFuturePool-ae2959c9-8f0c-4379-88d3-c4841aeaa647] WARN  c.m.tranquility.finagle.FutureRetry$ - Transient error, will try again in 16,843 ms
com.twitter.finagle.NoBrokersAvailableException: No hosts are available for disco!druid:overlord, Dtab.base=[], Dtab.local=[]
	at com.twitter.finagle.NoStacktrace(Unknown Source) ~[na:na]
2016-09-12 21:22:19,370 [ClusteredBeam-ZkFuturePool-ae2959c9-8f0c-4379-88d3-c4841aeaa647] INFO  com.metamx.common.scala.control$ - Creating druid indexing task (service = druid:overlord): {

**Comment by z50hz1988** [comment]
> I am also getting same error after restarting tranquility
> 
> Sep 12, 2016 9:22:18 PM com.twitter.finagle.Init$$anonfun$1 apply$mcV$sp
> INFO: Finagle version 6.31.0 (rev=50d3bb0eea5ad3ed332111d707184c80fed6a506) built at 20151203-164135
> 2016-09-12 21:22:19,161 [ClusteredBeam-ZkFuturePool-ae2959c9-8f0c-4379-88d3-c4841aeaa647] INFO c.m.c.s.net.finagle.DiscoResolver - Updating instances for service[druid:overlord] to Set()
> 2016-09-12 21:22:19,278 [ClusteredBeam-ZkFuturePool-ae2959c9-8f0c-4379-88d3-c4841aeaa647] INFO c.m.t.finagle.FinagleRegistry - Created client for service: disco!druid:overlord
> 2016-09-12 21:22:19,359 [ClusteredBeam-ZkFuturePool-ae2959c9-8f0c-4379-88d3-c4841aeaa647] WARN c.m.tranquility.finagle.FutureRetry$ - Transient error, will try again in 16,843 ms
> com.twitter.finagle.NoBrokersAvailableException: No hosts are available for disco!druid:overlord, Dtab.base=[], Dtab.local=[]
> at com.twitter.finagle.NoStacktrace(Unknown Source) ~[na:na]
> 2016-09-12 21:22:19,370 [ClusteredBeam-ZkFuturePool-ae2959c9-8f0c-4379-88d3-c4841aeaa647] INFO com.metamx.common.scala.control$ - Creating druid indexing task (service = druid:overlord): {

have you solved this problem ? I got the same problem just like yours, and I connected my zookeeper server ls the path '/druid/discovery/druid:overlord', the result is '[]' , it's empty, and I check the log of overlord, there is some error about metadata storage service connection refused, I changed Druid metadata storage type from derby to mysql and restart all components; but the value of '/druid/discovery/druid:overlord'  path is still '[]' ; do you have any idea ? thanks a lot.
