### ISSUE TITLE
SQLMetadataStorageActionHandlerTest.java fails intermittently

### ISSUE THREAD

**Issue by rasahner** [apache/incubator-druid#1536]
SQLMetadataStorageActionHandlerTest failed, then passed on a rebuild.

**Comment by fjy** [comment]
Any logs on what failed?

**Comment by rasahner** [comment]
Running io.druid.metadata.SQLMetadataStorageActionHandlerTest
Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.358 sec <<< FAILURE! - in io.druid.metadata.SQLMetadataStorageActionHandlerTest
testLocks(io.druid.metadata.SQLMetadataStorageActionHandlerTest)  Time elapsed: 0.799 sec  <<< ERROR!
org.skife.jdbi.v2.exceptions.CallbackFailedException: org.skife.jdbi.v2.exceptions.UnableToCreateStatementException: java.sql.SQLSyntaxErrorException: Table/View 'ENTRIES' does not exist. [statement:"SELECT payload FROM entries WHERE id = :id", located:"SELECT payload FROM entries WHERE id = :id", rewritten:"SELECT payload FROM entries WHERE id = ?", arguments:{ positional:{}, named:{id:'ABC123'}, finder:[]}]
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.compile.FromBaseTable.bindTableDescriptor(Unknown Source)
	at org.apache.derby.impl.sql.compile.FromBaseTable.bindNonVTITables(Unknown Source)
	at org.apache.derby.impl.sql.compile.FromList.bindTables(Unknown Source)
	at org.apache.derby.impl.sql.compile.SelectNode.bindNonVTITables(Unknown Source)
	at org.apache.derby.impl.sql.compile.DMLStatementNode.bindTables(Unknown Source)
	at org.apache.derby.impl.sql.compile.DMLStatementNode.bind(Unknown Source)
	at org.apache.derby.impl.sql.compile.CursorNode.bindStatement(Unknown Source)
	at org.apache.derby.impl.sql.GenericStatement.prepMinion(Unknown Source)
	at org.apache.derby.impl.sql.GenericStatement.prepare(Unknown Source)
	at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.prepareInternalStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement42.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver42.newEmbedPreparedStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(Unknown Source)
	at org.skife.jdbi.v2.DefaultStatementBuilder.create(DefaultStatementBuilder.java:48)
	at org.skife.jdbi.v2.SQLStatement.internalExecute(SQLStatement.java:1276)
	at org.skife.jdbi.v2.Query.fold(Query.java:172)
	at org.skife.jdbi.v2.Query.first(Query.java:267)
	at org.skife.jdbi.v2.Query.first(Query.java:259)
	at io.druid.metadata.SQLMetadataStorageActionHandler$3.withHandle(SQLMetadataStorageActionHandler.java:173)
	at io.druid.metadata.SQLMetadataStorageActionHandler$3.withHandle(SQLMetadataStorageActionHandler.java:164)
	at org.skife.jdbi.v2.DBI.withHandle(DBI.java:259)
	at io.druid.metadata.SQLMetadataStorageActionHandler$12.call(SQLMetadataStorageActionHandler.java:481)
	at com.metamx.common.RetryUtils.retry(RetryUtils.java:38)
	at io.druid.metadata.SQLMetadataStorageActionHandler.retryingHandle(SQLMetadataStorageActionHandler.java:494)
	at io.druid.metadata.SQLMetadataStorageActionHandler.getEntry(SQLMetadataStorageActionHandler.java:162)
	at io.druid.metadata.SQLMetadataStorageActionHandler.insert(SQLMetadataStorageActionHandler.java:129)
	at io.druid.metadata.SQLMetadataStorageActionHandlerTest.testLocks(SQLMetadataStorageActionHandlerTest.java:216)

**Comment by drcrallen** [comment]
yep, still seeing this:

```org.skife.jdbi.v2.exceptions.CallbackFailedException: org.skife.jdbi.v2.exceptions.UnableToCreateStatementException: java.sql.SQLSyntaxErrorException: Table/View 'ENTRIES' does not exist. [statement:"SELECT payload FROM entries WHERE id = :id", located:"SELECT payload FROM entries WHERE id = :id", rewritten:"SELECT payload FROM entries WHERE id = ?", arguments:{ positional:{}, named:{id:'ABC123'}, finder:[]}]```
