### ISSUE TITLE
transient build failure in IncrementalIndexTest.testConcurrentAddRead

### ISSUE THREAD

**Issue by himanshug** [apache/incubator-druid#1577]
io.druid.segment.data.IncrementalIndexTest.testConcurrentAddRead[0]

```
Error Message

Did not hit concurrency, please try again

Stacktrace

java.lang.AssertionError: Did not hit concurrency, please try again
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.assertTrue(Assert.java:41)
    at io.druid.segment.data.IncrementalIndexTest.__CLR4_0_0rbszzpkkz(IncrementalIndexTest.java:362)
    at io.druid.segment.data.IncrementalIndexTest.testConcurrentAddRead(IncrementalIndexTest.java:222)

Standard Output

2015-07-29T13:34:10,732 WARN [Finalizer] io.druid.collections.StupidPool - Not closed!  Object was[java.nio.HeapByteBuffer[pos=0 lim=10485760 cap=10485760]]. Allowing gc to prevent leak.
2015-07-29T13:34:10,732 WARN [Finalizer] io.druid.collections.StupidPool - Not closed!  Object was[java.nio.HeapByteBuffer[pos=0 lim=10485760 cap=10485760]]. Allowing gc to prevent leak.
2015-07-29T13:34:10,732 WARN [Finalizer] io.druid.collections.StupidPool - Not closed!  Object was[java.nio.HeapByteBuffer[pos=0 lim=10485760 cap=10485760]]. Allowing gc to prevent leak.
```

**Comment by mkobit** [comment]
+1. I see the same error after checking out the [`0.8.0`](https://github.com/druid-io/druid/tree/0.8.0) branch, and trying to build multiple times.
