### ISSUE TITLE
query hangs on broker with Jetty 9.2.13 version

### ISSUE THREAD

**Issue by nishantmonu51** [apache/incubator-druid#1807]
- Attached query when sent to the router hangs on bard 
  [groupBy_large.txt](https://github.com/druid-io/druid/files/9452/groupBy_large.
-  removing the filter from the query i.e reduce the size of serialized query makes it working. 
- from initial exploration it seems router AsyncProxy is being wierd with the latest jetty version when forwarding the query request to the broker and the broker keeps waiting for more content from the router. 
- reverting the Jetty version to 9.2.5 seems to fix it. 

Stack Trace where it hangs - 

```
"qtp1045677229-47@4865" daemon prio=5 tid=0x2f nid=NA waiting
  java.lang.Thread.State: WAITING
      at sun.misc.Unsafe.park(Unsafe.java:-1)
      at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
      at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
      at org.eclipse.jetty.util.SharedBlockingCallback$Blocker.block(SharedBlockingCallback.java:219)
      at org.eclipse.jetty.server.HttpInputOverHTTP.blockForContent(HttpInputOverHTTP.java:66)
      at org.eclipse.jetty.server.HttpInput$1.waitForContent(HttpInput.java:476)
      at org.eclipse.jetty.server.HttpInput.read(HttpInput.java:121)
      - locked <0x18d7> (a org.eclipse.jetty.server.HttpInputOverHTTP)
      at com.fasterxml.jackson.core.json.ByteSourceJsonBootstrapper.ensureLoaded(ByteSourceJsonBootstrapper.java:489)
      at com.fasterxml.jackson.core.json.ByteSourceJsonBootstrapper.detectEncoding(ByteSourceJsonBootstrapper.java:126)
      at com.fasterxml.jackson.core.json.ByteSourceJsonBootstrapper.constructParser(ByteSourceJsonBootstrapper.java:215)
      at com.fasterxml.jackson.core.JsonFactory._createParser(JsonFactory.java:1191)
      at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:753)
      at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2207)
      at io.druid.server.QueryResource.doPost(QueryResource.java:134)
      at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.lang.reflect.Method.invoke(Method.java:497)
      at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
```

creating this issue to investigate it further.

**Comment by nishantmonu51** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=479299
