### ISSUE TITLE
Cannot find indexer service

### ISSUE THREAD

**Issue by Walter0507** [apache/incubator-druid#1924]
Hi all:
I got a error when doing batch ingestion. The task has been submitted successfully, but show a "indexer service not found" error. The log shows maybe the zookeeper configuration is not correct? I use the default configuration(configures the zk host only). So could you give some advise how to check this?

Here below is the error message:

2015-11-06T06:33:31,595 ERROR [main] io.druid.curator.discovery.ServerDiscoverySelector - No server instance found
2015-11-06T06:33:31,595 WARN [main] io.druid.indexing.common.actions.RemoteTaskActionClient - Exception submitting action for task[index_test_2015-11-06T06:32:30.501Z]
java.io.IOException: Failed to locate service uri
        at io.druid.indexing.common.actions.RemoteTaskActionClient.submit(RemoteTaskActionClient.java:91) [druid-indexing-service-0.8.1.jar:0.8.1]
        at io.druid.indexing.common.task.AbstractFixedIntervalTask.isReady(AbstractFixedIntervalTask.java:67) [druid-indexing-service-0.8.1.jar:0.8.1]
        at io.druid.indexing.worker.executor.ExecutorLifecycle.start(ExecutorLifecycle.java:120) [druid-indexing-service-0.8.1.jar:0.8.1]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_85]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_85]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_85]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_85]
        at com.metamx.common.lifecycle.Lifecycle$AnnotationBasedHandler.start(Lifecycle.java:331) [java-util-0.27.0.jar:?]
        at com.metamx.common.lifecycle.Lifecycle.addMaybeStartHandler(Lifecycle.java:236) [java-util-0.27.0.jar:?]
        at com.metamx.common.lifecycle.Lifecycle.addMaybeStartManagedInstance(Lifecycle.java:182) [java-util-0.27.0.jar:?]
        at io.druid.guice.LifecycleScope$1.get(LifecycleScope.java:57) [druid-api-0.3.9.jar:0.8.1]
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41) [guice-4.0-beta.jar:?]
        at com.google.inject.internal.InjectorImpl$3$1.call(InjectorImpl.java:1005) [guice-4.0-beta.jar:?]
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1051) [guice-4.0-beta.jar:?]
        at com.google.inject.internal.InjectorImpl$3.get(InjectorImpl.java:1001) [guice-4.0-beta.jar:?]
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1040) [guice-4.0-beta.jar:?]
        at io.druid.cli.CliPeon.run(CliPeon.java:225) [druid-services-0.8.1.jar:0.8.1]
        at io.druid.cli.Main.main(Main.java:91) [druid-services-0.8.1.jar:0.8.1]
Caused by: com.metamx.common.ISE: Cannot find instance of indexer to talk to!
        at io.druid.indexing.common.actions.RemoteTaskActionClient.getServiceInstance(RemoteTaskActionClient.java:165) ~[druid-indexing-service-0.8.1.jar:0.8.1]
        at io.druid.indexing.common.actions.RemoteTaskActionClient.submit(RemoteTaskActionClient.java:86) ~[druid-indexing-service-0.8.1.jar:0.8.1]
        ... 17 more

**Comment by fjy** [comment]
Please post this in the user groups.

**Comment by meixinyun** [comment]
I  got the same problem, is there a solution ？
