### ISSUE TITLE
UnknownHostException during run example server/Wikipedia

### ISSUE THREAD

**Issue by uover82** [apache/incubator-druid#2283]
Hi,

I'm currently receiving the following when running the Wikipedia example (./run_example_server.sh):

java.net.UnknownHostException: 15g1d2r8: unknown error
    at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[?:1.8.0_66]
    at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928) ~[?:1.8.0_66]
    at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323) ~[?:1.8.0_66]
    at java.net.InetAddress.getAllByName0(InetAddress.java:1276) ~[?:1.8.0_66]
    at java.net.InetAddress.getAllByName(InetAddress.java:1192) ~[?:1.8.0_66]
    at java.net.InetAddress.getAllByName(InetAddress.java:1126) ~[?:1.8.0_66]
    at java.net.InetAddress.getByName(InetAddress.java:1076) ~[?:1.8.0_66]
    at io.druid.segment.realtime.firehose.WikipediaIrcDecoder.decodeMessage(WikipediaIrcDecoder.java:196) [druid-server-0.8.2.jar:0.8.2]
    at io.druid.segment.realtime.firehose.IrcInputRowParser.parse(IrcInputRowParser.java:87) [druid-server-0.8.2.jar:0.8.2]
    at io.druid.segment.realtime.firehose.IrcFirehoseFactory$4.hasMore(IrcFirehoseFactory.java:195) [druid-server-0.8.2.jar:0.8.2]
    at io.druid.segment.realtime.RealtimeManager$FireChief.runFirehose(RealtimeManager.java:342) [druid-server-0.8.2.jar:0.8.2]
    at io.druid.segment.realtime.RealtimeManager$FireChief.run(RealtimeManager.java:264) [druid-server-0.8.2.jar:0.8.2]
2016-01-18T13:33:24,500 ERROR [chief-wikipedia[0]] io.druid.segment.realtime.firehose.WikipediaIrcDecoder - invalid ip [15g1d2r8]

Let me know of any issues/questions/thoughts - thanks!

John

**Comment by fjy** [comment]
@uover82 Are you by any chance behind a corporate firewall?

**Comment by uover82** [comment]
Hi Fangjin - thanks for getting back.

I'm currently not behind a corporate firewall - home office on a Mac, OSX/ druid v.0.8.2

Perhaps OSX firewall contributing?

Thanks

John

**Comment by fjy** [comment]
@uover82 Hmm, okay, will ask some people to take a look. You can also try http://imply.io/docs/latest/quickstart for a quickstart that will probably be easier to get things up and running with Druid a bit faster than the current set of tutorials

**Comment by uover82** [comment]
Great - thanks for this tip :-) I'll look into this.

/run_example_server.sh seems to be a long-running process on my mac (>24 hrs) w/o other errors - seem reasonable?

Thanks for your help!

John
