### ISSUE TITLE
Transient failure on RemoteTaskRunnerTest.testStatusRemoved

### ISSUE THREAD

**Issue by drcrallen** [apache/incubator-druid#2373]
```
Tests run: 16, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 33.32 sec <<< FAILURE! - in io.druid.indexing.overlord.RemoteTaskRunnerTest
testStatusRemoved(io.druid.indexing.overlord.RemoteTaskRunnerTest)  Time elapsed: 6.46 sec  <<< ERROR!
java.util.NoSuchElementException: null
    at com.google.common.collect.Iterators$1.next(Iterators.java:80)
    at io.druid.indexing.overlord.RemoteTaskRunnerTest.testStatusRemoved(RemoteTaskRunnerTest.java:337)
```

**Comment by himanshug** [comment]
its frequency has increased recently, I have seen it fail a couple of times.

**Comment by nishantmonu51** [comment]
i wonder if this might be related to zk issue, bumping up version might help.

**Comment by himanshug** [comment]
another failure stacktrace ...

```
testStatusRemoved(io.druid.indexing.overlord.RemoteTaskRunnerTest)  Time elapsed: 21.225 sec  <<< ERROR!
java.util.concurrent.TimeoutException: Timeout waiting for task.
	at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:269)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:96)
	at io.druid.indexing.overlord.RemoteTaskRunnerTest.testStatusRemoved(RemoteTaskRunnerTest.java:316)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Results :
Tests in error: 
  RemoteTaskRunnerTest.testStatusRemoved:316 » Timeout Timeout waiting for task.
```

**Comment by jihoonson** [comment]
@himanshug the latest failure is 100% reproducible even in my local laptop. Do you have any idea about it?

**Comment by himanshug** [comment]
@jihoonson being reproducible is even better, thanks for quick fix.

**Comment by jihoonson** [comment]
Recently. the same task has been failing frequently.

- https://travis-ci.org/druid-io/druid/jobs/336714990
- https://travis-ci.org/druid-io/druid/jobs/337813434

**Comment by gianm** [comment]
Saw this one recently.

```testStatusRemoved(org.apache.druid.indexing.overlord.RemoteTaskRunnerTest)  Time elapsed: 21.168 sec  <<< ERROR!
java.util.concurrent.TimeoutException: Timeout waiting for task.
	at org.apache.druid.indexing.overlord.RemoteTaskRunnerTest.testStatusRemoved(RemoteTaskRunnerTest.java:315)
```

**Comment by jihoonson** [comment]
Closing this in favor of https://github.com/apache/incubator-druid/issues/6317.
