### ISSUE TITLE
Transient test failure - testSanity(io.druid.curator.inventory.CuratorInventoryManagerTest)

### ISSUE THREAD

**Issue by pjain1** [apache/incubator-druid#2390]
```
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 31.385 sec <<< FAILURE! - in io.druid.curator.inventory.CuratorInventoryManagerTest
testSanity(io.druid.curator.inventory.CuratorInventoryManagerTest)  Time elapsed: 31.385 sec  <<< ERROR!
org.apache.zookeeper.KeeperException$NodeExistsException: KeeperErrorCode = NodeExists for /container/billy
    at org.apache.zookeeper.KeeperException.create(KeeperException.java:119)
    at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
    at org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:783)
    at org.apache.curator.framework.imps.CreateBuilderImpl$11.call(CreateBuilderImpl.java:720)
    at org.apache.curator.framework.imps.CreateBuilderImpl$11.call(CreateBuilderImpl.java:703)
    at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:107)
    at org.apache.curator.framework.imps.CreateBuilderImpl.pathInForeground(CreateBuilderImpl.java:699)
    at org.apache.curator.framework.imps.CreateBuilderImpl.protectedPathInForeground(CreateBuilderImpl.java:477)
    at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:467)
    at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:44)
    at io.druid.curator.inventory.CuratorInventoryManagerTest.testSanity(CuratorInventoryManagerTest.java:77)
```

**Comment by erikdubbelboer** [comment]
Is this still an issue? I think it can be closed.
