### ISSUE TITLE
HDFS deep storage pulls in hadoop dependencies.

### ISSUE THREAD

**Issue by drcrallen** [apache/incubator-druid#2476]
druid-hdfs-storage pulls in a bunch of hadoop jars as can be seen below:

```
$ ls druid-hdfs-storage/
avro-1.7.4.jar                  commons-math3-3.1.1.jar             hadoop-mapreduce-client-app-2.3.0.jar       hadoop-yarn-server-common-2.3.0.jar
commons-beanutils-1.7.0.jar         commons-net-3.1.jar             hadoop-mapreduce-client-common-2.3.0.jar    jaxb-api-2.2.2.jar
commons-beanutils-core-1.8.0.jar        druid-hdfs-storage-0.9.0-rc2-SNAPSHOT.jar   hadoop-mapreduce-client-core-2.3.0.jar      paranamer-2.3.jar
commons-collections-3.2.1.jar           hadoop-annotations-2.3.0.jar            hadoop-mapreduce-client-jobclient-2.3.0.jar servlet-api-2.5.jar
commons-compress-1.4.1.jar          hadoop-auth-2.3.0.jar               hadoop-mapreduce-client-shuffle-2.3.0.jar   snappy-java-1.0.4.1.jar
commons-configuration-1.6.jar           hadoop-client-2.3.0.jar             hadoop-yarn-api-2.3.0.jar           stax-api-1.0-2.jar
commons-digester-1.8.jar            hadoop-common-2.3.0.jar             hadoop-yarn-client-2.3.0.jar            xmlenc-0.52.jar
commons-httpclient-3.1.jar          hadoop-hdfs-2.3.0.jar               hadoop-yarn-common-2.3.0.jar            xz-1.0.jar
```

This has the potential to interfere with hadoop deployments and also potentially cause hard-to-track dependency problems in the hadoop task isolated classloader.

If possible, it would be really cool if the hdfs deep storage didn't pull in all the hadoop jars, and they were loaded in some other mechanism for use in the hdfs extension.

**Comment by drcrallen** [comment]
I don't have any explicit cases where this causes a problem yet, so I'm not labeling it as anything in particular.

**Comment by ottomata** [comment]
We have problems with this.  We are using Hadoop 2.6.0 from Cloudera, and these dependencies conflict with the ones I am configuring via `hadoopDependencyCoordinates`.

**Comment by fjy** [comment]
@ottomata please see http://druid.io/docs/0.9.0/operations/other-hadoop.html

I think your issue may be different than the one described here

**Comment by ottomata** [comment]
Naw, I've worked around that by setting `-Dhadoop.mapreduce.job.user.classpath.first=true`, so I'm not having explicit Jackson issues.  It's been a few hours since I worked around this issue by replacing the hadoop dependencies in `druid-hdfs-storage` with my versions.  I'll try to get a descriptive error for ya next week (gotta run soon!).

**Comment by drcrallen** [comment]
@jaehc can you list your use case here so we can properly classify and respond to this?

**Comment by tjgiuli** [comment]
Hi, just to mirror some of the discussion from here https://groups.google.com/forum/#!topic/druid-user/kZVNO0MgCs4:

We have a CDH 5.3.3 Hadoop cluster and have set up our extensions such that we use the CDH 5.3.3 jars for the HDFS extension as well as the default hadoop coordinates.  Batch reingestion works well after setting `hadoop.mapreduce.job.user.classpath.first=true`, but we have intermittent realtime ingestion task failures.  We replicate our realtime ingestion tasks (2 total) and one of the replicas will fail with the following exception:

```
2016-07-05T00:15:03,160 ERROR [delta_netflow-2016-07-04T23:00:00.000Z-persist-n-merge] io.druid.segment.realtime.plumber.RealtimePlumber - Failed to persist merged index[delta_netflow]: {class=io.druid.segment.realtime.plumber.RealtimePlumber, exceptionType=class org.apache.hadoop.ipc.RemoteException, exceptionMessage=No lease on /druid/delta_netflow/20160704T230000.000Z_20160705T000000.000Z/2016-07-04T23_00_05.235Z/0/index.zip (inode 18375798): File does not exist. Holder DFSClient_NONMAPREDUCE_-1070421989_1 does not have any open files.
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkLease(FSNamesystem.java:3358)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.completeFileInternal(FSNamesystem.java:3446)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.completeFile(FSNamesystem.java:3416)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.complete(NameNodeRpcServer.java:675)
	at org.apache.hadoop.hdfs.server.namenode.AuthorizationProviderProxyClientProtocol.complete(AuthorizationProviderProxyClientProtocol.java:219)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.complete(ClientNamenodeProtocolServerSideTranslatorPB.java:520)
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:587)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1026)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2013)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2009)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1642)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2007)
, interval=2016-07-04T23:00:00.000Z/2016-07-05T00:00:00.000Z}
org.apache.hadoop.ipc.RemoteException: No lease on /druid/delta_netflow/20160704T230000.000Z_20160705T000000.000Z/2016-07-04T23_00_05.235Z/0/index.zip (inode 18375798): File does not exist. Holder DFSClient_NONMAPREDUCE_-1070421989_1 does not have any open files.
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkLease(FSNamesystem.java:3358)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.completeFileInternal(FSNamesystem.java:3446)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.completeFile(FSNamesystem.java:3416)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.complete(NameNodeRpcServer.java:675)
	at org.apache.hadoop.hdfs.server.namenode.AuthorizationProviderProxyClientProtocol.complete(AuthorizationProviderProxyClientProtocol.java:219)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.complete(ClientNamenodeProtocolServerSideTranslatorPB.java:520)
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:587)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1026)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2013)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2009)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1642)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2007)

	at org.apache.hadoop.ipc.Client.call(Client.java:1411) ~[?:?]
	at org.apache.hadoop.ipc.Client.call(Client.java:1364) ~[?:?]
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:206) ~[?:?]
	at com.sun.proxy.$Proxy63.complete(Unknown Source) ~[?:?]
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.complete(ClientNamenodeProtocolTranslatorPB.java:435) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_67]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_67]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_67]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_67]
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:187) ~[?:?]
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102) ~[?:?]
	at com.sun.proxy.$Proxy64.complete(Unknown Source) ~[?:?]
	at org.apache.hadoop.hdfs.DFSOutputStream.completeFile(DFSOutputStream.java:2164) ~[?:?]
	at org.apache.hadoop.hdfs.DFSOutputStream.close(DFSOutputStream.java:2148) ~[?:?]
	at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.close(FSDataOutputStream.java:72) ~[?:?]
	at org.apache.hadoop.fs.FSDataOutputStream.close(FSDataOutputStream.java:106) ~[?:?]
	at java.util.zip.DeflaterOutputStream.close(DeflaterOutputStream.java:241) ~[?:1.7.0_67]
	at java.util.zip.ZipOutputStream.close(ZipOutputStream.java:360) ~[?:1.7.0_67]
	at com.metamx.common.CompressionUtils.zip(CompressionUtils.java:104) ~[java-util-0.27.7.jar:?]
	at io.druid.storage.hdfs.HdfsDataSegmentPusher.push(HdfsDataSegmentPusher.java:92) ~[?:?]
	at io.druid.segment.realtime.plumber.RealtimePlumber$4.doRun(RealtimePlumber.java:550) [druid-server-0.9.0.jar:0.9.0]
	at io.druid.common.guava.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:42) [druid-common-0.9.0.jar:0.9.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_67]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_67]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_67]
```

We also tried using the stock 2.6.0 Hadoop jars but we get the same error.
