### ISSUE TITLE
Transient test issue RemoteTaskRunnerTest.testWorkerDisabled

### ISSUE THREAD

**Issue by drcrallen** [apache/incubator-druid#2549]
https://travis-ci.org/druid-io/druid/jobs/111808875

`RemoteTaskRunnerTest.testWorkerDisabled:451 expected:<SUCCESS> but was:<FAILED>`

```
testWorkerDisabled(io.druid.indexing.overlord.RemoteTaskRunnerTest)  Time elapsed: 7.076 sec  <<< FAILURE!
java.lang.AssertionError: expected:<SUCCESS> but was:<FAILED>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:144)
    at io.druid.indexing.overlord.RemoteTaskRunnerTest.testWorkerDisabled(RemoteTaskRunnerTest.java:451)
```

**Comment by gianm** [comment]
Saw another failure in the same test, but a different location.

https://travis-ci.org/druid-io/druid/jobs/145708810

```
testWorkerDisabled(io.druid.indexing.overlord.RemoteTaskRunnerTest)  Time elapsed: 1.225 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[]> but was:<[0]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at io.druid.indexing.overlord.RemoteTaskRunnerTest.testWorkerDisabled(RemoteTaskRunnerTest.java:423)
```
