### ISSUE TITLE
The method canAppendrow() of Sink throws NPE

### ISSUE THREAD

**Issue by Hailei** [apache/incubator-druid#2569]
@fjy @guobingkun 
Druid Version: 0.8.2

After hand off segments,Sink throw NPE

> 2016-02-27 01:03:02,796 ERROR i.d.s.r.RealtimeManager [chief-dsp_report[0]] RuntimeException aborted realtime processing[dsp_report]: {class=io.druid.segment.realtime.RealtimeManager, exceptionType=class java.lang.NullPointerException, exceptionMessage=null}
> java.lang.NullPointerException
>         at io.druid.segment.realtime.plumber.Sink.canAppendRow(Sink.java:134) ~[druid-server-0.8.2.jar:0.8.2]
>         at io.druid.segment.realtime.plumber.RealtimePlumber.add(RealtimePlumber.java:205) ~[druid-server-0.8.2.jar:0.8.2]
>         at io.druid.segment.realtime.RealtimeManager$FireChief.runFirehose(RealtimeManager.java:362) ~[druid-server-0.8.2.jar:0.8.2]
>         at io.druid.segment.realtime.RealtimeManager$FireChief.run(RealtimeManager.java:264) [druid-server-0.8.2.jar:0.8.2]

Maybe this is a bug.
Let's look at following code

``` java
 public int add(InputRow row) throws IndexSizeExceededException
  {
    if (currHydrant == null) {
      throw new IAE("No currHydrant but given row[%s]", row);
    }

    synchronized (hydrantLock) {
      IncrementalIndex index = currHydrant.getIndex();
      if (index == null) {
        return -1; // the hydrant was swapped without being replaced
      }
      return index.add(row);
    }
  }

  public boolean canAppendRow()
  {
    synchronized (currHydrant) {
      return currHydrant != null && currHydrant.getIndex().canAppendRow();
    }
  }
```

If currHydrant.getIndex() return null,will throw NPE.
inside add method,you add following check

``` java
  if (index == null) {
        return -1; // the hydrant was swapped without being replaced
      }
```

Why not add similar check to method canAppendRow()?

**Comment by Hailei** [comment]
@fjy 
As I see it,the hydrant that was swapped without being replaced must be the last hydrant in the sink,and this sink already merged.Because if execute persist() always execute sink.swap method to replace first,Only During the merge and push operation ,skip executing sink.swap method,directly execute persistHydrant() method.
It must be said,I don't deploy official release version,In order to do as much as possible not to drop message,change the code of NoopRejectionPolicyFactory base on 0.8.2.

If  add the message before the window period to the sink causes this behavior.
Found following message in the log
>2016-02-27 01:03:00,215 INFO i.d.s.r.p.RealtimePlumber [dsp_report_access_day-2016-02-26T23:00:00.000+08:00-persist-n-merge] Hydrant[FireHydrant{index=io.druid.segment.incremental.OnheapIncrementalIndex@11c39f36, queryable=io.druid.segment.ReferenceCountingSegment@42099b56, count=59}] hasn't swapped yet, swapping. Sink[Sink{interval=2016-02-26T23:00:00.000+08:00/2016-02-27T00:00:00.000+08:00, schema=DataSchema{dataSource='dsp_report_access_day', parser={parseSpec={format=tsv, listDelimiter=|, timestampSpec={column=timestamp, format=millis}, columns=[timestamp, position, sell_position, p_count], dimensionsSpec={dimensions=[position, sell_position], dimensionExclusions=[]}}}, aggregators=[LongSumAggregatorFactory{fieldName='p_count', name='count'}], granularitySpec=io.druid.segment.indexing.granularity.UniformGranularitySpec@7e4cd909}}]

I think it is useful.
