### ISSUE TITLE
cant use metadata-init with postgresql

### ISSUE THREAD

**Issue by pdeva** [apache/incubator-druid#2587]
Druid version: 0.8.3

i see there is a metadata-init command used in the docker based integration tests.
i tried using it by setting metadata.type=postgresql, but i get this error:

```
Feb 28, 2016 11:51:39 PM org.hibernate.validator.internal.util.Version <clinit>
INFO: HV000001: Hibernate Validator 5.1.3.Final
2016-02-28T23:51:39,852 INFO [main] io.druid.guice.JsonConfigurator - Loaded class[class io.druid.guice.ExtensionsConfig] from props[druid.extensions.] as [ExtensionsConfig{searchCurrentClassloader=true, coordinates=[], defaultVersion='0.8.3', localRepository='C:\Users\P
/.m2/repository', remoteRepositories=[https://repo1.maven.org/maven2/, https://metamx.artifactoryonline.com/metamx/pub-libs-releases-local]}]
2016-02-28T23:51:40,746 INFO [main] io.druid.guice.JsonConfigurator - Loaded class[class io.druid.server.metrics.DruidMonitorSchedulerConfig] from props[druid.monitoring.] as [io.druid.server.metrics.DruidMonitorSchedulerConfig@76911385]
2016-02-28T23:51:40,754 INFO [main] io.druid.guice.JsonConfigurator - Loaded class[class io.druid.server.metrics.MonitorsConfig] from props[druid.monitoring.] as [MonitorsConfig{monitors=[]}]
Exception in thread "main" com.google.inject.ProvisionException: Guice provision errors:

1) Unknown provider[postgresql] of Key[type=io.druid.metadata.MetadataStorageConnector, annotation=[none]], known options[[derby]]
  at io.druid.guice.PolyBind.createChoiceWithDefault(PolyBind.java:86)
  while locating io.druid.metadata.MetadataStorageConnector

1 error
        at com.google.inject.internal.InjectorImpl$3.get(InjectorImpl.java:1014)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1040)
        at io.druid.cli.CreateTables.run(CreateTables.java:108)
        at io.druid.cli.Main.main(Main.java:99)
```

I added the postgres extension in `config/_common/common.runtime.properties`.

```
 druid.extensions.coordinates=[\"io.druid.extensions:postgresql-metadata-storage"]
```

I get a similar result when trying with mysql. 

Looking at the error msg it seems only derby will work (which is strange since the integration test does use mysql).

**Comment by xvrl** [comment]
@pdeva how are you running the metadata-init command? what classpath are you setting?
From the logs it looks like the extension never gets loaded, so you must be missing something.

Also in your config, you are escaping one of the quotes, but not the other, maybe that is one of the issues?
