### ISSUE TITLE
Nullpoint exception in segment merge and can not be hand off

### ISSUE THREAD

**Issue by redlion99** [apache/incubator-druid#2826]
The version of druid I'm using is 0.8.3

I'm using tranquility to push event to druid with 3 partitions.

Here is the task log:

2016-04-13T08:50:04,518 INFO [cl_events-2016-04-12T00:00:00.000+08:00-persist-n-merge] io.druid.segment.IndexIO$DefaultIndexIOHandler - Processing file[time_LITTLE_ENDIAN.drd]
Exception in thread "plumber_merge_0" java.lang.NullPointerException
    at java.util.TreeMap.compare(TreeMap.java:1188)
    at java.util.TreeMap.put(TreeMap.java:531)
    at java.util.TreeSet.add(TreeSet.java:255)
    at java.util.AbstractCollection.addAll(AbstractCollection.java:342)
    at java.util.TreeSet.addAll(TreeSet.java:312)
    at io.druid.segment.IndexIO$DefaultIndexIOHandler.convertV8toV9(IndexIO.java:862)
    at io.druid.segment.IndexMerger.makeIndexFiles(IndexMerger.java:957)
    at io.druid.segment.IndexMerger.merge(IndexMerger.java:351)
    at io.druid.segment.IndexMerger.persist(IndexMerger.java:196)
    at io.druid.segment.IndexMerger.persist(IndexMerger.java:161)
    at io.druid.segment.IndexMerger.persist(IndexMerger.java:138)
    at io.druid.segment.realtime.plumber.RealtimePlumber.persistHydrant(RealtimePlumber.java:972)
    at io.druid.segment.realtime.plumber.RealtimePlumber$4.doRun(RealtimePlumber.java:480)
    at io.druid.common.guava.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:40)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
2016-04-13T08:51:07,053 INFO [plumber_merge_1] io.druid.segment.realtime.plumber.RealtimePlumber - Segment[DataSegment{size=51561, shardSpec=LinearShardSpec{partitionNum=0}, metrics=[count, duration, userCount, newSession, returningSession], dimensions=[a, acceptEmail, acceptSMS, aid, attr1, attr2, channelAccount, channelName, channelType, city, class, createFrom, createFromName, createMethod, customerId, customerName, domain, emailVerified, event, eventGroup, gender, hosting, inbound, isEmployee, isFirstTry, isMember, isReferrer, lastUpdated, m, mobileVerified, nickName, notAcceptEmail, notAcceptSMS, pageId, path, refDomain, refScore, rootDomain, source, subdivision, targetId, targetName, tenantId, token, triggerByCustomer, updateMethod, userId, utma, utmb, uuid], version='2016-04-13T00:00:02.588+08:00', loadSpec={type=ali, path=drd1/cl_events/20160413T000000.000+0800_20160414T000000.000+0800/2016-04-13T00_00_02.588+08_00/0/index.zip}, interval=2016-04-13T00:00:00.000+08:00/2016-04-14T00:00:00.000+08:00, dataSource='cl_events', binaryVersion='9'}] matches sink[Sink{interval=2016-04-13T00:00:00.000+08:00/2016-04-14T00:00:00.000+08:00, schema=DataSchema{dataSource='cl_events', parser={type=map, parseSpec={format=json, timestampSpec={column=timestamp, format=iso, missingValue=null}, dimensionsSpec={dimensionExclusions=[duration, sessionDepth, returningSession, score, amount, newSession, userCount], spatialDimensions=[]}}}, aggregators=[CountAggregatorFactory{name='count'}, LongSumAggregatorFactory{fieldName='duration', name='duration'}, LongSumAggregatorFactory{fieldName='userCount', name='userCount'}, LongSumAggregatorFactory{fieldName='newSession', name='newSession'}, LongSumAggregatorFactory{fieldName='returningSession', name='returningSession'}], granularitySpec=io.druid.segment.indexing.granularity.UniformGranularitySpec@773f0d3a}}] on server[DruidServerMetadata{name='druidhost:8083', host='druidhost:8083', maxSize=10000000000, tier='_default_tier', type='historical', priority='0'}]
2016-04-13T08:51:07,053 INFO [plumber_merge_1] io.druid.segment.realtime.plumber.RealtimePlumber - Segment version[2016-04-13T00:00:02.588+08:00] >= sink version[2016-04-13T00:00:02.588+08:00]
2016-04-13T08:51:07,054 INFO [plumber_merge_1] io.druid.server.coordination.BatchDataSegmentAnnouncer - Unannouncing segment[cl_events_2016-04-13T00:00:00.000+08:00_2016-04-14T00:00:00.000+08:00_2016-04-13T00:00:02.588+08:00] at path[/druid/convertlab/events/segments/druidhost:8101/druidhost:8101_realtime__default_tier_2016-04-12T09:02:20.695+08:00_4c27b67b7b2f416bb935abc38fa002ce1]
2016-04-13T08:51:07,054 INFO [plumber_merge_1] io.druid.indexing.common.actions.RemoteTaskActionClient - Performing action for task[index_realtime_cl_events_2016-04-12T00:00:00.000Z_0_0]: LockReleaseAction{interval=2016-04-13T00:00:00.000+08:00/2016-04-14T00:00:00.000+08:00}
2016-04-13T08:51:07,056 INFO [plumber_merge_1] io.druid.indexing.common.actions.RemoteTaskActionClient - Submitting action for task[index_realtime_cl_events_2016-04-12T00:00:00.000Z_0_0] to overlord[http://druidhost:8090/druid/indexer/v1/action]: LockReleaseAction{interval=2016-04-13T00:00:00.000+08:00/2016-04-14T00:00:00.000+08:00}
2016-04-13T08:51:07,056 INFO [plumber_merge_1] com.metamx.http.client.pool.ChannelResourceFactory - Generating: http://druidhost:8090
2016-04-13T08:51:07,079 INFO [plumber_merge_1] io.druid.segment.realtime.plumber.RealtimePlumber - Deleting Index File[/data/druid/task/index_realtime_cl_events_2016-04-12T00:00:00.000Z_0_0/work/persist/cl_events/2016-04-13T00:00:00.000+08:00_2016-04-14T00:00:00.000+08:00]
2016-04-13T08:51:07,140 INFO [plumber_merge_1] io.druid.segment.realtime.plumber.RealtimePlumber - Removing sinkKey 1460476800000 for segment cl_events_2016-04-13T00:00:00.000+08:00_2016-04-14T00:00:00.000+08:00_2016-04-13T00:00:02.588+08:00

**Comment by redlion99** [comment]
Another exception log

2016-04-27T12:50:02,682 INFO [cl_events-2016-04-27T06:00:00.000Z-persist-n-merge] io.druid.segment.IndexIO$DefaultIndexIOHandler - Processing file[spatial.drd]
2016-04-27T12:50:02,682 INFO [cl_events-2016-04-27T06:00:00.000Z-persist-n-merge] io.druid.segment.IndexIO$DefaultIndexIOHandler - Processing file[time_LITTLE_ENDIAN.drd]
Exception in thread "plumber_merge_0" java.lang.NullPointerException
	at java.util.TreeMap.compare(TreeMap.java:1290)
	at java.util.TreeMap.put(TreeMap.java:538)
	at java.util.TreeSet.add(TreeSet.java:255)
	at java.util.AbstractCollection.addAll(AbstractCollection.java:344)
	at java.util.TreeSet.addAll(TreeSet.java:312)
	at io.druid.segment.IndexIO$DefaultIndexIOHandler.convertV8toV9(IndexIO.java:862)
	at io.druid.segment.IndexMerger.makeIndexFiles(IndexMerger.java:957)
	at io.druid.segment.IndexMerger.merge(IndexMerger.java:351)
	at io.druid.segment.IndexMerger.persist(IndexMerger.java:196)
	at io.druid.segment.IndexMerger.persist(IndexMerger.java:161)
	at io.druid.segment.IndexMerger.persist(IndexMerger.java:138)
	at io.druid.segment.realtime.plumber.RealtimePlumber.persistHydrant(RealtimePlumber.java:972)
	at io.druid.segment.realtime.plumber.RealtimePlumber$4.doRun(RealtimePlumber.java:480)
	at io.druid.common.guava.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2016-04-27T12:51:00,516 INFO [ServerInventoryView-0] io.druid.client.BatchServerInventoryView - Server Disappeared[DruidServerMetadata{name='10.47.97.227:8101', host='10.47.97.227:8101', maxSize=0, tier='_default_tier', type='realtime', priority='0'}]
2016-04-27T12:51:00,543 INFO [ServerInventoryView-0] io.druid.client.BatchServerInventoryView - Server Disappeared[DruidServerMetadata{name='10.47.97.227:8100', host='10.47.97.227:8100', maxSize=0, tier='_default_tier', type='realtime', priority='0'}]

**Comment by redlion99** [comment]
This segment will not be closed during the next merge.

2016-04-28T00:45:00,002 INFO [cl_events-overseer-2] io.druid.segment.realtime.plumber.RealtimePlumber - Starting merge and push.
2016-04-28T00:45:00,002 INFO [cl_events-overseer-2] io.druid.segment.realtime.plumber.RealtimePlumber - Found [1] segments. Attempting to hand off segments that start before [1970-01-01T00:00:00.000Z].
2016-04-28T00:45:00,003 INFO [cl_events-overseer-2] io.druid.segment.realtime.plumber.RealtimePlumber - Skipping persist and merge for entry [1461736800000=Sink{interval=2016-04-27T06:00:00.000Z/2016-04-27T12:00:00.000Z, schema=DataSchema{dataSource='cl_events', parser={type=map, parseSpec={format=json, timestampSpec={column=timestamp, format=iso, missingValue=null}, dimensionsSpec={dimensionExclusions=[duration, sessionDepth, returningSession, score, amount, newSession, userCount], spatialDimensions=[]}}}, aggregators=[CountAggregatorFactory{name='count'}, LongSumAggregatorFactory{fieldName='duration', name='duration'}, LongSumAggregatorFactory{fieldName='userCount', name='userCount'}, LongSumAggregatorFactory{fieldName='newSession', name='newSession'}, LongSumAggregatorFactory{fieldName='returningSession', name='returningSession'}, HyperUniquesAggregatorFactory{name='customerUnique', fieldName='customerId'}], granularitySpec=io.druid.segment.indexing.granularity.UniformGranularitySpec@3414381}}] : Start time [2016-04-27T06:00:00.000Z] >= [1970-01-01T00:00:00.000Z] min timestamp required in this run. Segment will be picked up in a future run.
2016-04-28T00:45:00,003 INFO [cl_events-overseer-2] io.druid.segment.realtime.plumber.RealtimePlumber - Found [0] sinks to persist and merge

**Comment by redlion99** [comment]
Does this one fixed by #2744 ?  https://github.com/druid-io/druid/issues/2744
