### ISSUE TITLE
FAILURE! - in io.druid.segment.loading.LocalDataSegmentPusherTest

### ISSUE THREAD

**Issue by tkao1000** [apache/incubator-druid#2861]
Hi,
My operating system is Ubuntu 14.04 and I'm using java version "1.8.0_77".
When I try to compile druid using "mvn install", I get this error.

```
java.lang.AssertionError: Expected test to throw (an instance of java.io.IOException and exception with message a string containing "Cannot create directory")
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.rules.ExpectedException.failDueToMissingException(ExpectedException.java:184)
    at org.junit.rules.ExpectedException.access$100(ExpectedException.java:85)
    at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:170)
    at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
    at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```

I've tried commenting out that test, but then I get another error:

```
FAILURE!
java.lang.AssertionError: pushTaskLog should fail with exception of dir creation error
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.assertTrue(Assert.java:41)
    at org.junit.Assert.assertNotNull(Assert.java:621)
    at io.druid.indexing.common.tasklogs.FileTaskLogsTest.testPushTaskLogDirCreationFails(FileTaskLogsTest.java:87)
```

**Comment by drcrallen** [comment]
Thanks @tkao1000 , what file system are you using for the directory where the tests are run, and for the java tmp directory?

**Comment by drcrallen** [comment]
Other note-able test-fails-related-to-directory-stuff: https://github.com/druid-io/druid/issues/2694

**Comment by JonStrabala** [comment]
I see this issue too with a Druid GIT pull from today

But the error only happens when I run as user 'root' this is a JVM issue where FILE.canWrite behave different if you are user 'root' - why because the 'root' user always can write on some UNIX system - more on this at the bottom. BTW this seems to solve #2694 also.

My test system is probably in the "under-powered" test case one hard drive 4GB RAM 

Machine specs ...

```
[root@smart130 ~]# uname -a
SunOS smart130 5.11 joyent_20160422T185437Z i86pc i386 i86pc
[root@smart130 ~]# zpool upgrade
This system supports ZFS pool feature flags.
All pools are formatted using feature flags.
Every feature flags pool has all supported features enabled.
[root@smart130 ~]# psrinfo -vp
The physical processor has 2 virtual processors (0-1)
  x86 (AuthenticAMD 100F62 family 16 model 6 step 2 clock 2813 MHz)
        AMD Athlon(tm) II X2 240 Processor      [ Socket: AM3 ]
[root@smart130 ~]#  java -version
openjdk version "1.7.0-internal"
OpenJDK Runtime Environment (build 1.7.0-internal-pkgsrc_2015_07_10_14_31-b00)
OpenJDK 64-Bit Server VM (build 24.76-b04, mixed mode)
[root@smart130 ~]#
```

I do a "mvn test" and I get two failures now

(the #2694 issue)

```
Running io.druid.query.lookup.LookupSnapshotTakerTest
Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.023 sec <<< FAILURE! - in io.druid.query.lookup.LookupSnapshotTakerTest
testIOExceptionDuringLookupPersist(io.druid.query.lookup.LookupSnapshotTakerTest)  Time elapsed: 0.001 sec  <<< FAILURE!
java.lang.AssertionError: Expected exception: com.metamx.common.ISE
        at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:32)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
```

(this #2861 issue)

```
Running io.druid.segment.loading.LocalDataSegmentPusherTest
Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.196 sec <<< FAILURE! - in io.druid.segment.loading.LocalDataSegmentPusherTest
testPushCannotCreateDirectory(io.druid.segment.loading.LocalDataSegmentPusherTest)  Time elapsed: 0.079 sec  <<< FAILURE!
java.lang.AssertionError: Expected test to throw (an instance of java.io.IOException and exception with message a string containing "Cannot create directory")
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.rules.ExpectedException.failDueToMissingException(ExpectedException.java:184)
        at org.junit.rules.ExpectedException.access$100(ExpectedException.java:85)
```

Overall results ...

```
Results :

Failed tests:
  LookupSnapshotTakerTest.testIOExceptionDuringLookupPersist Expected exception: com.metamx.common.ISE
  LocalDataSegmentPusherTest.testPushCannotCreateDirectory Expected test to throw (an instance of java.io.IOException and exception with message a string containing "Cannot create directory")

Tests run: 851, Failures: 2, Errors: 0, Skipped: 3

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] io.druid:druid ..................................... SUCCESS [  0.305 s]
[INFO] druid-api .......................................... SUCCESS [  6.038 s]
[INFO] druid-common ....................................... SUCCESS [ 10.538 s]
[INFO] druid-processing ................................... SUCCESS [08:04 min]
[INFO] druid-aws-common ................................... SUCCESS [  0.223 s]
[INFO] druid-server ....................................... FAILURE [03:40 min]
[INFO] druid-examples ..................................... SKIPPED
```

Gosh  in method testPushCannotCreateDirectory() file LocalDataSegmentPusherTest.java we seem to make the directory non writable but it still seems to writes !

```
    config.storageDirectory.setWritable(false);
    localDataSegmentPusher.push(dataSegmentFiles, dataSegment);
```
As such the expected exception is not thrown.  From io.druid.segment.loading.LocalDataSegmentPusherTest-output.txt

```
2016-05-05T21:14:22,054 INFO [main] io.druid.segment.loading.LocalDataSegmentPusher - Creating descriptor file at[/var/tmp/junit4843793203992083798/junit3652270925579432594/ds/1970-01-01T00:00:00.000Z_1970-01-01T00:00:00.001Z/v2/0/descriptor.json]
2016-05-05T21:14:22,057 INFO [main] io.druid.segment.loading.LocalDataSegmentPusher - Configured local filesystem as deep storage
2016-05-05T21:14:22,057 INFO [main] io.druid.segment.loading.LocalDataSegmentPusher - Configured local filesystem as deep storage
2016-05-05T21:14:22,059 INFO [main] io.druid.segment.loading.LocalDataSegmentPusher - Configured local filesystem as deep storage
2016-05-05T21:14:22,067 INFO [main] io.druid.segment.loading.LocalDataSegmentPusher - Copying segment[ds_1970-01-01T00:00:00.000Z_1970-01-01T00:00:00.001Z_v1] to local filesystem at location[/var/tmp/junit3004239542637879041/junit3692105684512543586/xxx/ds/1970-01-01T00:00:00.000Z_1970-01-01T00:00:00.001Z/v1/0]
2016-05-05T21:14:22,067 INFO [main] io.druid.segment.loading.LocalDataSegmentPusher - Compressing files from[/var/tmp/junit3004239542637879041/junit1349266309281702105] to [/var/tmp/junit3004239542637879041/junit3692105684512543586/xxx/ds/1970-01-01T00:00:00.000Z_1970-01-01T00:00:00.001Z/v1/0/index.zip]
2016-05-05T21:14:22,068 INFO [main] com.metamx.common.CompressionUtils - Adding file[/var/tmp/junit3004239542637879041/junit1349266309281702105/version.bin] with size[4].  Total size so far[0]
2016-05-05T21:14:22,069 INFO [main] io.druid.segment.loading.LocalDataSegmentPusher - Creating descriptor file at[/var/tmp/junit3004239542637879041/junit3692105684512543586/xxx/ds/1970-01-01T00:00:00.000Z_1970-01-01T00:00:00.001Z/v1/0/descriptor.json]
2016-05-05T21:14:22,113 INFO [main] io.druid.segment.loading.LocalDataSegmentPusher - Configured local filesystem as deep storage
2016-05-05T21:14:22,113 INFO [main] io.druid.segment.loading.LocalDataSegmentPusher - Configured local filesystem as deep storage
```

Okay back to this is a JVM issue given the follwoing test program lets run it first as a non root user and then as a root user:

```
import java.io.File;

public class TestIssue {
    public static void main(String[] args){
        File f = new File("wibblefish");
        f.deleteOnExit();
        if (f.mkdirs())
            if (f.setWritable(false,false)) {
                if (f.canWrite()) {
                    System.out.println("Test failed");
                } else {
                    System.out.println("Test passed (setWritable() succeeded)");
                }
            } else {
                System.out.println("Test Passed (setWritable() failed)");
            }
    }
}
```

Compile

```
[wordpress@wp131 /tmp/work]$ javac TestIssue.java
[wordpress@wp131 /tmp/work]$ ls
TestIssue.class  TestIssue.java
[wordpress@wp131 /tmp/work]$
```

Run as non-root user

```
[wordpress@wp131 /tmp/work]$ java TestIssue
Test passed (setWritable() succeeded)
[wordpress@wp131 /tmp/work]$ ls
TestIssue.class  TestIssue.java
[wordpress@wp131
```

Run as root 

```
[root@wp131 /tmp/work]# ls
TestIssue.class  TestIssue.java
[root@wp131 /tmp/work]# java TestIssue
Test failed
[root@wp131 /tmp/work]# ls
TestIssue.class  TestIssue.java
[root@wp131 /tmp/work]#
```

Before anyone says why are you developing as user root - well I'm lazy - and I am doing this in a throw away SmartOS zone so I don't much care about mistakes or security etc.

**Comment by drcrallen** [comment]
In that case the test is catching what it should and properly failing. Running as a privileged user causes other side-effects.

**Comment by drcrallen** [comment]
Thanks for digging into one of the failure modes!

**Comment by JonStrabala** [comment]
Perhaps, a "druid" test could be done to make sure that the tests are not
being performed as a privlidged user.  Might help/remind others in the
future.

**Comment by drcrallen** [comment]
The reason I haven't closed this out is because the failure mode isn't informative enough, and I'm worried this thread will get buried if closed. Adding in more information on the failure mode is definitely deairable.

**Comment by JonStrabala** [comment]
You could build a TEST with code similar to the following I haven't really looked into Windows systems but it should work for Solaris/Linix and other *NIX systems.
```
import java.io.*;
import java.io.InputStream.*;

public class IsPrivUser
{

    public static String read(InputStream input) throws IOException {
        StringBuilder sb=new StringBuilder();
        BufferedReader br = new BufferedReader(new InputStreamReader(input));
        String read;
        while((read=br.readLine()) != null) {
            sb.append(read);
        }
        br.close();
        return sb.toString();
    }

    public static void main(String[] args)
    {
        String userName = System.getProperty("user.name");
        String output = null;
        String error = null;
        try {
            Process p = Runtime.getRuntime().exec("groups " + userName);
            output = read(p.getInputStream());
            error = read(p.getErrorStream());
            if (output != null) {
                System.out.println("output: <"+output+">");
            }
            if (error != null) {
                System.out.println("error: <"+error+">");
            }
            if (error == null || error.length() == 0) {
                if ( output.indexOf("root") != -1 ) {
                    System.out.println("userName "+ userName + " is privileged");
                } else {
                    System.out.println("userName "+ userName + " is NOT privileged");
                }
            } else {
                System.out.println("YIKES when checking userName "+ userName + " we had an error");
            }
        } catch (IOException e) {
            System.out.println("System is non-Unix/Linix/Solaris");
        }
    }
}

```

Root or privileged user on Unix/Linux/Solaris
```
root# id
uid=0(root) gid=0(root)
root# java IsPrivUser
output: <root other bin sys adm uucp mail tty lp nuucp daemon>
error: <>
userName root is privileged
root#
```

non-privileged user on Unix/Linux/Solaris
```
non-priv# id
uid=1015(crome) gid=1(other)
non-priv# java IsPrivUser
output: <crome : other>
error: <>
userName crome is NOT privileged
non-priv#
```
