### ISSUE TITLE
use guava 18 libraries

### ISSUE THREAD

**Issue by valenpo** [apache/incubator-druid#2901]
Hello everyone. 

I'm trying making embedded druid-io store (using druid-embedded project), but found druid using guava 16.0 that make libraries confusing as we are using guava 18. Is it possible use guava 18 instead of guava 16? 

Regards,
Valentin.

**Comment by drcrallen** [comment]
No because of Hadoop, see https://issues.apache.org/jira/browse/HADOOP-10101 for lots of related information.

**Comment by drcrallen** [comment]
Jackson is in the same class of libraries we can't upgrade due to hadoop issues. This issue can stay open since it isn't resolved, but it is certainly not an easy issue to address.

**Comment by valenpo** [comment]
Thanks, got it.

**Comment by valenpo** [comment]
I have such exception (i'm using embedded druid)
```
java.io.IOException: com.google.common.io.ByteStreams.join(Ljava/lang/Iterable;)Lcom/google/common/io/InputSupplier;
	at com.stimulus.archiva.analytics.druid.IndexHelper.getQueryableIndex(IndexHelper.java:73) ~[IndexHelper.class:na]
	at com.stimulus.archiva.analytics.VolumeBuilderProcess.end(VolumeBuilderProcess.java:77) ~[VolumeBuilderProcess.class:na]
	at com.stimulus.archiva.process.ArchivaProcess$ProcessThread.run(ArchivaProcess.java:437) ~[ArchivaProcess$ProcessThread.class:na]
```

I'll decorate such method execution with guava 18 methods.
