### ISSUE TITLE
Graphite Emitter - Broken Pipe Exception

### ISSUE THREAD

**Issue by skilledmonster** [apache/incubator-druid#3001]
While the Druid nodes were running, I had to restart my Graphite/Carbon components to make a small configuration change and this triggered a Broken Pipe Exception in the Druid Nodes and they stopped emitting metrics since then.

If the connection is lost, Druid should try to re-connect after a configurable amount of time.

```
2016-05-19T20:00:41,873 ERROR [GraphiteEmitter-0] io.druid.emitter.graphite.GraphiteEmitter - Broken pipe
java.net.SocketException: Broken pipe
    at java.net.SocketOutputStream.socketWrite0(Native Method) ~[?:1.8.0_74]
    at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109) ~[?:1.8.0_74]
    at java.net.SocketOutputStream.write(SocketOutputStream.java:141) ~[?:1.8.0_74]
    at com.codahale.metrics.graphite.PickledGraphite.writeMetrics(PickledGraphite.java:262) ~[metrics-graphite-3.1.2.jar:3.1.2]
    at com.codahale.metrics.graphite.PickledGraphite.flush(PickledGraphite.java:221) ~[metrics-graphite-3.1.2.jar:3.1.2]
    at io.druid.emitter.graphite.GraphiteEmitter$ConsumerRunnable.run(GraphiteEmitter.java:172) [graphite-emitter-0.9.0.jar:0.9.0]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_74]
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_74]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_74]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_74]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_74]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_74]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]

```

**Comment by b-slim** [comment]
do you have this fix https://github.com/druid-io/druid/pull/2952 ?

**Comment by skilledmonster** [comment]
@b-slim - No, I don't! I'll get it once 0.9.1 is officially released. Thanks!
