### ISSUE TITLE
realtime nodes stops processing entirely!

### ISSUE THREAD

**Issue by pdeva** [apache/incubator-druid#3023]
druid 0.9.0.

Host running realtime node was rebooted by azure. When i restarted realtime node on the host I now see this exception and the node doesnt do any processing:

```
2016-05-26 06:02:48,920 INFO i.d.s.r.p.RealtimePlumber [chief-dripstat[0]] Loading previously persisted segment at [/data/realtime/basePersist/dripstat/2016-05-26T05:00:00.000Z_2016-05-26T06:00:00.000Z/2]
2016-05-26 06:02:48,934 ERROR i.d.s.r.RealtimeManager [chief-dripstat[0]] RuntimeException aborted realtime processing[dripstat]: {class=io.druid.segment.realtime.RealtimeManager, exceptionType=class java.lang.IllegalArgumentException, exceptionMessage=array too small: 0 < 4}
java.lang.IllegalArgumentException: array too small: 0 < 4
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:148) ~[guava-16.0.1.jar:?]
        at com.google.common.primitives.Ints.fromByteArray(Ints.java:322) ~[guava-16.0.1.jar:?]
        at io.druid.segment.SegmentUtils.getVersionFromDir(SegmentUtils.java:38) ~[druid-api-0.3.16.jar:0.9.0]
        at io.druid.segment.IndexIO.loadIndex(IndexIO.java:214) ~[druid-processing-0.9.0.jar:0.9.0]
        at io.druid.segment.realtime.plumber.RealtimePlumber.bootstrapSinksFromDisk(RealtimePlumber.java:750) ~[druid-server-0.9.0.jar:0.9.0]
        at io.druid.segment.realtime.plumber.RealtimePlumber.startJob(RealtimePlumber.java:217) ~[druid-server-0.9.0.jar:0.9.0]
        at io.druid.segment.realtime.RealtimeManager$FireChief.run(RealtimeManager.java:255) [druid-server-0.9.0.jar:0.9.0]

```

**Comment by pdeva** [comment]
this could be due to the on-disk data getting corrupted by the host reboot.
however, the node should skip over it and not completely stop processing
