### ISSUE TITLE
Hadoop-based Batch Ingestion data to druid 

### ISSUE THREAD

**Issue by ziwulovejava** [apache/incubator-druid#3254]
hello ,I use Hadoop-based Batch Ingestion data to druid ,when I   execute
java -Xmx256m -Duser.timezone=UTC -Dfile.encoding=UTF-8 -classpath lib/_:conf/druid/_common/_ io.druid.cli.Main index hadoop  ./quickstart/test-index.json
occur below error:
2016-07-17T09:09:58,670 ERROR [main] io.druid.cli.CliHadoopIndexer - failure!!!!
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_73]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_73]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_73]
    at io.druid.cli.CliHadoopIndexer.run(CliHadoopIndexer.java:115) [druid-services-0.9.1.1.jar:0.9.1.1]
    at io.druid.cli.Main.main(Main.java:105) [druid-services-0.9.1.1.jar:0.9.1.1]
Caused by: java.lang.ExceptionInInitializerError
    at io.druid.cli.CliInternalHadoopIndexer.getHadoopDruidIndexerConfig(CliInternalHadoopIndexer.java:161) ~[druid-services-0.9.1.1.jar:0.9.1.1]
    at io.druid.cli.CliInternalHadoopIndexer$1.configure(CliInternalHadoopIndexer.java:89) ~[druid-services-0.9.1.1.jar:0.9.1.1]
    at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:230) ~[guice-4.0-beta.jar:?]
    at com.google.inject.spi.Elements.getElements(Elements.java:103) ~[guice-4.0-beta.jar:?]
    at com.google.inject.spi.Elements.getElements(Elements.java:94) ~[guice-4.0-beta.jar:?]
    at com.google.inject.util.Modules$RealOverriddenModuleBuilder$1.configure(Modules.java:173) ~[guice-4.0-beta.jar:?]
    at com.google.inject.AbstractModule.configure(AbstractModule.java:62) ~[guice-4.0-beta.jar:?]
    at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:230) ~[guice-4.0-beta.jar:?]
    at com.google.inject.spi.Elements.getElements(Elements.java:103) ~[guice-4.0-beta.jar:?]
    at com.google.inject.spi.Elements.getElements(Elements.java:94) ~[guice-4.0-beta.jar:?]
    at com.google.inject.util.Modules$RealOverriddenModuleBuilder$1.configure(Modules.java:153) ~[guice-4.0-beta.jar:?]
    at com.google.inject.AbstractModule.configure(AbstractModule.java:62) ~[guice-4.0-beta.jar:?]
    at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:230) ~[guice-4.0-beta.jar:?]
    at com.google.inject.spi.Elements.getElements(Elements.java:103) ~[guice-4.0-beta.jar:?]
    at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:136) ~[guice-4.0-beta.jar:?]
    at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104) ~[guice-4.0-beta.jar:?]
    at com.google.inject.Guice.createInjector(Guice.java:96) ~[guice-4.0-beta.jar:?]
    at com.google.inject.Guice.createInjector(Guice.java:73) ~[guice-4.0-beta.jar:?]
    at com.google.inject.Guice.createInjector(Guice.java:62) ~[guice-4.0-beta.jar:?]
    at io.druid.initialization.Initialization.makeInjectorWithModules(Initialization.java:367) ~[druid-server-0.9.1.1.jar:0.9.1.1]
    at io.druid.cli.GuiceRunnable.makeInjector(GuiceRunnable.java:60) ~[druid-services-0.9.1.1.jar:0.9.1.1]
    at io.druid.cli.CliInternalHadoopIndexer.run(CliInternalHadoopIndexer.java:108) ~[druid-services-0.9.1.1.jar:0.9.1.1]
    at io.druid.cli.Main.main(Main.java:105) ~[druid-services-0.9.1.1.jar:0.9.1.1]
    ... 6 more
Caused by: com.google.inject.CreationException: Guice creation errors:

1) A binding to com.google.common.base.Supplier<io.druid.server.audit.SQLAuditManagerConfig> was already configured at io.druid.guice.JsonConfigProvider.bind(JsonConfigProvider.java:131).
  at io.druid.guice.JsonConfigProvider.bind(JsonConfigProvider.java:131)

2) A binding to io.druid.server.audit.SQLAuditManagerConfig was already configured at io.druid.guice.JsonConfigProvider.bind(JsonConfigProvider.java:132).
  at io.druid.guice.JsonConfigProvider.bind(JsonConfigProvider.java:132)

2 errors
    at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:448) ~[guice-4.0-beta.jar:?]
    at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155) ~[guice-4.0-beta.jar:?]
    at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107) ~[guice-4.0-beta.jar:?]
    at com.google.inject.Guice.createInjector(Guice.java:96) ~[guice-4.0-beta.jar:?]
    at com.google.inject.Guice.createInjector(Guice.java:73) ~[guice-4.0-beta.jar:?]
    at com.google.inject.Guice.createInjector(Guice.java:62) ~[guice-4.0-beta.jar:?]
    at io.druid.initialization.Initialization.makeInjectorWithModules(Initialization.java:367) ~[druid-server-0.9.1.1.jar:0.9.1.1]
    at io.druid.indexer.HadoopDruidIndexerConfig.<clinit>(HadoopDruidIndexerConfig.java:98) ~[druid-indexing-hadoop-0.9.1.1.jar:0.9.1.1]
    at io.druid.cli.CliInternalHadoopIndexer.getHadoopDruidIndexerConfig(CliInternalHadoopIndexer.java:161) ~[druid-services-0.9.1.1.jar:0.9.1.1]
    at io.druid.cli.CliInternalHadoopIndexer$1.configure(CliInternalHadoopIndexer.java:89) ~[druid-services-0.9.1.1.jar:0.9.1.1]
    at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:230) ~[guice-4.0-beta.jar:?]
    at com.google.inject.spi.Elements.getElements(Elements.java:103) ~[guice-4.0-beta.jar:?]
    at com.google.inject.spi.Elements.getElements(Elements.java:94) ~[guice-4.0-beta.jar:?]
    at com.google.inject.util.Modules$RealOverriddenModuleBuilder$1.configure(Modules.java:173) ~[guice-4.0-beta.jar:?]
    at com.google.inject.AbstractModule.configure(AbstractModule.java:62) ~[guice-4.0-beta.jar:?]
    at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:230) ~[guice-4.0-beta.jar:?]
    at com.google.inject.spi.Elements.getElements(Elements.java:103) ~[guice-4.0-beta.jar:?]
    at com.google.inject.spi.Elements.getElements(Elements.java:94) ~[guice-4.0-beta.jar:?]
    at com.google.inject.util.Modules$RealOverriddenModuleBuilder$1.configure(Modules.java:153) ~[guice-4.0-beta.jar:?]
    at com.google.inject.AbstractModule.configure(AbstractModule.java:62) ~[guice-4.0-beta.jar:?]
    at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:230) ~[guice-4.0-beta.jar:?]
    at com.google.inject.spi.Elements.getElements(Elements.java:103) ~[guice-4.0-beta.jar:?]
    at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:136) ~[guice-4.0-beta.jar:?]
    at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104) ~[guice-4.0-beta.jar:?]
    at com.google.inject.Guice.createInjector(Guice.java:96) ~[guice-4.0-beta.jar:?]
    at com.google.inject.Guice.createInjector(Guice.java:73) ~[guice-4.0-beta.jar:?]
    at com.google.inject.Guice.createInjector(Guice.java:62) ~[guice-4.0-beta.jar:?]
    at io.druid.initialization.Initialization.makeInjectorWithModules(Initialization.java:367) ~[druid-server-0.9.1.1.jar:0.9.1.1]
    at io.druid.cli.GuiceRunnable.makeInjector(GuiceRunnable.java:60) ~[druid-services-0.9.1.1.jar:0.9.1.1]
    at io.druid.cli.CliInternalHadoopIndexer.run(CliInternalHadoopIndexer.java:108) ~[druid-services-0.9.1.1.jar:0.9.1.1]
    at io.druid.cli.Main.main(Main.java:105) ~[druid-services-0.9.1.1.jar:0.9.1.1]
    ... 6 more

**Comment by anonymous-shy** [comment]
Yes,I meet the error too.And How to solve it???

**Comment by ziwulovejava** [comment]
@anonymous-shy  mysql jar package conflict，I already solve it

**Comment by anonymous-shy** [comment]
@ziwulovejava how to resolve it？ replace the mysql jars to match Druid Or its mysql version conflict？
