### ISSUE TITLE
Transient failure in LoadQueuePeonTest.testMultipleLoadDropSegments

### ISSUE THREAD

**Issue by gianm** [apache/incubator-druid#3340]
https://travis-ci.org/druid-io/druid/jobs/150984834

```
testMultipleLoadDropSegments(io.druid.server.coordinator.LoadQueuePeonTest)  Time elapsed: 9.799 sec  <<< ERROR!
org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /druid/loadqueue/localhost:1234/test_load_queue_peon_2014-10-23T00:00:00.000Z_2014-10-24T00:00:00.000Z_2015-05-27T03:38:35.683Z
    at org.apache.zookeeper.KeeperException.create(KeeperException.java:111)
    at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
    at org.apache.zookeeper.ZooKeeper.delete(ZooKeeper.java:873)
    at org.apache.curator.framework.imps.DeleteBuilderImpl$5.call(DeleteBuilderImpl.java:243)
    at org.apache.curator.framework.imps.DeleteBuilderImpl$5.call(DeleteBuilderImpl.java:237)
    at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:108)
    at org.apache.curator.framework.imps.DeleteBuilderImpl.pathInForeground(DeleteBuilderImpl.java:234)
    at org.apache.curator.framework.imps.DeleteBuilderImpl.forPath(DeleteBuilderImpl.java:218)
    at org.apache.curator.framework.imps.DeleteBuilderImpl.forPath(DeleteBuilderImpl.java:42)
    at io.druid.server.coordinator.LoadQueuePeonTest.testMultipleLoadDropSegments(LoadQueuePeonTest.java:243)
```

**Comment by gianm** [comment]
Closing this -- haven't seen it recently and the issue is a couple years old.
