### ISSUE TITLE
Batch Data Ingestion with CSV Data Format fails on embedded line breaks

### ISSUE THREAD

**Issue by mark1900** [apache/incubator-druid#3376]
Druid version: 0.8.3.

Druid CSV implementations do not support embedded line breaks.
## CSV support for embedded line breaks

To quote https://en.wikipedia.org/wiki/Comma-separated_values

> Fields with embedded line breaks must be quoted (however, many CSV implementations do not support embedded line breaks).
> `1997,Ford,E350,"Go get one now`
> `they are going fast"`
## StackTrace

`2016-08-18T15:52:22,012 WARN [Thread-60] org.apache.hadoop.mapred.LocalJobRunner - job_local1512454943_0001
java.lang.Exception: com.metamx.common.RE: Failure on row[823,,,,SOMETHING,41,1,2,-1,2016-07-20T14:29:11.383Z,6,50,2,"Line 1]
        at org.apache.hadoop.mapred.LocalJobRunner$Job.runTasks(LocalJobRunner.java:462) ~[hadoop-mapreduce-client-common-2.7.1.jar:?]
        at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:522) [hadoop-mapreduce-client-common-2.7.1.jar:?]
Caused by: com.metamx.common.RE: Failure on row[823,,,,SOMETHING,41,1,2,-1,2016-07-20T14:29:11.383Z,6,50,2,"Line 1]
        at io.druid.indexer.HadoopDruidIndexerMapper.map(HadoopDruidIndexerMapper.java:99) ~[druid-indexing-hadoop-0.8.3.jar:0.8.3]
        at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:146) ~[hadoop-mapreduce-client-core-2.7.1.jar:?]
        at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:787) ~[hadoop-mapreduce-client-core-2.7.1.jar:?]
        at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341) ~[hadoop-mapreduce-client-core-2.7.1.jar:?]
        at org.apache.hadoop.mapred.LocalJobRunner$Job$MapTaskRunnable.run(LocalJobRunner.java:243) ~[hadoop-mapreduce-client-common-2.7.1.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_71]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_71]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_71]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_71]
        at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_71]
Caused by: com.metamx.common.parsers.ParseException: Unable to parse row [823,,,,SOMETHING,41,1,2,-1,2016-07-20T14:29:11.383Z,6,50,2,"Line 1]
        at com.metamx.common.parsers.CSVParser.parse(CSVParser.java:122) ~[java-util-0.27.4.jar:?]
        at io.druid.data.input.impl.StringInputRowParser.parseString(StringInputRowParser.java:126) ~[druid-api-0.3.13.jar:0.3.13]
        at io.druid.data.input.impl.StringInputRowParser.parse(StringInputRowParser.java:131) ~[druid-api-0.3.13.jar:0.3.13]
        at io.druid.indexer.HadoopDruidIndexerMapper.parseInputRow(HadoopDruidIndexerMapper.java:109) ~[druid-indexing-hadoop-0.8.3.jar:0.8.3]
        at io.druid.indexer.HadoopDruidIndexerMapper.map(HadoopDruidIndexerMapper.java:80) ~[druid-indexing-hadoop-0.8.3.jar:0.8.3]
        at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:146) ~[hadoop-mapreduce-client-core-2.7.1.jar:?]
        at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:787) ~[hadoop-mapreduce-client-core-2.7.1.jar:?]
        at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341) ~[hadoop-mapreduce-client-core-2.7.1.jar:?]
        at org.apache.hadoop.mapred.LocalJobRunner$Job$MapTaskRunnable.run(LocalJobRunner.java:243) ~[hadoop-mapreduce-client-common-2.7.1.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_71]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_71]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_71]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_71]
        at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_71]
Caused by: java.io.IOException: Un-terminated quoted field at end of CSV line
        at au.com.bytecode.opencsv.CSVParser.parseLine(CSVParser.java:268) ~[opencsv-2.3.jar:?]
        at au.com.bytecode.opencsv.CSVParser.parseLine(CSVParser.java:178) ~[opencsv-2.3.jar:?]
        at com.metamx.common.parsers.CSVParser.parse(CSVParser.java:113) ~[java-util-0.27.4.jar:?]
        at io.druid.data.input.impl.StringInputRowParser.parseString(StringInputRowParser.java:126) ~[druid-api-0.3.13.jar:0.3.13]
        at io.druid.data.input.impl.StringInputRowParser.parse(StringInputRowParser.java:131) ~[druid-api-0.3.13.jar:0.3.13]
        at io.druid.indexer.HadoopDruidIndexerMapper.parseInputRow(HadoopDruidIndexerMapper.java:109) ~[druid-indexing-hadoop-0.8.3.jar:0.8.3]
        at io.druid.indexer.HadoopDruidIndexerMapper.map(HadoopDruidIndexerMapper.java:80) ~[druid-indexing-hadoop-0.8.3.jar:0.8.3]
        at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:146) ~[hadoop-mapreduce-client-core-2.7.1.jar:?]
        at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:787) ~[hadoop-mapreduce-client-core-2.7.1.jar:?]
        at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341) ~[hadoop-mapreduce-client-core-2.7.1.jar:?]
        at org.apache.hadoop.mapred.LocalJobRunner$Job$MapTaskRunnable.run(LocalJobRunner.java:243) ~[hadoop-mapreduce-client-common-2.7.1.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_71]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_71]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_71]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_71]
        at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_71]
`

**Comment by okeeffdp** [comment]
Has there been any progress made on this issue?
