### ISSUE TITLE
Quickstart 405 Error

### ISSUE THREAD

**Issue by sopping** [apache/incubator-druid#3425]
When I am using Mac to try the quick start part,  it reports error like this:

```
2016-09-03T02:15:35,135 WARN [main] io.druid.indexing.common.actions.RemoteTaskActionClient - Exception submitting action for task[index_hadoop_wikiticker_2016-09-03T02:15:32.143Z]
java.io.IOException: Scary HTTP status returned: 405 Method Not Allowed. Check your overlord[192.168.1.101:8090] logs for exceptions.
    at io.druid.indexing.common.actions.RemoteTaskActionClient.submit(RemoteTaskActionClient.java:124) [druid-indexing-service-0.9.1.1.jar:0.9.1.1]
    at io.druid.indexing.common.task.HadoopIndexTask.isReady(HadoopIndexTask.java:137) [druid-indexing-service-0.9.1.1.jar:0.9.1.1]
    at io.druid.indexing.worker.executor.ExecutorLifecycle.start(ExecutorLifecycle.java:168) [druid-indexing-service-0.9.1.1.jar:0.9.1.1]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
    at com.metamx.common.lifecycle.Lifecycle$AnnotationBasedHandler.start(Lifecycle.java:350) [java-util-0.27.9.jar:?]
    at com.metamx.common.lifecycle.Lifecycle.start(Lifecycle.java:259) [java-util-0.27.9.jar:?]
    at io.druid.guice.LifecycleModule$2.start(LifecycleModule.java:155) [druid-api-0.9.1.1.jar:0.9.1.1]
    at io.druid.cli.GuiceRunnable.initLifecycle(GuiceRunnable.java:91) [druid-services-0.9.1.1.jar:0.9.1.1]
    at io.druid.cli.CliPeon.run(CliPeon.java:274) [druid-services-0.9.1.1.jar:0.9.1.1]
    at io.druid.cli.Main.main(Main.java:105) [druid-services-0.9.1.1.jar:0.9.1.1]
2016-09-03T02:15:35,139 INFO [main] io.druid.indexing.common.actions.RemoteTaskActionClient - Will try again in [PT3.530S].
2016-09-03T02:15:38,671 INFO [main] io.druid.indexing.common.actions.RemoteTaskActionClient - Submitting action for task[index_hadoop_wikiticker_2016-09-03T02:15:32.143Z] to overlord[http://192.168.1.101:8090/druid/indexer/v1/action]: LockTryAcquireAction{interval=2015-09-12T00:00:00.000Z/2015-09-13T00:00:00.000Z}
```

But I can't find any exception logs in the overlord console. Overlord log as: 

```
2016-09-03T02:36:34,046 INFO [MonitorScheduler-0] com.metamx.emitter.core.LoggingEmitter - Event [{"feed":"metrics","timestamp":"2016-09-03T02:36:34.046Z","service":"druid/overlord","host":"192.168.1.101:8090","metric":"jetty/numOpenConnections","value":1}]
2016-09-03T02:36:34,046 INFO [MonitorScheduler-0] com.metamx.emitter.core.LoggingEmitter - Event [{"feed":"metrics","timestamp":"2016-09-03T02:36:34.046Z","service":"druid/overlord","host":"192.168.1.101:8090","metric":"jvm/mem/max","value":257425408,"memKind":"heap"}]
2016-09-03T02:36:34,046 INFO [MonitorScheduler-0] com.metamx.emitter.core.LoggingEmitter - Event [{"feed":"metrics","timestamp":"2016-09-03T02:36:34.046Z","service":"druid/overlord","host":"192.168.1.101:8090","metric":"jvm/mem/committed","value":257425408,"memKind":"heap"}]
2016-09-03T02:36:34,047 INFO [MonitorScheduler-0] com.metamx.emitter.core.LoggingEmitter - Event [{"feed":"metrics","timestamp":"2016-09-03T02:36:34.046Z","service":"druid/overlord","host":"192.168.1.101:8090","metric":"jvm/mem/used","value":75072216,"memKind":"heap"}]
2016-09-03T02:36:34,047 INFO [MonitorScheduler-0] com.metamx.emitter.core.LoggingEmitter - Event [{"feed":"metrics","timestamp":"2016-09-03T02:36:34.047Z","service":"druid/overlord","host":"192.168.1.101:8090","metric":"jvm/mem/init","value":268435456,"memKind":"heap"}]
2016-09-03T02:36:34,047 INFO [MonitorScheduler-0] com.metamx.emitter.core.LoggingEmitter - Event [{"feed":"metrics","timestamp":"2016-09-03T02:36:34.047Z","service":"druid/overlord","host":"192.168.1.101:8090","metric":"jvm/mem/max","value":-1,"memKind":"nonheap"}]
2016-09-03T02:36:34,047 INFO [MonitorScheduler-0] com.metamx.emitter.core.LoggingEmitter - Event [{"feed":"metrics","timestamp":"2016-09-03T02:36:34.047Z","service":"druid/overlord","host":"192.168.1.101:8090","metric":"jvm/mem/committed","value":60555264,"memKind":"nonheap"}]
2016-09-03T02:36:34,047 INFO [MonitorScheduler-0] com.metamx.emitter.core.LoggingEmitter - Event [{"feed":"metrics","timestamp":"2016-09-03T02:36:34.047Z","service":"druid/overlord","host":"192.168.1.101:8090","metric":"jvm/mem/used","value":59473824,"memKind":"nonheap"}]
2016-09-03T02:36:34,047 INFO [MonitorScheduler-0] com.metamx.emitter.core.LoggingEmitter - Event [{"feed":"metrics","timestamp":"2016-09-03T02:36:34.047Z","service":"druid/overlord","host":"192.168.1.101:8090","metric":"jvm/mem/init","value":2555904,"memKind":"nonheap"}]
2016-09-03T02:36:34,047 INFO [MonitorScheduler-0] com.metamx.emitter.core.LoggingEmitter - Event [{"feed":"metrics","timestamp":"2016-09-03T02:36:34.047Z","service":"druid/overlord","host":"192.168.1.101:8090","metric":"jvm/pool/max","value":251658240,"poolKind":"nonheap","poolName":"Code Cache"}]
2016-09-03T02:36:34,047 INFO [MonitorScheduler-0] com.metamx.emitter.core.LoggingEmitter - Event [{"feed":"metrics","timestamp":"2016-09-03T02:36:34.047Z","service":"druid/overlord","host":"192.168.1.101:8090","metric":"jvm/pool/committed","value":11272192,"poolKind":"nonheap","poolName":"Code Cache"}]
2016-09-03T02:36:34,047 INFO [MonitorScheduler-0] com.metamx.emitter.core.LoggingEmitter - Event [{"feed":"metrics","timestamp":"2016-09-03T02:36:34.047Z","service":"druid/overlord","host":"192.168.1.101:8090","metric":"jvm/pool/used","value":11196672,"poolKind":"nonheap","poolName":"Code Cache"}]
2016-09-03T02:36:34,047 INFO [MonitorScheduler-0] com.metamx.emitter.core.LoggingEmitter - Event [{"feed":"metrics","timestamp":"2016-09-03T02:36:34.047Z","service":"druid/overlord","host":"192.168.1.101:8090","metric":"jvm/pool/init","value":2555904,"poolKind":"nonheap","poolName":"Code Cache"}]
2016-09-03T02:36:34,047 INFO [MonitorScheduler-0] com.metamx.emitter.core.LoggingEmitter - Event [{"feed":"metrics","timestamp":"2016-09-03T02:36:34.047Z","service":"druid/overlord","host":"192.168.1.101:8090","metric":"jvm/pool/max","value":-1,"poolKind":"nonheap","poolName":"Metaspace"}]
2016-09-03T02:36:34,047 INFO [MonitorScheduler-0] com.metamx.emitter.core.LoggingEmitter - Event [{"feed":"metrics","timestamp":"2016-09-03T02:36:34.047Z","service":"druid/overlord","host":"192.168.1.101:8090","metric":"jvm/pool/committed","value":43515904,"poolKind":"nonheap","poolName":"Metaspace"}]
2016-09-03T02:36:34,047 INFO [MonitorScheduler-0] com.metamx.emitter.core.LoggingEmitter - Event [{"feed":"metrics","timestamp":"2016-09-03T02:36:34.047Z","service":"druid/overlord","host":"192.168.1.101:8090","metric":"jvm/pool/used","value":42724472,"poolKind":"nonheap","poolName":"Metaspace"}]
2016-09-03T02:36:34,048 INFO [MonitorScheduler-0] com.metamx.emitter.core.LoggingEmitter - Event [{"feed":"metrics","timestamp":"2016-09-03T02:36:34.047Z","service":"druid/overlord","host":"192.168.1.101:8090","metric":"jvm/pool/init","value":0,"poolKind":"nonheap","poolName":"Metaspace"}]
2016-09-03T02:36:34,048 INFO [MonitorScheduler-0] com.metamx.emitter.core.LoggingEmitter - Event [{"feed":"metrics","timestamp":"2016-09-03T02:36:34.048Z","service":"druid/overlord","host":"192.168.1.101:8090","metric":"jvm/pool/max","value":1073741824,"poolKind":"nonheap","poolName":"Compressed Class Space"}]
2016-09-03T02:36:34,048 INFO [MonitorScheduler-0] com.metamx.emitter.core.LoggingEmitter - Event [{"feed":"metrics","timestamp":"2016-09-03T02:36:34.048Z","service":"druid/overlord","host":"192.168.1.101:8090","metric":"jvm/pool/committed","value":5767168,"poolKind":"nonheap","poolName":"Compressed Class Space"}]
2016-09-03T02:36:34,048 INFO [MonitorScheduler-0] com.metamx.emitter.core.LoggingEmitter - Event [{"feed":"metrics","timestamp":"2016-09-03T02:36:34.048Z","service":"druid/overlord","host":"192.168.1.101:8090","metric":"jvm/pool/used","value":5552680,"poolKind":"nonheap","poolName":"Compressed Class Space"}]
2016-09-03T02:36:34,048 INFO [MonitorScheduler-0] com.metamx.emitter.core.LoggingEmitter - Event [{"feed":"metrics","timestamp":"2016-09-03T02:36:34.048Z","service":"druid/overlord","host":"192.168.1.101:8090","metric":"jvm/pool/init","value":0,"poolKind":"nonheap","poolName":"Compressed Class Space"}]
2016-09-03T02:36:34,048 INFO [MonitorScheduler-0] com.metamx.emitter.core.LoggingEmitter - Event [{"feed":"metrics","timestamp":"2016-09-03T02:36:34.048Z","service":"druid/overlord","host":"192.168.1.101:8090","metric":"jvm/pool/max","value":67108864,"poolKind":"heap","poolName":"PS Eden Space"}]
2016-09-03T02:36:34,048 INFO [MonitorScheduler-0] com.metamx.emitter.core.LoggingEmitter - Event [{"feed":"metrics","timestamp":"2016-09-03T02:36:34.048Z","service":"druid/overlord","host":"192.168.1.101:8090","metric":"jvm/pool/committed","value":67108864,"poolKind":"heap","poolName":"PS Eden Space"}]
2016-09-03T02:36:34,048 INFO [MonitorScheduler-0] com.metamx.emitter.core.LoggingEmitter - Event [{"feed":"metrics","timestamp":"2016-09-03T02:36:34.048Z","service":"druid/overlord","host":"192.168.1.101:8090","metric":"jvm/pool/used","value":60478552,"poolKind":"heap","poolName":"PS Eden Space"}]
2016-09-03T02:36:34,048 INFO [MonitorScheduler-0] com.metamx.emitter.core.LoggingEmitter - Event [{"feed":"metrics","timestamp":"2016-09-03T02:36:34.048Z","service":"druid/overlord","host":"192.168.1.101:8090","metric":"jvm/pool/init","value":67108864,"poolKind":"heap","poolName":"PS Eden Space"}]
2016-09-03T02:36:34,048 INFO [MonitorScheduler-0] com.metamx.emitter.core.LoggingEmitter - Event [{"feed":"metrics","timestamp":"2016-09-03T02:36:34.048Z","service":"druid/overlord","host":"192.168.1.101:8090","metric":"jvm/pool/max","value":11010048,"poolKind":"heap","poolName":"PS Survivor Space"}]
2016-09-03T02:36:34,048 INFO [MonitorScheduler-0] com.metamx.emitter.core.LoggingEmitter - Event [{"feed":"metrics","timestamp":"2016-09-03T02:36:34.048Z","service":"druid/overlord","host":"192.168.1.101:8090","metric":"jvm/pool/committed","value":11010048,"poolKind":"heap","poolName":"PS Survivor Space"}]
2016-09-03T02:36:34,048 INFO [MonitorScheduler-0] com.metamx.emitter.core.LoggingEmitter - Event [{"feed":"metrics","timestamp":"2016-09-03T02:36:34.048Z","service":"druid/overlord","host":"192.168.1.101:8090","metric":"jvm/pool/used","value":3970408,"poolKind":"heap","poolName":"PS Survivor Space"}]
2016-09-03T02:36:34,048 INFO [MonitorScheduler-0] com.metamx.emitter.core.LoggingEmitter - Event [{"feed":"metrics","timestamp":"2016-09-03T02:36:34.048Z","service":"druid/overlord","host":"192.168.1.101:8090","metric":"jvm/pool/init","value":11010048,"poolKind":"heap","poolName":"PS Survivor Space"}]
2016-09-03T02:36:34,048 INFO [MonitorScheduler-0] com.metamx.emitter.core.LoggingEmitter - Event [{"feed":"metrics","timestamp":"2016-09-03T02:36:34.048Z","service":"druid/overlord","host":"192.168.1.101:8090","metric":"jvm/pool/max","value":179306496,"poolKind":"heap","poolName":"PS Old Gen"}]
2016-09-03T02:36:34,049 INFO [MonitorScheduler-0] com.metamx.emitter.core.LoggingEmitter - Event [{"feed":"metrics","timestamp":"2016-09-03T02:36:34.049Z","service":"druid/overlord","host":"192.168.1.101:8090","metric":"jvm/pool/committed","value":179306496,"poolKind":"heap","poolName":"PS Old Gen"}]
2016-09-03T02:36:34,049 INFO [MonitorScheduler-0] com.metamx.emitter.core.LoggingEmitter - Event [{"feed":"metrics","timestamp":"2016-09-03T02:36:34.049Z","service":"druid/overlord","host":"192.168.1.101:8090","metric":"jvm/pool/used","value":10773264,"poolKind":"heap","poolName":"PS Old Gen"}]
2016-09-03T02:36:34,049 INFO [MonitorScheduler-0] com.metamx.emitter.core.LoggingEmitter - Event [{"feed":"metrics","timestamp":"2016-09-03T02:36:34.049Z","service":"druid/overlord","host":"192.168.1.101:8090","metric":"jvm/pool/init","value":179306496,"poolKind":"heap","poolName":"PS Old Gen"}]
2016-09-03T02:36:34,049 INFO [MonitorScheduler-0] com.metamx.emitter.core.LoggingEmitter - Event [{"feed":"metrics","timestamp":"2016-09-03T02:36:34.049Z","service":"druid/overlord","host":"192.168.1.101:8090","metric":"jvm/gc/count","value":0,"gcName":"PS Scavenge"}]
2016-09-03T02:36:34,049 INFO [MonitorScheduler-0] com.metamx.emitter.core.LoggingEmitter - Event [{"feed":"metrics","timestamp":"2016-09-03T02:36:34.049Z","service":"druid/overlord","host":"192.168.1.101:8090","metric":"jvm/gc/time","value":0,"gcName":"PS Scavenge"}]
2016-09-03T02:36:34,049 INFO [MonitorScheduler-0] com.metamx.emitter.core.LoggingEmitter - Event [{"feed":"metrics","timestamp":"2016-09-03T02:36:34.049Z","service":"druid/overlord","host":"192.168.1.101:8090","metric":"jvm/gc/count","value":0,"gcName":"PS MarkSweep"}]
2016-09-03T02:36:34,049 INFO [MonitorScheduler-0] com.metamx.emitter.core.LoggingEmitter - Event [{"feed":"metrics","timestamp":"2016-09-03T02:36:34.049Z","service":"druid/overlord","host":"192.168.1.101:8090","metric":"jvm/gc/time","value":0,"gcName":"PS MarkSweep"}]
2016-09-03T02:36:34,049 INFO [MonitorScheduler-0] com.metamx.emitter.core.LoggingEmitter - Event [{"feed":"metrics","timestamp":"2016-09-03T02:36:34.049Z","service":"druid/overlord","host":"192.168.1.101:8090","metric":"jvm/bufferpool/capacity","value":1627696,"bufferpoolName":"direct"}]
2016-09-03T02:36:34,049 INFO [MonitorScheduler-0] com.metamx.emitter.core.LoggingEmitter - Event [{"feed":"metrics","timestamp":"2016-09-03T02:36:34.049Z","service":"druid/overlord","host":"192.168.1.101:8090","metric":"jvm/bufferpool/used","value":1627696,"bufferpoolName":"direct"}]
2016-09-03T02:36:34,050 INFO [MonitorScheduler-0] com.metamx.emitter.core.LoggingEmitter - Event [{"feed":"metrics","timestamp":"2016-09-03T02:36:34.050Z","service":"druid/overlord","host":"192.168.1.101:8090","metric":"jvm/bufferpool/count","value":79,"bufferpoolName":"direct"}]
2016-09-03T02:36:34,050 INFO [MonitorScheduler-0] com.metamx.emitter.core.LoggingEmitter - Event [{"feed":"metrics","timestamp":"2016-09-03T02:36:34.050Z","service":"druid/overlord","host":"192.168.1.101:8090","metric":"jvm/bufferpool/capacity","value":0,"bufferpoolName":"mapped"}]
2016-09-03T02:36:34,050 INFO [MonitorScheduler-0] com.metamx.emitter.core.LoggingEmitter - Event [{"feed":"metrics","timestamp":"2016-09-03T02:36:34.050Z","service":"druid/overlord","host":"192.168.1.101:8090","metric":"jvm/bufferpool/used","value":0,"bufferpoolName":"mapped"}]
2016-09-03T02:36:34,050 INFO [MonitorScheduler-0] com.metamx.emitter.core.LoggingEmitter - Event [{"feed":"metrics","timestamp":"2016-09-03T02:36:34.050Z","service":"druid/overlord","host":"192.168.1.101:8090","metric":"jvm/bufferpool/count","value":0,"bufferpoolName":"mapped"}]
2016-09-03T02:36:34,786 INFO [TaskQueue-StorageSync] io.druid.indexing.overlord.TaskQueue - Synced 1 tasks from storage (0 tasks added, 0 tasks removed).
```

Anybody know how to solve this error?

There is a same error report: [Google Groups](https://groups.google.com/forum/#!topic/druid-user/TnyNqh-9g7g)

**Comment by edwardzjl** [comment]
same problem, and the task just wont stop
