### ISSUE TITLE
Peon hung up when converting segment from v8 to v9

### ISSUE THREAD

**Issue by JackyWoo** [apache/incubator-druid#3558]
hi all, I have a problem when use Indexing service.  I use druid 0.9.1.1, centos 6.7, glibc 2.12 and  kernal 2.6.32-573.el6.x86_64

A peon hung up when converting segment from v8 to v9. And it waited hand off all the time. The log is like :

```
2016-10-08T16:15:31,150 INFO [add_rt_atm_event_minute-2016-10-08T15:00:00.000+08:00-persist-n-merge] io.druid.segment.IndexIO$DefaultIndexIOHandler - Converting v8[/opt/druid/default/var/task/index_realtime_add_rt_atm_event_minute_2016-10-08T07:00:00.000Z_3_0/work/persist/add_rt_atm_event_minute/2016-10-08T15:00:00.000+08:00_2016-10-08T16:00:00.000+08:00/merged/v8-tmp] to v9[/opt/druid/default/var/task/index_realtime_add_rt_atm_event_minute_2016-10-08T07:00:00.000Z_3_0/work/persist/add_rt_atm_event_minute/2016-10-08T15:00:00.000+08:00_2016-10-08T16:00:00.000+08:00/merged]
2016-10-08T16:15:31,150 INFO [add_rt_atm_event_minute-2016-10-08T15:00:00.000+08:00-persist-n-merge] io.druid.segment.IndexIO$DefaultIndexIOHandler - Processing file[dim_ad_access_status.drd]
2016-10-08T16:15:31,237 INFO [add_rt_atm_event_minute-2016-10-08T15:00:00.000+08:00-persist-n-merge] io.druid.segment.IndexIO$DefaultIndexIOHandler - Dimension[ad_access_status] is single value, converting...
2016-10-08T16:23:08,459 INFO [coordinator_handoff_scheduled_0] io.druid.segment.realtime.plumber.CoordinatorBasedSegmentHandoffNotifier - Still waiting for Handoff for Segments : [[SegmentDescriptor{interval=2016-10-08T15:00:00.000+08:00/2016-10-08T16:00:00.000+08:00, version='2016-10-08T15:00:09.130+08:00', partitionNumber=3}]]
2016-10-08T16:24:08,459 INFO [coordinator_handoff_scheduled_0] io.druid.segment.realtime.plumber.CoordinatorBasedSegmentHandoffNotifier - Still waiting for Handoff for Segments : [[SegmentDescriptor{interval=2016-10-08T15:00:00.000+08:00/2016-10-08T16:00:00.000+08:00, version='2016-10-08T15:00:09.130+08:00', partitionNumber=3}]]
2016-10-08T16:25:08,459 INFO [coordinator_handoff_scheduled_0] io.druid.segment.realtime.plumber.CoordinatorBasedSegmentHandoffNotifier - Still waiting for Handoff for Segments : [[SegmentDescriptor{interval=2016-10-08T15:00:00.000+08:00/2016-10-08T16:00:00.000+08:00, version='2016-10-08T15:00:09.130+08:00', partitionNumber=3}]]
...

```

I found thread "add_rt_atm_event_minute-2016-10-08T15:00:00.000+08:00-persist-n-merge"  do the converting. So I printed the Java stack:

```
"add_rt_atm_event_minute-2016-10-08T15:00:00.000+08:00-persist-n-merge" daemon prio=10 tid=0x00007ff804051000 nid=0x2db3 runnable [0x00007ffa3f25d000]
   java.lang.Thread.State: RUNNABLE
        at net.jpountz.lz4.LZ4JNI.LZ4_compressHC(Native Method)
        at net.jpountz.lz4.LZ4HCJNICompressor.compress(LZ4HCJNICompressor.java:44)
        at net.jpountz.lz4.LZ4Compressor.compress(LZ4Compressor.java:70)
        at net.jpountz.lz4.LZ4Compressor.compress(LZ4Compressor.java:99)
        at net.jpountz.lz4.LZ4Compressor.compress(LZ4Compressor.java:108)
        at io.druid.segment.data.CompressedObjectStrategy$LZ4Compressor.compress(CompressedObjectStrategy.java:255)
        at io.druid.segment.data.CompressedObjectStrategy.toBytes(CompressedObjectStrategy.java:323)
        at io.druid.segment.data.CompressedObjectStrategy.toBytes(CompressedObjectStrategy.java:42)
        at io.druid.segment.data.GenericIndexed.fromIterable(GenericIndexed.java:83)
        at io.druid.segment.data.CompressedVSizeIntsIndexedSupplier.fromList(CompressedVSizeIntsIndexedSupplier.java:201)
        at io.druid.segment.IndexIO$DefaultIndexIOHandler.convertV8toV9(IndexIO.java:709)
        at io.druid.segment.IndexMerger.makeIndexFiles(IndexMerger.java:1047)
        at io.druid.segment.IndexMerger.merge(IndexMerger.java:423)
        at io.druid.segment.IndexMerger.mergeQueryableIndex(IndexMerger.java:244)
        at io.druid.segment.IndexMerger.mergeQueryableIndex(IndexMerger.java:217)
        at io.druid.segment.realtime.plumber.RealtimePlumber$4.doRun(RealtimePlumber.java:548)
        at io.druid.common.guava.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

Because of native method I printed the C stack:

```
Thread 3 (Thread 0x7ffa3f25f700 (LWP 11699)):
#0  0x0000003ab42f80ce in __lll_lock_wait_private () from /lib64/libc.so.6
#1  0x0000003ab427cf7e in _L_lock_5746 () from /lib64/libc.so.6
#2  0x0000003ab4278a8b in _int_free () from /lib64/libc.so.6
#3  0x00007ffa46beb5e9 in LZ4_freeHC () from /opt/druid/druid-0.9.1.1/var/tmp/liblz4-java1423469244383277702.so
#4  0x00007ffa46beb8c1 in LZ4_compressHC2_limitedOutput () from /opt/druid/druid-0.9.1.1/var/tmp/liblz4-java1423469244383277702.so
#5  0x00007ffa46be345a in Java_net_jpountz_lz4_LZ4JNI_LZ4_1compressHC () from /opt/druid/druid-0.9.1.1/var/tmp/liblz4-java1423469244383277702.so
#6  0x00007ffa78e0ad98 in ?? ()
#7  0x00007ffa3f25dd48 in ?? ()
#8  0x0000000000000000 in ?? ()
```

Through the stacks I found the thread hung up when compressing segment with "LZ4". I googled "LZ4", but found nothing useful.

I also googled "__lll_lock_wait_private " method, maybe there is a dead lock. Because  I am not a C programmer. I do not understand much more.

Does anyone have the same problem. Anyone can help?

**Comment by JackyWoo** [comment]
The problem have been solved. I just use "LZF" instead of "LZ4" to compress dimensions.  But the real reason which causes "LZ4" hanging up peon is still not known yet.

I hope this may help somebody who have the same problem.
