### ISSUE TITLE
Druid ingestion ends with SUCCESS status but exception is thrown at the end

### ISSUE THREAD

**Issue by vvararu** [apache/incubator-druid#3851]
Hi guys,

I run a ingestion job druid (0.9.1.1) + hadoop 2.7.1 (custom version declared in common conf druid.extensions.hadoopDependenciesDir=/druid/hadoop-dependencies).

As deep storage - hdfs in a docker container.

Loaded extensions: druid.extensions.loadList=["druid-histogram", "druid-datasketches", "postgresql-metadata-storage", "druid-kafka-indexing-service", "druid-hdfs-storage"]

The job finishes successfully, data is ingested but at the very end i get the next exception:

> 2017-01-13T09:44:48,064 INFO [task-runner-0-priority-0] io.druid.indexing.worker.executor.ExecutorLifecycle - Task completed with status: {
>   "id" : "index_hadoop_impression_segments5_2017-01-13T09:42:05.410Z",
>   "status" : "SUCCESS",
>   "duration" : 159082
> }

after fiew lines:

> 2017-01-13 09:44:48,136 Thread-2 ERROR Unable to register shutdown hook because JVM is shutting down. java.lang.IllegalStateException: Not started
> 	at io.druid.common.config.Log4jShutdown.addShutdownCallback(Log4jShutdown.java:45)
> 	at org.apache.logging.log4j.core.impl.Log4jContextFactory.addShutdownCallback(Log4jContextFactory.java:273)
> 	at org.apache.logging.log4j.core.LoggerContext.setUpShutdownHook(LoggerContext.java:256)
> 	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:216)
> 	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:145)
> 	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:41)
> 	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:182)
> 	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(AbstractLoggerAdapter.java:103)
> 	at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:43)
> 	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:42)
> 	at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:29)
> 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:284)
> 	at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:155)
> 	at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:132)
> 	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:273)
> 	at org.apache.hadoop.hdfs.LeaseRenewer.<clinit>(LeaseRenewer.java:72)
> 	at org.apache.hadoop.hdfs.DFSClient.getLeaseRenewer(DFSClient.java:699)
> 	at org.apache.hadoop.hdfs.DFSClient.close(DFSClient.java:859)
> 	at org.apache.hadoop.hdfs.DistributedFileSystem.close(DistributedFileSystem.java:853)
> 	at org.apache.hadoop.fs.FileSystem$Cache.closeAll(FileSystem.java:2407)
> 	at org.apache.hadoop.fs.FileSystem$Cache$ClientFinalizer.run(FileSystem.java:2424)
> 	at org.apache.hadoop.util.ShutdownHookManager$1.run(ShutdownHookManager.java:54)

**Comment by gianm** [comment]
Original report in https://groups.google.com/d/topic/druid-user/5qKGnXsmqMw/discussion. I believe this is harmless, but annoying.

**Comment by NirajaM** [comment]
In my case job is failing. No other error is there in the log. Could you please confirm if is failing not because of this issue?

**Comment by RonnieTsang** [comment]
@gianm hi gianm, I am stuck with this issue too. and the historical node wasn't aware of the indexing task at all. so definitely there is no segment file generated. That is not so "harmless" in our case...
Do you know what the reason is causing this problem? I can't find any other error log message to debug. Great appreciation if there is any workaround to avoid this issue. Thanks!

**Comment by zhxiaom5** [comment]
i meet this to

**Comment by zhxiaom5** [comment]
I use  imply-2.0.0 and hadoop 2.7.3 
my log is 
```
2017-10-16T07:05:17,572 INFO [task-runner-0-priority-0] io.druid.indexing.worker.executor.ExecutorLifecycle - Task completed with status: {
  "id" : "index_hadoop_apmbox-data_2017-10-16T06:45:53.604Z",
  "status" : "SUCCESS",
  "duration" : 1148556
}
2017-10-16T07:05:17,583 INFO [main] com.metamx.common.lifecycle.Lifecycle$AnnotationBasedHandler - Invoking stop method[public void io.druid.server.coordination.AbstractDataSegmentAnnouncer.stop()] on object[io.druid.server.coordination.BatchDataSegmentAnnouncer@539c4830].
2017-10-16T07:05:17,583 INFO [main] io.druid.server.coordination.AbstractDataSegmentAnnouncer - Stopping class io.druid.server.coordination.BatchDataSegmentAnnouncer with config[io.druid.server.initialization.ZkPathsConfig@22e2266d]
2017-10-16T07:05:17,583 INFO [main] io.druid.curator.announcement.Announcer - unannouncing [/druid/announcements/druidio.cdn.gz4399.com:8109]
2017-10-16T07:05:17,604 INFO [main] com.metamx.common.lifecycle.Lifecycle$AnnotationBasedHandler - Invoking stop method[public void io.druid.server.listener.announcer.ListenerResourceAnnouncer.stop()] on object[io.druid.query.lookup.LookupResourceListenerAnnouncer@7994a0d1].
2017-10-16T07:05:17,604 INFO [main] io.druid.curator.announcement.Announcer - unannouncing [/druid/listeners/lookups/__default/druidio.cdn.gz4399.com:8109]
2017-10-16T07:05:17,606 INFO [main] io.druid.server.listener.announcer.ListenerResourceAnnouncer - Unannouncing start time on [/druid/listeners/lookups/__default/druidio.cdn.gz4399.com:8109]
2017-10-16T07:05:17,606 INFO [main] com.metamx.common.lifecycle.Lifecycle$AnnotationBasedHandler - Invoking stop method[public void io.druid.query.lookup.LookupReferencesManager.stop()] on object[io.druid.query.lookup.LookupReferencesManager@7a66c35a].
2017-10-16T07:05:17,606 INFO [main] io.druid.query.lookup.LookupReferencesManager - Stopping lookup factory references manager
2017-10-16T07:05:17,612 INFO [main] org.eclipse.jetty.server.ServerConnector - Stopped ServerConnector@3457cc8d{HTTP/1.1}{0.0.0.0:8109}
2017-10-16T07:05:17,615 INFO [main] org.eclipse.jetty.server.handler.ContextHandler - Stopped o.e.j.s.ServletContextHandler@1785d194{/,null,UNAVAILABLE}
2017-10-16T07:05:17,618 INFO [main] com.metamx.common.lifecycle.Lifecycle$AnnotationBasedHandler - Invoking stop method[public void io.druid.indexing.worker.executor.ExecutorLifecycle.stop() throws java.lang.Exception] on object[io.druid.indexing.worker.executor.ExecutorLifecycle@73afe2b7].
2017-10-16T07:05:17,619 INFO [main] com.metamx.common.lifecycle.Lifecycle$AnnotationBasedHandler - Invoking stop method[public void io.druid.indexing.overlord.ThreadPoolTaskRunner.stop()] on object[io.druid.indexing.overlord.ThreadPoolTaskRunner@1c84d80a].
2017-10-16T07:05:17,620 INFO [main] com.metamx.common.lifecycle.Lifecycle$AnnotationBasedHandler - Invoking stop method[public void io.druid.curator.discovery.ServerDiscoverySelector.stop() throws java.io.IOException] on object[io.druid.curator.discovery.ServerDiscoverySelector@285583d4].
2017-10-16T07:05:17,624 INFO [main] com.metamx.common.lifecycle.Lifecycle$AnnotationBasedHandler - Invoking stop method[public void io.druid.curator.announcement.Announcer.stop()] on object[io.druid.curator.announcement.Announcer@9accff0].
2017-10-16T07:05:17,625 INFO [main] com.metamx.common.lifecycle.Lifecycle$AnnotationBasedHandler - Invoking stop method[public void io.druid.curator.discovery.ServerDiscoverySelector.stop() throws java.io.IOException] on object[io.druid.curator.discovery.ServerDiscoverySelector@83bb0f].
2017-10-16T07:05:17,625 INFO [main] io.druid.curator.CuratorModule - Stopping Curator
2017-10-16T07:05:17,626 INFO [Curator-Framework-0] org.apache.curator.framework.imps.CuratorFrameworkImpl - backgroundOperationsLoop exiting
2017-10-16T07:05:17,628 INFO [main] org.apache.zookeeper.ZooKeeper - Session: 0x15f22e66fb00049 closed
2017-10-16T07:05:17,628 INFO [main-EventThread] org.apache.zookeeper.ClientCnxn - EventThread shut down for session: 0x15f22e66fb00049
2017-10-16T07:05:17,628 INFO [main] com.metamx.common.lifecycle.Lifecycle$AnnotationBasedHandler - Invoking stop method[public void com.metamx.http.client.NettyHttpClient.stop()] on object[com.metamx.http.client.NettyHttpClient@5e26f1ed].
2017-10-16T07:05:17,648 INFO [main] com.metamx.common.lifecycle.Lifecycle$AnnotationBasedHandler - Invoking stop method[public void io.druid.storage.hdfs.HdfsStorageAuthentication.stop()] on object[io.druid.storage.hdfs.HdfsStorageAuthentication@4c51077d].
2017-10-16T07:05:17,648 INFO [main] com.metamx.common.lifecycle.Lifecycle$AnnotationBasedHandler - Invoking stop method[public void com.metamx.metrics.MonitorScheduler.stop()] on object[com.metamx.metrics.MonitorScheduler@733c464f].
2017-10-16T07:05:17,648 INFO [main] com.metamx.common.lifecycle.Lifecycle$AnnotationBasedHandler - Invoking stop method[public void com.metamx.emitter.service.ServiceEmitter.close() throws java.io.IOException] on object[com.metamx.emitter.service.ServiceEmitter@180b3819].
2017-10-16T07:05:17,648 INFO [main] com.metamx.common.lifecycle.Lifecycle$AnnotationBasedHandler - Invoking stop method[public void io.druid.initialization.Log4jShutterDownerModule$Log4jShutterDowner.stop()] on object[io.druid.initialization.Log4jShutterDownerModule$Log4jShutterDowner@3f6f3cc].
2017-10-16 07:05:17,690 Thread-2 ERROR Unable to register shutdown hook because JVM is shutting down. java.lang.IllegalStateException: Not started
	at io.druid.common.config.Log4jShutdown.addShutdownCallback(Log4jShutdown.java:45)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.addShutdownCallback(Log4jContextFactory.java:273)
	at org.apache.logging.log4j.core.LoggerContext.setUpShutdownHook(LoggerContext.java:256)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:216)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:145)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:41)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:182)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(AbstractLoggerAdapter.java:103)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:43)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:42)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:29)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:284)
	at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:155)
	at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:132)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:685)
	at org.apache.hadoop.hdfs.LeaseRenewer.<clinit>(LeaseRenewer.java:72)
	at org.apache.hadoop.hdfs.DFSClient.getLeaseRenewer(DFSClient.java:699)
	at org.apache.hadoop.hdfs.DFSClient.close(DFSClient.java:859)
	at org.apache.hadoop.hdfs.DistributedFileSystem.close(DistributedFileSystem.java:853)
	at org.apache.hadoop.fs.FileSystem$Cache.closeAll(FileSystem.java:2407)
	at org.apache.hadoop.fs.FileSystem$Cache$ClientFinalizer.run(FileSystem.java:2424)
	at org.apache.hadoop.util.ShutdownHookManager$1.run(ShutdownHookManager.java:54)
```

**Comment by liubiggun** [comment]
Any progress？

**Comment by bigtree3721** [comment]
I saw the same issues from overlord's log via overlord console GUI page. Initially I also think this is a bug. But after survey, I found that my historical node is down as I forget to bring this node up. After historical node is up, so I can query the result from broker now and druid system behave well.

**Comment by bigtree3721** [comment]
BTW, I use druid 0.12.0 which carries extension of  hadoop 2.7.3, my Hadoop cluster uses hadoop 2.9.0. 
So if this is case in your environment, pay attention to different hadoop version issue. See 
http://druid.io/docs/latest/operations/other-hadoop.html

**Comment by gavinju** [comment]
I have encountered the same error，the druid version is 0.12.2.
How to solve it?
Can anyone give me a suggestion?

**Comment by jon-wei** [comment]
This exception `2017-10-16 07:05:17,690 Thread-2 ERROR Unable to register shutdown hook because JVM is shutting down. java.lang.IllegalStateException: Not started` is safe to ignore.

If a task is failing, it is failing for some other reason.

**Comment by YingHun** [comment]
I also  meet this issue

`
2018-10-29 09:35:15,235 Thread-3 ERROR Unable to register shutdown hook because JVM is shutting down. java.lang.IllegalStateException: Not started
	at io.druid.common.config.Log4jShutdown.addShutdownCallback(Log4jShutdown.java:47)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.addShutdownCallback(Log4jContextFactory.java:273)
	at org.apache.logging.log4j.core.LoggerContext.setUpShutdownHook(LoggerContext.java:256)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:216)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:145)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:41)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:182)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(AbstractLoggerAdapter.java:103)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:43)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:42)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:29)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:253)
	at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:155)
	at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:132)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:685)
	at org.apache.hadoop.hdfs.LeaseRenewer.<clinit>(LeaseRenewer.java:72)
	at org.apache.hadoop.hdfs.DFSClient.getLeaseRenewer(DFSClient.java:818)
	at org.apache.hadoop.hdfs.DFSClient.close(DFSClient.java:956)
	at org.apache.hadoop.hdfs.DistributedFileSystem.close(DistributedFileSystem.java:1079)
	at org.apache.hadoop.fs.FileSystem$Cache.closeAll(FileSystem.java:2760)
	at org.apache.hadoop.fs.FileSystem$Cache$ClientFinalizer.run(FileSystem.java:2777)
	at org.apache.hadoop.util.ShutdownHookManager$1.run(ShutdownHookManager.java:54)
`

**Comment by jihoonson** [comment]
I think this issue was fixed in https://github.com/apache/incubator-druid/pull/6864. Please reopen if it happens again.

**Comment by buckeyze** [comment]
https://groups.google.com/forum/m/?utm_medium=email&utm_source=footer#!msg/druid-user/5qmrmMEDD8g/yrh7wOVVBAAJ

I just posted about my similar issue in the Druid forums at the link above. I would be very grateful if you could recommend how to fix my problem. I am also getting the unable to register shutdown hook in my logs. Thank you very much

**Comment by 87139511** [comment]
I have same problem .how to solve it?

**Comment by 87139511** [comment]
my druid.version is 0.12.3

**Comment by salmanbw** [comment]
Hi Team.. I am also facing the same error and in my case, no data is ingested into segment. My segment granularity is hour, so after a certain point, no data is getting ingested into druid and it's throwing this error only. The task status is SUCCESS. Not sure how to debug it. It would be great help if you can help with it.
