### ISSUE TITLE
doubleLast function not working on firehose re-indexing

### ISSUE THREAD

**Issue by naman-gupta810** [apache/incubator-druid#4011]
If i give index task for existing datasource in which i want last value function to be used, then it gives me ClassCastException. I think it passes the last value only to the combine function not serialziable pair. Here is logs which I am getting on the console and the query which I fired.

Please let me know if you need any further logs or information. Thanks.

Log:
2017-03-06T06:47:12,983 ERROR [task-runner-0-priority-0] io.druid.indexing.overlord.ThreadPoolTaskRunner - Exception while running task[IndexTask{id=index_RAMBO_DAILY_TEST_FINAL2_2017-03-06T06:38:41.555Z, type=index, dataSource=RAMBO_DAILY_TEST_FINAL2}]
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.ClassCastException: io.druid.collections.SerializablePair cannot be cast to java.lang.Number
                at com.google.common.base.Throwables.propagate(Throwables.java:160) ~[guava-16.0.1.jar:?]
                at io.druid.segment.realtime.appenderator.FiniteAppenderatorDriver.persist(FiniteAppenderatorDriver.java:240) ~[druid-server-0.10.0-rc1.jar:0.10.0-rc1]
                at io.druid.indexing.common.task.IndexTask.generateAndPublishSegments(IndexTask.java:453) ~[druid-indexing-service-0.10.0-rc1.jar:0.10.0-rc1]
                at io.druid.indexing.common.task.IndexTask.run(IndexTask.java:207) ~[druid-indexing-service-0.10.0-rc1.jar:0.10.0-rc1]
                at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:436) [druid-indexing-service-0.10.0-rc1.jar:0.10.0-rc1]
                at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:408) [druid-indexing-service-0.10.0-rc1.jar:0.10.0-rc1]
                at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_91]
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_91]
                at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.util.concurrent.ExecutionException: java.lang.ClassCastException: io.druid.collections.SerializablePair cannot be cast to java.lang.Number
                at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_91]
                at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_91]
                at io.druid.segment.realtime.appenderator.FiniteAppenderatorDriver.persist(FiniteAppenderatorDriver.java:232) ~[druid-server-0.10.0-rc1.jar:0.10.0-rc1]
                ... 8 more
Caused by: java.lang.ClassCastException: io.druid.collections.SerializablePair cannot be cast to java.lang.Number
                at io.druid.segment.FloatColumnSerializer.serialize(FloatColumnSerializer.java:77) ~[druid-processing-0.10.0-rc1.jar:0.10.0-rc1]
                at io.druid.segment.IndexMergerV9.mergeIndexesAndWriteColumns(IndexMergerV9.java:460) ~[druid-processing-0.10.0-rc1.jar:0.10.0-rc1]
                at io.druid.segment.IndexMergerV9.makeIndexFiles(IndexMergerV9.java:207) ~[druid-processing-0.10.0-rc1.jar:0.10.0-rc1]
                at io.druid.segment.IndexMerger.merge(IndexMerger.java:437) ~[druid-processing-0.10.0-rc1.jar:0.10.0-rc1]
                at io.druid.segment.IndexMerger.persist(IndexMerger.java:185) ~[druid-processing-0.10.0-rc1.jar:0.10.0-rc1]
                at io.druid.segment.IndexMerger.persist(IndexMerger.java:151) ~[druid-processing-0.10.0-rc1.jar:0.10.0-rc1]
                at io.druid.segment.realtime.appenderator.AppenderatorImpl.persistHydrant(AppenderatorImpl.java:1001) ~[druid-server-0.10.0-rc1.jar:0.10.0-rc1]
                at io.druid.segment.realtime.appenderator.AppenderatorImpl.access$200(AppenderatorImpl.java:95) ~[druid-server-0.10.0-rc1.jar:0.10.0-rc1]
                at io.druid.segment.realtime.appenderator.AppenderatorImpl$2.doCall(AppenderatorImpl.java:389) ~[druid-server-0.10.0-rc1.jar:0.10.0-rc1]
                at io.druid.common.guava.ThreadRenamingCallable.call(ThreadRenamingCallable.java:44) ~[druid-common-0.10.0-rc1.jar:0.10.0-rc1]
                ... 4 more
2017-03-06T06:47:12,988 INFO [task-runner-0-priority-0] io.druid.indexing.overlord.TaskRunnerUtils - Task [index_RAMBO_DAILY_TEST_FINAL2_2017-03-06T06:38:41.555Z] status changed to [FAILED].
2017-03-06T06:47:12,991 INFO [task-runner-0-priority-0] io.druid.indexing.worker.executor.ExecutorLifecycle - Task completed with status: {
  "id" : "index_RAMBO_DAILY_TEST_FINAL2_2017-03-06T06:38:41.555Z",
  "status" : "FAILED",
  "duration" : 502607
}

Query:
{
"type": "index",
"spec": {
"dataSchema": {
"dataSource": "RAMBO_DAILY_TEST_FINAL2",
"parser": {
"type": "string",
"parseSpec": {
"format": "json",
"timestampSpec": {
"column": "CREATED_TIMESTAMP",
"format": "ddMMyyyyHHmmss"
},
"dimensionsSpec": {
"dimensions": [],
"dimensionExclusions": [],
"spatialDimensions": []
}
}
},
"metricsSpec": [
{
"name" : "PMP_DSL_OPR_MODE_LAST",
"type" : "doubleLast",
"fieldName" : "PMP_DSL_OPR_MODE"
}
],
"granularitySpec": {
"type": "uniform",
"segmentGranularity": "year",
"queryGranularity": "all",
"intervals" : ["2017-03-01/2017-04-01"]
}
},
"ioConfig": {
"type": "index",
"firehose": {
"type"    : "ingestSegment",
"dataSource"   : "DSLAMMarch",
"interval" : "2017-03-01/2017-03-02",
"filter": null,
"dimensions": null,
"metrics": null
},
"taskCount": 4,
  "replicas": 1
}
}
}

**Comment by gianm** [comment]
@naman-aasaan, according to the docs,

> First and Last aggregator cannot be used in ingestion spec, and should only be specified as part of queries.

So the thing you're doing is not supported at this time. What are you trying to accomplish? Maybe there's another way or maybe this is a missing feature.

**Comment by naman-aasaan** [comment]
Hi Gianm, We have requirement of finding out last value with re-indexing from 24 hours of data.
 What is the way forward ? We were highly relying upon this aggregation type.

**Comment by gianm** [comment]
If you just want the last row matching a certain filter, you can do a select query with a filter, threshold: 1, and descending: true. You don't need reindexing for that.

If that's not what you want then could you describe what you're looking for in more detail?

**Comment by naman-aasaan** [comment]
Hi Gianm, 

We have raw data being stored in Druid data source and we need to send some of the aggregations on 24 hours of data to some other interface.

We are thinking to perform re indexing on 24 hours of raw data to prepare aggregated feed where we need to prepare multiple aggregations on the raw metrics like SUM, MIN, MAX, LAST.  etc. 

It looks odd to me if we have to read complete raw data again through standalone Java and prepare those required aggregations. We have around 8million rows coming per 15 mins and it comes to around 768 million for 24 hours.

Kindly suggest the way forward.

**Comment by gianm** [comment]
Could you use a groupBy query instead of reindexing to prepare the aggregation? With groupBy v2 we can now spill to disk so the only limit is disk space. That should work, since groupBy supports all those aggregations.

If you have to use reindexing, the for that to work, someone (possibly you) would have to make the last aggregators work at indexing time. This would probably involve a new column type (pair of timestamp + value) similar to how the variance aggregator works.

**Comment by naman-aasaan** [comment]
Hi Gian, I can try groupBy query but the only problem looks to be about data - we have raw data for around 7.5 million subelments  and output of groupBy query is going to be little bit more than 7.5 million.

Kindly suggest.

**Comment by gianm** [comment]
7.5 million rows in the result should be okay. If necessary you can enable spilling to disk for groupBy using `druid.query.groupBy.maxOnDiskStorage`.

**Comment by arpankhagram** [comment]
@gianm  We have been able to make some progress by using groupBy queries to fetch those large result sets but the problem we are facing is with respect to inability of druid to response other small queries when we run these large groupBy queries. we have requests coming from multiple sources on demand to fetch the data - we can't let those requests timed out because of this large groupBy query.

Can you suggest something please. Thanks in advance.

Regards,
Arpan Khagram

**Comment by andresgomezfrr** [comment]
Hi @gianm ,

Do you know if someone is working on "last aggregator at indexing time" ??

> If you have to use reindexing, the for that to work, someone (possibly you) would have to make the last aggregators work at indexing time. This would probably involve a new column type (pair of timestamp + value) similar to how the variance aggregator works.

I'm interested in this feature .. and maybe I will start the development.
