### ISSUE TITLE
0.10 Want to know the meaning of this Exception

### ISSUE THREAD

**Issue by arpankhagram** [apache/incubator-druid#4051]
I am running tasks through kafka indexing service. Found historical node down with below exception -

2017-03-14T13:43:34,681 INFO [Thread-43] org.eclipse.jetty.server.AbstractConnector - Stopped ServerConnector@72443081{HTTP/1.1,[http/1.1]}{0.0.0.0:8083}
2017-03-14T13:43:34,684 INFO [Thread-43] org.eclipse.jetty.server.handler.ContextHandler - Stopped o.e.j.s.ServletContextHandler@59fc6d05{/,null,UNAVAILABLE}
2017-03-14T13:43:34,679 WARN [qtp1415624532-61] org.eclipse.jetty.servlet.ServletHandler - /druid/v2/
com.fasterxml.jackson.databind.JsonMappingException: Task io.druid.query.PrioritizedListenableFutureTask@33893a rejected from java.util.concurrent.ThreadPoolExecutor@46
dad4b2[Terminated, pool size = 3, active threads = 0, queued tasks = 0, completed tasks = 24649]
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:139) ~[jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.ObjectWriter._configAndWriteValue(ObjectWriter.java:800) ~[jackson-databind-2.4.6.jar:2.4.6]
        at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:642) ~[jackson-databind-2.4.6.jar:2.4.6]
        at io.druid.server.QueryResource$1.write(QueryResource.java:259) ~[druid-server-0.10.0-rc2-SNAPSHOT.jar:0.10.0-rc2-SNAPSHOT]
        at com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:71) ~[jersey-core-1.19.jar:1.19]
        at com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:57) ~[jersey-core-1.19.jar:1.19]
        at com.sun.jersey.spi.container.ContainerResponse.write(ContainerResponse.java:302) ~[jersey-server-1.19.jar:1.19]
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1510) ~[jersey-server-1.19.jar:1.19]
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419) ~[jersey-server-1.19.jar:1.19]
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409) ~[jersey-server-1.19.jar:1.19]
        at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409) ~[jersey-servlet-1.19.jar:1.19]
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558) ~[jersey-servlet-1.19.jar:1.19]
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733) ~[jersey-servlet-1.19.jar:1.19]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[javax.servlet-api-3.1.0.jar:3.1.0]
        at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:286) ~[guice-servlet-4.1.0.jar:?]
        at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:276) ~[guice-servlet-4.1.0.jar:?]
        at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:181) ~[guice-servlet-4.1.0.jar:?]
        at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91) ~[guice-servlet-4.1.0.jar:?]
        at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120) ~[guice-servlet-4.1.0.jar:?]
        at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135) ~[guice-servlet-4.1.0.jar:?]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759) ~[jetty-servlet-9.3.16.v20170120.jar:9.3.16.v20170120]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582) [jetty-servlet-9.3.16.v20170120.jar:9.3.16.v20170120]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224) [jetty-server-9.3.16.v20170120.jar:9.3.16.v20170120]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180) [jetty-server-9.3.16.v20170120.jar:9.3.16.v20170120]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512) [jetty-servlet-9.3.16.v20170120.jar:9.3.16.v20170120]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.3.16.v20170120.jar:9.3.16.v20170120]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112) [jetty-server-9.3.16.v20170120.jar:9.3.16.v20170120]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.3.16.v20170120.jar:9.3.16.v20170120]
        at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:493) [jetty-server-9.3.16.v20170120.jar:9.3.16.v20170120]
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52) [jetty-server-9.3.16.v20170120.jar:9.3.16.v20170120]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134) [jetty-server-9.3.16.v20170120.jar:9.3.16.v20170120]
        at org.eclipse.jetty.server.Server.handle(Server.java:534) [jetty-server-9.3.16.v20170120.jar:9.3.16.v20170120]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320) [jetty-server-9.3.16.v20170120.jar:9.3.16.v20170120]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) [jetty-server-9.3.16.v20170120.jar:9.3.16.v20170120]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283) [jetty-io-9.3.16.v20170120.jar:9.3.16.v20170120]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110) [jetty-io-9.3.16.v20170120.jar:9.3.16.v20170120]
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93) [jetty-io-9.3.16.v20170120.jar:9.3.16.v20170120]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303) [jetty-util-9.3.16.v20170120.jar:9.3.16.v20170120]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148) [jetty-util-9.3.16.v20170120.jar:9.3.16.v20170120]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136) [jetty-util-9.3.16.v20170120.jar:9.3.16.v20170120]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671) [jetty-util-9.3.16.v20170120.jar:9.3.16.v20170120]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589) [jetty-util-9.3.16.v20170120.jar:9.3.16.v20170120]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.util.concurrent.RejectedExecutionException: Task io.druid.query.PrioritizedListenableFutureTask@33893a rejected from java.util.concurrent.ThreadPoolExecutor@46dad4b2[Terminated, pool size = 3, active threads = 0, queued tasks = 0, completed tasks = 24649]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047) ~[?:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823) ~[?:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369) ~[?:1.8.0_91]
        at com.google.common.util.concurrent.MoreExecutors$ListeningDecorator.execute(MoreExecutors.java:484) ~[guava-16.0.1.jar:?]
        at io.druid.query.PrioritizedExecutorService.execute(PrioritizedExecutorService.java:195) ~[druid-processing-0.10.0-rc2-SNAPSHOT.jar:0.10.0-rc2-SNAPSHOT]
        at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134) ~[?:1.8.0_91]
        at io.druid.query.PrioritizedExecutorService.submit(PrioritizedExecutorService.java:159) ~[druid-processing-0.10.0-rc2-SNAPSHOT.jar:0.10.0-rc2-SNAPSHOT]
        at io.druid.query.MetricsEmittingExecutorService.submit(MetricsEmittingExecutorService.java:54) ~[druid-processing-0.10.0-rc2-SNAPSHOT.jar:0.10.0-rc2-SNAPSHOT]
        at io.druid.query.metadata.SegmentMetadataQueryRunnerFactory$2$1.run(SegmentMetadataQueryRunnerFactory.java:206) ~[druid-processing-0.10.0-rc2-SNAPSHOT.jar:0.10.0-rc2-SNAPSHOT]
        at io.druid.query.ConcatQueryRunner$1.apply(ConcatQueryRunner.java:51) ~[druid-processing-0.10.0-rc2-SNAPSHOT.jar:0.10.0-rc2-SNAPSHOT]
        at io.druid.query.ConcatQueryRunner$1.apply(ConcatQueryRunner.java:47) ~[druid-processing-0.10.0-rc2-SNAPSHOT.jar:0.10.0-rc2-SNAPSHOT]
        at io.druid.java.util.common.guava.MappingYieldingAccumulator.accumulate(MappingYieldingAccumulator.java:60) ~[java-util-0.10.0-rc2-SNAPSHOT.jar:0.10.0-rc2-SNAPSHOT]
        at io.druid.java.util.common.guava.MappingYieldingAccumulator.accumulate(MappingYieldingAccumulator.java:60) ~[java-util-0.10.0-rc2-SNAPSHOT.jar:0.10.0-rc2-SNAPSHOT]
        at io.druid.java.util.common.guava.BaseSequence.makeYielder(BaseSequence.java:89) ~[java-util-0.10.0-rc2-SNAPSHOT.jar:0.10.0-rc2-SNAPSHOT]
        at io.druid.java.util.common.guava.BaseSequence.access$100(BaseSequence.java:28) ~[java-util-0.10.0-rc2-SNAPSHOT.jar:0.10.0-rc2-SNAPSHOT]
        at io.druid.java.util.common.guava.BaseSequence$2.next(BaseSequence.java:120) ~[java-util-0.10.0-rc2-SNAPSHOT.jar:0.10.0-rc2-SNAPSHOT]
        at io.druid.java.util.common.guava.ConcatSequence.wrapYielder(ConcatSequence.java:129) ~[java-util-0.10.0-rc2-SNAPSHOT.jar:0.10.0-rc2-SNAPSHOT]
        at io.druid.java.util.common.guava.ConcatSequence.access$000(ConcatSequence.java:29) ~[java-util-0.10.0-rc2-SNAPSHOT.jar:0.10.0-rc2-SNAPSHOT]
        at io.druid.java.util.common.guava.ConcatSequence$3.next(ConcatSequence.java:143) ~[java-util-0.10.0-rc2-SNAPSHOT.jar:0.10.0-rc2-SNAPSHOT]
        at io.druid.common.guava.CombiningSequence$1.next(CombiningSequence.java:130) ~[druid-common-0.10.0-rc2-SNAPSHOT.jar:0.10.0-rc2-SNAPSHOT]
        at io.druid.java.util.common.guava.WrappingYielder$1.get(WrappingYielder.java:53) ~[java-util-0.10.0-rc2-SNAPSHOT.jar:0.10.0-rc2-SNAPSHOT]
        at io.druid.java.util.common.guava.WrappingYielder$1.get(WrappingYielder.java:49) ~[java-util-0.10.0-rc2-SNAPSHOT.jar:0.10.0-rc2-SNAPSHOT]
        at io.druid.query.CPUTimeMetricQueryRunner$1.wrap(CPUTimeMetricQueryRunner.java:78) ~[druid-processing-0.10.0-rc2-SNAPSHOT.jar:0.10.0-rc2-SNAPSHOT]
        at io.druid.java.util.common.guava.WrappingYielder.next(WrappingYielder.java:48) ~[java-util-0.10.0-rc2-SNAPSHOT.jar:0.10.0-rc2-SNAPSHOT]
        at io.druid.jackson.DruidDefaultSerializersModule$4.serialize(DruidDefaultSerializersModule.java:128) ~[druid-processing-0.10.0-rc2-SNAPSHOT.jar:0.10.0-rc2-SNAPSHOT]
        at io.druid.jackson.DruidDefaultSerializersModule$4.serialize(DruidDefaultSerializersModule.java:118) ~[druid-processing-0.10.0-rc2-SNAPSHOT.jar:0.10.0-rc2-SNAPSHOT]
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:128) ~[jackson-databind-2.4.6.jar:2.4.6]
        ... 42 more
2017-03-14T13:43:34,689 INFO [Thread-43] io.druid.java.util.common.lifecycle.Lifecycle$AnnotationBasedHandler - Invoking stop method[public void io.druid.storage.hdfs.HdfsStorageAuthentication.stop()] on object[io.druid.storage.hdfs.HdfsStorageAuthentication@ceddaf8].
2017-03-14T13:43:34,690 INFO [Thread-43] io.druid.java.util.common.lifecycle.Lifecycle$AnnotationBasedHandler - Invoking stop method[public void com.metamx.metrics.MonitorScheduler.stop()] on object[com.metamx.metrics.MonitorScheduler@3003e580].
2017-03-14T13:43:34,690 INFO [Thread-43] io.druid.java.util.common.lifecycle.Lifecycle$AnnotationBasedHandler - Invoking stop method[public void com.metamx.emitter.service.ServiceEmitter.close() throws java.io.IOException] on object[com.metamx.emitter.service.ServiceEmitter@2b38b1f].
2017-03-14T13:43:34,690 INFO [Thread-43] com.metamx.emitter.core.LoggingEmitter - Close: started [false]
2017-03-14T13:43:34,690 INFO [Thread-43] io.druid.java.util.common.lifecycle.Lifecycle$AnnotationBasedHandler - Invoking stop method[public void io.druid.initialization.Log4jShutterDownerModule$Log4jShutterDowner.stop()] on object[io.druid.initialization.Log4jShutterDownerModule$Log4jShutterDowner@67531e3a].
Heap
 par new generation   total 943680K, used 48076K [0x00000005c0000000, 0x00000005ffff0000, 0x0000000640000000)
  eden space 838848K,   3% used [0x00000005c0000000, 0x00000005c1e9d928, 0x00000005f3330000)
  from space 104832K,  15% used [0x00000005f3330000, 0x00000005f4385988, 0x00000005f9990000)
  to   space 104832K,   0% used [0x00000005f9990000, 0x00000005f9990000, 0x00000005ffff0000)
 concurrent mark-sweep generation total 286132K, used 172553K [0x0000000640000000, 0x000000065176d000, 0x00000007c0000000)
 Metaspace       used 50628K, capacity 51463K, committed 51752K, reserved 1095680K
  class space    used 6181K, capacity 6416K, committed 6508K, reserved 1048576K

Can someone tell me what could have gone wrong or if it is some known issue with 0.10  version of druid.

**Comment by arpankhagram** [comment]
I am finding historical node down again and again with above exception. Any clue ?

**Comment by gianm** [comment]
@arpankhagram I think you probably have the cause and effect backwards. This exception is not making your historical node shut down, it's happening _because_ your historical node is shutting down. Is it possible something is killing it? Maybe you're running it from a terminal that then closes, or something like that? Are there any exceptions further up in the log that look like they might be fatal to the historical node?

Going to untag this from 0.10.0 since it doesn't appear to be an 0.10.0 issue to me.
