### ISSUE TITLE
Why `avro-extension` just only support `GenericDatumReader` rather than `SpecificDatumReader`?

### ISSUE THREAD

**Issue by asdf2014** [apache/incubator-druid#4091]
Druid 0.9.2
Should we add some options to support `SpecificDatumReader`?
```
"Tranquilizer-BackgroundSend-[com.metamx.tranquility.beam.TransformingBeam@26f2a752]" #45 daemon prio=5 os_prio=0 tid=0x00007f5a6cd48800 nid=0x4a43 runnable [0x00007f5a53afd000]
   java.lang.Thread.State: RUNNABLE
	at java.lang.Throwable.fillInStackTrace(Native Method)
	at java.lang.Throwable.fillInStackTrace(Throwable.java:783)
	- locked <0x00000006475afa38> (a java.io.EOFException)
	at java.lang.Throwable.<init>(Throwable.java:250)
	at java.lang.Exception.<init>(Exception.java:54)
	at java.io.IOException.<init>(IOException.java:47)
	at java.io.EOFException.<init>(EOFException.java:50)
	at org.apache.avro.util.ByteBufferInputStream.getBuffer(ByteBufferInputStream.java:86)
	at org.apache.avro.util.ByteBufferInputStream.read(ByteBufferInputStream.java:48)
	at org.apache.avro.io.BinaryDecoder$InputStreamByteSource.readRaw(BinaryDecoder.java:824)
	at org.apache.avro.io.BinaryDecoder.doReadBytes(BinaryDecoder.java:349)
	at org.apache.avro.io.BinaryDecoder.readString(BinaryDecoder.java:263)
	at org.apache.avro.io.ResolvingDecoder.readString(ResolvingDecoder.java:201)
	at org.apache.avro.generic.GenericDatumReader.readString(GenericDatumReader.java:363)
	at org.apache.avro.generic.GenericDatumReader.readString(GenericDatumReader.java:355)
	at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:157)
	at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:155)
	at org.apache.avro.generic.GenericDatumReader.readField(GenericDatumReader.java:193)
	at org.apache.avro.generic.GenericDatumReader.readRecord(GenericDatumReader.java:183)
	at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:151)
	at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:142)
	at io.druid.data.input.avro.InlineSchemaAvroBytesDecoder.parse(InlineSchemaAvroBytesDecoder.java:86)
	at io.druid.data.input.AvroStreamInputRowParser.parse(AvroStreamInputRowParser.java:53)
	at io.druid.data.input.AvroStreamInputRowParser.parse(AvroStreamInputRowParser.java:33)
	at com.metamx.tranquility.druid.DruidBeams$$anonfun$1$$anonfun$7.apply(DruidBeams.scala:182)
	at com.metamx.tranquility.druid.DruidBeams$$anonfun$1$$anonfun$7.apply(DruidBeams.scala:182)
	at com.metamx.tranquility.druid.DruidBeams$$anonfun$1$$anonfun$apply$1.apply(DruidBeams.scala:200)
	at com.metamx.tranquility.druid.DruidBeams$$anonfun$1$$anonfun$apply$1.apply(DruidBeams.scala:200)
	at com.metamx.tranquility.beam.TransformingBeam$$anonfun$sendAll$2$$anonfun$2.apply(TransformingBeam.scala:36)
	at com.twitter.util.Try$.apply(Try.scala:13)
	at com.metamx.tranquility.beam.TransformingBeam$$anonfun$sendAll$2.apply(TransformingBeam.scala:36)
	at com.metamx.tranquility.beam.TransformingBeam$$anonfun$sendAll$2.apply(TransformingBeam.scala:35)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:772)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:771)
	at com.metamx.tranquility.beam.TransformingBeam.sendAll(TransformingBeam.scala:35)
	at com.metamx.tranquility.tranquilizer.Tranquilizer.com$metamx$tranquility$tranquilizer$Tranquilizer$$sendBuffer(Tranquilizer.scala:301)
	at com.metamx.tranquility.tranquilizer.Tranquilizer$$anonfun$3.apply(Tranquilizer.scala:116)
	at com.metamx.common.scala.concurrent.package$$anon$1.run(package.scala:37)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by asdf2014** [comment]
Maybe, we should add `kryo-extension` for better performance about the speed of serializer and the ratio of compression.
![image](https://cloud.githubusercontent.com/assets/8108788/24186242/62bdb28c-0f12-11e7-890b-f432586c7271.png)
