### ISSUE TITLE
overlord http is very slow with kafka index task

### ISSUE THREAD

**Issue by kingnj** [apache/incubator-druid#4237]
i use kafka index task to get data,  i hava 10 Supervisor config to get data from 10 topic , and write to 10 datasource

when i use http to  submit the nineth Supervisor, it become slow

and after some minute, overlord hase error like 
2017-05-02T12:05:45,614 ERROR [qtp438493423-169] com.sun.jersey.spi.container.ContainerResponse - The RuntimeException could not be mapped to a response, re-throwing to the HTTP container
com.metamx.common.ISE: Unable to grant lock to inactive Task [index_kafka_appstore_storm_test_3_935d1c3b346939c_ffnjaidm]

2017-05-02T06:11:36,035 ERROR [KafkaSupervisor-appstore_druid_storm_2] io.druid.indexing.kafka.supervisor.KafkaSupervisor - KafkaSupervisor[appstore_druid_storm_2] failed to handle notice: {class=io.druid.indexing.kafka.supervisor.KafkaSupervisor, exceptionType=class java.util.concurrent.RejectedExecutionException, exceptionMessage=Task com.google.common.util.concurrent.ListenableFutureTask@1e39a06f rejected from java.util.concurrent.ThreadPoolExecutor@6fdd8c9d[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 12], noticeClass=RunNotice}
java.util.concurrent.RejectedExecutionException: Task com.google.common.util.concurrent.ListenableFutureTask@1e39a06f rejected from java.util.concurrent.ThreadPoolExecutor@6fdd8c9d[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 12]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047) ~[?:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823) ~[?:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369) ~[?:1.8.0_112]
	at com.google.common.util.concurrent.MoreExecutors$ListeningDecorator.execute(MoreExecutors.java:484) ~[guava-16.0.1.jar:?]
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134) ~[?:1.8.0_112]
	at com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:58) ~[guava-16.0.1.jar:?]
	at io.druid.indexing.kafka.KafkaIndexTaskClient.getStatusAsync(KafkaIndexTaskClient.java:353) ~[druid-kafka-indexing-service-0.9.2.jar:0.9.2]
	at io.druid.indexing.kafka.supervisor.KafkaSupervisor.discoverTasks(KafkaSupervisor.java:695) ~[druid-kafka-indexing-service-0.9.2.jar:0.9.2]
	at io.druid.indexing.kafka.supervisor.KafkaSupervisor.runInternal(KafkaSupervisor.java:542) ~[druid-kafka-indexing-service-0.9.2.jar:0.9.2]
	at io.druid.indexing.kafka.supervisor.KafkaSupervisor$RunNotice.handle(KafkaSupervisor.java:462) ~[druid-kafka-indexing-service-0.9.2.jar:0.9.2]
	at io.druid.indexing.kafka.supervisor.KafkaSupervisor$2.run(KafkaSupervisor.java:298) [druid-kafka-indexing-service-0.9.2.jar:0.9.2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_112]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_112]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]

and then overlord http is very slow, can somebody give me suggestion?thanks

ps: i get overload log,middlemanager log , there ere no other errror.

**Comment by gianm** [comment]
@kingnj I think these ops are done in parallel now -- have you tried with 0.10.0 and has the situation improved?

**Comment by kinghw** [comment]
@gianm thanks, i used 0.10.0, but this issue is open
