### ISSUE TITLE
Permanently Deleting Data

### ISSUE THREAD

**Issue by PanYifeng** [apache/incubator-druid#4375]
Hi, I want to delete some specified segments and removes them from deep storage by kill task.

I posted my request of killTask after the datasource was disabled:
curl --request POST 'http://overload:8090/druid/indexer/v1/task' -H 'Content-Type:application/json' -d @killTask.json

killTask.json:
{
    "type": "kill",
    "id": "clean-2017-05-27T16:00:00.000Z",
    "dataSource": "qns-cost",
    "interval": "2017-05-27T16:00:00.000Z/2017-05-28T16:00:00.000Z"
}

it returned:
{"task":"clean-2017-05-27T16:00:00.000Z"}

But ,unfortunately , it seems that nothing happened to these segments, there still exist the segments I want to delete in HDFS.

There is an error in log from Coordinator Console:
2017-06-07 18:06:00,510 Thread-2 ERROR Unable to register shutdown hook because JVM is shutting down. java.lang.IllegalStateException: Not started
	at io.druid.common.config.Log4jShutdown.addShutdownCallback(Log4jShutdown.java:45)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.addShutdownCallback(Log4jContextFactory.java:273)
	at org.apache.logging.log4j.core.LoggerContext.setUpShutdownHook(LoggerContext.java:256)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:216)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:145)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:41)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:182)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(AbstractLoggerAdapter.java:103)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:43)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:42)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:29)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:284)
	at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:155)
	at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:132)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:685)
	at org.apache.hadoop.hdfs.LeaseRenewer.<clinit>(LeaseRenewer.java:72)
	at org.apache.hadoop.hdfs.DFSClient.getLeaseRenewer(DFSClient.java:699)
	at org.apache.hadoop.hdfs.DFSClient.close(DFSClient.java:859)
	at org.apache.hadoop.hdfs.DistributedFileSystem.close(DistributedFileSystem.java:853)
	at org.apache.hadoop.fs.FileSystem$Cache.closeAll(FileSystem.java:2407)
	at org.apache.hadoop.fs.FileSystem$Cache$ClientFinalizer.run(FileSystem.java:2424)
	at org.apache.hadoop.util.ShutdownHookManager$1.run(ShutdownHookManager.java:54)

@gianm: Could your please help me solve this problem?

**Comment by stevenchen3** [comment]
encountered the same issue here.

**Comment by niketh** [comment]
@PanYifeng @stevenchen3 Can you paste a gist link with the complete logs
