### ISSUE TITLE
overlord  start up failed

### ISSUE THREAD

**Issue by AndyLin0128** [apache/incubator-druid#4477]
1) Unknown provider[hdfs] of Key[type=io.druid.tasklogs.TaskLogs, annotation=[none]], known options[[s3, noop, file]]
  at io.druid.guice.PolyBind.createChoice(PolyBind.java:67) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> io.druid.guice.IndexingServiceTaskLogsModule)
  while locating io.druid.tasklogs.TaskLogs
  while locating io.druid.tasklogs.TaskLogKiller
    for the 1st parameter of io.druid.indexing.overlord.helpers.TaskLogAutoCleaner.<init>(TaskLogAutoCleaner.java:44)
  while locating io.druid.indexing.overlord.helpers.TaskLogAutoCleaner
  while locating io.druid.indexing.overlord.helpers.OverlordHelper annotated with @com.google.inject.multibindings.Element(setName=,uniqueId=98, type=MULTIBINDER, keyType=)
  at io.druid.cli.CliOverlord$1.configureOverlordHelpers(CliOverlord.java:258) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> io.druid.cli.CliOverlord$1 -> com.google.inject.multibindings.Multibinder$RealMultibinder)
  while locating java.util.Set<io.druid.indexing.overlord.helpers.OverlordHelper>
    for the 2nd parameter of io.druid.indexing.overlord.helpers.OverlordHelperManager.<init>(OverlordHelperManager.java:48)
  while locating io.druid.indexing.overlord.helpers.OverlordHelperManager
    for the 13th parameter of io.druid.indexing.overlord.TaskMaster.<init>(TaskMaster.java:87)
  at io.druid.cli.CliOverlord$1.configure(CliOverlord.java:140) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> io.druid.cli.CliOverlord$1)
  while locating io.druid.indexing.overlord.TaskMaster
    for the 1st parameter of io.druid.indexing.overlord.http.OverlordRedirectInfo.<init>(OverlordRedirectInfo.java:45)
  while locating io.druid.indexing.overlord.http.OverlordRedirectInfo
  at io.druid.cli.CliOverlord$1.configure(CliOverlord.java:174) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> io.druid.cli.CliOverlord$1)
  while locating io.druid.server.http.RedirectInfo
    for the 1st parameter of io.druid.server.http.RedirectFilter.<init>(RedirectFilter.java:49)
  at io.druid.cli.CliOverlord$1.configure(CliOverlord.java:173) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> io.druid.cli.CliOverlord$1)
  while locating io.druid.server.http.RedirectFilter
  at io.druid.server.initialization.jetty.JettyServerModule.getServer(JettyServerModule.java:136) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> io.druid.server.initialization.jetty.JettyServerModule)
  at io.druid.server.initialization.jetty.JettyServerModule.getServer(JettyServerModule.java:136) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> io.druid.server.initialization.jetty.JettyServerModule)
  while locating org.eclipse.jetty.server.Server

1 error
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1028) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1050) ~[guice-4.1.0.jar:?]
	at io.druid.guice.LifecycleModule$2.start(LifecycleModule.java:154) ~[druid-api-0.10.1.jar:0.10.1]
	at io.druid.cli.GuiceRunnable.initLifecycle(GuiceRunnable.java:103) [druid-services-0.10.1.jar:0.10.1]
	at io.druid.cli.ServerRunnable.run(ServerRunnable.java:41) [druid-services-0.10.1.jar:0.10.1]
	at io.druid.cli.Main.main(Main.java:108) [druid-services-0.10.1.jar:0.10.1]

**Comment by gianm** [comment]
Try loading the druid-hdfs-storage extension.

**Comment by AndyLin0128** [comment]
thanks

**Comment by xu-xlucas** [comment]
i meet the same question ,i fixed use classpath add conf/druid/_common/ and config the druid.extensions.hadoopDependenciesDir
