### ISSUE TITLE
kafka-0.10.2.0 config kafka-emitter exception

### ISSUE THREAD

**Issue by ambition119** [apache/incubator-druid#4584]
#  Use  kafka-0.10.2.0 status is exception :
     WARN [pool-18-thread-2] io.druid.emitter.kafka.KafkaEmitter - Failed to take record from queue!
java.lang.InterruptedException at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_131]	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_131]
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442) ~[?:1.8.0_131]
	at io.druid.emitter.kafka.MemoryBoundLinkedBlockingQueue.take(MemoryBoundLinkedBlockingQueue.java:59) ~[?:?]
	at io.druid.emitter.kafka.KafkaEmitter.sendToKafka(KafkaEmitter.java:147) ~[?:?]
	at io.druid.emitter.kafka.KafkaEmitter.sendAlertToKafka(KafkaEmitter.java:139) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_131]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_131]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

#
# kafka-emitter
#
druid.monitoring.monitors=["com.metamx.metrics.JvmMonitor"]
druid.emitter=kafka
druid.emitter.kafka.bootstrap.servers=hdp:9092
druid.emitter.kafka.metric.topic=druid-metric
druid.emitter.kafka.alert.topic=druid-alert
druid.emitter.kafka.producer.config={"max.block.ms":10}

**Comment by dkhwangbo** [comment]
Hi. I cannot reproduce this report. Anyone else can reproduce it?

**Comment by ambition119** [comment]
conf/druid/_common/common.runtime.properties:
druid.extensions.loadList=["druid-kafka-eight", "druid-hdfs-storage", "druid-histogram", "druid-datasketches", "druid-lookups-cached-global", "mysql-metadata-storage", "kafka-emitter"]

#
# kafka-emitter
#
druid.monitoring.monitors=["com.metamx.metrics.JvmMonitor"]
druid.emitter=composing
druid.emitter.composing.emitters=["logging","kafka"]
druid.emitter.logging.logLevel=info
druid.emitter.kafka.bootstrap.servers=hdp:9092
druid.emitter.kafka.metric.topic=druid-metric
druid.emitter.kafka.alert.topic=druid-alert
druid.emitter.kafka.producer.config={"max.block.ms":10,"buffer.memory":10,"batch.size":10,"receive.buffer.bytes":10,"receive.buffer.bytes":10,"max.request.size":10,"send.buffer.bytes":10}

$ ll extensions/kafka-emitter
jopt-simple-5.0.3.jar
kafka_2.10-0.10.2.0.jar
kafka-clients-0.10.2.0.jar
kafka-emitter-0.11.0-SNAPSHOT.jar
metrics-core-2.2.0.jar
scala-library-2.10.6.jar
snappy-java-1.1.2.6.jar
zkclient-0.10.jar


$ bin/broker.sh start
$ tail -100f log/broker.log
....
INFO [MonitorScheduler-0] com.metamx.emitter.core.LoggingEmitter - Event [{"feed":"metrics","timestamp":"2017-07-23T23:38:54.320-08:00","service":"druid/broker","host":"hdp:8082","version":"0.11.0-SNAPSHOT","metric":"jetty/numOpenConnections","value":0}]
...

$bin/kafka-console-consumer.sh -zookeeper hdp:2181 --from-beginning --topic druid-metric
// no message consumer
$bin/broker.sh stop

$ tail -100f log/broker.log
WARN [pool-18-thread-1] io.druid.emitter.kafka.KafkaEmitter - Failed to take record from queue!
java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_131]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_131]
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442) ~[?:1.8.0_131]
	at io.druid.emitter.kafka.MemoryBoundLinkedBlockingQueue.take(MemoryBoundLinkedBlockingQueue.java:59) ~[?:?]
	at io.druid.emitter.kafka.KafkaEmitter.sendToKafka(KafkaEmitter.java:147) ~[?:?]
	at io.druid.emitter.kafka.KafkaEmitter.sendMetricToKafka(KafkaEmitter.java:134) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_131]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_131]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

**Comment by sharks222** [comment]
I have meet the same problem.
Anyone get the idea on how to solve it?
