### ISSUE TITLE
NullPointerException when starting historic node on standalone cluster

### ISSUE THREAD

**Issue by ashishpahwa7** [apache/incubator-druid#4589]
```2017-07-22T17:06:39,026 ERROR [main] io.druid.cli.CliHistorical - Error when starting up.  Failing.
java.lang.NullPointerException
	at java.util.Hashtable.put(Hashtable.java:459) ~[?:1.8.0_131]
	at org.apache.hadoop.security.authentication.server.AuthenticationFilter.getConfiguration(AuthenticationFilter.java:247) ~[?:?]
	at org.apache.hadoop.security.authentication.server.AuthenticationFilter.init(AuthenticationFilter.java:129) ~[?:?]
	at io.druid.security.kerberos.SpnegoFilterHolder$1.init(SpnegoFilterHolder.java:69) ~[?:?]
	at org.eclipse.jetty.servlet.FilterHolder.initialize(FilterHolder.java:139) ~[jetty-servlet-9.3.16.v20170120.jar:9.3.16.v20170120]
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:873) ~[jetty-servlet-9.3.16.v20170120.jar:9.3.16.v20170120]
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:349) ~[jetty-servlet-9.3.16.v20170120.jar:9.3.16.v20170120]
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:778) ~[jetty-server-9.3.16.v20170120.jar:9.3.16.v20170120]
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:262) ~[jetty-servlet-9.3.16.v20170120.jar:9.3.16.v20170120]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.3.16.v20170120.jar:9.3.16.v20170120]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131) ~[jetty-util-9.3.16.v20170120.jar:9.3.16.v20170120]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105) ~[jetty-util-9.3.16.v20170120.jar:9.3.16.v20170120]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61) ~[jetty-server-9.3.16.v20170120.jar:9.3.16.v20170120]
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.doStart(GzipHandler.java:253) ~[jetty-server-9.3.16.v20170120.jar:9.3.16.v20170120]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.3.16.v20170120.jar:9.3.16.v20170120]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131) ~[jetty-util-9.3.16.v20170120.jar:9.3.16.v20170120]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113) ~[jetty-util-9.3.16.v20170120.jar:9.3.16.v20170120]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61) ~[jetty-server-9.3.16.v20170120.jar:9.3.16.v20170120]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.3.16.v20170120.jar:9.3.16.v20170120]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131) ~[jetty-util-9.3.16.v20170120.jar:9.3.16.v20170120]
	at org.eclipse.jetty.server.Server.start(Server.java:422) ~[jetty-server-9.3.16.v20170120.jar:9.3.16.v20170120]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105) ~[jetty-util-9.3.16.v20170120.jar:9.3.16.v20170120]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61) ~[jetty-server-9.3.16.v20170120.jar:9.3.16.v20170120]
	at org.eclipse.jetty.server.Server.doStart(Server.java:389) ~[jetty-server-9.3.16.v20170120.jar:9.3.16.v20170120]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.3.16.v20170120.jar:9.3.16.v20170120]
	at io.druid.server.initialization.jetty.JettyServerModule$1.start(JettyServerModule.java:206) ~[druid-server-0.10.0.jar:0.10.0]
	at io.druid.java.util.common.lifecycle.Lifecycle.start(Lifecycle.java:263) ~[java-util-0.10.0.jar:0.10.0]
	at io.druid.guice.LifecycleModule$2.start(LifecycleModule.java:156) ~[druid-api-0.10.0.jar:0.10.0]
	at io.druid.cli.GuiceRunnable.initLifecycle(GuiceRunnable.java:102) [druid-services-0.10.0.jar:0.10.0]
	at io.druid.cli.ServerRunnable.run(ServerRunnable.java:41) [druid-services-0.10.0.jar:0.10.0]
	at io.druid.cli.Main.main(Main.java:108) [druid-services-0.10.0.jar:0.10.0]
```

**Comment by ashishpahwa7** [comment]
It just worked fine the first time I launched it . I am currently using conf-quick-start default settings on 8 GB machine

**Comment by astopaolo** [comment]
I have the same problem. Did you manage to solve it?

**Comment by ashishpahwa7** [comment]
Yes I did, It turned out that default configuration files provided in the distribution were not tuned as per the requirements of my system. So you need to configure your architecture depending upon your machine size.

Could you share the content of jvm.config of your historic node ?

**Comment by astopaolo** [comment]
It is the default one
[jvm.zip](https://github.com/druid-io/druid/files/1244609/jvm.zip)

**Comment by ashishpahwa7** [comment]
-Xms256m
-Xmx256m
-XX:MaxDirectMemorySize=768m
