### ISSUE TITLE
how to start realtime node in Druid

### ISSUE THREAD

**Issue by JLLNANA** [apache/incubator-druid#4695]
Druid version is: druid-0.10.0

In the package of druid, the folder named conf/druid only has the configuration of nodes(broker,_common, coordinator,historical,middleManager and overlord) without realtime configuration.
When i cp historical configurations to realtime configuration and modify some parameters.
The settings in runtime.properties like this:
druid.service=druid/realtime
druid.port=8084

# HTTP server threads
druid.server.http.numThreads=9

# Processing threads and buffers
druid.processing.buffer.sizeBytes=256000000
druid.processing.numThreads=2

# Segment storage
#druid.segmentCache.locations=[{"path":"var/druid/segment-cache","maxSize"\:300000000000}]
druid.segmentCache.locations=[{"path":"/data0/druid_var/segment-cache","maxSize"\:300000000000}]
druid.server.maxSize=300000000000
~                                   
and then start realtime node using the command like this:
java -Xmx256m -Duser.timezone=UTC -Dfile.encoding=UTF-8 `cat conf-quickstart/druid/realtime/jvm.config | xargs` -cp "conf-quickstart/druid/_common:conf-quickstart/druid/realtime:lib/*" io.druid.cli.Main server realtime

Then error

2017-08-17T03:19:04,105 ERROR [main] io.druid.cli.CliRealtime - Error when starting up.  Failing.
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, java.lang.NullPointerException
  at io.druid.guice.FireDepartmentsProvider.<init>(FireDepartmentsProvider.java:43)
  while locating io.druid.guice.FireDepartmentsProvider
  at io.druid.guice.RealtimeModule.configure(RealtimeModule.java:86) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> io.druid.guice.RealtimeModule)
  while locating java.util.List<io.druid.segment.realtime.FireDepartment>
    for the 1st parameter of io.druid.segment.realtime.RealtimeManager.<init>(RealtimeManager.java:80)
  while locating io.druid.segment.realtime.RealtimeManager
  at io.druid.guice.RealtimeModule.configure(RealtimeModule.java:103) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> io.druid.guice.RealtimeModule)
  while locating io.druid.query.QuerySegmentWalker
    for the 5th parameter of io.druid.server.QueryResource.<init>(QueryResource.java:118)
  while locating io.druid.server.QueryResource

1 error
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1028) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1050) ~[guice-4.1.0.jar:?]
	at io.druid.guice.LifecycleModule$2.start(LifecycleModule.java:154) ~[druid-api-0.10.0.jar:0.10.0]
	at io.druid.cli.GuiceRunnable.initLifecycle(GuiceRunnable.java:102) [druid-services-0.10.0.jar:0.10.0]
	at io.druid.cli.ServerRunnable.run(ServerRunnable.java:41) [druid-services-0.10.0.jar:0.10.0]
	at io.druid.cli.Main.main(Main.java:108) [druid-services-0.10.0.jar:0.10.0]
Caused by: java.lang.NullPointerException
	at java.io.FileInputStream.<init>(FileInputStream.java:130) ~[?:1.8.0_131]
	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:708) ~[jackson-core-2.4.6.jar:2.4.6]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2122) ~[jackson-databind-2.4.6.jar:2.4.6]
	at io.druid.guice.FireDepartmentsProvider.<init>(FireDepartmentsProvider.java:46) ~[druid-server-0.10.0.jar:0.10.0]
	at io.druid.guice.FireDepartmentsProvider$$FastClassByGuice$$229da177.newInstance(<generated>) ~[druid-server-0.10.0.jar:0.10.0]
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:61) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[guice-4.1.0.jar:?]
	at io.druid.guice.LifecycleScope$1.get(LifecycleScope.java:69) ~[druid-api-0.10.0.jar:0.10.0]
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015) ~[guice-4.1.0.jar:?]
	... 5 more
^C

**Comment by jihoonson** [comment]
Hi @JLLNANA, have you had a chance to read the documents for streaming ingestion using realtime node? http://druid.io/docs/latest/ingestion/stream-pull.html and http://druid.io/docs/latest/configuration/realtime.html will be helpful for you. I guess something is missed in your realtime node configuration.

**Comment by pld** [comment]
@JLLNANA looks like your `runtime.properties` is missing the `druid.realtime.specFile` property and its value

**Comment by kang-junyoung** [comment]
@JLLNANA  If you use tranquility, you don't need a realtime node.

### Reference
https://github.com/druid-io/tranquility/blob/master/docs/overview.md#druid-setup
```
 To get started with the Druid indexing service, you'll need an Overlord, enough Middle Managers for your realtime workload, and enough historical nodes to receive handoffs.
 You don't need any realtime nodes, since Tranquility uses the indexing service for all of its ingestion needs.
```
