### ISSUE TITLE
Cant build source code from tag druid-0.10.1 because of some checkstyle issue in druid-thrift-extensions

### ISSUE THREAD

**Issue by isongga** [apache/incubator-druid#4719]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (validate) on project druid-thrift-extensions: Failed during checkstyle execution: There are 59 errors reported by Checkstyle 6.19 with codestyle/checkstyle.xml ruleset. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (validate) on project druid-thrift-extensions: Failed during checkstyle execution
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed during checkstyle execution
	at org.apache.maven.plugin.checkstyle.CheckstyleViolationCheckMojo.execute(CheckstyleViolationCheckMojo.java:547)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: org.apache.maven.plugin.checkstyle.exec.CheckstyleExecutorException: There are 59 errors reported by Checkstyle 6.19 with codestyle/checkstyle.xml ruleset.
	at org.apache.maven.plugin.checkstyle.exec.DefaultCheckstyleExecutor.executeCheckstyle(DefaultCheckstyleExecutor.java:313)
	at org.apache.maven.plugin.checkstyle.CheckstyleViolationCheckMojo.execute(CheckstyleViolationCheckMojo.java:538)
	... 22 more

**Comment by isongga** [comment]
DEBUG] Added '/Users/wusong/Rongcapital/projects01/druid/extensions-contrib/thrift-extensions/src/test/thrift' as a source directory.
[INFO] Starting audit...
[ERROR] /Users/wusong/Rongcapital/projects01/druid/extensions-contrib/thrift-extensions/target/generated-test-sources/thrift/scrooge/io/druid/data/input/thrift/Author.java:9:8: 无用导入 - java.util.List 。 [UnusedImports]
[ERROR] /Users/wusong/Rongcapital/projects01/druid/extensions-contrib/thrift-extensions/target/generated-test-sources/thrift/scrooge/io/druid/data/input/thrift/Author.java:10:8: 无用导入 - java.util.ArrayList 。 [UnusedImports]
[ERROR] /Users/wusong/Rongcapital/projects01/druid/extensions-contrib/thrift-extensions/target/generated-test-sources/thrift/scrooge/io/druid/data/input/thrift/Author.java:14:8: 无用导入 - java.util.Set 。 [UnusedImports]
[ERROR] /Users/wusong/Rongcapital/projects01/druid/extensions-contrib/thrift-extensions/target/generated-test-sources/thrift/scrooge/io/druid/data/input/thrift/Author.java:15:8: 无用导入 - java.util.HashSet 。 [UnusedImports]
[ERROR] /Users/wusong/Rongcapital/projects01/druid/extensions-contrib/thrift-extensions/target/generated-test-sources/thrift/scrooge/io/druid/data/input/thrift/Author.java:18:8: 无用导入 - java.util.BitSet 。 [UnusedImports]
[ERROR] /Users/wusong/Rongcapital/projects01/druid/extensions-contrib/thrift-extensions/target/generated-test-sources/thrift/scrooge/io/druid/data/input/thrift/Author.java:19:8: 无用导入 - java.nio.ByteBuffer 。 [UnusedImports]
[ERROR] /Users/wusong/Rongcapital/projects01/druid/extensions-contrib/thrift-extensions/target/generated-test-sources/thrift/scrooge/io/druid/data/input/thrift/Author.java:20:8: 无用导入 - java.util.Arrays 。 [UnusedImports]
[ERROR] /Users/wusong/Rongcapital/projects01/druid/extensions-contrib/thrift-extensions/target/generated-test-sources/thrift/scrooge/io/druid/data/input/thrift/Author.java:21:8: 无用导入 - org.slf4j.Logger 。 [UnusedImports]
[ERROR] /Users/wusong/Rongcapital/projects01/druid/extensions-contrib/thrift-extensions/target/generated-test-sources/thrift/scrooge/io/druid/data/input/thrift/Author.java:22:8: 无用导入 - org.slf4j.LoggerFactory 。 [UnusedImports]
[ERROR] /Users/wusong/Rongcapital/projects01/druid/extensions-contrib/thrift-extensions/target/generated-test-sources/thrift/scrooge/io/druid/data/input/thrift/Author.java:24: 不应使用 '.*' 形式的导入 - org.apache.thrift.* 。 [AvoidStarImport]
[ERROR] /Users/wusong/Rongcapital/projects01/druid/extensions-contrib/thrift-extensions/target/generated-test-sources/thrift/scrooge/io/druid/data/input/thrift/Author.java:25: 不应使用 '.*' 形式的导入 - org.apache.thrift.async.* 。 [AvoidStarImport]
[ERROR] /Users/wusong/Rongcapital/projects01/druid/extensions-contrib/thrift-extensions/target/generated-test-sources/thrift/scrooge/io/druid/data/input/thrift/Author.java:26: 不应使用 '.*' 形式的导入 - org.apache.thrift.meta_data.* 。 [AvoidStarImport]
[ERROR] /Users/wusong/Rongcapital/projects01/druid/extensions-contrib/thrift-extensions/target/generated-test-sources/thrift/scrooge/io/druid/data/input/thrift/Author.java:27: 不应使用 '.*' 形式的导入 - org.apache.thrift.transport.* 。 [AvoidStarImport]
[ERROR] /Users/wusong/Rongcapital/projects01/druid/extensions-contrib/thrift-extensions/target/generated-test-sources/thrift/scrooge/io/druid/data/input/thrift/Author.java:28: 不应使用 '.*' 形式的导入 - org.apache.thrift.protocol.* 。 [AvoidStarImport]
[ERROR] /Users/wusong/Rongcapital/projects01/druid/extensions-contrib/thrift-extensions/target/generated-test-sources/thrift/scrooge/io/druid/data/input/thrift/Author.java:61:3: 文件含有制表符 tab （这只是第一例）。 [FileTabCharacter]
[ERROR] /Users/wusong/Rongcapital/projects01/druid/extensions-contrib/thrift-extensions/target/generated-test-sources/thrift/scrooge/io/druid/data/input/thrift/Author.java:75: 'if' 结构必须使用大括号 '{}'。 [NeedBraces]
[ERROR] /Users/wusong/Rongcapital/projects01/druid/extensions-contrib/thrift-extensions/target/generated-test-sources/thrift/scrooge/io/druid/data/input/thrift/Author.java:248: 'if' 结构必须使用大括号 '{}'。 [NeedBraces]
[ERROR] /Users/wusong/Rongcapital/projects01/druid/extensions-contrib/thrift-extensions/target/generated-test-sources/thrift/scrooge/io/druid/data/input/thrift/Author.java:250: 'if' 结构必须使用大括号 '{}'。 [NeedBraces]
[ERROR] /Users/wusong/Rongcapital/projects01/druid/extensions-contrib/thrift-extensions/target/generated-test-sources/thrift/scrooge/io/druid/data/input/thrift/Author.java:256: 'if' 结构必须使用大括号 '{}'。 [NeedBraces]
[ERROR] /Users/wusong/Rongcapital/projects01/druid/extensions-contrib/thrift-extensions/target/generated-test-sources/thrift/scrooge/io/druid/data/input/thrift/Author.java:261: 'if' 结构必须使用大括号 '{}'。 [NeedBraces]
[ERROR] /Users/wusong/Rongcapital/projects01/druid/extensions-contrib/thrift-extensions/target/generated-test-sources/thrift/scrooge/io/druid/data/input/thrift/Author.java:263: 'if' 结构必须使用大括号 '{}'。 [NeedBraces]
[ERROR] /Users/wusong/Rongcapital/projects01/druid/extensions-contrib/thrift-extensions/target/generated-test-sources/thrift/scrooge/io/druid/data/input/thrift/Author.java:269: 'if' 结构必须使用大括号 '{}'。 [NeedBraces]
[ERROR] /Users/wusong/Rongcapital/projects01/druid/extensions-contrib/thrift-extensions/target/generated-test-sources/thrift/scrooge/io/druid/data/input/thrift/Author.java:271: 'if' 结构必须使用大括号 '{}'。 [NeedBraces]
[ERROR] /Users/wusong/Rongcapital/projects01/druid/extensions-contrib/thrift-extensions/target/generated-test-sources/thrift/scrooge/io/druid/data/input/thrift/Author.java:283: 'if' 结构必须使用大括号 '{}'。 [NeedBraces]
[ERROR] /Users/wusong/Rongcapital/projects01/druid/extensions-contrib/thrift-extensions/target/generated-test-sources/thrift/scrooge/io/druid/data/input/thrift/Author.java:287: 'if' 结构必须使用大括号 '{}'。 [NeedBraces]
[ERROR] /Users/wusong/Rongcapital/projects01/druid/extensions-contrib/thrift-extensions/target/generated-test-sources/thrift/scrooge/io/druid/data/input/thrift/Author.java:392: 'if' 结构必须使用大括号 '{}'。 [NeedBraces]
[ERROR] /Users/wusong/Rongcapital/projects01/druid/extensions-contrib/thrift-extensions/target/generated-test-sources/thrift/scrooge/io/druid/data/input/thrift/Book.java:9:8: 无用导入 - java.util.List 。 [UnusedImports]
[ERROR] /Users/wusong/Rongcapital/projects01/druid/extensions-contrib/thrift-extensions/target/generated-test-sources/thrift/scrooge/io/druid/data/input/thrift/Book.java:10:8: 无用导入 - java.util.ArrayList 。 [UnusedImports]
[ERROR] /Users/wusong/Rongcapital/projects01/druid/extensions-contrib/thrift-extensions/target/generated-test-sources/thrift/scrooge/io/druid/data/input/thrift/Book.java:14:8: 无用导入 - java.util.Set 。 [UnusedImports]
[ERROR] /Users/wusong/Rongcapital/projects01/druid/extensions-contrib/thrift-extensions/target/generated-test-sources/thrift/scrooge/io/druid/data/input/thrift/Book.java:15:8: 无用导入 - java.util.HashSet 。 [UnusedImports]
[ERROR] /Users/wusong/Rongcapital/projects01/druid/extensions-contrib/thrift-extensions/target/generated-test-sources/thrift/scrooge/io/druid/data/input/thrift/Book.java:19:8: 无用导入 - java.nio.ByteBuffer 。 [UnusedImports]
[ERROR] /Users/wusong/Rongcapital/projects01/druid/extensions-contrib/thrift-extensions/target/generated-test-sources/thrift/scrooge/io/druid/data/input/thrift/Book.java:20:8: 无用导入 - java.util.Arrays 。 [UnusedImports]
[ERROR] /Users/wusong/Rongcapital/projects01/druid/extensions-contrib/thrift-extensions/target/generated-test-sources/thrift/scrooge/io/druid/data/input/thrift/Book.java:21:8: 无用导入 - org.slf4j.Logger 。 [UnusedImports]
[ERROR] /Users/wusong/Rongcapital/projects01/druid/extensions-contrib/thrift-extensions/target/generated-test-sources/thrift/scrooge/io/druid/data/input/thrift/Book.java:22:8: 无用导入 - org.slf4j.LoggerFactory 。 [UnusedImports]
[ERROR] /Users/wusong/Rongcapital/projects01/druid/extensions-contrib/thrift-extensions/target/generated-test-sources/thrift/scrooge/io/druid/data/input/thrift/Book.java:24: 不应使用 '.*' 形式的导入 - org.apache.thrift.* 。 [AvoidStarImport]
[ERROR] /Users/wusong/Rongcapital/projects01/druid/extensions-contrib/thrift-extensions/target/generated-test-sources/thrift/scrooge/io/druid/data/input/thrift/Book.java:25: 不应使用 '.*' 形式的导入 - org.apache.thrift.async.* 。 [AvoidStarImport]
[ERROR] /Users/wusong/Rongcapital/projects01/druid/extensions-contrib/thrift-extensions/target/generated-test-sources/thrift/scrooge/io/druid/data/input/thrift/Book.java:26: 不应使用 '.*' 形式的导入 - org.apache.thrift.meta_data.* 。 [AvoidStarImport]
[ERROR] /Users/wusong/Rongcapital/projects01/druid/extensions-contrib/thrift-extensions/target/generated-test-sources/thrift/scrooge/io/druid/data/input/thrift/Book.java:27: 不应使用 '.*' 形式的导入 - org.apache.thrift.transport.* 。 [AvoidStarImport]
[ERROR] /Users/wusong/Rongcapital/projects01/druid/extensions-contrib/thrift-extensions/target/generated-test-sources/thrift/scrooge/io/druid/data/input/thrift/Book.java:28: 不应使用 '.*' 形式的导入 - org.apache.thrift.protocol.* 。 [AvoidStarImport]
[ERROR] /Users/wusong/Rongcapital/projects01/druid/extensions-contrib/thrift-extensions/target/generated-test-sources/thrift/scrooge/io/druid/data/input/thrift/Book.java:67:3: 文件含有制表符 tab （这只是第一例）。 [FileTabCharacter]
[ERROR] /Users/wusong/Rongcapital/projects01/druid/extensions-contrib/thrift-extensions/target/generated-test-sources/thrift/scrooge/io/druid/data/input/thrift/Book.java:85: 'if' 结构必须使用大括号 '{}'。 [NeedBraces]
[ERROR] /Users/wusong/Rongcapital/projects01/druid/extensions-contrib/thrift-extensions/target/generated-test-sources/thrift/scrooge/io/druid/data/input/thrift/Book.java:349: 'if' 结构必须使用大括号 '{}'。 [NeedBraces]
[ERROR] /Users/wusong/Rongcapital/projects01/druid/extensions-contrib/thrift-extensions/target/generated-test-sources/thrift/scrooge/io/druid/data/input/thrift/Book.java:351: 'if' 结构必须使用大括号 '{}'。 [NeedBraces]
[ERROR] /Users/wusong/Rongcapital/projects01/druid/extensions-contrib/thrift-extensions/target/generated-test-sources/thrift/scrooge/io/druid/data/input/thrift/Book.java:357: 'if' 结构必须使用大括号 '{}'。 [NeedBraces]
[ERROR] /Users/wusong/Rongcapital/projects01/druid/extensions-contrib/thrift-extensions/target/generated-test-sources/thrift/scrooge/io/druid/data/input/thrift/Book.java:362: 'if' 结构必须使用大括号 '{}'。 [NeedBraces]
[ERROR] /Users/wusong/Rongcapital/projects01/druid/extensions-contrib/thrift-extensions/target/generated-test-sources/thrift/scrooge/io/druid/data/input/thrift/Book.java:364: 'if' 结构必须使用大括号 '{}'。 [NeedBraces]
[ERROR] /Users/wusong/Rongcapital/projects01/druid/extensions-contrib/thrift-extensions/target/generated-test-sources/thrift/scrooge/io/druid/data/input/thrift/Book.java:370: 'if' 结构必须使用大括号 '{}'。 [NeedBraces]
[ERROR] /Users/wusong/Rongcapital/projects01/druid/extensions-contrib/thrift-extensions/target/generated-test-sources/thrift/scrooge/io/druid/data/input/thrift/Book.java:372: 'if' 结构必须使用大括号 '{}'。 [NeedBraces]
[ERROR] /Users/wusong/Rongcapital/projects01/druid/extensions-contrib/thrift-extensions/target/generated-test-sources/thrift/scrooge/io/druid/data/input/thrift/Book.java:378: 'if' 结构必须使用大括号 '{}'。 [NeedBraces]
[ERROR] /Users/wusong/Rongcapital/projects01/druid/extensions-contrib/thrift-extensions/target/generated-test-sources/thrift/scrooge/io/druid/data/input/thrift/Book.java:380: 'if' 结构必须使用大括号 '{}'。 [NeedBraces]
[ERROR] /Users/wusong/Rongcapital/projects01/druid/extensions-contrib/thrift-extensions/target/generated-test-sources/thrift/scrooge/io/druid/data/input/thrift/Book.java:386: 'if' 结构必须使用大括号 '{}'。 [NeedBraces]
[ERROR] /Users/wusong/Rongcapital/projects01/druid/extensions-contrib/thrift-extensions/target/generated-test-sources/thrift/scrooge/io/druid/data/input/thrift/Book.java:388: 'if' 结构必须使用大括号 '{}'。 [NeedBraces]
[ERROR] /Users/wusong/Rongcapital/projects01/druid/extensions-contrib/thrift-extensions/target/generated-test-sources/thrift/scrooge/io/druid/data/input/thrift/Book.java:400: 'if' 结构必须使用大括号 '{}'。 [NeedBraces]
[ERROR] /Users/wusong/Rongcapital/projects01/druid/extensions-contrib/thrift-extensions/target/generated-test-sources/thrift/scrooge/io/druid/data/input/thrift/Book.java:404: 'if' 结构必须使用大括号 '{}'。 [NeedBraces]
[ERROR] /Users/wusong/Rongcapital/projects01/druid/extensions-contrib/thrift-extensions/target/generated-test-sources/thrift/scrooge/io/druid/data/input/thrift/Book.java:408: 'if' 结构必须使用大括号 '{}'。 [NeedBraces]
[ERROR] /Users/wusong/Rongcapital/projects01/druid/extensions-contrib/thrift-extensions/target/generated-test-sources/thrift/scrooge/io/druid/data/input/thrift/Book.java:412: 'if' 结构必须使用大括号 '{}'。 [NeedBraces]
[ERROR] /Users/wusong/Rongcapital/projects01/druid/extensions-contrib/thrift-extensions/target/generated-test-sources/thrift/scrooge/io/druid/data/input/thrift/Book.java:561: 'if' 结构必须使用大括号 '{}'。 [NeedBraces]
[ERROR] /Users/wusong/Rongcapital/projects01/druid/extensions-contrib/thrift-extensions/target/generated-test-sources/thrift/scrooge/io/druid/data/input/thrift/Book.java:565: 'if' 结构必须使用大括号 '{}'。 [NeedBraces]
[ERROR] /Users/wusong/Rongcapital/projects01/druid/extensions-contrib/thrift-extensions/target/generated-test-sources/thrift/scrooge/io/druid/data/input/thrift/Book.java:573: 'if' 结构必须使用大括号 '{}'。 [NeedBraces]
Audit done.
