### ISSUE TITLE
DoubleFirstAggregatorFactory java.lang.ClassCastException

### ISSUE THREAD

**Issue by wysstartgo** [apache/incubator-druid#4734]
my code is:
 
 private static void executeTopNQuery(DruidClient druidClient) {
        // Create a simple select query using the Druids query builder.
        final int threshold = 1500;
        // final Query query = getSelectQuery(threshold);
        // TopNQuery topNQuery = new TopNQueryBuilder()
        AggregatorFactory aggregatorFactory = new DoubleMaxAggregatorFactory("highPx", "mostHighPx");
        CountAggregatorFactory countAggregatorFactory = new CountAggregatorFactory("count");
        DoubleMinAggregatorFactory doubleMinAggregatorFactory = new DoubleMinAggregatorFactory("lowPx", "worstLowPx");
        DoubleFirstAggregatorFactory doubleFirstAggregatorFactory = new DoubleFirstAggregatorFactory("openPxs", "openPx");
        DoubleLastAggregatorFactory doubleLastAggregatorFactory = new DoubleLastAggregatorFactory("closePxs", "lastClosePx");

        DateTime startDateTime = new DateTime(2017, 8, 31, 10, 5).toDateTime(DateTimeZone.UTC);
        DateTime endDateTime = new DateTime(2017, 8, 31, 11, 10).toDateTime(DateTimeZone.UTC);
        Interval interval = new Interval(startDateTime, endDateTime);
        //表明是按照prodCode来查找topN
        TopNQuery topNQuery = new TopNQueryBuilder().dataSource(dataSource).dimension("prodCode")
                .metric("highPx").threshold(threshold)
                .intervals(ImmutableList.<Interval>of(interval))
                .granularity(Granularities.HOUR)
                //.intervals("2012-01-01/2018-01-01")
                .aggregators(ImmutableList.of(aggregatorFactory,
                        countAggregatorFactory,
                        doubleMinAggregatorFactory,
                        doubleFirstAggregatorFactory,
                        doubleLastAggregatorFactory
                )).build();
        // Fetch the results.
        final long startTime = System.currentTimeMillis();
        final Sequence<Result<TopNResultValue>> resultSequence = druidClient.execute(topNQuery);
        System.out.println(resultSequence);
        final List<Result<TopNResultValue>> resultList = Sequences.toList(resultSequence,
                Lists.<Result<TopNResultValue>> newArrayList());
        final long fetchTime = System.currentTimeMillis() - startTime;

        // Print the results.
        int resultCount = 0;
        for (final Result<TopNResultValue> result : resultList) {
            System.out.println("时间戳为:" + result.getTimestamp());
            TopNResultValue topNResultValue = result.getValue();
            List<DimensionAndMetricValueExtractor> dimensionAndMetricValueExtractors = topNResultValue.getValue();
            System.out.println("DimensionAndMetricValueExtractor size is:" + dimensionAndMetricValueExtractors.size());
            for (DimensionAndMetricValueExtractor dimensionAndMetricValueExtractor : dimensionAndMetricValueExtractors) {
                resultCount++;
                System.out.println(dimensionAndMetricValueExtractor.getBaseObject());
            }
        }

        // Print statistics.
        System.out.println(String.format("Fetched %,d rows in %,dms.", resultCount, fetchTime));
    }

when execute:

Exception in thread "main" java.lang.ClassCastException: java.lang.Double cannot be cast to java.util.Map
	at io.druid.query.aggregation.first.DoubleFirstAggregatorFactory.deserialize(DoubleFirstAggregatorFactory.java:175)
	at io.druid.query.aggregation.MetricManipulatorFns$3.manipulate(MetricManipulatorFns.java:59)
	at io.druid.query.topn.TopNQueryQueryToolChest$5$1.apply(TopNQueryQueryToolChest.java:193)
	at io.druid.query.topn.TopNQueryQueryToolChest$5$1.apply(TopNQueryQueryToolChest.java:181)
	at com.google.common.collect.Iterators$8.transform(Iterators.java:794)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.collect.Iterators.addAll(Iterators.java:357)
	at com.google.common.collect.Lists.newArrayList(Lists.java:147)
	at com.google.common.collect.Lists.newArrayList(Lists.java:129)
	at io.druid.query.topn.TopNQueryQueryToolChest$5.apply(TopNQueryQueryToolChest.java:177)
	at io.druid.query.topn.TopNQueryQueryToolChest$5.apply(TopNQueryQueryToolChest.java:167)
	at io.druid.java.util.common.guava.MappingAccumulator.accumulate(MappingAccumulator.java:42)
	at io.druid.java.util.common.guava.BaseSequence.accumulate(BaseSequence.java:46)
	at io.druid.java.util.common.guava.MappedSequence.accumulate(MappedSequence.java:43)
	at io.druid.java.util.common.guava.Sequences.toList(Sequences.java:150)
	at io.imply.druid.query.ExampleMain.executeTopNQuery(ExampleMain.java:256)
	at io.imply.druid.query.ExampleMain.main(ExampleMain.java:78)

**Comment by wysstartgo** [comment]
when delete the DoubleFirstAggregatorFactory  from aggregators，the exception disappeared。

**Comment by wysstartgo** [comment]
I test druid 0.10.0 and 0.10.1  ,the DoubleFirstAggregatorFactory and DoubleLastAggregatorFactory can't work and occur  java.lang.ClassCastException: java.lang.Double cannot be cast to java.util.Map
at io.druid.query.aggregation.first.DoubleFirstAggregatorFactory.deserialize(DoubleFirstAggregatorFactory.java:175) .But it can works well in linux console as command like:
 curl -L -H'Content-Type: application/json' -XPOST --data-binary @quickstart/market-top.json http://localhost:8082/druid/v2/?pretty


market-top.json is:
{
  "queryType" : "topN",
  "dataSource" : "market-wys-test",
  "intervals" : ["2017-09-04/2017-09-05"],
  "granularity" : "all",
  "dimension" : "prodCode",
  "metric" : "highPx",
  "threshold" : 25,
  "aggregations" : [
    {
      "type" : "doubleMax",
      "name" : "highPx",
      "fieldName" : "mostHighPx"
    },
    {
      "type" : "doubleFirst",
      "name" : "lowPx",
      "fieldName" : "worstLowPx"
    }
  ]
}

**Comment by leventov** [comment]
@wysstartgo would you be able to provide a patch that fixes this bug?

**Comment by QubitPi** [comment]
@leventov I have some experiences on developing custom Druid aggregator and I am a core contributor of a [Druid-based project](https://github.com/yahoo/fili). Could I try and submit a patch for this issue? Looks like @wysstartgo didn't have much time for it.

**Comment by jihoonson** [comment]
Hi @wysstartgo and @QubitPi, have you had a chance to check this issue? Is this still valid? I've tested in 0.12.2 but it looks working.

**Comment by fjy** [comment]
Closing this issue, please reopen if it is still a problem
