### ISSUE TITLE
Issues wth Hadoop batch indexing using S3A in 0.10.1 and hadoop client 2.7.3

### ISSUE THREAD

**Issue by sata** [apache/incubator-druid#4841]
Hi,

I'm having issues  with getting hadoop batch indexing to work with S3A. We are at the moment running 0.9.2 with S3N and would like to upgrade to 0.10.1 with S3A due to the stability improvements in S3A.

From the releases notes of 0.10.1[1] There isn't much to go on in terms of how to get it working properly.

> Amazon's S3A filesystem is now supported for deep storage and as an input source for batch ingestion tasks. Please refer to <> for documentation.

A stripped example of the Hadoop index job can be found at [2]. I had to pull down the hadoop-aws:2.7.3 as well as specify it "hadoopDependencyCoordinates". Otherwise I would be met with 

> Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found

What seems to be the problem now is library version clashes. The exception I'm seeing now  is:

> java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.google.common.base.Throwables.propagate(Throwables.java:160) ~[guava-16.0.1.jar:?]
	at io.druid.indexing.common.task.HadoopTask.invokeForeignLoader(HadoopTask.java:218) ~[druid-indexing-service-0.10.1.jar:0.10.1]
	at io.druid.indexing.common.task.HadoopIndexTask.run(HadoopIndexTask.java:177) ~[druid-indexing-service-0.10.1.jar:0.10.1]
	at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:436) [druid-indexing-service-0.10.1.jar:0.10.1]
	at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:408) [druid-indexing-service-0.10.1.jar:0.10.1]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at io.druid.indexing.common.task.HadoopTask.invokeForeignLoader(HadoopTask.java:215) ~[druid-indexing-service-0.10.1.jar:0.10.1]
	... 7 more
**Caused by: java.lang.NoSuchMethodError: com.amazonaws.AmazonWebServiceRequest.copyPrivateRequestParameters()Ljava/util/Map;**
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3506) ~[?:?]
	at com.amazonaws.services.s3.AmazonS3Client.headBucket(AmazonS3Client.java:1031) ~[?:?]
	**at com.amazonaws.services.s3.AmazonS3Client.doesBucketExist(AmazonS3Client.java:994) ~[?:?]
	at org.apache.hadoop.fs.s3a.S3AFileSystem.initialize(S3AFileSystem.java:297) ~[?:?]**
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2669) ~[?:?]
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:94) ~[?:?]
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2703) ~[?:?]
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2685) ~[?:?]
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373) ~[?:?]
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295) ~[?:?]
	at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.setInputPaths(FileInputFormat.java:500) ~[?:?]
	at org.apache.hadoop.mapreduce.lib.input.DelegatingInputFormat.getSplits(DelegatingInputFormat.java:110) ~[?:?]
	at org.apache.hadoop.mapreduce.JobSubmitter.writeNewSplits(JobSubmitter.java:301) ~[?:?]
	at org.apache.hadoop.mapreduce.JobSubmitter.writeSplits(JobSubmitter.java:318) ~[?:?]
	at org.apache.hadoop.mapreduce.JobSubmitter.submitJobInternal(JobSubmitter.java:196) ~[?:?]
	at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1290) ~[?:?]
	at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1287) ~[?:?]

By the looks of it, it seems to conflicting libraries. 

/lib/aws-java-sdk-core-1.10.77.jar contains AmazonWebServiceRequest  class which doesn't have copyPrivateRequestParameters but hadoop-aws lib fetched through pull-deps has aws-java-sdk-1.7.4.jar under ../hadoop-dependencies/hadoop-aws which indeed has this function.

So my questions now are how has people set S3A up with hadoop indexing jobs with Druid 0.10.1 to avoid the situation I'm facing?

[1] https://github.com/druid-io/druid/issues/4384
[2] https://gist.github.com/sata/114d7efca956befc0e485dd9dc49f78f

**Comment by sata** [comment]
I've seen threads in google groups but I can't see a solution there. Example: https://groups.google.com/forum/?#!msg/druid-user/HhcMkkbKRXI/6BYEs8HDAgAJ

**Comment by jon-wei** [comment]
@sata Can you try adding `mapreduce.job.classloader = true` or `mapreduce.job.user.classpath.first = true` to the tuningConfig -> jobProperties of the ingestion spec

**Comment by sata** [comment]
Hi @jon-wei,

I've tried it and I still get the same error.

I also tried to use

`"mapreduce.job.classloader.system.classes":"-com.amazonaws"`

in combination with `mapreduce.job.classloader = true` but it didn't work.

**Comment by jon-wei** [comment]
Hm, what happens if you replace the 1.7.4 jars under hadoop-aws with the 1.10.77 jars?

@b-slim @himanshug Any thoughts on this issue?

**Comment by himanshug** [comment]
sorry, I don't have first hand experience with AWS but here are a few observations...

@sata Also, I checked 0.10.1 archive available for download at http://druid.io/downloads.html and it does contain `druid-0.10.1/extensions/druid-hdfs-storage/hadoop-aws-2.7.3.jar` so not sure why you had to manually pull it. Are you building druid yourself or using the archive available ? i hope you did not download it into `druid-0.10.1/lib` folder which created the conflict.
also, do you add any hadoop jars explicitly on the druid process classpath ?

however, in case of clear conflict bug, this failure would happen every time so it would have been caught in manual testing of s3a use , @b-slim have you seen above error in your testing of 0.10.1 and s3a ?

**Comment by b-slim** [comment]
@sata are you using the HDFS module to write segments to S3A support?

**Comment by sata** [comment]
@himanshug We're not using HDFS extension, at all. For deep storage we use S3. We are using the stable release and not building ourselves though we're stripping away unused extensions such as druid-hdfs-storage.

@b-slim No. We're not using HDFS but relying on S3 for deep storage. Are you saying to be able to use S3A the HDFS extension needs to be loaded and available through druid.extensions.loadList?

Preferably it would be good not needing to rely on HDFS extension for S3A support if we aren't  intending on using HDFS as deep storage solution.

**Comment by b-slim** [comment]
@sata yes you can use the hdfs deep storage extension to write data via Hadoop indexing jobs (in the end of the day you are using hadoop to run jobs so why not use native hadoop API to write to S3 via S3A driver, that's how I tested it).

**Comment by sata** [comment]
@b-slim According to the docs of hdfs deep storage I need to set druid.storage.type to hdfs and define druid.storage.storageDirectory.  If I leave druid.storage.type to s3 and leave druid.storage.storageDirectory undefined, I get  

> 2017-10-05T14:03:00,954 ERROR [main] io.druid.cli.CliPeon - Error when starting up.  Failing.
> com.google.inject.ProvisionException: Unable to provision, see the following errors:
> 
> 1) Error injecting constructor, java.lang.IllegalArgumentException: Can not create a Path from an empty string
>   at io.druid.storage.hdfs.HdfsDataSegmentKiller.<init>(HdfsDataSegmentKiller.java:46)

Has anyone tested to write to S3 with HDFS extension when using s3 as deep storage?

**Comment by b-slim** [comment]
@sata yes `druid.storage.type` must be `hdfs` and path can be `s3a://bucket/dir`

**Comment by b-slim** [comment]
@sata you might want to  look at this for the security setups to read/write on S3a https://hortonworks.github.io/hdp-aws/s3-security/index.html

**Comment by shaoxinye** [comment]
@sata how to solute this ? help!!!

**Comment by bjitd** [comment]
@b-slim is there any reference doc how to define the path, I was trying to use HDFS to push the segment. However, I noticed if I mention hdfs it uses segmentOutputPath from hdfs config.

**Comment by bendrecm** [comment]
Is anyone able to solve this issue ? I encountered this while deploying Druid in Mumbai AWS region. There were no issues in Ireland region.

**Comment by jihoonson** [comment]
Hi @bendrecm, I've been done several tests against several Hadoop versions on #5382, and S3A shouldn't work because of the version mismatch of `aws-java-sdk` between Hadoop 2.7 and Druid. AFAIK, using S3N is the easiest workaround if you don't much care about performance degradation. Or, if you want to use S3A, another possible workaround is building a customized `hadoop-aws.jar` which shades aws libraries, and using it. You can find which changes are needed [here](https://github.com/apache/hadoop/compare/branch-2.7.5...jihoonson:hadoop-aws-for-druid?expand=1).

BTW, would you elaborate more on `There were no issues in Ireland region.`? Was there no problem at all using S3A and Hadoop 2.7 with Druid 0.10.1?

**Comment by kskalski** [comment]
Is it a viable solution to replace hadoop-aws with a more recent version (from newer Hadoop release) to obtain a working S3A storage or will it cause some other incompatibilites with rest of the jars?

It would be nice if Druid distributed a fixed version of hadoop-aws.jar that works correctly with aws-java-sdk distributed with it.

**Comment by jihoonson** [comment]
Hi @kskalski, a possible solution is to build your own hadoop-aws.jar which shades all conflicting dependencies in it. At least aws-java-sdk and jackson should be shaded.

Probably recent versions of hadoop-aws would work because they're shading the common libraries, but I haven't tested them.

**Comment by kskalski** [comment]
FIY, I tried using hadoop-aws.jar from Hadoop 2.9 release, but it required a lot of other jars to be replaced, both in hadoop-dependencies and from Druid's extensions/druid-hdfs-storage/ (e.g. aws-java-sdk used by hadoop's 2.9 is already newer than Druid 0.12.1's version, so I had to make both directories converge). Ultimately S3A started working, but the way to achieve it was quite messy.

Not sure if shading would work, I couldn't build the custom jar, because Hadoop 2.7 requires dependencies (protoc) that are no longer available on OS at my disposal. For now I settled with using S3N, but it forces provising AWS secret credentials in plain text within config / task spec, so it's a pain.

**Comment by jihoonson** [comment]
@kskalski thanks for sharing your experience. I'm wondering what the version of your Hadoop cluster is. If you're using 2.9, then S3A should work with hadoop-client and hadoop-aws of 2.9 without touching any conflicting libraries. I've tested it in https://github.com/apache/incubator-druid/pull/5382. Note that I set `mapreduce.job.classloader = true`. If it doesn't work, it's probably a bug or something. Would you tell me more details (especially error messages or stack traces)?

**Comment by kskalski** [comment]
At the moment my use-case is local indexing task ("index_hadoop" but without remote Hadoop cluster) with ioConfig type "hadoop" and input path pointing to "s3a://bucket/..." location, all running on AWS vms. The feature I wanted to use is role-based access to S3, which allows reading data from storage using credentials taken from environment (EC2 vm). This make s3a implementation call out to aws sdk and version incompatibility arises caused by very similar exception as mentioned here, i.e.:
```
Caused by: java.lang.NoSuchMethodError: com.amazonaws.AmazonWebServiceRequest.copyPrivateRequestParameters()Ljava/util/Map;
at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3506) ~[?:?]
at com.amazonaws.services.s3.AmazonS3Client.headBucket(AmazonS3Client.java:1031) ~[?:?]
at com.amazonaws.services.s3.AmazonS3Client.doesBucketExist(AmazonS3Client.java:994) ~[?:?]
at org.apache.hadoop.fs.s3a.S3AFileSystem.initialize(S3AFileSystem.java:297) ~[?:?]
```

I thought that using newer hadoop-aws.jar would help, but using the oldest newer than 2.7, that is 2.9 didn't help in itself. Instead it had other errors due to incompatibilities between different jars. In afterthought, maybe the culprit is not hadoop-aws.jar, but simply the fact that hadoop-dependencies/2.7 uses too old aws-java-sdk and converging it on the same version as placed in extensions/druid-hdfs-storage/ would be enough (though it will likely require several other jars to be brought in sync between those two dirs).

I could try using ``mapreduce.job.classloader = true`` and/or just upgrading aws sdk.
