### ISSUE TITLE
Dose druid support CacheDB?

### ISSUE THREAD

**Issue by whiterye** [apache/incubator-druid#4864]
When I try to connect CacheDB based on DRUID , I meet some question like this:

```
16:16:49.219 [localhost-startStop-1] WARN  OldSpringSupport - Import of META-INF/cxf/cxf-extension-soap.xml has been deprecated and is unnecessary.
16:16:49.346 [localhost-startStop-1] ERROR DruidAbstractDataSource - maxIdle is deprecated
16:16:50.240 [localhost-startStop-1] ERROR DruidAbstractDataSource - maxIdle is deprecated
16:16:50.276 [localhost-startStop-1] ERROR DruidDataSource - {dataSource-1} init error
java.sql.SQLException: com.intersys.jdbc.CacheDriver
	at com.alibaba.druid.util.JdbcUtils.createDriver(JdbcUtils.java:566) ~[druid-1.0.26.jar:1.0.26]
	at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:642) [druid-1.0.26.jar:1.0.26]
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:988) [druid-1.0.26.jar:1.0.26]
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:984) [druid-1.0.26.jar:1.0.26]
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:103) [druid-1.0.26.jar:1.0.26]
	at org.apache.ibatis.mapping.VendorDatabaseIdProvider.getDatabaseProductName(VendorDatabaseIdProvider.java:77) [mybatis-3.2.7.jar:3.2.7]
	at org.apache.ibatis.mapping.VendorDatabaseIdProvider.getDatabaseName(VendorDatabaseIdProvider.java:62) [mybatis-3.2.7.jar:3.2.7]
	at org.apache.ibatis.mapping.VendorDatabaseIdProvider.getDatabaseId(VendorDatabaseIdProvider.java:50) [mybatis-3.2.7.jar:3.2.7]
```

**Comment by leventov** [comment]
This issue belongs to https://github.com/alibaba/druid
