### ISSUE TITLE
Hadoop index task occasionally fail

### ISSUE THREAD

**Issue by erankor** [apache/incubator-druid#5114]
Hi all,

I'm having an issue where some of our Hadoop indexing tasks fail (most of our tasks are successful). I think it happens when the input / resulting segment size is large (maybe some memory limit is exceeded), but I can't find any hint to that in the exception. The task reaches `map 100% reduce 100%` and then fails.

This is the error from the task log:
```
2017-11-23T04:14:20,685 INFO [task-runner-0-priority-0] org.apache.hadoop.mapreduce.Job -  map 100% reduce 100%
2017-11-23T04:15:07,856 INFO [HttpPostEmitter-1-0] com.metamx.http.client.pool.ChannelResourceFactory - Generating: http://x.y.z.w:7000
...
2017-11-23T04:26:23,588 INFO [task-runner-0-priority-0] org.apache.hadoop.mapreduce.Job - Job job_1509360417142_3862 failed with state FAILED due to: Task failed task_1509360417142_3862_r_000000
Job failed as tasks failed. failedMaps:0 failedReduces:1

2017-11-23T04:26:23,659 INFO [task-runner-0-priority-0] org.apache.hadoop.mapreduce.Job - Counters: 42
	File System Counters
		FILE: Number of bytes read=8892350534
		FILE: Number of bytes written=17857749481
		FILE: Number of read operations=0
		FILE: Number of large read operations=0
		FILE: Number of write operations=0
		HDFS: Number of bytes read=23059
		HDFS: Number of bytes written=0
		HDFS: Number of read operations=148
		HDFS: Number of large read operations=0
		HDFS: Number of write operations=0
		S3: Number of bytes read=3482384404
		S3: Number of bytes written=0
		S3: Number of read operations=0
		S3: Number of large read operations=0
		S3: Number of write operations=0
	Job Counters 
		Failed reduce tasks=4
		Launched map tasks=74
		Launched reduce tasks=4
		Rack-local map tasks=74
		Total time spent by all maps in occupied slots (ms)=188764650
		Total time spent by all reduces in occupied slots (ms)=2024207616
		Total time spent by all map tasks (ms)=4194770
		Total time spent by all reduce tasks (ms)=10542748
		Total vcore-milliseconds taken by all map tasks=4194770
		Total vcore-milliseconds taken by all reduce tasks=10542748
		Total megabyte-milliseconds taken by all map tasks=6040468800
		Total megabyte-milliseconds taken by all reduce tasks=64774643712
	Map-Reduce Framework
		Map input records=102196318
		Map output records=102196318
		Map output bytes=48889085383
		Map output materialized bytes=8949241057
		Input split bytes=23059
		Combine input records=0
		Spilled Records=203673175
		Failed Shuffles=0
		Merged Map outputs=0
		GC time elapsed (ms)=101204
		CPU time spent (ms)=5133010
		Physical memory (bytes) snapshot=46403289088
		Virtual memory (bytes) snapshot=190116319232
		Total committed heap usage (bytes)=39559626752
	File Input Format Counters 
		Bytes Read=0
2017-11-23T04:26:23,662 INFO [task-runner-0-priority-0] io.druid.indexer.JobHelper - Deleting path[/tmp/druid-indexing/bandwidth-usage/2017-11-23T010002.727Z_45281c93490b4a659656249535b63608]
2017-11-23T04:26:23,687 ERROR [task-runner-0-priority-0] io.druid.indexing.overlord.ThreadPoolTaskRunner - Exception while running task[HadoopIndexTask{id=index_hadoop_bandwidth-usage_2017-11-23T01:00:02.713Z, type=index_hadoop, dataSource=bandwidth-usage}]
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.google.common.base.Throwables.propagate(Throwables.java:160) ~[guava-16.0.1.jar:?]
	at io.druid.indexing.common.task.HadoopTask.invokeForeignLoader(HadoopTask.java:211) ~[druid-indexing-service-0.10.0.jar:0.10.0]
	at io.druid.indexing.common.task.HadoopIndexTask.run(HadoopIndexTask.java:223) ~[druid-indexing-service-0.10.0.jar:0.10.0]
	at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:436) [druid-indexing-service-0.10.0.jar:0.10.0]
	at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:408) [druid-indexing-service-0.10.0.jar:0.10.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at io.druid.indexing.common.task.HadoopTask.invokeForeignLoader(HadoopTask.java:208) ~[druid-indexing-service-0.10.0.jar:0.10.0]
	... 7 more
Caused by: io.druid.java.util.common.ISE: Job[class io.druid.indexer.IndexGeneratorJob] failed!
	at io.druid.indexer.JobHelper.runJobs(JobHelper.java:369) ~[druid-indexing-hadoop-0.10.0.jar:0.10.0]
	at io.druid.indexer.HadoopDruidIndexerJob.run(HadoopDruidIndexerJob.java:95) ~[druid-indexing-hadoop-0.10.0.jar:0.10.0]
	at io.druid.indexing.common.task.HadoopIndexTask$HadoopIndexGeneratorInnerProcessing.runTask(HadoopIndexTask.java:276) ~[druid-indexing-service-0.10.0.jar:0.10.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at io.druid.indexing.common.task.HadoopTask.invokeForeignLoader(HadoopTask.java:208) ~[druid-indexing-service-0.10.0.jar:0.10.0]
	... 7 more
2017-11-23T04:26:23,693 INFO [task-runner-0-priority-0] io.druid.indexing.overlord.TaskRunnerUtils - Task [index_hadoop_bandwidth-usage_2017-11-23T01:00:02.713Z] status changed to [FAILED].
2017-11-23T04:26:23,695 INFO [task-runner-0-priority-0] io.druid.indexing.worker.executor.ExecutorLifecycle - Task completed with status: {
  "id" : "index_hadoop_bandwidth-usage_2017-11-23T01:00:02.713Z",
  "status" : "FAILED",
  "duration" : 12375913
}
```
Any help is appreciated!

Thanks,

Eran

**Comment by jdlzy** [comment]
you can try to adjust memory size of yarn in the yarn-site.xml,and maprduce memory
```
 "jobProperties" : {
        "mapreduce.reduce.java.opts" : "-Xmx10240m",
        "mapreduce.map.java.opts" : "-Xmx10240m"
      }
```
this code wile adjust the memory size of mapreduce,
sorry,i'm english isn't good......

**Comment by erankor** [comment]
Thanks @jdlzy! I currently have much lower values (512M / 2G) but do you know this is really the problem? because I don't see any indication of this in the exception...

**Comment by jdlzy** [comment]
I think,you can try to less data(eg:<20m or <10m),if  that's the case  success,that's your memory to lower。
but the (512M / 2G) is too lower

**Comment by jdlzy** [comment]
"jobProperties" : {
        "mapreduce.reduce.java.opts" : "-Xmx10240m",
        "mapreduce.map.java.opts" : "-Xmx1024m"
      }

this configuration in the index file,you should amplify "mapreduce.reduce.java.opts",

**Comment by erankor** [comment]
Thanks! I will try it out

**Comment by erankor** [comment]
Just to update this thread that the problem seems to be solved, didn't have a failed task for a few days. However I made 3 changes in parallel, so not entirely sure yet which ones were actually required -
1. Increased the map/reduce Java heap limit (as suggested by @jdlzy), 10g didn't work for me, I'm now using 1g for map and 3g for reduce.
2. Reduced the number of concurrent Hadoop tasks that I'm submitting
3. Enabled hashed partitioning (targetPartitionSize)
