### ISSUE TITLE
Null storage adapter found. Probably trying to issue a query against a segment being memory unmapped.

### ISSUE THREAD

**Issue by erikdubbelboer** [apache/incubator-druid#5127]
On our realtime nodes we keep seeing the following sequence of errors occur about once a day:

```
druid - Audit - Exception with one of the sequences!
... <repeated 57 times> ...
druid - Audit - input future failed.
... <also repeated 57 times> ...
Audit - Exception with one of the sequences!
... <repeated twice> ...
druid - Audit - Exception handling request: {class=io.druid.server.QueryResource, exceptionType=class io.druid.java.util.common.ISE, exceptionMessage=Null storage adapter found. Probably trying to issue a query against a segment being memory unmapped., exception=io.druid.java.util.common.ISE: Null storage adapter found. Probably trying to issue a query against a segment being memory unmapped., query=GroupByQuery{dataSource='requests', querySegmentSpec=MultipleSpecificSegmentSpec{descriptors=[SegmentDescriptor{interval=2017-11-29T20:00:00.000Z/2017-11-29T21:00:00.000Z, version='2017-11-29T20:00:00.000Z', partitionNumber=1}, SegmentDescriptor{interval=2017-11-29T21:00:00.000Z/2017-11-29T22:00:00.000Z, version='2017-11-29T21:00:00.000Z', partitionNumber=1}, SegmentDescriptor{interval=2017-11-29T22:00:00.000Z/2017-11-29T23:00:00.000Z, version='2017-11-29T22:00:00.000Z', partitionNumber=1}]}, virtualColumns=[], limitSpec=NoopLimitSpec, dimFilter=null, granularity=AllGranularity, dimensions=[DefaultDimensionSpec{dimension='foo_id', outputName='foo_id', outputType='STRING'}, DefaultDimensionSpec{dimension='bar_id', outputName='bar_id', outputType='STRING'}], aggregatorSpecs=[FilteredAggregatorFactory{delegate=LongSumAggregatorFactory{fieldName='requests', expression='null', name='requests'}, filter=baz_id = 1}, DoubleSumAggregatorFactory{fieldName='bax', expression='null', name='bax'}, DoubleSumAggregatorFactory{fieldName='faa', expression='null', name='faa'}, FilteredAggregatorFactory{delegate=LongSumAggregatorFactory{fieldName='requests', expression='null', name='something'}, filter=(baz_id = 1 && !bla = 0)}], postAggregatorSpecs=[], havingSpec=null}, peer=10.240.0.7}
```

We are using Druid 0.10.1-rc2 at the moment.

The realtime nodes build segments with a `HOUR` granularity, `intermediatePersistPeriod` is `PT5M` and `windowPeriod` is `PT1H`.

Is there anything we can do about this or is it maybe fixed in a newer version? I couldn't find any issue about this.

**Comment by gianm** [comment]
Nothing known that comes to mind. What ingestion method are you using (realtime node, tranquility, kafka indexing, etc)?

**Comment by erikdubbelboer** [comment]
We are using a realtime node ingesting from kafka using the kafka-0.8 firehose.

**Comment by gianm** [comment]
Ah, I'm not sure what might be going on there. Do you have a full stack trace?

**Comment by erikdubbelboer** [comment]
```
Exception with one of the sequences!
io.druid.java.util.common.ISE: Null storage adapter found. Probably trying to issue a query against a segment being memory unmapped.
  at io.druid.query.groupby.epinephelinae.GroupByQueryEngineV2.process(GroupByQueryEngineV2.java:96) ~[druid-processing-0.10.1-rc2-SNAPSHOT.jar:0.10.1-rc2-SNAPSHOT]
  at io.druid.query.groupby.strategy.GroupByStrategyV2.process(GroupByStrategyV2.java:349) ~[druid-processing-0.10.1-rc2-SNAPSHOT.jar:0.10.1-rc2-SNAPSHOT]
  at io.druid.query.groupby.GroupByQueryRunnerFactory$GroupByQueryRunner.run(GroupByQueryRunnerFactory.java:108) ~[druid-processing-0.10.1-rc2-SNAPSHOT.jar:0.10.1-rc2-SNAPSHOT]
  at io.druid.query.QueryRunnerHelper$2.run(QueryRunnerHelper.java:82) ~[druid-processing-0.10.1-rc2-SNAPSHOT.jar:0.10.1-rc2-SNAPSHOT]
  at io.druid.client.CachingQueryRunner.run(CachingQueryRunner.java:195) ~[druid-server-0.10.1-rc2-SNAPSHOT.jar:0.10.1-rc2-SNAPSHOT]
  at io.druid.query.ChainedExecutionQueryRunner$1$1$1.call(ChainedExecutionQueryRunner.java:125) [druid-processing-0.10.1-rc2-SNAPSHOT.jar:0.10.1-rc2-SNAPSHOT]
  at io.druid.query.ChainedExecutionQueryRunner$1$1$1.call(ChainedExecutionQueryRunner.java:120) [druid-processing-0.10.1-rc2-SNAPSHOT.jar:0.10.1-rc2-SNAPSHOT]
  at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
  at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:297) [guava-16.0.1.jar:?]
  at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134) [?:1.8.0_131]
  at com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:58) [guava-16.0.1.jar:?]
  at io.druid.query.ChainedExecutionQueryRunner$1$1.apply(ChainedExecutionQueryRunner.java:118) [druid-processing-0.10.1-rc2-SNAPSHOT.jar:0.10.1-rc2-SNAPSHOT]
  at io.druid.query.ChainedExecutionQueryRunner$1$1.apply(ChainedExecutionQueryRunner.java:110) [druid-processing-0.10.1-rc2-SNAPSHOT.jar:0.10.1-rc2-SNAPSHOT]
  at com.google.common.collect.Iterators$8.transform(Iterators.java:794) [guava-16.0.1.jar:?]
  at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48) [guava-16.0.1.jar:?]
  at com.google.common.collect.Iterators.addAll(Iterators.java:357) [guava-16.0.1.jar:?]
  at com.google.common.collect.Lists.newArrayList(Lists.java:147) [guava-16.0.1.jar:?]
  at com.google.common.collect.Lists.newArrayList(Lists.java:129) [guava-16.0.1.jar:?]
  at io.druid.query.ChainedExecutionQueryRunner$1.make(ChainedExecutionQueryRunner.java:106) [druid-processing-0.10.1-rc2-SNAPSHOT.jar:0.10.1-rc2-SNAPSHOT]
  at io.druid.java.util.common.guava.BaseSequence.accumulate(BaseSequence.java:43) [java-util-0.10.1-rc2-SNAPSHOT.jar:0.10.1-rc2-SNAPSHOT]
  at io.druid.java.util.common.guava.LazySequence.accumulate(LazySequence.java:40) [java-util-0.10.1-rc2-SNAPSHOT.jar:0.10.1-rc2-SNAPSHOT]
  at io.druid.java.util.common.guava.WrappingSequence$1.get(WrappingSequence.java:50) [java-util-0.10.1-rc2-SNAPSHOT.jar:0.10.1-rc2-SNAPSHOT]
  at io.druid.java.util.common.guava.SequenceWrapper.wrap(SequenceWrapper.java:55) [java-util-0.10.1-rc2-SNAPSHOT.jar:0.10.1-rc2-SNAPSHOT]
  at io.druid.java.util.common.guava.WrappingSequence.accumulate(WrappingSequence.java:45) [java-util-0.10.1-rc2-SNAPSHOT.jar:0.10.1-rc2-SNAPSHOT]
  at io.druid.java.util.common.guava.LazySequence.accumulate(LazySequence.java:40) [java-util-0.10.1-rc2-SNAPSHOT.jar:0.10.1-rc2-SNAPSHOT]
  at io.druid.java.util.common.guava.WrappingSequence$1.get(WrappingSequence.java:50) [java-util-0.10.1-rc2-SNAPSHOT.jar:0.10.1-rc2-SNAPSHOT]
  at io.druid.java.util.common.guava.SequenceWrapper.wrap(SequenceWrapper.java:55) [java-util-0.10.1-rc2-SNAPSHOT.jar:0.10.1-rc2-SNAPSHOT]
  at io.druid.java.util.common.guava.WrappingSequence.accumulate(WrappingSequence.java:45) [java-util-0.10.1-rc2-SNAPSHOT.jar:0.10.1-rc2-SNAPSHOT]
  at io.druid.java.util.common.guava.WrappingSequence$1.get(WrappingSequence.java:50) [java-util-0.10.1-rc2-SNAPSHOT.jar:0.10.1-rc2-SNAPSHOT]
  at io.druid.query.CPUTimeMetricQueryRunner$1.wrap(CPUTimeMetricQueryRunner.java:74) [druid-processing-0.10.1-rc2-SNAPSHOT.jar:0.10.1-rc2-SNAPSHOT]
  at io.druid.java.util.common.guava.WrappingSequence.accumulate(WrappingSequence.java:45) [java-util-0.10.1-rc2-SNAPSHOT.jar:0.10.1-rc2-SNAPSHOT]
  at io.druid.query.spec.SpecificSegmentQueryRunner$2.accumulate(SpecificSegmentQueryRunner.java:85) [druid-processing-0.10.1-rc2-SNAPSHOT.jar:0.10.1-rc2-SNAPSHOT]
  at io.druid.java.util.common.guava.WrappingSequence$1.get(WrappingSequence.java:50) [java-util-0.10.1-rc2-SNAPSHOT.jar:0.10.1-rc2-SNAPSHOT]
  at io.druid.query.spec.SpecificSegmentQueryRunner.doNamed(SpecificSegmentQueryRunner.java:171) [druid-processing-0.10.1-rc2-SNAPSHOT.jar:0.10.1-rc2-SNAPSHOT]
  at io.druid.query.spec.SpecificSegmentQueryRunner.access$200(SpecificSegmentQueryRunner.java:44) [druid-processing-0.10.1-rc2-SNAPSHOT.jar:0.10.1-rc2-SNAPSHOT]
  at io.druid.query.spec.SpecificSegmentQueryRunner$3.wrap(SpecificSegmentQueryRunner.java:151) [druid-processing-0.10.1-rc2-SNAPSHOT.jar:0.10.1-rc2-SNAPSHOT]
  at io.druid.java.util.common.guava.WrappingSequence.accumulate(WrappingSequence.java:45) [java-util-0.10.1-rc2-SNAPSHOT.jar:0.10.1-rc2-SNAPSHOT]
  at io.druid.java.util.common.guava.Sequences.toList(Sequences.java:150) [java-util-0.10.1-rc2-SNAPSHOT.jar:0.10.1-rc2-SNAPSHOT]
  at io.druid.query.ChainedExecutionQueryRunner$1$1$1.call(ChainedExecutionQueryRunner.java:130) [druid-processing-0.10.1-rc2-SNAPSHOT.jar:0.10.1-rc2-SNAPSHOT]
  at io.druid.query.ChainedExecutionQueryRunner$1$1$1.call(ChainedExecutionQueryRunner.java:120) [druid-processing-0.10.1-rc2-SNAPSHOT.jar:0.10.1-rc2-SNAPSHOT]
  at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
  at io.druid.query.PrioritizedListenableFutureTask.run(PrioritizedExecutorService.java:271) [druid-processing-0.10.1-rc2-SNAPSHOT.jar:0.10.1-rc2-SNAPSHOT]
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_131]
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_131]
  at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

**Comment by erikdubbelboer** [comment]
We are only doing a couple of queries per minute now and this error is happening multiple times per day.

**Comment by himanshug** [comment]
@erikdubbelboer does it fail around the same time when the segment is handed off and realtime node is abandoning the segment.
there is a possiblity that broker forwarded the realtime node a query and right after that, segment was abandoned ... 
I had suggested @niketh to give priority to historicals and fanning out queries to take care of above scenario, that work is done in https://github.com/druid-io/druid/pull/4764 .

however, that wouldn't explain why you've started seeing this issue with increased frequency in 0.10.1 only.

**Comment by erikdubbelboer** [comment]
The increased frequency is probably only because we started running more periodic queries.

**Comment by erikdubbelboer** [comment]
We have updated everything to `0.11.0`. This issue is happening less than before but still happens at least once a week.

**Comment by himanshug** [comment]
@erikdubbelboer I came across a workaround to give historical segments priority . it is described in https://github.com/druid-io/druid/pull/4764#issuecomment-355369156 . hopefully that would help you solve this issue.
