### ISSUE TITLE
Illegal instant due to time zone offset transition

### ISSUE THREAD

**Issue by erankor** [apache/incubator-druid#5200]
Hi all,

I have the following query -
```
{
	"dataSource": "player-events-historical",
	"intervals": ["2017-10-10T00:00:00-03:00\/2017-11-09T23:59:59-03:00"],
	"granularity": {
		"type": "period",
		"period": "P1D",
		"timeZone": "America\/Sao_Paulo"
	},
	"aggregations": [{
		"type": "longSum",
		"name": "count",
		"fieldName": "count"
	}],
	"queryType": "timeseries"
}
```
When I post it to Druid, I'm getting the following exception -
```
# curl -HContent-Type:application/json -i -d @/tmp/sp.json localhost:8082/druid/v2/
HTTP/1.1 500 Internal Server Error
Date: Mon, 01 Jan 2018 15:44:02 GMT
Content-Type: application/json
Content-Length: 321
Server: Jetty(9.3.16.v20170120)

{"error":"Unknown exception","errorMessage":"Value 0 for hourOfDay is not supported: Illegal instant due to time zone offset transition (daylight savings time 'gap'): 2017-10-15T00:00:00.000 (America/Sao_Paulo)","errorClass":"org.joda.time.IllegalFieldValueException","host":"ip-..."}
```
If I change the timezone to `Etc/GMT+3` it works fine. 
I see the following exception in one of the historical nodes -
```
2018-01-01T15:44:02,182 ERROR [processing-12] io.druid.query.ChainedExecutionQueryRunner - Exception with one ofthe sequences!
org.joda.time.IllegalFieldValueException: Value 0 for hourOfDay is not supported: Illegal instant due to time zone offset transition (daylight savings time 'gap'): 2017-10-15T00:00:00.000 (America/Sao_Paulo)
        at org.joda.time.chrono.ZonedChronology$ZonedDateTimeField.set(ZonedChronology.java:486) ~[joda-time-2.8.2.jar:2.8.2]
        at io.druid.java.util.common.granularity.PeriodGranularity.truncate(PeriodGranularity.java:314) ~[java-util-0.10.0.jar:0.10.0]
        at io.druid.java.util.common.granularity.PeriodGranularity.bucketStart(PeriodGranularity.java:124) ~[java-util-0.10.0.jar:0.10.0]
        at io.druid.java.util.common.granularity.Granularity.bucketEnd(Granularity.java:124) ~[java-util-0.10.0.jar:0.10.0]
        at io.druid.segment.QueryableIndexStorageAdapter.makeCursors(QueryableIndexStorageAdapter.java:213) ~[druid-processing-0.10.0.jar:0.10.0]
        at io.druid.query.QueryRunnerHelper.makeCursorBasedQuery(QueryRunnerHelper.java:61) ~[druid-processing-0.10.0.jar:0.10.0]
        at io.druid.query.timeseries.TimeseriesQueryEngine.process(TimeseriesQueryEngine.java:50) ~[druid-processing-0.10.0.jar:0.10.0]
        at io.druid.query.timeseries.TimeseriesQueryRunnerFactory$TimeseriesQueryRunner.run(TimeseriesQueryRunnerFactory.java:102) ~[druid-processing-0.10.0.jar:0.10.0]
        at io.druid.query.ReferenceCountingSegmentQueryRunner.run(ReferenceCountingSegmentQueryRunner.java:55) ~[druid-processing-0.10.0.jar:0.10.0]
        at io.druid.query.MetricsEmittingQueryRunner$2.get(MetricsEmittingQueryRunner.java:102) ~[druid-processing-0.10.0.jar:0.10.0]
        at io.druid.query.MetricsEmittingQueryRunner$2.get(MetricsEmittingQueryRunner.java:98) ~[druid-processing-0.10.0.jar:0.10.0]
        at io.druid.java.util.common.guava.LazySequence.accumulate(LazySequence.java:40) ~[java-util-0.10.0.jar:0.10.0]
        at io.druid.java.util.common.guava.WrappingSequence$1.get(WrappingSequence.java:50) ~[java-util-0.10.0.jar:0.10.0]
        at io.druid.java.util.common.guava.SequenceWrapper.wrap(SequenceWrapper.java:55) ~[java-util-0.10.0.jar:0.10.0]
        at io.druid.java.util.common.guava.WrappingSequence.accumulate(WrappingSequence.java:45) ~[java-util-0.10.0.jar:0.10.0]
        at io.druid.java.util.common.guava.Sequences.toList(Sequences.java:150) ~[java-util-0.10.0.jar:0.10.0]
        at io.druid.query.BySegmentQueryRunner.run(BySegmentQueryRunner.java:56) ~[druid-processing-0.10.0.jar:0.10.0]
        at io.druid.query.MetricsEmittingQueryRunner$2.get(MetricsEmittingQueryRunner.java:102) ~[druid-processing-0.10.0.jar:0.10.0]
        at io.druid.query.MetricsEmittingQueryRunner$2.get(MetricsEmittingQueryRunner.java:98) ~[druid-processing-0.10.0.jar:0.10.0]
        at io.druid.java.util.common.guava.LazySequence.accumulate(LazySequence.java:40) ~[java-util-0.10.0.jar:0.10.0]
        at io.druid.java.util.common.guava.WrappingSequence$1.get(WrappingSequence.java:50) ~[java-util-0.10.0.jar:0.10.0]
        at io.druid.java.util.common.guava.SequenceWrapper.wrap(SequenceWrapper.java:55) ~[java-util-0.10.0.jar:0.10.0]
        at io.druid.java.util.common.guava.WrappingSequence.accumulate(WrappingSequence.java:45) ~[java-util-0.10.0.jar:0.10.0]
        at io.druid.query.spec.SpecificSegmentQueryRunner$2.accumulate(SpecificSegmentQueryRunner.java:83) ~[druid-processing-0.10.0.jar:0.10.0]
        at io.druid.java.util.common.guava.WrappingSequence$1.get(WrappingSequence.java:50) ~[java-util-0.10.0.jar:0.10.0]
        at io.druid.query.spec.SpecificSegmentQueryRunner.doNamed(SpecificSegmentQueryRunner.java:169) ~[druid-processing-0.10.0.jar:0.10.0]
        at io.druid.query.spec.SpecificSegmentQueryRunner.access$200(SpecificSegmentQueryRunner.java:43) ~[druid-processing-0.10.0.jar:0.10.0]
        at io.druid.query.spec.SpecificSegmentQueryRunner$3.wrap(SpecificSegmentQueryRunner.java:149) ~[druid-processing-0.10.0.jar:0.10.0]
        at io.druid.java.util.common.guava.WrappingSequence.accumulate(WrappingSequence.java:45) ~[java-util-0.10.0.jar:0.10.0]
        at io.druid.java.util.common.guava.WrappingSequence$1.get(WrappingSequence.java:50) ~[java-util-0.10.0.jar:0.10.0]
        at io.druid.query.CPUTimeMetricQueryRunner$1.wrap(CPUTimeMetricQueryRunner.java:78) ~[druid-processing-0.10.0.jar:0.10.0]
        at io.druid.java.util.common.guava.WrappingSequence.accumulate(WrappingSequence.java:45) ~[java-util-0.10.0.jar:0.10.0]
        at io.druid.java.util.common.guava.Sequences.toList(Sequences.java:150) ~[java-util-0.10.0.jar:0.10.0]
        at io.druid.query.ChainedExecutionQueryRunner$1$1$1.call(ChainedExecutionQueryRunner.java:129) [druid-processing-0.10.0.jar:0.10.0]
        at io.druid.query.ChainedExecutionQueryRunner$1$1$1.call(ChainedExecutionQueryRunner.java:119) [druid-processing-0.10.0.jar:0.10.0]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
        at io.druid.query.PrioritizedListenableFutureTask.run(PrioritizedExecutorService.java:271) [druid-processing-0.10.0.jar:0.10.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: org.joda.time.IllegalInstantException: Illegal instant due to time zone offset transition (daylight savings time 'gap'): 2017-10-15T00:00:00.000 (America/Sao_Paulo)
        at org.joda.time.chrono.ZonedChronology$ZonedDateTimeField.set(ZonedChronology.java:485) ~[joda-time-2.8.2.jar:2.8.2]
        ... 39 more
```
Since the failed timestamp occurs somewhere within the requested interval (it's not close to the edges), I believe this is a bug in Druid (I'm using Druid 0.10.0), but please let me know if you think I'm doing something wrong.

Thank you!

Eran

**Comment by nishantmonu51** [comment]
As per link - http://joda-time.sourceforge.net/faq.html#illegalinstant
The error "Illegal instant due to time zone offset transition" refers to the gap in time caused due to DST.

**Comment by erankor** [comment]
Thanks @nishantmonu51, I figured that part... however, since the timezone in the exception (2017-10-15T00:00:00.000) is not a timestamp I send, I can't really solve it on my side... it's contained within the interval I send (2017-10-10T00:00:00-03:00/2017-11-09T23:59:59-03:00) but it's not one of them.
I believe it's a bug in the Druid code that breaks the query into sub-queries for sending to the historical nodes.

**Comment by thomask** [comment]
Hi there! We're dealing with the same issue. Did you ever find a solution?

**Comment by erankor** [comment]
We are using timezones like Etc/GMT-## or Etc/GMT+##, it seems those are not subject to daylight saving changes, so it works around the issue. 
But this is far from ideal, I hope this issue will be addressed...

**Comment by thomask** [comment]
Thanks for letting me know! Are you able to re-open this issue in that case?

**Comment by erankor** [comment]
I don't have a reopen button, maybe they blocked it somehow... maybe you should try mentioning one of the owners.

**Comment by gianm** [comment]
@thomask @erankor I just reopened this issue; what is the latest Druid version you have seen this issue on?

**Comment by gianm** [comment]
I think https://github.com/apache/incubator-druid/pull/8711 will fix it. Hopefully.

**Comment by erankor** [comment]
Thanks @gianm, regarding Druid version, we've just reproduced it on druid-0.12.1, haven't tested with the fix yet
