### ISSUE TITLE
ORC file and numeric dimension ends with error

### ISSUE THREAD

**Issue by 13Homer** [apache/incubator-druid#5419]
Hi,
I'm using Druid 0.11.0 with druid-orc-extension. Ingestion using this kind of config:
```
{
  "type": "index_hadoop",
    "spec": {
      "ioConfig": {
        "type": "hadoop",
        "inputSpec": {
          "type": "static",
          "inputFormat": "org.apache.hadoop.hive.ql.io.orc.OrcNewInputFormat",
          "paths": "/p/a/t/h"
        }
      },
      "dataSchema": {
        "dataSource": "ds",
        "parser": {
          "type": "orc",
          "parseSpec": {
            "format": "timeAndDims",
            "timestampSpec": {
              "column": "ts",
              "format": "auto"
          },
          "dimensionsSpec": {
            "dimensions": [
              "dimension1",
              {
                "name": "metric1",
                "type": "float"
              }
            ],
            "dimensionExclusions": [],
            "spatialDimensions": []
          }
        },
       "typeString":"struct<ts:date,dimension1:string,metric1:float>"
      },
      "metricsSpec": [
          {"type": "floatSum", "name": "Metric no 1", "fieldName": "metric1" }
      ],
      "granularitySpec": {
        "type": "uniform",
        "rollup":"false",
        "segmentGranularity": "YEAR",
        "queryGranularity": "MONTH",
        "intervals": ["2008-12-01T00:00:00.000Z/2017-12-01T00:00:00.000Z"]
      }
    },
    "tuningConfig": {
      "type": "hadoop",
      "partitionsSpec": {
        "type": "hashed",
        "targetPartitionSize": 5000000
      },
      "leaveIntermediate": false,
      "forceExtendableShardSpecs": "true"
    }
  }
}
```

ends with this exception:
```
2018-02-23T16:42:40,019 WARN [Thread-30] org.apache.hadoop.mapred.LocalJobRunner - job_local1968931578_0001
java.lang.Exception: io.druid.java.util.common.RE: Failure on row[{2017-11-01, SKU, 0.0}]
	at org.apache.hadoop.mapred.LocalJobRunner$Job.runTasks(LocalJobRunner.java:462) ~[hadoop-mapreduce-client-common-2.7.3.jar:?]
	at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:522) [hadoop-mapreduce-client-common-2.7.3.jar:?]
Caused by: io.druid.java.util.common.RE: Failure on row[{2017-11-01, SKU, 0.0}]
	at io.druid.indexer.HadoopDruidIndexerMapper.map(HadoopDruidIndexerMapper.java:91) ~[druid-indexing-hadoop-0.11.0.jar:0.11.0]
	at io.druid.indexer.DetermineHashedPartitionsJob$DetermineCardinalityMapper.run(DetermineHashedPartitionsJob.java:288) ~[druid-indexing-hadoop-0.11.0.jar:0.11.0]
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:787) ~[hadoop-mapreduce-client-core-2.7.3.jar:?]
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341) ~[hadoop-mapreduce-client-core-2.7.3.jar:?]
	at org.apache.hadoop.mapred.LocalJobRunner$Job$MapTaskRunnable.run(LocalJobRunner.java:243) ~[hadoop-mapreduce-client-common-2.7.3.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_151]
Caused by: java.lang.ClassCastException: org.apache.hadoop.io.FloatWritable cannot be cast to org.apache.hadoop.io.Text
	at org.apache.hadoop.hive.serde2.objectinspector.primitive.WritableStringObjectInspector.getPrimitiveJavaObject(WritableStringObjectInspector.java:46) ~[hive-exec-2.0.0.jar:2.0.0]
	at org.apache.hadoop.hive.serde2.objectinspector.primitive.WritableStringObjectInspector.getPrimitiveJavaObject(WritableStringObjectInspector.java:26) ~[hive-exec-2.0.0.jar:2.0.0]
	at io.druid.data.input.orc.OrcHadoopInputRowParser.parse(OrcHadoopInputRowParser.java:90) ~[druid-orc-extensions-0.11.0.jar:0.11.0]
	at io.druid.data.input.orc.OrcHadoopInputRowParser.parse(OrcHadoopInputRowParser.java:55) ~[druid-orc-extensions-0.11.0.jar:0.11.0]
	at io.druid.indexer.HadoopDruidIndexerMapper.parseInputRow(HadoopDruidIndexerMapper.java:105) ~[druid-indexing-hadoop-0.11.0.jar:0.11.0]
	at io.druid.indexer.HadoopDruidIndexerMapper.map(HadoopDruidIndexerMapper.java:72) ~[druid-indexing-hadoop-0.11.0.jar:0.11.0]
	at io.druid.indexer.DetermineHashedPartitionsJob$DetermineCardinalityMapper.run(DetermineHashedPartitionsJob.java:288) ~[druid-indexing-hadoop-0.11.0.jar:0.11.0]
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:787) ~[hadoop-mapreduce-client-core-2.7.3.jar:?]
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341) ~[hadoop-mapreduce-client-core-2.7.3.jar:?]
	at org.apache.hadoop.mapred.LocalJobRunner$Job$MapTaskRunnable.run(LocalJobRunner.java:243) ~[hadoop-mapreduce-client-common-2.7.3.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_151]
```
If there is no "metric as a numeric dimension" import ends successfully. Seems like column metric1 is imported always as string.
Is this a problem with orc extension or in druid directly? Is there any workaround for this?
Regards

**Comment by Hailei** [comment]
You should define type information,add a field as following
"typeString": "struct<druid__time:timestamp,city_id:string,province_id:string,pv:bigint,duration:bigint>”

**Comment by 13Homer** [comment]
It is defined as a float:
"typeString":"struct<ts:date,dimension1:string,metric1:float>"
dimension is defined as a float too:
{ "name": "metric1", "type": "float" }
What am I missing?
