### ISSUE TITLE
Queries with UNION do not work in Druid SQL

### ISSUE THREAD

**Issue by TwojaWina** [apache/incubator-druid#5473]
<img width="661" alt="screen shot 2018-03-07 at 1 37 23 pm" src="https://user-images.githubusercontent.com/9752231/37120944-ae919b8a-2210-11e8-92fc-106d00ec4bd8.png">

And in the Broker log we got following error : 

2018-03-07T21:37:20,888 WARN [qtp570017514-169] io.druid.sql.http.SqlResource - Failed to handle query: SqlQuery{query='select * from (
SELECT COUNT(*) FROM (
select id as trump4id from trump4
union
select id as trump5id from trump5
)
) limit 5000', context={timeout=40000}}
org.apache.calcite.tools.ValidationException: java.lang.NullPointerException
        at org.apache.calcite.prepare.PlannerImpl.validate(PlannerImpl.java:195) ~[calcite-core-1.14.0-iap1.jar:1.14.0-iap1]
        at io.druid.sql.calcite.planner.DruidPlanner.plan(DruidPlanner.java:108) ~[druid-sql-0.11.0-iap5.jar:0.11.0-iap5]
        at io.druid.sql.http.SqlResource.doPost(SqlResource.java:88) [druid-sql-0.11.0-iap5.jar:0.11.0-iap5]
...
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.lang.NullPointerException
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:213) ~[guava-16.0.1.jar:?]
        at org.apache.calcite.sql.SqlBasicCall.setOperator(SqlBasicCall.java:68) ~[calcite-core-1.14.0-iap1.jar:1.14.0-iap1]
        at org.apache.calcite.sql.SqlOperator.deriveType(SqlOperator.java:508) ~[calcite-core-1.14.0-iap1.jar:1.14.0-iap1]
...
        at org.apache.calcite.prepare.PlannerImpl.validate(PlannerImpl.java:193) ~[calcite-core-1.14.0-iap1.jar:1.14.0-iap1]
        ... 58 more

**Comment by jigar1101** [comment]
Hey @TwojaWina Did you find a solution to this issue?

**Comment by syedkhassan** [comment]
Any update on union query using SQL ?

**Comment by gianm** [comment]
#6314 would add UNION ALL, although not plain UNION.
