### ISSUE TITLE
Hive Druid Handler not loading data from Hive to Druid

### ISSUE THREAD

**Issue by abhijoshi4695** [apache/incubator-druid#5476]
Hive version - 2.3.2
Hadoop version - 2.7.5
Hive Druid Handler version - 2.3.2
Druid version - 0.11.0

This is a standalone setup on a single machine. We are able to pull Druid datasources into Hive. But, we are not able to push data from Hive to Druid. The issue seen is:
`Caused by: org.apache.hadoop.hive.ql.metadata.HiveException: org.apache.hadoop.hive.ql.metadata.HiveException: java.lang.NullPointerException: cache
	at org.apache.hadoop.hive.ql.exec.FileSinkOperator.createBucketFiles(FileSinkOperator.java:564)
	at org.apache.hadoop.hive.ql.exec.FileSinkOperator.process(FileSinkOperator.java:664)
	at org.apache.hadoop.hive.ql.exec.vector.VectorFileSinkOperator.process(VectorFileSinkOperator.java:101)
	at org.apache.hadoop.hive.ql.exec.Operator.baseForward(Operator.java:955)
	at org.apache.hadoop.hive.ql.exec.Operator.forward(Operator.java:903)
	at org.apache.hadoop.hive.ql.exec.vector.VectorSelectOperator.process(VectorSelectOperator.java:145)
	at org.apache.hadoop.hive.ql.exec.tez.ReduceRecordSource.processVectorGroup(ReduceRecordSource.java:464)
	... 19 more
Caused by: org.apache.hadoop.hive.ql.metadata.HiveException: java.lang.NullPointerException: cache
	at org.apache.hadoop.hive.ql.io.HiveFileFormatUtils.getHiveRecordWriter(HiveFileFormatUtils.java:272)
	at org.apache.hadoop.hive.ql.exec.FileSinkOperator.createBucketForFileIdx(FileSinkOperator.java:609)
	at org.apache.hadoop.hive.ql.exec.FileSinkOperator.createBucketFiles(FileSinkOperator.java:553)
	... 25 more
Caused by: java.lang.NullPointerException: cache
	at org.apache.hive.druid.com.google.common.base.Preconditions.checkNotNull(Preconditions.java:229)
	at org.apache.hive.druid.io.druid.segment.realtime.appenderator.AppenderatorImpl.<init>(AppenderatorImpl.java:146)
	at org.apache.hive.druid.io.druid.segment.realtime.appenderator.Appenderators.createOffline(Appenderators.java:84)
	at org.apache.hadoop.hive.druid.io.DruidRecordWriter.<init>(DruidRecordWriter.java:106)
	at org.apache.hadoop.hive.druid.io.DruidOutputFormat.getHiveRecordWriter(DruidOutputFormat.java:222)
	at org.apache.hadoop.hive.ql.io.HiveFileFormatUtils.getRecordWriter(HiveFileFormatUtils.java:284)
	at org.apache.hadoop.hive.ql.io.HiveFileFormatUtils.getHiveRecordWriter(HiveFileFormatUtils.java:269)
	... 27 more`

Query used is:
`CREATE TABLE druid_table_1
STORED BY 'org.apache.hadoop.hive.druid.DruidStorageHandler'
TBLPROPERTIES ("druid.datasource" = "wikiticker")
AS
<select timecolumn as ___time, dimension1, dimension2, metric1, metric2....>;`

Select statement gives proper results and there is a timestamp column present. Please help in resolving the issue.

**Comment by pawangoyalaca** [comment]
I am also facing the same issue.Did you able to find any solution.

**Comment by jihoonson** [comment]
This looks to be a Hive error which should be reported to the Hive community. However, maybe someone knows about this. @b-slim do you have any idea?

**Comment by PrashantN86** [comment]
Facing the same issue.
Unable to create druid datasource from hive using druid storage handler.
@b-slim  Can you point to the Hive and Druid versions where this issue is fixed for druid storage handler?
