### ISSUE TITLE
Compaction Task failing

### ISSUE THREAD

**Issue by indrekj** [apache/incubator-druid#5512]
Druid Version: 0.12.0

Compaction task worked fine for 2017-02 to 2018-03. We're changing hourly/daily segments to monthly segments. Segments 2016 to 2017-02 is failing with:
```
2018-03-21 11:30:36,552 ERROR [task-runner-0-priority-0] i.d.i.o.ThreadPoolTaskRunner Exception while running task[CompactionTask{id=index_compaction_engagement_events-cobrowsing_events-v2_24176, type=compact, dataSource=engagement_events-cobrowsing_events-v2}]
java.lang.NullPointerException
        at io.druid.indexing.common.task.CompactionTask.lambda$createDataSchema$0(CompactionTask.java:289) ~[druid-indexing-service-0.12.0.jar:0.12.0]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_161]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_161]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_161]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_161]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_161]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_161]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_161]
        at io.druid.indexing.common.task.CompactionTask.createDataSchema(CompactionTask.java:290) ~[druid-indexing-service-0.12.0.jar:0.12.0]
        at io.druid.indexing.common.task.CompactionTask.createIngestionSchema(CompactionTask.java:232) ~[druid-indexing-service-0.12.0.jar:0.12.0]
        at io.druid.indexing.common.task.CompactionTask.run(CompactionTask.java:184) ~[druid-indexing-service-0.12.0.jar:0.12.0]
        at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:444) [druid-indexing-service-0.12.0.jar:0.12.0]
        at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:416) [druid-indexing-service-0.12.0.jar:0.12.0]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
2018-03-21 11:30:36,558 INFO [task-runner-0-priority-0] i.d.i.o.TaskRunnerUtils Task [index_compaction_engagement_events-cobrowsing_events-v2_24176] status changed to [FAILED].
2018-03-21 11:30:36,563 INFO [task-runner-0-priority-0] i.d.i.w.e.ExecutorLifecycle Task completed with status: {
  "id" : "index_compaction_engagement_events-cobrowsing_events-v2_24176",
  "status" : "FAILED",
  "duration" : 44417
}
```

**Comment by jihoonson** [comment]
Hi @indrekj, thank you for the reporting. That error might happen if there is no corresponding metadata files (`metadata.smoosh` or `metadata.drd`) for segments. Which version of segment format are you using?

**Comment by indrekj** [comment]
An example of a segment:
```
  {
    "dataSource": "engagement_events-cobrowsing_events-v2",
    "interval": "2016-02-22T18:00:00.000Z/2016-02-22T19:00:00.000Z",
    "version": "2016-05-04T08:28:26.063Z",
    "loadSpec": {
      "type": "s3_zip",
      "bucket": "REPLACED",
      "key": "REPLACED/engagement_events-cobrowsing_events-v2/2016-02-22T18:00:00.000Z_2016-02-22T19:00:00.000Z/2016-05-04T08:28:26.063Z/0/index.zip"
    },
    "dimensions": "operator_id,site_id,sub_engagement_id,type",
    "metrics": "count",
    "shardSpec": {
      "type": "none"
    },
    "binaryVersion": 9,
    "size": 4296,
    "identifier": "engagement_events-cobrowsing_events-v2_2016-02-22T18:00:00.000Z_2016-02-22T19:00:00.000Z_2016-05-04T08:28:26.063Z"
  }
```

Given index.zip has `00000.smoosh`, `meta.smoosh` and `version.bin` inside it.

`meta.smoosh` content:
```
v1,2147483647,1
__time,0,3508,3918
count,0,3101,3508
index.drd,0,3918,4131
operator_id,0,0,824
site_id,0,824,1592
sub_engagement_id,0,1592,2584
type,0,2584,3101
```

`xxd -p version.bin` content: `00000009`

**Comment by jihoonson** [comment]
@indrekj thanks for posting them. ```CompactionTask``` internally generates an indexTask spec using the metadata of existing segments. The metadata is stored in `xxxxx.smoosh` file and `metadata.drd` is seen in `meta.smoosh` file which represents the position of metadata in `xxxxx.smoosh` file. This is valid for only directly created V9 segments. If you converted segment versions using a sort of convertSegmentTask, `metadata.drd` might not exist. 

I raised https://github.com/druid-io/druid/issues/5520. In the meantime, you can use indexTask to explicitly specify metricsSpec.
