### ISSUE TITLE
Segments not covered by locks for task

### ISSUE THREAD

**Issue by yorkart** [apache/incubator-druid#5673]
druid version: 0.12(update from 0.11)

delete deep storage
```
curl -XPOST -H 'X-Druid-Author: wy' -H 'X-Druid-Comment: delete deep storage data' -H 'Content-Type: application/json' http://localhost:8090/druid/indexer/v1/task -d '
{
    "type": "kill",
    "id": "index_[my-task]_kill_2018-01-01_4",
    "dataSource": "my-ds",
    "interval" : "2018-01-02T00:00:00.000+08:00/2018-01-03T00:00:00.000+08:00"
}'
```

 error:
```
2018-04-23 17:03:30 WARN [qtp436028378-142] org.eclipse.jetty.servlet.ServletHandler - /druid/indexer/v1/action
io.druid.java.util.common.ISE: Segments not covered by locks for task: index_[my-task]_kill_2018-01-01_4
        at io.druid.indexing.common.actions.TaskActionPreconditions.checkLockCoversSegments(TaskActionPreconditions.java:45) ~[druid-indexing-service-0.12.0.jar:0.12.0]
        at io.druid.indexing.common.actions.SegmentNukeAction.perform(SegmentNukeAction.java:70) ~[druid-indexing-service-0.12.0.jar:0.12.0]
        at io.druid.indexing.common.actions.SegmentNukeAction.perform(SegmentNukeAction.java:40) ~[druid-indexing-service-0.12.0.jar:0.12.0]
        at io.druid.indexing.common.actions.LocalTaskActionClient.submit(LocalTaskActionClient.java:64) ~[druid-indexing-service-0.12.0.jar:0.12.0]
        at io.druid.indexing.overlord.http.OverlordResource$3.apply(OverlordResource.java:345) ~[druid-indexing-service-0.12.0.jar:0.12.0]
        at io.druid.indexing.overlord.http.OverlordResource$3.apply(OverlordResource.java:334) ~[druid-indexing-service-0.12.0.jar:0.12.0]
        at io.druid.indexing.overlord.http.OverlordResource.asLeaderWith(OverlordResource.java:672) ~[druid-indexing-service-0.12.0.jar:0.12.0]
        at io.druid.indexing.overlord.http.OverlordResource.doAction(OverlordResource.java:331) ~[druid-indexing-service-0.12.0.jar:0.12.0]

...
```

**Comment by jihoonson** [comment]
@yorkart can you let us know which unused segments exist for the interval `"2018-01-02T00:00:00.000+08:00/2018-01-03T00:00:00.000+08:00"`? You might need to run the below SQL against metastore.

```
SELECT payload FROM druid_segments WHERE dataSource = 'my-ds' AND start >= '2018-01-02T00:00:00.000+08:00' AND "end" <= '2018-01-03T00:00:00.000+08:00 ' AND used = false
```
