### ISSUE TITLE
Druid-0.12.0, Indexing Service load data to Deep Storage failed.

### ISSUE THREAD

**Issue by chimmy869** [apache/incubator-druid#5705]
Tasks always run ok, but exception throw when load data to  Deep Storage failed. 

2018-04-25T14:15:00,300 INFO [test_portal-2018-04-25T05:00:00.000Z-persist-n-merge] io.druid.java.util.common.io.smoosh.FileSmoosher - Created smoosh file [/data/druid/druid-0.12.0/var/druid/task/index_realtime_test_portal_2018-04-25T05:00:00.000Z_0_0/work/persist/test_portal/2018-04-25T05:00:00.000Z_2018-04-25T06:00:00.000Z/merged/00000.smoosh] of size [202216] bytes.
2018-04-25T14:15:00,302 INFO [test_portal-2018-04-25T05:00:00.000Z-persist-n-merge] io.druid.segment.realtime.plumber.RealtimePlumber - Pushing [test_portal_2018-04-25T05:00:00.000Z_2018-04-25T06:00:00.000Z_2018-04-25T05:00:00.313Z] to deep storage
2018-04-25T14:15:00,306 INFO [test_portal-2018-04-25T05:00:00.000Z-persist-n-merge] io.druid.storage.hdfs.HdfsDataSegmentPusher - Copying segment[test_portal_2018-04-25T05:00:00.000Z_2018-04-25T06:00:00.000Z_2018-04-25T05:00:00.313Z] to HDFS at location[hdfs://10.208.47.156:9000/druid-v12/segments/test_portal/20180425T050000.000Z_20180425T060000.000Z/2018-04-25T05_00_00.313Z]
2018-04-25T14:15:00,400 INFO [test_portal-2018-04-25T05:00:00.000Z-persist-n-merge] **io.druid.storage.hdfs.HdfsDataSegmentPusher - Compressing files from[var/druid/task/index_realtime_test_portal_2018-04-25T05:00:00.000Z_0_0/work/persist/test_portal/2018-04-25T05:00:00.000Z_2018-04-25T06:00:00.000Z/merged] to [hdfs://10.208.47.156:9000/druid-v12/segments/test_portal/a84329111cf6424ea9e7da2570ada8c8/0_index.zip]**
2018-04-25T14:15:00,475 INFO [test_portal-2018-04-25T05:00:00.000Z-persist-n-merge] io.druid.java.util.common.CompressionUtils - Adding file[var/druid/task/index_realtime_test_portal_2018-04-25T05:00:00.000Z_0_0/work/persist/test_portal/2018-04-25T05:00:00.000Z_2018-04-25T06:00:00.000Z/merged/00000.smoosh] with size[202,216].  Total size so far[0]
2018-04-25T14:15:00,507 INFO [test_portal-2018-04-25T05:00:00.000Z-persist-n-merge] io.druid.java.util.common.CompressionUtils - Adding file[var/druid/task/index_realtime_test_portal_2018-04-25T05:00:00.000Z_0_0/work/persist/test_portal/2018-04-25T05:00:00.000Z_2018-04-25T06:00:00.000Z/merged/meta.smoosh] with size[172].  Total size so far[202,216]
2018-04-25T14:15:00,508 INFO [test_portal-2018-04-25T05:00:00.000Z-persist-n-merge] io.druid.java.util.common.CompressionUtils - Adding file[var/druid/task/index_realtime_test_portal_2018-04-25T05:00:00.000Z_0_0/work/persist/test_portal/2018-04-25T05:00:00.000Z_2018-04-25T06:00:00.000Z/merged/factory.json] with size[29].  Total size so far[202,388]
2018-04-25T14:15:00,508 INFO [test_portal-2018-04-25T05:00:00.000Z-persist-n-merge] io.druid.java.util.common.CompressionUtils - Adding file[var/druid/task/index_realtime_test_portal_2018-04-25T05:00:00.000Z_0_0/work/persist/test_portal/2018-04-25T05:00:00.000Z_2018-04-25T06:00:00.000Z/merged/version.bin] with size[4].  **Total size so far[202,417]**
2018-04-25T14:15:00,511 INFO [test_portal-2018-04-25T05:00:00.000Z-persist-n-merge] io.druid.storage.hdfs.HdfsDataSegmentPusher - Creating descriptor file at[hdfs://10.208.47.156:9000/druid-v12/segments/test_portal/a84329111cf6424ea9e7da2570ada8c8/0_descriptor.json]
2018-04-25T14:15:00,703 ERROR [test_portal-2018-04-25T05:00:00.000Z-persist-n-merge] io.druid.segment.realtime.plumber.RealtimePlumber - Failed to persist merged index[test_portal]: {class=io.druid.segment.realtime.plumber.RealtimePlumber, exceptionType=class org.apache.hadoop.ipc.RemoteException, exceptionMessage=No lease on **/druid-v12/segments/test_portal/a84329111cf6424ea9e7da2570ada8c8/0_index.zip: File does not exist.** [Lease.  Holder: DFSClient_NONMAPREDUCE_717490607_135, pendingcreates: 1]
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkLease(FSNamesystem.java:2848)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.completeFileInternal(FSNamesystem.java:2912)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.completeFile(FSNamesystem.java:2892)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.complete(NameNodeRpcServer.java:620)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.complete(ClientNamenodeProtocolServerSideTranslatorPB.java:451)
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:585)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:928)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:1962)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:1958)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1548)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:1956)
, interval=2018-04-25T05:00:00.000Z/2018-04-25T06:00:00.000Z}
org.apache.hadoop.ipc.RemoteException: **No lease on /druid-v12/segments/test_portal/a84329111cf6424ea9e7da2570ada8c8/0_index.zip: File does not exist**. [Lease.  Holder: DFSClient_NONMAPREDUCE_717490607_135, pendingcreates: 1]
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkLease(FSNamesystem.java:2848)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.completeFileInternal(FSNamesystem.java:2912)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.completeFile(FSNamesystem.java:2892)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.complete(NameNodeRpcServer.java:620)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.complete(ClientNamenodeProtocolServerSideTranslatorPB.java:451)
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:585)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:928)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:1962)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:1958)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1548)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:1956)
	at org.apache.hadoop.ipc.Client.call(Client.java:1475) ~[?:?]
	at org.apache.hadoop.ipc.Client.call(Client.java:1412) ~[?:?]
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:229) ~[?:?]
	at com.sun.proxy.$Proxy91.complete(Unknown Source) ~[?:?]
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.complete(ClientNamenodeProtocolTranslatorPB.java:462) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_73]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_73]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_73]
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:191) ~[?:?]
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102) ~[?:?]
	at com.sun.proxy.$Proxy92.complete(Unknown Source) ~[?:?]
	at org.apache.hadoop.hdfs.DFSOutputStream.completeFile(DFSOutputStream.java:2291) ~[?:?]
	at org.apache.hadoop.hdfs.DFSOutputStream.closeImpl(DFSOutputStream.java:2267) ~[?:?]
	at org.apache.hadoop.hdfs.DFSOutputStream.close(DFSOutputStream.java:2232) ~[?:?]
	at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.close(FSDataOutputStream.java:72) ~[?:?]
	at org.apache.hadoop.fs.FSDataOutputStream.close(FSDataOutputStream.java:106) ~[?:?]
	at io.druid.storage.hdfs.HdfsDataSegmentPusher.push(HdfsDataSegmentPusher.java:150) ~[?:?]
	at io.druid.segment.realtime.plumber.RealtimePlumber$2.doRun(RealtimePlumber.java:454) [druid-server-0.12.0.jar:0.12.0]
	at io.druid.common.guava.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:42) [druid-common-0.12.0.jar:0.12.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_73]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_73]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_73]

It has some problem when task merge data, has anyone ever had the same problem?
Thanks

**Comment by licl2014** [comment]
@gianm @nishantmonu51 please have  a look.

**Comment by YingHun** [comment]
@licl2014 Hi, I also meet this issue, have you resolved this problem?

**Comment by YingHun** [comment]
@chimmy869  @licl2014  Hi, I also meet this issue, have you resolved this problem?
