### ISSUE TITLE
kafka indexing sevice cause kafka broker memory leak and OOM 

### ISSUE THREAD

**Issue by terry19850829** [apache/incubator-druid#5754]
apache kafka_2.12-1.0.0 with kafka streams 
druid 0.11.0
java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)

Reproducing process:

I use a kafka client produce messages to kafka broker and kstreams just redirect the topic messages
to another topic which consumed by druid indexing service.

kafka client => broker(1.0) => kstreams(1.0) => broker(1.0) => kafka indexing service

If the supervisor's task has some exception and shutdown and then a new task start, The kafka broker will memory leak.(byteBuffer instances will increasing until OOM)

To reproducing the exception , just set the topic's timestamp field to null and cause NPE:

```
2018-05-08T04:03:53,215 ERROR [task-runner-0-priority-0] io.druid.indexing.overlord.ThreadPoolTaskRunner - Exception while running task[KafkaIndexTask{id=index_kafka_transaction_stat_ds_521b7bdac80002a_afjnadcf, type=index_kafka, dataSource=transaction_stat_ds}]
java.lang.NullPointerException: timestamp
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:229) ~[guava-16.0.1.jar:?]
	at io.druid.indexing.common.actions.SegmentAllocateAction.<init>(SegmentAllocateAction.java:78) ~[druid-indexing-service-0.11.0.jar:0.11.0]
	at io.druid.indexing.appenderator.ActionBasedSegmentAllocator.allocate(ActionBasedSegmentAllocator.java:57) ~[druid-indexing-service-0.11.0.jar:0.11.0]
	at io.druid.segment.realtime.appenderator.AppenderatorDriver.getSegment(AppenderatorDriver.java:402) ~[druid-server-0.11.0.jar:0.11.0]
	at io.druid.segment.realtime.appenderator.AppenderatorDriver.add(AppenderatorDriver.java:229) ~[druid-server-0.11.0.jar:0.11.0]
	at io.druid.indexing.kafka.KafkaIndexTask.run(KafkaIndexTask.java:480) ~[?:?]
	at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:436) [druid-indexing-service-0.11.0.jar:0.11.0]
	at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:408) [druid-indexing-service-0.11.0.jar:0.11.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_162]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
2018-05-08T04:03:53,223 INFO [task-runner-0-priority-0] io.druid.indexing.overlord.TaskRunnerUtils - Task [index_kafka_transaction_stat_ds_521b7bdac80002a_afjnadcf] status changed to [FAILED].
```

kafka broker memory check:

```
superuser@t1-open-001:~$ jmap -histo:live brokerPID | head -20

 num     #instances         #bytes  class name
----------------------------------------------
   1:          2345     1713510328  [B
   2:         26909        2743592  [C
   3:         68268        1638432  java.util.concurrent.ConcurrentSkipListMap$Node
   4:         67807        1627368  java.lang.Double
   5:         34074         817776  java.util.concurrent.ConcurrentSkipListMap$Index
   6:         26840         644160  java.lang.String
   7:          5629         617176  java.lang.Class
   8:          7120         389344  [Ljava.lang.Object;



```

**Comment by terry19850829** [comment]
It's a kafka OOM issue
