### ISSUE TITLE
snapshot quickstart error

### ISSUE THREAD

**Issue by AlexanderSaydakov** [apache/incubator-druid#6037]
I am trying to follow the quick start guide using the snapshot from the master.
http://druid.io/docs/latest/tutorials/quickstart.html
All services appear to start, wiki data indexing succeeds, but never becomes fully available (red dot in the console view).
By looking at the logs, the following error in the log/server-coordinator.log seems to be relevant:
`
2018-07-24T00:47:29,773 ERROR [LeaderSelector[/druid/coordinator/_COORDINATOR]] org.apache.curator.framework.listen.ListenerContainer - Listener (io.druid.curator.discovery.CuratorDruidLeaderSelector$1@7e15f4d4) threw an exception
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    io/druid/server/coordinator/DruidCoordinator$CoordinatorHistoricalManagerRunnable.<init>(Lio/druid/server/coordinator/DruidCoordinator;I)V @16: invokedynamic
  Reason:
    Type uninitializedThis (current frame, stack[3]) is not assignable to 'io/druid/server/coordinator/DruidCoordinator$CoordinatorHistoricalManagerRunnable'
  Current Frame:
    bci: @16
    flags: { flagThisUninit }
    locals: { uninitializedThis, 'io/druid/server/coordinator/DruidCoordinator', integer }
    stack: { uninitializedThis, 'io/druid/server/coordinator/DruidCoordinator', 'io/druid/server/coordinator/helper/DruidCoordinatorSegmentInfoLoader', uninitializedThis }
  Bytecode:
    0x0000000: 2a2b b500 012a 2bbb 0002 592b b700 032a
    0x0000010: ba00 0400 00bb 0005 592b b700 06bb 0007
    0x0000020: 592b b700 08bb 0009 592b b700 0abb 000b
    0x0000030: 592b b700 0cbb 000d 592b b700 0eb8 000f
    0x0000040: 1cb7 0010 b1                           

        at io.druid.server.coordinator.DruidCoordinator.becomeLeader(DruidCoordinator.java:540) ~[druid-server-0.13.0-SNAPSHOT.jar:0.13.0-SNAPSHOT]
        at io.druid.server.coordinator.DruidCoordinator.access$000(DruidCoordinator.java:96) ~[druid-server-0.13.0-SNAPSHOT.jar:0.13.0-SNAPSHOT]
        at io.druid.server.coordinator.DruidCoordinator$1.becomeLeader(DruidCoordinator.java:495) ~[druid-server-0.13.0-SNAPSHOT.jar:0.13.0-SNAPSHOT]
        at io.druid.curator.discovery.CuratorDruidLeaderSelector$1.isLeader(CuratorDruidLeaderSelector.java:98) ~[druid-server-0.13.0-SNAPSHOT.jar:0.13.0-SNAPSHOT]
        at org.apache.curator.framework.recipes.leader.LeaderLatch$9.apply(LeaderLatch.java:665) ~[curator-recipes-4.0.0.jar:4.0.0]
        at org.apache.curator.framework.recipes.leader.LeaderLatch$9.apply(LeaderLatch.java:661) ~[curator-recipes-4.0.0.jar:4.0.0]
        at org.apache.curator.framework.listen.ListenerContainer$1.run(ListenerContainer.java:93) [curator-framework-4.0.0.jar:4.0.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_60]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_60]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
`

**Comment by gianm** [comment]
I have seen this happen with older versions of javac; perhaps try upgrading that (looks like your jdk is 1.8.0_60).

**Comment by AlexanderSaydakov** [comment]
0.12.1 release works, but doesn't have the module I wanted to play with.
1.8.0_60 jdk seems to be the latest available in our corporate environment at the moment.

**Comment by gianm** [comment]
The release should work, since the issue (I believe) is with the javac compiler, not with the runtime. Maybe you could try building the package with a newer jdk and then running it on the _60 environment?

**Comment by AlexanderSaydakov** [comment]
I built the package on my Mac laptop with java 1.8.0_40.
I tried building on the target Linux machine with 1.8.0_60, but got exactly the same result

**Comment by jihoonson** [comment]
The latest version of Java 8 is `1.8.0_181`. Try that one.

**Comment by clintropolis** [comment]
This looks similar to this issue https://github.com/apache/incubator-druid/pull/5591#issuecomment-379393497

**Comment by AlexanderSaydakov** [comment]
I found a machine with java 1.8.0_161, built druid on it, and there is no problem.
I think we can close this issue.
Thank you.
