### ISSUE TITLE
Coordinator `asOverlord` broken on master.

### ISSUE THREAD

**Issue by KenjiTakahashi** [apache/incubator-druid#6133]
Fails at startup with:
```
Exception in thread "main" com.google.inject.CreationException: Unable to create injector, see the following errors:

1) A binding to io.druid.client.indexing.IndexingServiceClient was already configured at io.druid.cli.CliCoordinator$1.configure(CliCoordinator.java:171) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> io.druid.cli.CliCoordinator$1).
  at io.druid.cli.CliOverlord$1.configure(CliOverlord.java:191) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> io.druid.cli.CliOverlord$1)

1 error
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
        at com.google.inject.Guice.createInjector(Guice.java:99)
        at com.google.inject.Guice.createInjector(Guice.java:73)
        at com.google.inject.Guice.createInjector(Guice.java:62)
        at io.druid.initialization.Initialization.makeInjectorWithModules(Initialization.java:421)
        at io.druid.cli.GuiceRunnable.makeInjector(GuiceRunnable.java:68)
        at io.druid.cli.ServerRunnable.run(ServerRunnable.java:49)
        at io.druid.cli.Main.main(Main.java:116)
```

Last known working at e4ef753a6041d90289c33d34eba819659315ce23.

**Comment by KenjiTakahashi** [comment]
I've bisected and this is caused by line https://github.com/apache/incubator-druid/blob/1c8032f9f3715c93e64673cbe6c2ccf5fca8e843/services/src/main/java/io/druid/cli/CliOverlord.java#L191, added in 56ab4363ea30ead876c11b43e1480ff6c0dfd941. Removing the line fixes the problem at hand, but I'm not sure it wouldn't break something else.

/cc @jihoonson

**Comment by gianm** [comment]
It's used whenever the leader coordinator needs to talk to the leader indexer. Probably better to replace that line with:

```
binder.bind(IndexingServiceClient.class).to(HttpIndexingServiceClient.class).in(LazySingleton.class);
```
