### ISSUE TITLE
java.lang.NullPointerException: taskGroupId   when middlemanager rolling update to 0.12.2

### ISSUE THREAD

**Issue by wpcnjupt** [apache/incubator-druid#6163]
hi
I am rolling update to 0.12.2. 
I have updated the Historical nodes and one middlemanager node. 
when the updated middlemanage run KIS workers, it failed sometimes, the peon log is:

`[19:33:41:332] [INFO] - io.druid.java.util.common.logger.Logger.info(Logger.java:78) - Unannouncing self[DruidServerMetadata{name='172.16.226.7:8104', hostAndPort='172.16.226.7:8104', hostAndTlsPort='null', maxSize=0, tier='_default_tier', type=indexer-executor, priority=0}] at [/druid/announcements/172.16.226.7:8104]
[19:33:41:332] [INFO] - io.druid.java.util.common.logger.Logger.info(Logger.java:78) - unannouncing [/druid/announcements/172.16.226.7:8104]
[19:33:41:338] [ERROR] - io.druid.java.util.common.logger.Logger.error(Logger.java:130) - Exception while running task[AbstractTask{id='index_kafka_crawler-worker-event_027f5c0ae282e3f_mdifgfpg', groupId='index_kafka_crawler-worker-event', taskResource=TaskResource{availabilityGroup='index_kafka_crawler-worker-event_027f5c0ae282e3f', requiredCapacity=1}, dataSource='crawler-worker-event', context={checkpoints={"1":{"0":21547776416,"1":11299531938,"2":11299574531,"3":11299914740},"2":{"0":21549477707,"1":11301233731,"2":11301277162,"3":11301615534}}, IS_INCREMENTAL_HANDOFF_SUPPORTED=true}}]
java.lang.NullPointerException: taskGroupId
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:229) ~[guava-16.0.1.jar:?]
	at io.druid.indexing.common.actions.CheckPointDataSourceMetadataAction.<init>(CheckPointDataSourceMetadataAction.java:45) ~[druid-indexing-service-0.12.2.jar:0.12.2]
	at io.druid.indexing.kafka.KafkaIndexTask.run(KafkaIndexTask.java:708) ~[?:?]
	at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:444) [druid-indexing-service-0.12.2.jar:0.12.2]
	at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:416) [druid-indexing-service-0.12.2.jar:0.12.2]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[19:33:41:339] [INFO] - io.druid.java.util.common.logger.Logger.info(Logger.java:78) - Task [index_kafka_crawler-worker-event_027f5c0ae282e3f_mdifgfpg] status changed to [FAILED].
[19:33:41:340] [INFO] - io.druid.java.util.common.logger.Logger.info(Logger.java:78) - Task completed with status: {
  "id" : "index_kafka_crawler-worker-event_027f5c0ae282e3f_mdifgfpg",
  "status" : "FAILED",
  "duration" : 1333794
}
[19:33:41:346] [INFO] - io.druid.java.util.common.logger.Logger.info(Logger.java:78) - Invoking stop method[public void io.druid.server.listener.announcer.ListenerResourceAnnouncer.stop()] on object[io.druid.query.lookup.LookupResourceListenerAnnouncer@266da047].`

**Comment by jihoonson** [comment]
Thanks @wpcnjupt. Please check #6168.

**Comment by pdeva** [comment]
this is a major issue. any workarounds till 0.12.3 release?

**Comment by gianm** [comment]
@pdeva I think no, however, the issue should clear up after your rolling update is done. If you see any issues persisting for more than a few hours then please raise a new issue describing what you are seeing. Sorry for the inconvenience!

**Comment by licl2014** [comment]
@wpcnjupt  are u from njupt？
