### ISSUE TITLE
AssertionError at testCheckpointForInactiveTaskGroup in KafkaSupervisorTest

### ISSUE THREAD

**Issue by jihoonson** [apache/incubator-druid#6174]
```
Tests run: 64, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 26.081 sec <<< FAILURE! - in io.druid.indexing.kafka.supervisor.KafkaSupervisorTest
testCheckpointForInactiveTaskGroup[numThreads = 8](io.druid.indexing.kafka.supervisor.KafkaSupervisorTest)  Time elapsed: 0.124 sec  <<< FAILURE!
java.lang.AssertionError: 
expected null, but was:<java.lang.AssertionError: 
  Unexpected method call TaskRunner.getRunningTasks():
	at org.easymock.internal.MockInvocationHandler.invoke(MockInvocationHandler.java:44)
	at org.easymock.internal.ObjectMethodsFilter.invoke(ObjectMethodsFilter.java:94)
	at com.sun.proxy.$Proxy43.getRunningTasks(Unknown Source)
	at io.druid.indexing.kafka.supervisor.KafkaSupervisor$1.getTaskLocation(KafkaSupervisor.java:296)
	at io.druid.indexing.kafka.supervisor.KafkaSupervisor.checkpointTaskGroup(KafkaSupervisor.java:1503)
	at io.druid.indexing.kafka.supervisor.KafkaSupervisor.checkTaskDuration(KafkaSupervisor.java:1433)
	at io.druid.indexing.kafka.supervisor.KafkaSupervisor.runInternal(KafkaSupervisor.java:879)
	at io.druid.indexing.kafka.supervisor.KafkaSupervisor$RunNotice.handle(KafkaSupervisor.java:595)
	at io.druid.indexing.kafka.supervisor.KafkaSupervisor$2.run(KafkaSupervisor.java:369)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
>
	at io.druid.indexing.kafka.supervisor.KafkaSupervisorTest.testCheckpointForInactiveTaskGroup(KafkaSupervisorTest.java:2118)
```

**Comment by asdf2014** [comment]
Hi, @jihoonson . I also encountered this issues in job#[417558893](https://travis-ci.org/apache/incubator-druid/jobs/417558893#L2440) too. Should we add the following code to avoid it, similar to the [operation](https://github.com/apache/incubator-druid/blob/master/extensions-core/kafka-indexing-service/src/test/java/io/druid/indexing/kafka/supervisor/KafkaSupervisorTest.java#L2188-L2190) in the `testCheckpointForUnknownTaskGroup` test case?

**Comment by jihoonson** [comment]
@asdf2014 yes, I think so.

**Comment by asdf2014** [comment]
Okay, thanks for your confirmation. I will open a `PR` to solve this problem.
