### ISSUE TITLE
Node startup fails while using HttpEmitter under ComposingEmitter

### ISSUE THREAD

**Issue by a2l007** [apache/incubator-druid#6499]
Testing in master with the following emitter configuration:
```
druid.emitter=composing
druid.emitter.composing.emitters=["http","logging"]
```
Druid node fails to startup with the following exception:
```
1) Error in custom provider, org.apache.druid.java.util.common.ISE: Cannot add a handler after the Lifecycle has started, it doesn't work that way.
  at org.apache.druid.server.emitter.HttpEmitterModule.getEmitter(HttpEmitterModule.java:104) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.server.emitter.EmitterModule -> org.apache.druid.server.emitter.HttpEmitterModule)
  at org.apache.druid.server.emitter.HttpEmitterModule.getEmitter(HttpEmitterModule.java:104) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.server.emitter.EmitterModule -> org.apache.druid.server.emitter.HttpEmitterModule)
  while locating org.apache.druid.java.util.emitter.core.Emitter annotated with @com.google.inject.name.Named(value=http)

1 error
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1028) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1050) ~[guice-4.1.0.jar:?]
	at org.apache.druid.server.emitter.ComposingEmitterModule$1.apply(ComposingEmitterModule.java:73) ~[classes/:?]
	at org.apache.druid.server.emitter.ComposingEmitterModule$1.apply(ComposingEmitterModule.java:69) ~[classes/:?]
	at com.google.common.collect.Lists$TransformingRandomAccessList$1.transform(Lists.java:582) ~[guava-16.0.1.jar:?]
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48) ~[guava-16.0.1.jar:?]
	at org.apache.druid.java.util.emitter.core.ComposingEmitter.start(ComposingEmitter.java:47) ~[classes/:?]
	... 10 more
Caused by: org.apache.druid.java.util.common.ISE: Cannot add a handler after the Lifecycle has started, it doesn't work that way.
	at org.apache.druid.java.util.common.lifecycle.Lifecycle.addHandler(Lifecycle.java:175) ~[classes/:?]
	at org.apache.druid.java.util.common.lifecycle.Lifecycle.addHandler(Lifecycle.java:157) ~[classes/:?]
	at org.apache.druid.java.util.common.lifecycle.Lifecycle.addCloseableInstance(Lifecycle.java:248) ~[classes/:?]
	at org.apache.druid.server.emitter.HttpEmitterModule.getEmitter(HttpEmitterModule.java:106) ~[classes/:?]
	at org.apache.druid.server.emitter.HttpEmitterModule$$FastClassByGuice$$670180c9.invoke(<generated>) ~[classes/:?]
	at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:264) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.ProviderMethod$Factory.provision(ProviderMethod.java:401) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.ProviderMethod$Factory.get(ProviderMethod.java:376) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[guice-4.1.0.jar:?]
	at org.apache.druid.guice.LifecycleScope$1.get(LifecycleScope.java:68) ~[classes/:?]
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1050) ~[guice-4.1.0.jar:?]
	at org.apache.druid.server.emitter.ComposingEmitterModule$1.apply(ComposingEmitterModule.java:73) ~[classes/:?]
	at org.apache.druid.server.emitter.ComposingEmitterModule$1.apply(ComposingEmitterModule.java:69) ~[classes/:?]
	at com.google.common.collect.Lists$TransformingRandomAccessList$1.transform(Lists.java:582) ~[guava-16.0.1.jar:?]
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48) ~[guava-16.0.1.jar:?]
	at org.apache.druid.java.util.emitter.core.ComposingEmitter.start(ComposingEmitter.java:47) ~[classes/:?]
	... 10 more
```
Haven't investigated this further yet, but wanted to check if anyone else is facing the same issue.

**Comment by a2l007** [comment]
The root cause is that since an explicit log4j2.xml was not provided, the StatusLogger was throwing an exception and this must have caused a problem in the Lifecycle execution. The issue was resolved once the log4j2.xml was explicitly specified using `-Dlog4j.configurationFile`
