### ISSUE TITLE
NPE at io.druid.cli.CliInternalHadoopIndexer

### ISSUE THREAD

**Issue by Tagar** [apache/incubator-druid#6673]
> 2018-11-28T05:47:02,778 ERROR [main] io.druid.cli.CliHadoopIndexer - failure!!!!
> java.lang.reflect.InvocationTargetException
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_162]
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_162]
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_162]
>         at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_162]
>         at io.druid.cli.CliHadoopIndexer.run(CliHadoopIndexer.java:117) [druid-services-0.12.3.jar:0.12.3]
>         at io.druid.cli.Main.main(Main.java:116) [druid-services-0.12.3.jar:0.12.3]
> Caused by: com.google.inject.CreationException: Unable to create injector, see the following errors:
> 
> 1) An exception was caught and reported. Message: null
>   at com.google.inject.util.Modules$OverrideModule.configure(Modules.java:198)
> 
> 2) Binding to null instances is not allowed. Use toProvider(Providers.of(null)) if this is your intended behaviour.
>   at io.druid.cli.CliInternalHadoopIndexer$1.configure(CliInternalHadoopIndexer.java:95) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> io.druid.cli.CliInternalHadoopIndexer$1)
> 
> 3) Binding to null instances is not allowed. Use toProvider(Providers.of(null)) if this is your intended behaviour.
>   at io.druid.cli.CliInternalHadoopIndexer$1.configure(CliInternalHadoopIndexer.java:95) (via modules: com.google.inject.util.Modules$OverrideModule -> io.druid.cli.CliInternalHadoopIndexer$1)
> 
> 4) Binding to null instances is not allowed. Use toProvider(Providers.of(null)) if this is your intended behaviour.
>   at io.druid.cli.CliInternalHadoopIndexer$1.configure(CliInternalHadoopIndexer.java:96)
> 
> 5) Could not find a suitable constructor in io.druid.metadata.MetadataStorageTablesConfig. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
>   at io.druid.metadata.MetadataStorageTablesConfig.class(MetadataStorageTablesConfig.java:35)
>   at io.druid.cli.CliInternalHadoopIndexer$1.configure(CliInternalHadoopIndexer.java:97) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> io.druid.cli.CliInternalHadoopIndexer$1)
> 
> 5 errors
>         at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470) ~[guice-4.1.0.jar:?]
>         at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155) ~[guice-4.1.0.jar:?]
>         at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107) ~[guice-4.1.0.jar:?]
>         at com.google.inject.Guice.createInjector(Guice.java:99) ~[guice-4.1.0.jar:?]
>         at com.google.inject.Guice.createInjector(Guice.java:73) ~[guice-4.1.0.jar:?]
>         at com.google.inject.Guice.createInjector(Guice.java:62) ~[guice-4.1.0.jar:?]
>         at io.druid.initialization.Initialization.makeInjectorWithModules(Initialization.java:403) ~[druid-server-0.12.3.jar:0.12.3]
>         at io.druid.cli.GuiceRunnable.makeInjector(GuiceRunnable.java:62) ~[druid-services-0.12.3.jar:0.12.3]
>         at io.druid.cli.CliInternalHadoopIndexer.run(CliInternalHadoopIndexer.java:110) ~[druid-services-0.12.3.jar:0.12.3]
>         at io.druid.cli.Main.main(Main.java:116) ~[druid-services-0.12.3.jar:0.12.3]
>         ... 6 more
> Caused by: java.lang.NullPointerException
>         at io.druid.cli.CliInternalHadoopIndexer$1.configure(CliInternalHadoopIndexer.java:97) ~[druid-services-0.12.3.jar:0.12.3]
>         at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340) ~[guice-4.1.0.jar:?]
>         at com.google.inject.spi.Elements.getElements(Elements.java:110) ~[guice-4.1.0.jar:?]
>         at com.google.inject.util.Modules$OverrideModule.configure(Modules.java:198) ~[guice-4.1.0.jar:?]
>         at com.google.inject.AbstractModule.configure(AbstractModule.java:62) ~[guice-4.1.0.jar:?]
>         at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340) ~[guice-4.1.0.jar:?]
>         at com.google.inject.spi.Elements.getElements(Elements.java:110) ~[guice-4.1.0.jar:?]
>         at com.google.inject.util.Modules$OverrideModule.configure(Modules.java:177) ~[guice-4.1.0.jar:?]
>         at com.google.inject.AbstractModule.configure(AbstractModule.java:62) ~[guice-4.1.0.jar:?]
>         at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340) ~[guice-4.1.0.jar:?]
>         at com.google.inject.spi.Elements.getElements(Elements.java:110) ~[guice-4.1.0.jar:?]
>         at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138) ~[guice-4.1.0.jar:?]
>         at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104) ~[guice-4.1.0.jar:?]
>         at com.google.inject.Guice.createInjector(Guice.java:99) ~[guice-4.1.0.jar:?]
>         at com.google.inject.Guice.createInjector(Guice.java:73) ~[guice-4.1.0.jar:?]
>         at com.google.inject.Guice.createInjector(Guice.java:62) ~[guice-4.1.0.jar:?]
>         at io.druid.initialization.Initialization.makeInjectorWithModules(Initialization.java:403) ~[druid-server-0.12.3.jar:0.12.3]
>         at io.druid.cli.GuiceRunnable.makeInjector(GuiceRunnable.java:62) ~[druid-services-0.12.3.jar:0.12.3]
>         at io.druid.cli.CliInternalHadoopIndexer.run(CliInternalHadoopIndexer.java:110) ~[druid-services-0.12.3.jar:0.12.3]
>         at io.druid.cli.Main.main(Main.java:116) ~[druid-services-0.12.3.jar:0.12.3]
>         ... 6 more
> 

Command to run indexing :

`./cli.sh index hadoop hadoopDependencies org.apache.hadoop:hadoop-client:2.6.4 --no-default-hadoop mv-parquet-hadoop.json`

`hadoop-client:2.6.4` I downloaded through `pull-deps` - that's the closest version to CDH 5.14 that we use.

**Comment by Tagar** [comment]
Error happens here 
https://github.com/apache/incubator-druid/blob/0.12.3/services/src/main/java/io/druid/cli/CliInternalHadoopIndexer.java#L97

**Comment by Tagar** [comment]
NPE probably happens because `metadataSpec` is null returned by 
https://github.com/apache/incubator-druid/blob/0.12.3/services/src/main/java/io/druid/cli/CliInternalHadoopIndexer.java#L91
(my json file doesn't have `metadataUpdateSpec` ) - I thought it is optional.

Hopefully this would be captured and reported better, and hopefully documented too.

**Comment by Tagar** [comment]
I found it is documented here http://druid.io/docs/latest/ingestion/command-line-hadoop-indexer.html 
but the error still should be reported better.
