### ISSUE TITLE
Kerberos support for Hadoop indexer?

### ISSUE THREAD

**Issue by Tagar** [apache/incubator-druid#6675]
Getting following error when trying to run hadoop indexer

> 2018-11-28T08:01:52,341 ERROR [main] io.druid.cli.CliHadoopIndexer - failure!!!!
> java.lang.reflect.InvocationTargetException
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_162]
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_162]
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_162]
>         at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_162]
>         at io.druid.cli.CliHadoopIndexer.run(CliHadoopIndexer.java:117) [druid-services-0.12.3.jar:0.12.3]
>         at io.druid.cli.Main.main(Main.java:116) [druid-services-0.12.3.jar:0.12.3]
> Caused by: java.lang.RuntimeException: org.apache.hadoop.security.AccessControlException: SIMPLE authentication is not enabled.  Available:[TOKEN, KERBEROS]
>         at com.google.common.base.Throwables.propagate(Throwables.java:160) ~[guava-16.0.1.jar:?]
>         at io.druid.indexer.DetermineHashedPartitionsJob.run(DetermineHashedPartitionsJob.java:209) ~[druid-indexing-hadoop-0.12.3.jar:0.12.3]
>         at io.druid.indexer.JobHelper.runJobs(JobHelper.java:369) ~[druid-indexing-hadoop-0.12.3.jar:0.12.3]
>         at io.druid.indexer.HadoopDruidDetermineConfigurationJob.run(HadoopDruidDetermineConfigurationJob.java:91) ~[druid-indexing-hadoop-0.12.3.jar:0.12.3]
>         at io.druid.indexer.JobHelper.runJobs(JobHelper.java:369) ~[druid-indexing-hadoop-0.12.3.jar:0.12.3]
>         at io.druid.cli.CliInternalHadoopIndexer.run(CliInternalHadoopIndexer.java:132) ~[druid-services-0.12.3.jar:0.12.3]
>         at io.druid.cli.Main.main(Main.java:116) ~[druid-services-0.12.3.jar:0.12.3]
>         ... 6 more
> Caused by: org.apache.hadoop.security.AccessControlException: SIMPLE authentication is not enabled.  Available:[TOKEN, KERBEROS]
>         at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_162]
>         at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_162]
>         at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_162]
>         at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_162]
>         at org.apache.hadoop.ipc.RemoteException.instantiateException(RemoteException.java:106) ~[hadoop-common-2.6.5.jar:?]
>         at org.apache.hadoop.ipc.RemoteException.unwrapRemoteException(RemoteException.java:73) ~[hadoop-common-2.6.5.jar:?]
>         at org.apache.hadoop.hdfs.DFSClient.listPaths(DFSClient.java:1960) ~[hadoop-hdfs-2.6.5.jar:?]
>         at org.apache.hadoop.hdfs.DFSClient.listPaths(DFSClient.java:1941) ~[hadoop-hdfs-2.6.5.jar:?]
>         at org.apache.hadoop.hdfs.DistributedFileSystem.listStatusInternal(DistributedFileSystem.java:693) ~[hadoop-hdfs-2.6.5.jar:?]
>         at org.apache.hadoop.hdfs.DistributedFileSystem.access$600(DistributedFileSystem.java:105) ~[hadoop-hdfs-2.6.5.jar:?]
>         at org.apache.hadoop.hdfs.DistributedFileSystem$15.doCall(DistributedFileSystem.java:755) ~[hadoop-hdfs-2.6.5.jar:?]
>         at org.apache.hadoop.hdfs.DistributedFileSystem$15.doCall(DistributedFileSystem.java:751) ~[hadoop-hdfs-2.6.5.jar:?]
>         at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81) ~[hadoop-common-2.6.5.jar:?]
>         at org.apache.hadoop.hdfs.DistributedFileSystem.listStatus(DistributedFileSystem.java:751) ~[hadoop-hdfs-2.6.5.jar:?]
>         at org.apache.hadoop.fs.Globber.listStatus(Globber.java:69) ~[hadoop-common-2.6.5.jar:?]
>         at org.apache.hadoop.fs.Globber.glob(Globber.java:217) ~[hadoop-common-2.6.5.jar:?]
>         at org.apache.hadoop.fs.FileSystem.globStatus(FileSystem.java:1644) ~[hadoop-common-2.6.5.jar:?]
> 

Our Hadoop is secured / kerberized, so it seems Druid Hadoop Indexer doesn't try to use Kerberos for authentication.. 

We do have `druid.hadoop.security.kerberos.principal` and `druid.hadoop.security.kerberos.keytab`
set accordingly..

**Comment by Tagar** [comment]
Was missing /etc/hadoop/conf in classpath
