### ISSUE TITLE
QueryableIndexes are not sorted

### ISSUE THREAD

**Issue by smildlzj** [apache/incubator-druid#6721]
when submit a conpact task, but fail. 

how can resolve it ?
```
java.lang.IllegalStateException: QueryableIndexes are not sorted! Interval[2018-11-25T15:00:00.000Z/2018-11-25T16:00:00.000Z] of segment[mywork@pageview_2018-
11-25T15:00:00.000Z_2018-11-25T16:00:00.000Z_2018-12-07T11:52:53.432Z] is laster than interval[2018-11-23T00:00:00.000Z/2018-12-04T00:00:00.000Z] of segment[m
ywork@pageview_2018-11-23T00:00:00.000Z_2018-12-04T00:00:00.000Z_2018-12-05T18:50:02.159Z]
        at com.google.common.base.Preconditions.checkState(Preconditions.java:200) ~[guava-16.0.1.jar:?]
        at io.druid.indexing.common.task.CompactionTask.createDimensionsSpec(CompactionTask.java:362) ~[druid-indexing-service-0.12.2.jar:0.12.2]
        at io.druid.indexing.common.task.CompactionTask.createDataSchema(CompactionTask.java:333) ~[druid-indexing-service-0.12.2.jar:0.12.2]
        at io.druid.indexing.common.task.CompactionTask.createIngestionSchema(CompactionTask.java:243) ~[druid-indexing-service-0.12.2.jar:0.12.2]
        at io.druid.indexing.common.task.CompactionTask.run(CompactionTask.java:186) ~[druid-indexing-service-0.12.2.jar:0.12.2]
        at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:444) [druid-indexing-service-0.12.2.jar
:0.12.2]
        at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:416) [druid-indexing-service-0.12.2.jar
:0.12.2]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
```

![image](https://user-images.githubusercontent.com/1638850/49745329-ac159b00-fcd9-11e8-962c-2ff03142f9d8.png)
![image](https://user-images.githubusercontent.com/1638850/49745375-c64f7900-fcd9-11e8-9883-1ed910cd245f.png)

**Comment by jihoonson** [comment]
Hi @smildlzj, sorry for late response. 

This error is just a sanity check and shouldn't happen in production. Do you still see the same error?

**Comment by smildlzj** [comment]
> Hi @smildlzj, sorry for late response.
> 
> This error is just a sanity check and shouldn't happen in production. Do you still see the same error?

Hi, it still happen

**Comment by stevenchen3** [comment]
Encountered the same with version 0.16.0. Any fix or workaround? thanks.
