### ISSUE TITLE
tranquility kafka version 52.0

### ISSUE THREAD

**Issue by huahuang12** [apache/incubator-druid#6752]
Version druid0.9.2 kafka2.10_0.8.1 used to get rid of ility0.8.0 JDK 1.7
Write data to tranquility kafka to druid successfully. Later, after Linux goes down and restarts, the service of tranquility kafka cannot write written data to druid. Even if a new topic is created, it cannot succeed
The error report content is shown in the picture. I hope someone can help me solve the problem. Thank you
![_20181218161507](https://user-images.githubusercontent.com/45962263/50140568-251b8080-02e0-11e9-917d-cfe9372775f7.jpg)
![_20181218161516](https://user-images.githubusercontent.com/45962263/50140578-2c428e80-02e0-11e9-9cc6-b276bd673ab2.jpg)

**Comment by dragonls** [comment]
Use JDK8 instead of JDK7.

**Comment by huahuang12** [comment]
The druid0.9.2 official website is available with jdk1.7
Jdk1.7 was used before the server went down.
This error will also occur if kafka offset is lost before

> 使用JDK8而不是JDK7。
druid0.9.2官网上介绍是可以使用jdk1.7的
在服务器宕机重启之前，都可以正常运行，
之前kafka offset丢失，也会出现52 这个错误，所以可以肯定不是版本的问题，还是谢谢你

The druid0.9.2 official website is available with jdk1.7
Before the server is down and restarted, it can run normally.
Before, kafka offset was lost, and the error 52 would appear, so I'm sure it's not the version problem. Thank you again

**Comment by huahuang12** [comment]
> 咖啡因缓存扩展需要并使用JDK8构建，即使其余的Druid是使用JDK7构建的：
> 
> [＃3028](https://github.com/apache/incubator-druid/pull/3028)

但是 我之前一直使用的jdk1.7可以正常运行不会出现这个错误，
出现这个错误我进行过尝试，kafka offset丢失，时间格式错误也会出现这个错误
所以我觉得是可以排除jdk版本的问题。
谢谢你
However, jdk1.7, which I have been using before, works without this error.
I have tried this error before. Kafka offset is lost, and time format error will also result in this error
So I think it's possible to troubleshoot JDK versions.
Thank you

**Comment by jon-wei** [comment]
You'll need to either use Java 8 or disable the caffeine cache.

Please note that the doc page (http://druid.io/docs/0.9.2/development/extensions-core/caffeine-cache.html) mentions: 

> A highly performant local cache implementation for Druid based on Caffeine. Requires a JRE8u60 or higher

**Comment by huahuang12** [comment]
> 您需要使用Java 8或禁用咖啡因缓存。
> 
> 请注意，doc页面（http://druid.io/docs/0.9.2/development/extensions-core/caffeine-cache.html）提到：
> 
> > 基于Caffeine的德鲁伊高性能本地缓存实现。需要JRE8u60或更高版本

I rebuilt the operating environment with jdk1.8, and when I first started tranquility kafka, I could normally write kafka data into druid. When I modified the Java variable to 1.7, the following error occurred when I started tranquility kafka service again.Tranquility - distribution - 0.8.0 lib directory. IO druid. The druid - processing - 0.9.0. Jar is no IO/druid/query/lookup/LookupExtractorFactory class, because it belongs to the druid lib directory of the druid - processing - 0.9.2. Jar package, why is this case?

我使用jdk1.8重新搭建了运行环境，第一次启动 tranquility kafka可以正常将kafka数据写入druid,当我修改java变量 ，为1.7版本，再次启动  tranquility kafka 服务出现如下错误，tranquility-distribution-0.8.0 lib目录下io.druid.druid-processing-0.9.0.jar 确实没有 io/druid/query/lookup/LookupExtractorFactory 类，因为它属于druid lib 目录下的druid-processing-0.9.2.jar 包，为什么会出现这种情况呢？


2018-12-20 10:29:15,119 [KafkaConsumer-1] INFO  i.d.initialization.Initialization - Loading extension [mysql-metadata-storage] for class [io.druid.initialization.DruidModule]
2018-12-20 10:29:15,120 [KafkaConsumer-1] INFO  i.d.initialization.Initialization - added URL[file:/bigdata/druid-0.9.2/extensions/mysql-metadata-storage/mysql-connector-java-5.1.38.jar]
2018-12-20 10:29:15,120 [KafkaConsumer-1] INFO  i.d.initialization.Initialization - added URL[file:/bigdata/druid-0.9.2/extensions/mysql-metadata-storage/mysql-metadata-storage-0.9.2.jar]
2018-12-20 10:29:15,123 [KafkaConsumer-1] INFO  i.d.initialization.Initialization - Adding local file system extension module [io.druid.metadata.storage.mysql.MySQLMetadataStorageModule] for class [io.druid.initialization.DruidModule]
2018-12-20 10:29:15,162 [KafkaConsumer-1] ERROR c.m.tranquility.kafka.KafkaConsumer - Exception: 
java.lang.NoClassDefFoundError: io/druid/query/lookup/LookupExtractorFactory
	at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.8.0_131]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[na:1.8.0_131]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.8.0_131]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[na:1.8.0_131]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[na:1.8.0_131]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[na:1.8.0_131]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[na:1.8.0_131]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_131]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[na:1.8.0_131]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_131]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_131]
	at io.druid.server.lookup.LookupExtractionModule$1.setupModule(LookupExtractionModule.java:43) ~[na:na]
	at com.fasterxml.jackson.databind.ObjectMapper.registerModule(ObjectMapper.java:549) ~[com.fasterxml.jackson.core.jackson-databind-2.4.6.jar:2.4.6]
	at com.metamx.tranquility.druid.DruidGuicer$$anonfun$registerWithJackson$1$1.apply(DruidGuicer.scala:82) ~[io.druid.tranquility-core-0.8.0.jar:0.8.0]
	at com.metamx.tranquility.druid.DruidGuicer$$anonfun$registerWithJackson$1$1.apply(DruidGuicer.scala:81) ~[io.druid.tranquility-core-0.8.0.jar:0.8.0]
	at scala.collection.Iterator$class.foreach(Iterator.scala:742) ~[org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1194) ~[org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72) ~[org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54) ~[org.scala-lang.scala-library-2.11.7.jar:na]
	at com.metamx.tranquility.druid.DruidGuicer.registerWithJackson$1(DruidGuicer.scala:80) ~[io.druid.tranquility-core-0.8.0.jar:0.8.0]
	at com.metamx.tranquility.druid.DruidGuicer.com$metamx$tranquility$druid$DruidGuicer$$toGuiceModule$1(DruidGuicer.scala:89) ~[io.druid.tranquility-core-0.8.0.jar:0.8.0]
	at com.metamx.tranquility.druid.DruidGuicer$$anonfun$3.apply(DruidGuicer.scala:127) ~[io.druid.tranquility-core-0.8.0.jar:0.8.0]
	at com.metamx.tranquility.druid.DruidGuicer$$anonfun$3.apply(DruidGuicer.scala:127) ~[io.druid.tranquility-core-0.8.0.jar:0.8.0]
	at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:418) ~[org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:418) ~[org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1233) ~[org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1223) ~[org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.collection.generic.Growable$class.loop$1(Growable.scala:54) ~[org.scala-lang.scala-library-2.11.7.jar:na]

**Comment by dragonls** [comment]
It seems that the tranquility is loading extension from druid 0.9.2, while the codes in druid 0.9.2 are using the class io.druid.query.lookup.LookupExtractorFactory. Try using the druid 0.9.2 codes in front of druid 0.9.0, i.e. put the druid-processing-0.9.2.jar in front of druid-processing-0.9.0.jar in classpath.
Why not try the newer version of Druid? Just curious.
