### ISSUE TITLE
Tranquility, java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by huahuang12** [apache/incubator-druid#6763]
我用jdk1.8重建了操作环境，当我第一次开始宁静的kafka时，我通常可以将kafka数据写入德鲁伊。当我将Java变量修改为1.7时，当我再次启动安静kafka服务时发生以下错误.Tranquility - distribution - 0.8.0 lib目录。IO德鲁伊。德鲁伊 - 处理 - 0.9.0。Jar不是IO / druid / query / lookup / LookupExtractorFactory类，因为它属于德鲁伊的德鲁伊lib目录 - 处理 - 0.9.2。Jar包，为什么会这样？

我使用jdk1.8重新搭建了运行环境，第一次启动宁静kafka可以正常将kafka数据写入德鲁伊，当我修改java变量，为1.7版本，再次启动宁静kafka服务出现如下错误，tranquility-distribution-0.8 .0 lib目录下io.druid.druid-processing-0.9.0.jar确实没有io / druid / query / lookup / LookupExtractorFactory类，因为它属于druid lib目录下的druid-processing-0.9.2.jar包，为什么会出现这种情况呢？

2018-12-20 16:36:13,317 [KafkaConsumer-1] INFO  i.d.initialization.Initialization - Loading extension [druid-s3-extensions] for class [io.druid.initialization.DruidModule]
2018-12-20 16:36:13,317 [KafkaConsumer-1] INFO  i.d.initialization.Initialization - added URL[file:/bigdata/druid-0.9.2/extensions/druid-s3-extensions/druid-s3-extensions-0.9.2.jar]
2018-12-20 16:36:13,414 [KafkaConsumer-1] INFO  i.d.initialization.Initialization - Adding local file system extension module [io.druid.storage.s3.S3StorageDruidModule] for class [io.druid.initialization.DruidModule]
2018-12-20 16:36:13,415 [KafkaConsumer-1] INFO  i.d.initialization.Initialization - Adding local file system extension module [io.druid.firehose.s3.S3FirehoseDruidModule] for class [io.druid.initialization.DruidModule]
2018-12-20 16:36:13,415 [KafkaConsumer-1] INFO  i.d.initialization.Initialization - Loading extension [druid-stats] for class [io.druid.initialization.DruidModule]
2018-12-20 16:36:13,415 [KafkaConsumer-1] INFO  i.d.initialization.Initialization - added URL[file:/bigdata/druid-0.9.2/extensions/druid-stats/druid-stats-0.9.2.jar]
2018-12-20 16:36:13,418 [KafkaConsumer-1] INFO  i.d.initialization.Initialization - Adding local file system extension module [io.druid.query.aggregation.stats.DruidStatsModule] for class [io.druid.initialization.DruidModule]
2018-12-20 16:36:13,418 [KafkaConsumer-1] INFO  i.d.initialization.Initialization - Loading extension [mysql-metadata-storage] for class [io.druid.initialization.DruidModule]
2018-12-20 16:36:13,418 [KafkaConsumer-1] INFO  i.d.initialization.Initialization - added URL[file:/bigdata/druid-0.9.2/extensions/mysql-metadata-storage/mysql-connector-java-5.1.38.jar]
2018-12-20 16:36:13,418 [KafkaConsumer-1] INFO  i.d.initialization.Initialization - added URL[file:/bigdata/druid-0.9.2/extensions/mysql-metadata-storage/mysql-metadata-storage-0.9.2.jar]
2018-12-20 16:36:13,421 [KafkaConsumer-1] INFO  i.d.initialization.Initialization - Adding local file system extension module [io.druid.metadata.storage.mysql.MySQLMetadataStorageModule] for class [io.druid.initialization.DruidModule]
2018-12-20 16:36:13,422 [KafkaConsumer-1] INFO  i.d.initialization.Initialization - Loading extension [postgresql-metadata-storage] for class [io.druid.initialization.DruidModule]
2018-12-20 16:36:13,422 [KafkaConsumer-1] INFO  i.d.initialization.Initialization - added URL[file:/bigdata/druid-0.9.2/extensions/postgresql-metadata-storage/postgresql-9.4.1208.jre7.jar]
2018-12-20 16:36:13,422 [KafkaConsumer-1] INFO  i.d.initialization.Initialization - added URL[file:/bigdata/druid-0.9.2/extensions/postgresql-metadata-storage/postgresql-metadata-storage-0.9.2.jar]
2018-12-20 16:36:13,424 [KafkaConsumer-1] INFO  i.d.initialization.Initialization - Adding local file system extension module [io.druid.metadata.storage.postgresql.PostgreSQLMetadataStorageModule] for class [io.druid.initialization.DruidModule]
2018-12-20 16:36:13,441 [KafkaConsumer-1] ERROR c.m.tranquility.kafka.KafkaConsumer - Exception: 
java.lang.NoClassDefFoundError: io/druid/query/lookup/LookupExtractorFactory
	at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.8.0_131]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[na:1.8.0_131]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.8.0_131]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[na:1.8.0_131]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[na:1.8.0_131]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[na:1.8.0_131]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[na:1.8.0_131]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_131]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[na:1.8.0_131]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_131]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_131]
	at io.druid.server.lookup.LookupExtractionModule$1.setupModule(LookupExtractionModule.java:43) ~[na:na]
	at com.fasterxml.jackson.databind.ObjectMapper.registerModule(ObjectMapper.java:549) ~[com.fasterxml.jackson.core.jackson-databind-2.4.6.jar:2.4.6]
	at com.metamx.tranquility.druid.DruidGuicer$$anonfun$registerWithJackson$1$1.apply(DruidGuicer.scala:82) ~[io.druid.tranquility-core-0.8.0.jar:0.8.0]
	at com.metamx.tranquility.druid.DruidGuicer$$anonfun$registerWithJackson$1$1.apply(DruidGuicer.scala:81) ~[io.druid.tranquility-core-0.8.0.jar:0.8.0]
	at scala.collection.Iterator$class.foreach(Iterator.scala:742) ~[org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1194) ~[org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72) ~[org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54) ~[org.scala-lang.scala-library-2.11.7.jar:na]
	at com.metamx.tranquility.druid.DruidGuicer.registerWithJackson$1(DruidGuicer.scala:80) ~[io.druid.tranquility-core-0.8.0.jar:0.8.0]
	at com.metamx.tranquility.druid.DruidGuicer.com$metamx$tranquility$druid$DruidGuicer$$toGuiceModule$1(DruidGuicer.scala:89) ~[io.druid.tranquility-core-0.8.0.jar:0.8.0]
	at com.metamx.tranquility.druid.DruidGuicer$$anonfun$3.apply(DruidGuicer.scala:127) ~[io.druid.tranquility-core-0.8.0.jar:0.8.0]
	at com.metamx.tranquility.druid.DruidGuicer$$anonfun$3.apply(DruidGuicer.scala:127) ~[io.druid.tranquility-core-0.8.0.jar:0.8.0]
	at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:418) ~[org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:418) ~[org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1233) ~[org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1223) ~[org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.collection.generic.Growable$class.loop$1(Growable.scala:54) ~[org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:57) ~[org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:183) ~[org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:45) ~[org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.collection.TraversableLike$class.$plus$plus(TraversableLike.scala:158) ~[org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.collection.immutable.List.$plus$plus(List.scala:196) ~[org.scala-lang.scala-library-2.11.7.jar:na]
	at com.metamx.tranquility.druid.DruidGuicer.<init>(DruidGuicer.scala:128) ~[io.druid.tranquility-core-0.8.0.jar:0.8.0]
	at com.metamx.tranquility.druid.DruidGuicer$.<init>(DruidGuicer.scala:138) ~[io.druid.tranquility-core-0.8.0.jar:0.8.0]
	at com.metamx.tranquility.druid.DruidGuicer$.<clinit>(DruidGuicer.scala) ~[io.druid.tranquility-core-0.8.0.jar:0.8.0]
	at com.metamx.tranquility.druid.DruidBeams$.makeFireDepartment(DruidBeams.scala:406) ~[io.druid.tranquility-core-0.8.0.jar:0.8.0]
	at com.metamx.tranquility.druid.DruidBeams$.fromConfigInternal(DruidBeams.scala:291) ~[io.druid.tranquility-core-0.8.0.jar:0.8.0]
	at com.metamx.tranquility.druid.DruidBeams$.fromConfig(DruidBeams.scala:199) ~[io.druid.tranquility-core-0.8.0.jar:0.8.0]
	at com.metamx.tranquility.kafka.KafkaBeamUtils$.createTranquilizer(KafkaBeamUtils.scala:40) ~[io.druid.tranquility-kafka-0.8.0.jar:0.8.0]
	at com.metamx.tranquility.kafka.KafkaBeamUtils.createTranquilizer(KafkaBeamUtils.scala) ~[io.druid.tranquility-kafka-0.8.0.jar:0.8.0]
	at com.metamx.tranquility.kafka.writer.TranquilityEventWriter.<init>(TranquilityEventWriter.java:64) ~[io.druid.tranquility-kafka-0.8.0.jar:0.8.0]
	at com.metamx.tranquility.kafka.writer.WriterController.createWriter(WriterController.java:171) ~[io.druid.tranquility-kafka-0.8.0.jar:0.8.0]
	at com.metamx.tranquility.kafka.writer.WriterController.getWriter(WriterController.java:98) ~[io.druid.tranquility-kafka-0.8.0.jar:0.8.0]
	at com.metamx.tranquility.kafka.KafkaConsumer$2.run(KafkaConsumer.java:231) ~[io.druid.tranquility-kafka-0.8.0.jar:0.8.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
Caused by: java.lang.ClassNotFoundException: io.druid.query.lookup.LookupExtractorFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_131]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_131]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_131]
	... 50 common frames omitted
2018-12-20 16:36:13,442 [KafkaConsumer-1] INFO  c.m.tranquility.kafka.KafkaConsumer - Shutting down - attempting to flush buffers and commit final offsets
2018-12-20 16:36:13,714 [KafkaConsumer-1] INFO  org.apache.zookeeper.ZooKeeper - Session: 0x67caa2b5010008 closed
2018-12-20 16:36:13,714 [KafkaConsumer-1-EventThread] INFO  org.apache.zookeeper.ClientCnxn - EventThread shut down
2018-12-20 16:36:13,878 [KafkaConsumer-1] INFO  k.c.ZookeeperConsumerConnector - [tranquility-kafka0012_node-1-1545294920232-111b85a0], ZKConsumerConnector shutting down
2018-12-20 16:36:13,884 [KafkaConsumer-1] INFO  k.c.ZookeeperTopicEventWatcher - Shutting down topic event watcher.
2018-12-20 16:36:13,884 [KafkaConsumer-1] INFO  k.consumer.ConsumerFetcherManager - [ConsumerFetcherManager-1545294920330] Stopping leader finder thread
2018-12-20 16:36:13,884 [KafkaConsumer-1] INFO  k.c.ConsumerFetcherManager$LeaderFinderThread - [tranquility-kafka0012_node-1-1545294920232-111b85a0-leader-finder-thread], Shutting down
2018-12-20 16:36:13,885 [tranquility-kafka0012_node-1-1545294920232-111b85a0-leader-finder-thread] INFO  k.c.ConsumerFetcherManager$LeaderFinderThread - [tranquility-kafka0012_node-1-1545294920232-111b85a0-leader-finder-thread], Stopped 
2018-12-20 16:36:13,885 [KafkaConsumer-1] INFO  k.c.ConsumerFetcherManager$LeaderFinderThread - [tranquility-kafka0012_node-1-1545294920232-111b85a0-leader-finder-thread], Shutdown completed
2018-12-20 16:36:13,885 [KafkaConsumer-1] INFO  k.consumer.ConsumerFetcherManager - [ConsumerFetcherManager-1545294920330] Stopping all fetchers
2018-12-20 16:36:13,885 [KafkaConsumer-1] INFO  kafka.consumer.ConsumerFetcherThread - [ConsumerFetcherThread-tranquility-kafka0012_node-1-1545294920232-111b85a0-0-1], Shutting down
2018-12-20 16:36:13,886 [ConsumerFetcherThread-tranquility-kafka0012_node-1-1545294920232-111b85a0-0-1] INFO  kafka.consumer.SimpleConsumer - Reconnect due to socket error: java.nio.channels.ClosedByInterruptException
2018-12-20 16:36:13,887 [ConsumerFetcherThread-tranquility-kafka0012_node-1-1545294920232-111b85a0-0-1] INFO  kafka.consumer.ConsumerFetcherThread - [ConsumerFetcherThread-tranquility-kafka0012_node-1-1545294920232-111b85a0-0-1], Stopped 
2018-12-20 16:36:13,887 [KafkaConsumer-1] INFO  kafka.consumer.ConsumerFetcherThread - [ConsumerFetcherThread-tranquility-kafka0012_node-1-1545294920232-111b85a0-0-1], Shutdown completed
2018-12-20 16:36:13,887 [KafkaConsumer-1] INFO  k.consumer.ConsumerFetcherManager - [ConsumerFetcherManager-1545294920330] All connections stopped
2018-12-20 16:36:13,889 [ZkClient-EventThread-13-node-1:2181,node-2:2181,node-3:2181/kafka] INFO  org.I0Itec.zkclient.ZkEventThread - Terminate ZkClient event thread.
2018-12-20 16:36:13,949 [KafkaConsumer-1] INFO  org.apache.zookeeper.ZooKeeper - Session: 0x67caa2b5010007 closed
2018-12-20 16:36:13,949 [main-EventThread] INFO  org.apache.zookeeper.ClientCnxn - EventThread shut down
2018-12-20 16:36:13,950 [KafkaConsumer-1] INFO  k.c.ZookeeperConsumerConnector - [tranquility-kafka0012_node-1-1545294920232-111b85a0], ZKConsumerConnector shutdown completed in 71 ms
2018-12-20 16:36:13,950 [KafkaConsumer-1] INFO  c.m.tranquility.kafka.KafkaConsumer - Finished clean shutdown.
2018-12-20 16:36:13,950 [KafkaConsumer-CommitThread] INFO  c.m.tranquility.kafka.KafkaConsumer - Commit thread interrupted.
2018-12-20 16:36:14,431 [tranquility-kafka0012_node-1-1545294920232-111b85a0_watcher_executor] INFO  k.c.ZookeeperConsumerConnector - [tranquility-kafka0012_node-1-1545294920232-111b85a0], stopping watcher executor thread for consumer tranquility-kafka0012_node-1-1545294920232-111b85a0
2018-12-20 16:36:14,432 [Thread-4] INFO  c.metamx.tranquility.kafka.KafkaMain - Initiating shutdown...

**Comment by egor-ryashin** [comment]
@huahuang12 I wonder whether you have managed to resolve the issue?
