### ISSUE TITLE
Specified key was too long; max key length is 767 bytes

### ISSUE THREAD

**Issue by dangerousfeng** [apache/incubator-druid#6781]
```
2018-12-27T16:55:28,812 INFO [main] org.apache.druid.metadata.SQLMetadataConnector - Creating table[druid_config]
2018-12-27T16:55:28,815 WARN [main] org.apache.druid.java.util.common.RetryUtils - Retrying (6 of 9) in 32,430ms.
org.skife.jdbi.v2.exceptions.CallbackFailedException: org.skife.jdbi.v2.exceptions.UnableToExecuteStatementException: java.sql.BatchUpdateException: Specified key was too long; max key length is 767 bytes [statement:"null", located:"null", rewritten:"null", arguments:null]
        at org.skife.jdbi.v2.DBI.withHandle(DBI.java:284) ~[jdbi-2.63.1.jar:2.63.1]
        at org.apache.druid.metadata.SQLMetadataConnector.lambda$retryWithHandle$0(SQLMetadataConnector.java:130) ~[druid-server-0.13.0-incubating.jar:0.13.0-incubating]
        at org.apache.druid.java.util.common.RetryUtils.retry(RetryUtils.java:86) [java-util-0.13.0-incubating.jar:0.13.0-incubating]
        at org.apache.druid.java.util.common.RetryUtils.retry(RetryUtils.java:114) [java-util-0.13.0-incubating.jar:0.13.0-incubating]
        at org.apache.druid.java.util.common.RetryUtils.retry(RetryUtils.java:104) [java-util-0.13.0-incubating.jar:0.13.0-incubating]
        at org.apache.druid.metadata.SQLMetadataConnector.retryWithHandle(SQLMetadataConnector.java:130) [druid-server-0.13.0-incubating.jar:0.13.0-incubating]
        at org.apache.druid.metadata.SQLMetadataConnector.retryWithHandle(SQLMetadataConnector.java:139) [druid-server-0.13.0-incubating.jar:0.13.0-incubating]
        at org.apache.druid.metadata.SQLMetadataConnector.createTable(SQLMetadataConnector.java:172) [druid-server-0.13.0-incubating.jar:0.13.0-incubating]
        at org.apache.druid.metadata.SQLMetadataConnector.createConfigTable(SQLMetadataConnector.java:303) [druid-server-0.13.0-incubating.jar:0.13.0-incubating]
        at org.apache.druid.metadata.SQLMetadataConnector.createConfigTable(SQLMetadataConnector.java:557) [druid-server-0.13.0-incubating.jar:0.13.0-incubating]
        at org.apache.druid.guice.JacksonConfigManagerModule$1.start(JacksonConfigManagerModule.java:58) [druid-common-0.13.0-incubating.jar:0.13.0-incubating]
        at org.apache.druid.java.util.common.lifecycle.Lifecycle.start(Lifecycle.java:311) [java-util-0.13.0-incubating.jar:0.13.0-incubating]
        at org.apache.druid.guice.LifecycleModule$2.start(LifecycleModule.java:134) [druid-api-0.13.0-incubating.jar:0.13.0-incubating]
        at org.apache.druid.cli.GuiceRunnable.initLifecycle(GuiceRunnable.java:107) [druid-services-0.13.0-incubating.jar:0.13.0-incubating]
        at org.apache.druid.cli.ServerRunnable.run(ServerRunnable.java:50) [druid-services-0.13.0-incubating.jar:0.13.0-incubating]
        at org.apache.druid.cli.Main.main(Main.java:118) [druid-services-0.13.0-incubating.jar:0.13.0-incubating]
Caused by: org.skife.jdbi.v2.exceptions.UnableToExecuteStatementException: java.sql.BatchUpdateException: Specified key was too long; max key length is 767 bytes [statement:"null", located:"null", rewritten:"null", arguments:null]
        at org.skife.jdbi.v2.Batch.execute(Batch.java:131) ~[jdbi-2.63.1.jar:2.63.1]
        at org.apache.druid.metadata.SQLMetadataConnector$2.withHandle(SQLMetadataConnector.java:184) ~[druid-server-0.13.0-incubating.jar:0.13.0-incubating]
        at org.apache.druid.metadata.SQLMetadataConnector$2.withHandle(SQLMetadataConnector.java:174) ~[druid-server-0.13.0-incubating.jar:0.13.0-incubating]
        at org.skife.jdbi.v2.DBI.withHandle(DBI.java:281) ~[jdbi-2.63.1.jar:2.63.1]
        ... 15 more
Caused by: java.sql.BatchUpdateException: Specified key was too long; max key length is 767 bytes
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_60]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_60]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_60]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_60]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:404) ~[?:?]
        at com.mysql.jdbc.Util.getInstance(Util.java:387) ~[?:?]
        at com.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1161) ~[?:?]
        at com.mysql.jdbc.StatementImpl.executeBatchInternal(StatementImpl.java:1048) ~[?:?]
        at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:958) ~[?:?]
        at org.apache.commons.dbcp2.DelegatingStatement.executeBatch(DelegatingStatement.java:345) ~[commons-dbcp2-2.0.1.jar:2.0.1]
        at org.apache.commons.dbcp2.DelegatingStatement.executeBatch(DelegatingStatement.java:345) ~[commons-dbcp2-2.0.1.jar:2.0.1]
        at org.skife.jdbi.v2.Batch.execute(Batch.java:121) ~[jdbi-2.63.1.jar:2.63.1]
        at org.apache.druid.metadata.SQLMetadataConnector$2.withHandle(SQLMetadataConnector.java:184) ~[druid-server-0.13.0-incubating.jar:0.13.0-incubating]
        at org.apache.druid.metadata.SQLMetadataConnector$2.withHandle(SQLMetadataConnector.java:174) ~[druid-server-0.13.0-incubating.jar:0.13.0-incubating]
        at org.skife.jdbi.v2.DBI.withHandle(DBI.java:281) ~[jdbi-2.63.1.jar:2.63.1]
        ... 15 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Specified key was too long; max key length is 767 bytes
```

**Comment by dangerousfeng** [comment]
I have solved it.  mysql. Utf8 instead of utf8mb4.
