### ISSUE TITLE
ava.lang.Exception: java.lang.IllegalArgumentException: Invalid format: "1546300800000" is malformed at "0000"

### ISSUE THREAD

**Issue by chinalinux2012** [apache/incubator-druid#6825]
java.lang.Exception: java.lang.IllegalArgumentException: Invalid format: "1546300800000" is malformed at "0000" (through reference chain: io.druid.indexer.HadoopDruidIndexerConfig["spec"]->io.druid.indexer.HadoopIngestionSpec["tuningConfig"]->io.druid.indexer.HadoopTuningConfig["shardSpecs"])
	at org.apache.hadoop.mapred.LocalJobRunner$Job.runTasks(LocalJobRunner.java:489) ~[hadoop-mapreduce-client-common-2.8.3.jar:?]
	at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:549) [hadoop-mapreduce-client-common-2.8.3.jar:?]
Caused by: java.lang.IllegalArgumentException: Invalid format: "1546300800000" is malformed at "0000" (through reference chain: io.druid.indexer.HadoopDruidIndexerConfig["spec"]->io.druid.indexer.HadoopIngestionSpec["tuningConfig"]->io.druid.indexer.HadoopTuningConfig["shardSpecs"])
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3459) ~[jackson-databind-2.6.7.jar:2.6.7]
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3378) ~[jackson-databind-2.6.7.jar:2.6.7]
	at io.druid.indexer.HadoopDruidIndexerConfig.fromMap(HadoopDruidIndexerConfig.java:139) ~[druid-indexing-hadoop-0.9.2.jar:0.9.2]
	at io.druid.indexer.HadoopDruidIndexerConfig.fromString(HadoopDruidIndexerConfig.java:174) ~[druid-indexing-hadoop-0.9.2.jar:0.9.2]
	at io.druid.indexer.HadoopDruidIndexerConfig.fromConfiguration(HadoopDruidIndexerConfig.java:211) ~[druid-indexing-hadoop-0.9.2.jar:0.9.2]
	at org.apache.parquet.avro.DruidParquetReadSupport.getPartialReadSchema(DruidParquetReadSupport.java:49) ~[druid-parquet-extensions-0.9.2.jar:0.9.2]
	at org.apache.parquet.avro.DruidParquetReadSupport.init(DruidParquetReadSupport.java:79) ~[druid-parquet-extensions-0.9.2.jar:0.9.2]
	at org.apache.parquet.hadoop.InternalParquetRecordReader.initialize(InternalParquetRecordReader.java:172) ~[parquet-hadoop-1.8.1.jar:1.8.1]
	at org.apache.parquet.hadoop.ParquetRecordReader.initializeInternalReader(ParquetRecordReader.java:201) ~[parquet-hadoop-1.8.1.jar:1.8.1]
	at org.apache.parquet.hadoop.ParquetRecordReader.initialize(ParquetRecordReader.java:145) ~[parquet-hadoop-1.8.1.jar:1.8.1]
	at org.apache.hadoop.mapreduce.lib.input.DelegatingRecordReader.initialize(DelegatingRecordReader.java:84) ~[hadoop-mapreduce-client-core-2.8.3.jar:?]
	at org.apache.hadoop.mapred.MapTask$NewTrackingRecordReader.initialize(MapTask.java:548) ~[hadoop-mapreduce-client-core-2.8.3.jar:?]
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:786) ~[hadoop-mapreduce-client-core-2.8.3.jar:?]
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341) ~[hadoop-mapreduce-client-core-2.8.3.jar:?]
	at org.apache.hadoop.mapred.LocalJobRunner$Job$MapTaskRunnable.run(LocalJobRunner.java:270) ~[hadoop-mapreduce-client-common-2.8.3.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_192]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_192]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_192]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_192]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_192]

index_hadoop ingestion task which was successfully finished on druid 0.9.2, but was down on druid 0.13.0, anybody help?

**Comment by egor-ryashin** [comment]
@chinalinux2012 could you provide the task spec and data sample?
