### ISSUE TITLE
Rolling update failure in Kafka indexing service

### ISSUE THREAD

**Issue by jihoonson** [apache/incubator-druid#7330]
### Affected Version

0.14.0-rc2

### Description

[When publishing a segment, the start offsets of the new sequence is matched to the end offsets of the previous sequence](https://github.com/apache/incubator-druid/blob/master/server/src/main/java/org/apache/druid/metadata/IndexerSQLMetadataStorageCoordinator.java#L889). Here, the start offsets must contain `SeekableStreamStartSequenceNumbers`. However, the Kafka tasks of an old version would send `SeekableStreamEndSequenceNumbers` because it's the default implementation of `SeekableStreamSequenceNumbers`.

Here is the stack trace.

```
Caused by: org.skife.jdbi.v2.exceptions.CallbackFailedException: org.apache.druid.java.util.common.IAE: Expected instance of org.apache.druid.indexing.seekables
tream.SeekableStreamEndSequenceNumbers, got org.apache.druid.indexing.seekablestream.SeekableStreamStartSequenceNumbers
        at org.skife.jdbi.v2.DBI.withHandle(DBI.java:284) ~[jdbi-2.63.1.jar:2.63.1]
        at org.skife.jdbi.v2.DBI.inTransaction(DBI.java:353) ~[jdbi-2.63.1.jar:2.63.1]
        at org.apache.druid.metadata.SQLMetadataConnector.lambda$retryTransaction$1(SQLMetadataConnector.java:148) ~[druid-server-0.14.0-iap-pre5.jar:0.14.0-iap
-pre5]
        at org.apache.druid.java.util.common.RetryUtils.retry(RetryUtils.java:86) ~[druid-core-0.14.0-iap-pre5.jar:0.14.0-iap-pre5]
        at org.apache.druid.java.util.common.RetryUtils.retry(RetryUtils.java:114) ~[druid-core-0.14.0-iap-pre5.jar:0.14.0-iap-pre5]
        at org.apache.druid.metadata.SQLMetadataConnector.retryTransaction(SQLMetadataConnector.java:148) ~[druid-server-0.14.0-iap-pre5.jar:0.14.0-iap-pre5]
        at org.apache.druid.metadata.IndexerSQLMetadataStorageCoordinator.announceHistoricalSegments(IndexerSQLMetadataStorageCoordinator.java:285) ~[druid-serv
er-0.14.0-iap-pre5.jar:0.14.0-iap-pre5]
        at org.apache.druid.indexing.common.actions.SegmentTransactionalInsertAction.lambda$perform$0(SegmentTransactionalInsertAction.java:115) ~[druid-indexin
g-service-0.14.0-iap-pre5.jar:0.14.0-iap-pre5]
        at org.apache.druid.indexing.overlord.CriticalAction.perform(CriticalAction.java:53) ~[druid-indexing-service-0.14.0-iap-pre5.jar:0.14.0-iap-pre5]
        at org.apache.druid.indexing.overlord.TaskLockbox.doInCriticalSection(TaskLockbox.java:627) ~[druid-indexing-service-0.14.0-iap-pre5.jar:0.14.0-iap-pre5
]
        at org.apache.druid.indexing.common.actions.SegmentTransactionalInsertAction.perform(SegmentTransactionalInsertAction.java:110) ~[druid-indexing-service
-0.14.0-iap-pre5.jar:0.14.0-iap-pre5]
        ... 75 more
Caused by: org.apache.druid.java.util.common.IAE: Expected instance of org.apache.druid.indexing.seekablestream.SeekableStreamEndSequenceNumbers, got org.apache
.druid.indexing.seekablestream.SeekableStreamStartSequenceNumbers
        at org.apache.druid.indexing.seekablestream.SeekableStreamEndSequenceNumbers.plus(SeekableStreamEndSequenceNumbers.java:132) ~[druid-indexing-service-0.
14.0-iap-pre5.jar:0.14.0-iap-pre5]
        at org.apache.druid.indexing.seekablestream.SeekableStreamDataSourceMetadata.plus(SeekableStreamDataSourceMetadata.java:77) ~[druid-indexing-service-0.1
4.0-iap-pre5.jar:0.14.0-iap-pre5]
        at org.apache.druid.indexing.seekablestream.SeekableStreamDataSourceMetadata.matches(SeekableStreamDataSourceMetadata.java:59) ~[druid-indexing-service-
0.14.0-iap-pre5.jar:0.14.0-iap-pre5]
        at org.apache.druid.metadata.IndexerSQLMetadataStorageCoordinator.updateDataSourceMetadataWithHandle(IndexerSQLMetadataStorageCoordinator.java:890) ~[dr
uid-server-0.14.0-iap-pre5.jar:0.14.0-iap-pre5]
        at org.apache.druid.metadata.IndexerSQLMetadataStorageCoordinator$1.inTransaction(IndexerSQLMetadataStorageCoordinator.java:300) ~[druid-server-0.14.0-i
ap-pre5.jar:0.14.0-iap-pre5]
        at org.apache.druid.metadata.IndexerSQLMetadataStorageCoordinator$1.inTransaction(IndexerSQLMetadataStorageCoordinator.java:287) ~[druid-server-0.14.0-i
ap-pre5.jar:0.14.0-iap-pre5]
        at org.skife.jdbi.v2.tweak.transactions.LocalTransactionHandler.inTransaction(LocalTransactionHandler.java:184) ~[jdbi-2.63.1.jar:2.63.1]
        at org.skife.jdbi.v2.tweak.transactions.LocalTransactionHandler.inTransaction(LocalTransactionHandler.java:216) ~[jdbi-2.63.1.jar:2.63.1]
        at org.skife.jdbi.v2.BasicHandle.inTransaction(BasicHandle.java:350) ~[jdbi-2.63.1.jar:2.63.1]
        at org.skife.jdbi.v2.DBI$7.withHandle(DBI.java:357) ~[jdbi-2.63.1.jar:2.63.1]
        at org.skife.jdbi.v2.DBI.withHandle(DBI.java:281) ~[jdbi-2.63.1.jar:2.63.1]
        at org.skife.jdbi.v2.DBI.inTransaction(DBI.java:353) ~[jdbi-2.63.1.jar:2.63.1]
        at org.apache.druid.metadata.SQLMetadataConnector.lambda$retryTransaction$1(SQLMetadataConnector.java:148) ~[druid-server-0.14.0-iap-pre5.jar:0.14.0-iap
-pre5]
        at org.apache.druid.java.util.common.RetryUtils.retry(RetryUtils.java:86) ~[druid-core-0.14.0-iap-pre5.jar:0.14.0-iap-pre5]
        at org.apache.druid.java.util.common.RetryUtils.retry(RetryUtils.java:114) ~[druid-core-0.14.0-iap-pre5.jar:0.14.0-iap-pre5]
        at org.apache.druid.metadata.SQLMetadataConnector.retryTransaction(SQLMetadataConnector.java:148) ~[druid-server-0.14.0-iap-pre5.jar:0.14.0-iap-pre5]
        at org.apache.druid.metadata.IndexerSQLMetadataStorageCoordinator.announceHistoricalSegments(IndexerSQLMetadataStorageCoordinator.java:285) ~[druid-serv
er-0.14.0-iap-pre5.jar:0.14.0-iap-pre5]
        at org.apache.druid.indexing.common.actions.SegmentTransactionalInsertAction.lambda$perform$0(SegmentTransactionalInsertAction.java:115) ~[druid-indexin
g-service-0.14.0-iap-pre5.jar:0.14.0-iap-pre5]
        at org.apache.druid.indexing.overlord.CriticalAction.perform(CriticalAction.java:53) ~[druid-indexing-service-0.14.0-iap-pre5.jar:0.14.0-iap-pre5]
        at org.apache.druid.indexing.overlord.TaskLockbox.doInCriticalSection(TaskLockbox.java:627) ~[druid-indexing-service-0.14.0-iap-pre5.jar:0.14.0-iap-pre5
]
        at org.apache.druid.indexing.common.actions.SegmentTransactionalInsertAction.perform(SegmentTransactionalInsertAction.java:110) ~[druid-indexing-service
-0.14.0-iap-pre5.jar:0.14.0-iap-pre5]
        ... 75 more
```

**Comment by vachyuta** [comment]
Noticing similar issue with druid 0.14.2

2019-08-13 13:06:12,122 ERROR o.a.d.i.s.s.SeekableStreamSupervisor [KafkaSupervisor-az] SeekableStreamSupervisor[az] failed to handle notice: {class=org.apache.druid.indexing.seekablestream.supervisor.SeekableStreamSupervisor, exceptionType=class org.apache.druid.java.util.common.IAE, exceptionMessage=Expected instance of org.apache.druid.indexing.seekablestream.SeekableStreamEndSequenceNumbers, got org.apache.druid.indexing.seekablestream.SeekableStreamStartSequenceNumbers, noticeClass=ResetNotice}
org.apache.druid.java.util.common.IAE: Expected instance of org.apache.druid.indexing.seekablestream.SeekableStreamEndSequenceNumbers, got org.apache.druid.indexing.seekablestream.SeekableStreamStartSequenceNumbers
	at org.apache.druid.indexing.seekablestream.SeekableStreamEndSequenceNumbers.minus(SeekableStreamEndSequenceNumbers.java:159) ~[druid-indexing-service-0.14.2-incubating.jar:0.14.2-incubating]
	at org.apache.druid.indexing.seekablestream.SeekableStreamDataSourceMetadata.minus(SeekableStreamDataSourceMetadata.java:95) ~[druid-indexing-service-0.14.2-incubating.jar:0.14.2-incubating]
	at org.apache.druid.indexing.seekablestream.supervisor.SeekableStreamSupervisor.resetInternal(SeekableStreamSupervisor.java:1173) ~[druid-indexing-service-0.14.2-incubating.jar:0.14.2-incubating]
	at org.apache.druid.indexing.seekablestream.supervisor.SeekableStreamSupervisor$ResetNotice.handle(SeekableStreamSupervisor.java:331) ~[druid-indexing-service-0.14.2-incubating.jar:0.14.2-incubating]
	at org.apache.druid.indexing.seekablestream.supervisor.SeekableStreamSupervisor.lambda$tryInit$3(SeekableStreamSupervisor.java:750) ~[druid-indexing-service-0.14.2-incubating.jar:0.14.2-incubating]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_162]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_162]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]

**Comment by jihoonson** [comment]
Hi @vachyuta, your issue looks more like https://github.com/apache/incubator-druid/issues/7926 which is fixed in https://github.com/apache/incubator-druid/pull/8305. Would you please check it again once 0.16.0 comes out?
