### ISSUE TITLE
why so many littleEndByteBuff 

### ISSUE THREAD

**Issue by shizhengchao** [apache/incubator-druid#7485]
a large number of "littleEndByteBuff" log，causing OOM

### Affected Version
druid-0.13.0-incubating

### Description
```log
2019-04-14T08:15:02,242 INFO [fcbox_send-2019-04-13T00:00:00.000Z-persist-n-merge] org.apache.druid.segment.CompressedPools - Allocating new littleEndByteBuf[3,049]
2019-04-14T08:15:02,242 INFO [fcbox_send-2019-04-13T00:00:00.000Z-persist-n-merge] org.apache.druid.segment.CompressedPools - Allocating new littleEndByteBuf[3,050]
2019-04-14T08:15:02,242 INFO [fcbox_send-2019-04-13T00:00:00.000Z-persist-n-merge] org.apache.druid.segment.CompressedPools - Allocating new littleEndByteBuf[3,051]
2019-04-14T08:15:02,242 INFO [fcbox_send-2019-04-13T00:00:00.000Z-persist-n-merge] org.apache.druid.segment.CompressedPools - Allocating new littleEndByteBuf[3,052]
2019-04-14T08:15:02,242 INFO [fcbox_send-2019-04-13T00:00:00.000Z-persist-n-merge] org.apache.druid.segment.CompressedPools - Allocating new littleEndByteBuf[3,053]
2019-04-14T08:15:02,242 INFO [fcbox_send-2019-04-13T00:00:00.000Z-persist-n-merge] org.apache.druid.segment.CompressedPools - Allocating new littleEndByteBuf[3,054]
2019-04-14T08:15:02,242 INFO [fcbox_send-2019-04-13T00:00:00.000Z-persist-n-merge] org.apache.druid.segment.CompressedPools - Allocating new littleEndByteBuf[3,055]
2019-04-14T08:15:02,242 INFO [fcbox_send-2019-04-13T00:00:00.000Z-persist-n-merge] org.apache.druid.segment.CompressedPools - Allocating new littleEndByteBuf[3,056]
2019-04-14T08:15:02,242 INFO [fcbox_send-2019-04-13T00:00:00.000Z-persist-n-merge] org.apache.druid.segment.CompressedPools - Allocating new littleEndByteBuf[3,057]
2019-04-14T08:15:02,242 INFO [fcbox_send-2019-04-13T00:00:00.000Z-persist-n-merge] org.apache.druid.segment.CompressedPools - Allocating new littleEndByteBuf[3,058]
2019-04-14T08:15:02,242 INFO [fcbox_send-2019-04-13T00:00:00.000Z-persist-n-merge] org.apache.druid.segment.CompressedPools - Allocating new littleEndByteBuf[3,059]
Exception in thread "plumber_merge_0" java.lang.OutOfMemoryError: Direct buffer memory
	at java.nio.Bits.reserveMemory(Bits.java:658)
	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123)
	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)
	at org.apache.druid.segment.CompressedPools$4.get(CompressedPools.java:105)
	at org.apache.druid.segment.CompressedPools$4.get(CompressedPools.java:98)
	at org.apache.druid.collections.StupidPool.makeObjectWithHandler(StupidPool.java:116)
	at org.apache.druid.collections.StupidPool.take(StupidPool.java:107)
	at org.apache.druid.segment.CompressedPools.getByteBuf(CompressedPools.java:113)
	at org.apache.druid.segment.data.DecompressingByteBufferObjectStrategy.fromByteBuffer(DecompressingByteBufferObjectStrategy.java:49)
	at org.apache.druid.segment.data.DecompressingByteBufferObjectStrategy.fromByteBuffer(DecompressingByteBufferObjectStrategy.java:28)
	at org.apache.druid.segment.data.GenericIndexed$BufferIndexed.bufferedIndexedGet(GenericIndexed.java:444)
	at org.apache.druid.segment.data.GenericIndexed$2.get(GenericIndexed.java:599)
	at org.apache.druid.segment.data.BlockLayoutColumnarLongsSupplier$1.loadBuffer(BlockLayoutColumnarLongsSupplier.java:84)
	at org.apache.druid.segment.data.BlockLayoutColumnarLongsSupplier$1.get(BlockLayoutColumnarLongsSupplier.java:73)
	at org.apache.druid.segment.data.ColumnarLongs$1HistoricalLongColumnSelector.getLong(ColumnarLongs.java:60)
	at org.apache.druid.segment.QueryableIndexIndexableAdapter$RowIteratorImpl.setRowPointerValues(QueryableIndexIndexableAdapter.java:317)
	at org.apache.druid.segment.QueryableIndexIndexableAdapter$RowIteratorImpl.moveToNext(QueryableIndexIndexableAdapter.java:298)
	at org.apache.druid.segment.ForwardingRowIterator.moveToNext(ForwardingRowIterator.java:62)
	at org.apache.druid.segment.ForwardingRowIterator.moveToNext(ForwardingRowIterator.java:62)
	at org.apache.druid.segment.MergingRowIterator.lambda$new$0(MergingRowIterator.java:84)
	at java.util.stream.IntPipeline$9$1.accept(IntPipeline.java:343)
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:545)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:438)
	at org.apache.druid.segment.MergingRowIterator.<init>(MergingRowIterator.java:92)
	at org.apache.druid.segment.IndexMergerV9.makeMergedTimeAndDimsIterator(IndexMergerV9.java:1032)
	at org.apache.druid.segment.IndexMergerV9.makeIndexFiles(IndexMergerV9.java:180)
	at org.apache.druid.segment.IndexMergerV9.merge(IndexMergerV9.java:915)
	at org.apache.druid.segment.IndexMergerV9.mergeQueryableIndex(IndexMergerV9.java:833)
	at org.apache.druid.segment.IndexMergerV9.mergeQueryableIndex(IndexMergerV9.java:811)
	at org.apache.druid.segment.realtime.plumber.RealtimePlumber$2.doRun(RealtimePlumber.java:433)
	at org.apache.druid.common.guava.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

As you see, nearly 3,060 "littleEndByteBuf", and my task OOM

**Comment by shizhengchao** [comment]
this is my realtime task json:
{
  "dataSources": [
    {
      "spec": {
        "dataSchema": {
          "dataSource": "fcbox_send",
          "metricsSpec": [
            { "type" : "count", "name" : "count" },
            { "type" : "longSum", "fieldName" : "order_count", "name" : "order_count" },
            { "type" : "longSum", "fieldName" : "drop_send_count", "name" : "drop_send_count" },
            { "type" : "longSum", "fieldName" : "staff_get_count", "name" : "staff_get_count" },
            { "type" : "longSum", "fieldName" : "in_flight_count", "name" : "in_flight_count" },
            { "type" : "longSum", "fieldName" : "cancel_count", "name" : "cancel_count" }
          ],
          "granularitySpec": {
            "type": "uniform",
            "segmentGranularity": "day",
            "queryGranularity": "none",
            "rollup": false
          },
          "parser": {
            "type": "map",
            "parseSpec": {
              "format": "json",
              "timestampSpec": {
                "column": "timestamp",
                "format": "auto"
              },
              "dimensionsSpec": {
                "dimensions": [
                  "order_time",
                  "client_post_time",
                  "staff_get_time",
                  "in_flight_time",
                  "cancel_time",
                  "send_status",
                  "dis_code",
                  "company_id",
                  "source_type",
                  "box_type",
                  "throw_area_type"
                ]
              }
            }
          }
        },
        "tuningConfig": {
          "type" : "realtime",
          "windowPeriod" : "PT10M",
          "intermediatePersistPeriod" : "PT5M",
          "maxRowsInMemory" : 250000
        },
        "properties" : {
          "task.partitions" : "1",
          "task.replicants" : "2"
        }
      }
    }
  ]
}

**Comment by shizhengchao** [comment]
MiddleManager jvm config and runtime config:
```
-server
-Xms128m
-Xmx128m
-Duser.timezone=UTC+0800
-Dfile.encoding=UTF-8
-Dhadoop.hadoop.tmp.dir=/data/druid/hadoop-tmp
-Djava.io.tmpdir=/data/druid/tmp
-Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager


druid.service=druid/middlemanager
druid.port=8091

# Number of tasks per middleManager
druid.worker.capacity=15

# Task launch parameters
druid.indexer.runner.javaOpts=-server -Xmx2g -Duser.timezone=UTC+0800 -Dfile.encoding=UTF-8 -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager
druid.indexer.task.baseTaskDir=/data/druid/task
druid.indexer.task.restoreTasksOnRestart=true

# HTTP server threads
druid.server.http.numThreads=40

# Processing threads and buffers
druid.processing.buffer.sizeBytes=100000000
druid.processing.numMergeBuffers=2
druid.processing.numThreads=15
druid.processing.tmpDir=/data/druid/middlemanager-processing

# Hadoop indexing
druid.indexer.task.hadoopWorkingPath=/druid/hadoop-tmp
druid.indexer.task.defaultHadoopCoordinates=["org.apache.hadoop:hadoop-client:2.8.3", "org.apache.hadoop:hadoop-aws:2.8.3"]

```

**Comment by shizhengchao** [comment]
Is my Peno memory configuration too small?(Forgive my English level....)

**Comment by dutta1kartik3** [comment]
@shizhengchao How did you solve this issue ?

**Comment by JackyYangPassion** [comment]
is there in realtime ingest with many query? or how many data?

**Comment by merilonline** [comment]
How did you fix this issue? Can you share the specific memory configs.? I am also facing similar issue

**Comment by shizhengchao** [comment]
> How did you fix this issue? Can you share the specific memory configs.? I am also facing similar issue

 `Peno` memory configuration too small, and after increasing the peno memory, it works good

**Comment by himanshug** [comment]
haven't looked at the discussion here but https://github.com/apache/incubator-druid/issues/7824 might be related
