### ISSUE TITLE
When permissions are enabled, Datasources permissions are displayed differently on the Router and Coordinator Console

### ISSUE THREAD

**Issue by cttq-wubin** [apache/incubator-druid#7565]
### Affected Version

0.14.0

### Description
Hello Everyone :  
403 error occurred when I enabled permission validation, Who can tell me how to configure it!
thank you !

My configuration is as follows:

druid-basic-security:
![aa](https://user-images.githubusercontent.com/31197733/56861998-fe313180-69d8-11e9-8f49-c98134aeafab.png)

perms.json
![pp](https://user-images.githubusercontent.com/31197733/56862021-202ab400-69d9-11e9-9ed6-e1fbdc591eef.png)

Router Console
![nn](https://user-images.githubusercontent.com/31197733/56862041-494b4480-69d9-11e9-99cb-14819b04691a.png)

Legacy Consoles
![cc](https://user-images.githubusercontent.com/31197733/56862049-5a945100-69d9-11e9-88c9-9d2be3e1b8a0.png)

**Comment by vogievetsky** [comment]
This seems to be directly related to https://github.com/apache/incubator-druid/issues/7563

**Comment by cttq-wubin** [comment]
> This seems to be directly related to #7563
@vogievetsky 
Thank you for your answer, this problem has been resolved!
However, another error occurred when I used this account to connect to BI via JDBC, There is no error if the account is admin!

The connection information:
org.apache.calcite.avatica.remote.Driver
jdbc:avatica:remote:url=http://BROKER:8082/druid/v2/sql/avatica/

The error message is as follows:

org.apache.druid.server.security.ForbiddenException: Allowed:false, Message:
	at org.apache.druid.sql.SqlLifecycle.planAndAuthorize(SqlLifecycle.java:212)
	at org.apache.druid.sql.avatica.DruidStatement.prepare(DruidStatement.java:156)
	at org.apache.druid.sql.avatica.DruidMeta.prepareAndExecute(DruidMeta.java:191)
	at org.apache.druid.sql.avatica.DruidMeta.sqlResultSet(DruidMeta.java:616)
	at org.apache.druid.sql.avatica.DruidMeta.getTableTypes(DruidMeta.java:507)
	at org.apache.calcite.avatica.remote.LocalService.apply(LocalService.java:167)
	at org.apache.calcite.avatica.remote.Service$TableTypesRequest.accept(Service.java:525)
	at org.apache.calcite.avatica.remote.Service$TableTypesRequest.accept(Service.java:510)
	at org.apache.calcite.avatica.remote.AbstractHandler.apply(AbstractHandler.java:94)
	at org.apache.calcite.avatica.remote.JsonHandler.apply(JsonHandler.java:52)
	at org.apache.calcite.avatica.server.AvaticaJsonHandler.handle(AvaticaJsonHandler.java:130)
	at org.apache.druid.sql.avatica.DruidAvaticaHandler.handle(DruidAvaticaHandler.java:59)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:169)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:531)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:760)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:678)
	at java.lang.Thread.run(Thread.java:748)
