### ISSUE TITLE
druid-bloom-filter could not work

### ISSUE THREAD

**Issue by shizhengchao** [apache/incubator-druid#7580]
the extensions 'druid-bloom-filter' can not work

### Affected Version
0.14.0

### Description
When is user BLOOM_FILTER in my sql: `SELECT BLOOM_FILTER(bar, 10000) FROM "kafka-test"` 
i get the error message:
`Unknown exception / [B cannot be cast to org.apache.druid.query.filter.BloomKFilter / java.lang.ClassCastException`

`
java.lang.ClassCastException: [B cannot be cast to org.apache.druid.query.filter.BloomKFilter
	at org.apache.druid.query.aggregation.bloom.BloomFilterAggregatorFactory.combine(BloomFilterAggregatorFactory.java:171) ~[?:?]
	at org.apache.druid.query.timeseries.TimeseriesBinaryFn.apply(TimeseriesBinaryFn.java:67) ~[druid-processing-0.14.0-incubating.jar:0.14.0-incubating]
	at org.apache.druid.query.timeseries.TimeseriesBinaryFn.apply(TimeseriesBinaryFn.java:34) ~[druid-processing-0.14.0-incubating.jar:0.14.0-incubating]
	at org.apache.druid.common.guava.CombiningSequence$CombiningYieldingAccumulator.accumulate(CombiningSequence.java:210) ~[druid-core-0.14.0-incubating.jar:0.14.0-incubating]
	at org.apache.druid.java.util.common.guava.MergeSequence.makeYielder(MergeSequence.java:106) ~[druid-core-0.14.0-incubating.jar:0.14.0-incubating]
	at org.apache.druid.java.util.common.guava.MergeSequence.toYielder(MergeSequence.java:94) ~[druid-core-0.14.0-incubating.jar:0.14.0-incubating]
	at org.apache.druid.java.util.common.guava.LazySequence.toYielder(LazySequence.java:46) ~[druid-core-0.14.0-incubating.jar:0.14.0-incubating]
	at org.apache.druid.query.RetryQueryRunner$1.toYielder(RetryQueryRunner.java:97) ~[druid-processing-0.14.0-incubating.jar:0.14.0-incubating]
	at org.apache.druid.common.guava.CombiningSequence.toYielder(CombiningSequence.java:79) ~[druid-core-0.14.0-incubating.jar:0.14.0-incubating]
	at org.apache.druid.java.util.common.guava.MappedSequence.toYielder(MappedSequence.java:49) ~[druid-core-0.14.0-incubating.jar:0.14.0-incubating]
	at org.apache.druid.java.util.common.guava.WrappingSequence$2.get(WrappingSequence.java:87) ~[druid-core-0.14.0-incubating.jar:0.14.0-incubating]
	at org.apache.druid.java.util.common.guava.WrappingSequence$2.get(WrappingSequence.java:83) ~[druid-core-0.14.0-incubating.jar:0.14.0-incubating]
	at org.apache.druid.query.CPUTimeMetricQueryRunner$1.wrap(CPUTimeMetricQueryRunner.java:74) ~[druid-processing-0.14.0-incubating.jar:0.14.0-incubating]
	at org.apache.druid.java.util.common.guava.WrappingSequence.toYielder(WrappingSequence.java:82) ~[druid-core-0.14.0-incubating.jar:0.14.0-incubating]
	at org.apache.druid.java.util.common.guava.WrappingSequence$2.get(WrappingSequence.java:87) ~[druid-core-0.14.0-incubating.jar:0.14.0-incubating]
	at org.apache.druid.java.util.common.guava.WrappingSequence$2.get(WrappingSequence.java:83) ~[druid-core-0.14.0-incubating.jar:0.14.0-incubating]
	at org.apache.druid.java.util.common.guava.SequenceWrapper.wrap(SequenceWrapper.java:55) ~[druid-core-0.14.0-incubating.jar:0.14.0-incubating]
	at org.apache.druid.java.util.common.guava.WrappingSequence.toYielder(WrappingSequence.java:82) ~[druid-core-0.14.0-incubating.jar:0.14.0-incubating]
	at org.apache.druid.java.util.common.guava.MappedSequence.toYielder(MappedSequence.java:49) ~[druid-core-0.14.0-incubating.jar:0.14.0-incubating]
	at org.apache.druid.java.util.common.guava.Yielders.each(Yielders.java:32) ~[druid-core-0.14.0-incubating.jar:0.14.0-incubating]
	at org.apache.druid.sql.http.SqlResource.doPost(SqlResource.java:109) [druid-sql-0.14.0-incubating.jar:0.14.0-incubating]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_65]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_65]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_65]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_65]
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60) [jersey-server-1.19.3.jar:1.19.3]
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205) [je
`

**Comment by clintropolis** [comment]
This should be fixed by #7496 which will be released in 0.14.1-incubating, currently under vote, with any luck to be released sometime later this week.

**Comment by shizhengchao** [comment]
thank you
