### ISSUE TITLE
How to Enable HistoricalMetricsMonitor、QueryCountStatsMonitor metric for Historical 、Middle Manager ；Because I started both Historical and Middle Manager processes on the same node

### ISSUE THREAD

**Issue by DockerLive** [apache/incubator-druid#7623]
When I configured the monitors for the following：
druid.monitoring.monitors=["org.apache.druid.server.metrics.HistoricalMetricsMonitor",
"org.apache.druid.server.metrics.QueryCountStatsMonitor",
"org.apache.druid.server.metrics.EventReceiverFirehoseMonitor"]

The process could not start. The exception is shown below：
Exception in thread "main" com.google.inject.CreationException: Guice creation errors:
1) No implementation for io.druid.client.cache.Cache was bound.
  while locating io.druid.client.cache.Cache
    for parameter 6 at io.druid.server.coordination.ServerManager.<init>(ServerManager.java:106)
  while locating io.druid.server.coordination.ServerManager
    for parameter 1 at io.druid.server.metrics.HistoricalMetricsMonitor.<init>(HistoricalMetricsMonitor.java:42)
  while locating io.druid.server.metrics.HistoricalMetricsMonitor
  at io.druid.server.metrics.MetricsModule.getMonitorScheduler(MetricsModule.java:90)
  at io.druid.server.metrics.MetricsModule.getMonitorScheduler(MetricsModule.java:90)
  while locating com.metamx.metrics.MonitorScheduler
  at io.druid.server.metrics.MetricsModule.configure(MetricsModule.java:75)
  while locating com.metamx.metrics.MonitorScheduler annotated with @com.google.inject.name.Named(value=ForTheEagerness)

1 error
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:448)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:184)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
        at com.google.inject.Guice.createInjector(Guice.java:96)
        at com.google.inject.Guice.createInjector(Guice.java:73)
        at com.google.inject.Guice.createInjector(Guice.java:62)
        at io.druid.initialization.Initialization.makeInjectorWithModules(Initialization.java:324)
        at io.druid.cli.GuiceRunnable.makeInjector(GuiceRunnable.java:60)
        at io.druid.cli.ServerRunnable.run(ServerRunnable.java:39)
        at io.druid.cli.Main.main(Main.java:105)

Exception in thread "main" com.google.inject.CreationException: Unable to create injector, see the following errors:

1) No implementation for org.apache.druid.server.metrics.QueryCountStatsProvider was bound.
  while locating org.apache.druid.server.metrics.QueryCountStatsProvider
    for the 1st parameter of org.apache.druid.server.metrics.QueryCountStatsMonitor.<init>(QueryCountStatsMonitor.java:40)
  while locating org.apache.druid.server.metrics.QueryCountStatsMonitor
  at org.apache.druid.server.metrics.MetricsModule.getMonitorScheduler(MetricsModule.java:92) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.server.metrics.MetricsModule)
  at org.apache.druid.server.metrics.MetricsModule.getMonitorScheduler(MetricsModule.java:92) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.server.metrics.MetricsModule)
  while locating org.apache.druid.java.util.metrics.MonitorScheduler
  at org.apache.druid.server.metrics.MetricsModule.configure(MetricsModule.java:77) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.server.metrics.MetricsModule)
  while locating org.apache.druid.java.util.metrics.MonitorScheduler annotated with @com.google.inject.name.Named(value=ForTheEagerness)

1 error
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:184)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
        at com.google.inject.Guice.createInjector(Guice.java:99)
        at com.google.inject.Guice.createInjector(Guice.java:73)
        at com.google.inject.Guice.createInjector(Guice.java:62)
        at org.apache.druid.initialization.Initialization.makeInjectorWithModules(Initialization.java:422)
        at org.apache.druid.cli.GuiceRunnable.makeInjector(GuiceRunnable.java:69)
        at org.apache.druid.cli.ServerRunnable.run(ServerRunnable.java:57)
        at org.apache.druid.cli.Main.main(Main.java:118)

**Comment by prabakarankrishnan** [comment]
I am also getting same error in Druid 0.14.0 version... Any update

**Comment by DockerLive** [comment]
I solved this problem, but it's not a problem because we misunderstand our own configuration

The configuration unique to each role should be configured in the "runtime.properties" file of the corresponding role.And the public monitor similar to "JvmMonitor" needs to be added to the role profile, otherwise the common configuration will be overridden by the "runtime.properties" configuration

**Comment by terry19850829** [comment]
Misunderstand too

**Comment by vinaygulani1** [comment]
@terry19850829 @DockerLive - I am also getting the same error with version 0.16.1 while enabling "TaskCountStatsMonitor, QueryCountStatsMonitor" metrics. Tried to enable it on Broker/Middlemanager & historical hosts both services failing with same error mentioned in this ticket.
I have also tried updating "druid.monitoring.monitors" in both common and role specific runtime.properties files, still same error. Any suggestions on this will be really helpful. Thanks

**Comment by terry19850829** [comment]
@vinaygulani1 Configuration is corresponding to the server role. 

This is my **historical** server config:

`druid.monitoring.monitors=["org.apache.druid.client.cache.CacheMonitor", "org.apache.druid.java.util.metrics.SysMonitor", "org.apache.druid.java.util.metrics.JvmMonitor", "org.apache.druid.java.util.metrics.JvmCpuMonitor", "org.apache.druid.java.util.metrics.CpuAcctDeltaMonitor", "org.apache.druid.java.util.metrics.JvmThreadsMonitor", "org.apache.druid.server.metrics.QueryCountStatsMonitor", "org.apache.druid.server.metrics.HistoricalMetricsMonitor"]`

and this is my **broker** config:

`druid.monitoring.monitors=["org.apache.druid.client.cache.CacheMonitor", "org.apache.druid.java.util.metrics.SysMonitor", "org.apache.druid.java.util.metrics.JvmMonitor", "org.apache.druid.java.util.metrics.JvmCpuMonitor", "org.apache.druid.java.util.metrics.CpuAcctDeltaMonitor", "org.apache.druid.java.util.metrics.JvmThreadsMonitor", "org.apache.druid.server.metrics.QueryCountStatsMonitor"]`

Config above will be worked. Some Metrics needs sigar, so you should install it.

https://stackoverflow.com/questions/21894128/how-to-install-sigar-on-ubuntu-based-linux/21894613

**Comment by partomia09** [comment]
@terry19850829 

QueryCountStats worked perfectly using the above config.
We did not install Sigar and we tested the configs, its still working fine. Do you suggest to install Sigar still?

**Comment by partomia09** [comment]
@terry19850829 
I figured that Sigar is required only for MiddleManager. 

Thanks Again!

**Comment by terry19850829** [comment]
@partomia09  ok. Some metric depend on the sigar. You can skip it if you don't need those metrics.

**Comment by nttoan26** [comment]
same issue, I do think this is a document defect, since it does not tell which one should be enabled on which process
```

Name | Description
-- | --
org.apache.druid.client.cache.CacheMonitor | Emits metrics (to logs) about the segment results cache for Historical and Broker processes. Reports typical cache statistics include hits, misses, rates, and size (bytes and number of entries), as well as timeouts and and errors.
org.apache.druid.java.util.metrics.SysMonitor | This uses the&nbsp;SIGAR library&nbsp;to report on various system activities and statuses.
org.apache.druid.server.metrics.HistoricalMetricsMonitor | Reports statistics on Historical processes.
org.apache.druid.java.util.metrics.JvmMonitor | Reports various JVM-related statistics.
org.apache.druid.java.util.metrics.JvmCpuMonitor | Reports statistics of CPU consumption by the JVM.
org.apache.druid.java.util.metrics.CpuAcctDeltaMonitor | Reports consumed CPU as per the cpuacct cgroup.
org.apache.druid.java.util.metrics.JvmThreadsMonitor | Reports Thread statistics in the JVM, like numbers of total, daemon, started, died threads.
org.apache.druid.segment.realtime.RealtimeMetricsMonitor | Reports statistics on Realtime processes.
org.apache.druid.server.metrics.EventReceiverFirehoseMonitor | Reports how many events have been queued in the EventReceiverFirehose.
org.apache.druid.server.metrics.QueryCountStatsMonitor | Reports how many queries have been successful/failed/interrupted.
org.apache.druid.server.emitter.HttpEmittingMonitor | Reports internal metrics of&nbsp;http&nbsp;or&nbsp;parametrized&nbsp;emitter (see below). Must not be used with another emitter type. See the description of the metrics here:&nbsp;https://github.com/apache/druid/pull/4973.
org.apache.druid.server.metrics.TaskCountStatsMonitor | Reports how many ingestion tasks are currently running/pending/waiting and also the number of successful/failed tasks per emission period.


```

**Comment by ZhanHui-Xu** [comment]
> @vinaygulani1 Configuration is corresponding to the server role.
> 
> This is my **historical** server config:
> 
> `druid.monitoring.monitors=["org.apache.druid.client.cache.CacheMonitor", "org.apache.druid.java.util.metrics.SysMonitor", "org.apache.druid.java.util.metrics.JvmMonitor", "org.apache.druid.java.util.metrics.JvmCpuMonitor", "org.apache.druid.java.util.metrics.CpuAcctDeltaMonitor", "org.apache.druid.java.util.metrics.JvmThreadsMonitor", "org.apache.druid.server.metrics.QueryCountStatsMonitor", "org.apache.druid.server.metrics.HistoricalMetricsMonitor"]`
> 
> and this is my **broker** config:
> 
> `druid.monitoring.monitors=["org.apache.druid.client.cache.CacheMonitor", "org.apache.druid.java.util.metrics.SysMonitor", "org.apache.druid.java.util.metrics.JvmMonitor", "org.apache.druid.java.util.metrics.JvmCpuMonitor", "org.apache.druid.java.util.metrics.CpuAcctDeltaMonitor", "org.apache.druid.java.util.metrics.JvmThreadsMonitor", "org.apache.druid.server.metrics.QueryCountStatsMonitor"]`
> 
> Config above will be worked. Some Metrics needs sigar, so you should install it.
> 
> https://stackoverflow.com/questions/21894128/how-to-install-sigar-on-ubuntu-based-linux/21894613

hi, bro, how to configure middle manager runtime config

**Comment by srinisuryadevara** [comment]
For middle manager metrics I'm using push gateway.  From push gateway Prometheus would able to scrap metrics
