### ISSUE TITLE
Possible invalid read issue with GroupBy V2 spilled dictionaries

### ISSUE THREAD

**Issue by jon-wei** [apache/incubator-druid#7690]
### Affected Version

0.13.0

### Description

A user reported seeing issues when using a GroupBy V2 query: https://groups.google.com/forum/#!topic/druid-user/uM690lhVo7k

```
2019-05-08T21:16:35,187 ERROR [qtp269685385-140[groupBy_[(redacted)]] org.apache.druid.server.QueryResource - Exception handling request: {class=org.apache.druid.server.QueryResource, exceptionType=class com.fasterxml.jackson.databind.RuntimeJsonMappingException, exceptionMessage=Can not deserialize instance of java.lang.String out of VALUE_NULL token
 at [Source: LZ4BlockInputStream(in=java.io.FileInputStream@5441412, decompressor=LZ4JNIFastDecompressor, checksum=StreamingXXHash32JNI(seed=-1756908916)); line: -1, column: 1259], exception=com.fasterxml.jackson.databind.RuntimeJsonMappingException: Cannot deserialize instance of java.lang.String out of VALUE_NULL token at [Source: LZ4BlockInputStream(in=java.io.FileInputStream@5441412, decompressor=LZ4JNIFastDecompressor, checksum=StreamingXXHash32JNI(seed=-1756908916)); line: -1, column: 1259], query=GroupByQuery{dataSource='(redacted)', querySegmentSpec=MultipleSpecificSegmentSpec{descriptors=[SegmentDescriptor{interval=2019-05-01T00:00:00.000Z/2019-05-05T00:00:00.000Z, version='2019-05-08T12:01:15.823Z', partitionNumber=0}]}, virtualColumns=[], limitSpec=NoopLimitSpec, dimFilter=((redacted)}
com.fasterxml.jackson.databind.RuntimeJsonMappingException: Can not deserialize instance of java.lang.String out of VALUE_NULL token
 at [Source: LZ4BlockInputStream(in=java.io.FileInputStream@5441412, decompressor=LZ4JNIFastDecompressor, checksum=StreamingXXHash32JNI(seed=-1756908916)); line: -1, column: 1259]
        at com.fasterxml.jackson.databind.MappingIterator.next(MappingIterator.java:194) ~[jackson-databind-2.6.7.jar:2.6.7]
        at org.apache.druid.query.groupby.epinephelinae.SpillingGrouper.mergeAndGetDictionary(SpillingGrouper.java:223) ~[druid-processing-0.13.0-incubating.jar:0.13.0-incubating]
        at org.apache.druid.query.groupby.epinephelinae.ConcurrentGrouper.tryMergeDictionary(ConcurrentGrouper.java:392) ~[druid-processing-0.13.0-incubating.jar:0.13.0-incubating]
        at org.apache.druid.query.groupby.epinephelinae.ConcurrentGrouper.iterator(ConcurrentGrouper.java:320) ~[druid-processing-0.13.0-incubating.jar:0.13.0-incubating]
        at org.apache.druid.query.groupby.epinephelinae.CloseableGrouperIterator.<init>(CloseableGrouperIterator.java:44) ~[druid-processing-0.13.0-incubating.jar:0.13.0-incubating]
        at org.apache.druid.query.groupby.epinephelinae.RowBasedGrouperHelper.makeGrouperIterator(RowBasedGrouperHelper.java:426) ~[druid-processing-0.13.0-incubating.jar:0.13.0-incubating]
        at org.apache.druid.query.groupby.epinephelinae.RowBasedGrouperHelper.makeGrouperIterator(RowBasedGrouperHelper.java:414) ~[druid-processing-0.13.0-incubating.jar:0.13.0-incubating]
        at org.apache.druid.query.groupby.epinephelinae.GroupByMergingQueryRunnerV2$1.make(GroupByMergingQueryRunnerV2.java:282) ~[druid-processing-0.13.0-incubating.jar:0.13.0-incubating]
        at org.apache.druid.query.groupby.epinephelinae.GroupByMergingQueryRunnerV2$1.make(GroupByMergingQueryRunnerV2.java:158) ~[druid-processing-0.13.0-incubating.jar:0.13.0-incubating]
        at org.apache.druid.java.util.common.guava.BaseSequence.toYielder(BaseSequence.java:64) ~[java-util-0.13.0-incubating.jar:0.13.0-incubating]
        at org.apache.druid.common.guava.CombiningSequence.toYielder(CombiningSequence.java:80) ~[druid-common-0.13.0-incubating.jar:0.13.0-incubating]
```

From the stack trace, it looks like invalid data is possibly being read/written from the on-disk spilled dictionaries.

**Comment by hienduyph** [comment]
Same error when I set `druid.query.groupBy.numParallelCombineThreads` greater than `1`

**Comment by vikramarsid** [comment]
@jon-wei Any update on this issue? I see the same error with `druid.query.groupBy.numParallelCombineThreads` > 1

```
2021-02-12T05:28:08,963 WARN [sql[da01c505-69db-4ffd-8a42-77a020c9d460]] org.apache.druid.server.QueryLifecycle - Exception while processing queryId [7cd2d9df-c948-43ed-8447-9b287d64d1cf] (QueryInterruptedException{msg=Cannot deserialize instance of `java.lang.String` out of VALUE_NULL token
 at [Source: (net.jpountz.lz4.LZ4BlockInputStream); line: -1, column: 114], code=Unknown exception, class=com.fasterxml.jackson.databind.RuntimeJsonMappingException, host=10.219.97.69:8083})
2021-02-12T05:28:08,963 WARN [sql[da01c505-69db-4ffd-8a42-77a020c9d460]] org.apache.druid.sql.http.SqlResource - Failed to handle query: SqlQuery{query='SELECT a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, sum("a11") AS total_count,  min(__time) as first_, max(__time) as last_, count(DISTINCT a12) as unique_ac_count
FROM hashes WHERE (a3 <> '' OR a4 <> '' OR a5 <> '') AND __time BETWEEN '2020-12-01T00:00:00.000Z' AND '2020-12-02T23:59:59.000Z'
GROUP BY a1, a2, a3, a4, a5, a6, a7, a8, a9, a10
HAVING count(DISTINCT a12) <2', resultFormat=ARRAY, header=true, context={}, parameters=[]}
org.apache.druid.query.QueryInterruptedException: Cannot deserialize instance of `java.lang.String` out of VALUE_NULL token
 at [Source: (net.jpountz.lz4.LZ4BlockInputStream); line: -1, column: 114]
	at org.apache.druid.client.JsonParserIterator.interruptQuery(JsonParserIterator.java:197) ~[druid-server-0.20.1.jar:0.20.1]
	at org.apache.druid.client.JsonParserIterator.init(JsonParserIterator.java:176) ~[druid-server-0.20.1.jar:0.20.1]
	at org.apache.druid.client.JsonParserIterator.hasNext(JsonParserIterator.java:89) ~[druid-server-0.20.1.jar:0.20.1]
	at org.apache.druid.java.util.common.guava.BaseSequence.makeYielder(BaseSequence.java:89) ~[druid-core-0.20.1.jar:0.20.1]
	at org.apache.druid.java.util.common.guava.BaseSequence.toYielder(BaseSequence.java:69) ~[druid-core-0.20.1.jar:0.20.1]
	at org.apache.druid.java.util.common.guava.MappedSequence.toYielder(MappedSequence.java:49) ~[druid-core-0.20.1.jar:0.20.1]
	at org.apache.druid.java.util.common.guava.ParallelMergeCombiningSequence$ResultBatch.fromSequence(ParallelMergeCombiningSequence.java:869) ~[druid-core-0.20.1.jar:0.20.1]
	at org.apache.druid.java.util.common.guava.ParallelMergeCombiningSequence$SequenceBatcher.block(ParallelMergeCombiningSequence.java:920) ~[druid-core-0.20.1.jar:0.20.1]
	at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3313) ~[?:1.8.0_282]
	at org.apache.druid.java.util.common.guava.ParallelMergeCombiningSequence$SequenceBatcher.getBatchYielder(ParallelMergeCombiningSequence.java:909) ~[druid-core-0.20.1.jar:0.20.1]
	at org.apache.druid.java.util.common.guava.ParallelMergeCombiningSequence$YielderBatchedResultsCursor.initialize(ParallelMergeCombiningSequence.java:1017) ~[druid-core-0.20.1.jar:0.20.1]
	at org.apache.druid.java.util.common.guava.ParallelMergeCombiningSequence$PrepareMergeCombineInputsAction.compute(ParallelMergeCombiningSequence.java:721) ~[druid-core-0.20.1.jar:0.20.1]
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189) ~[?:1.8.0_282]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_282]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_282]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_282]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) ~[?:1.8.0_282]
Caused by: org.apache.druid.query.QueryInterruptedException: Cannot deserialize instance of `java.lang.String` out of VALUE_NULL token
 at [Source: (net.jpountz.lz4.LZ4BlockInputStream); line: -1, column: 114]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_282]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_282]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_282]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_282]
	at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:124) ~[jackson-databind-2.10.5.1.jar:2.10.5.1]
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:283) ~[jackson-databind-2.10.5.1.jar:2.10.5.1]
	at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromObjectWith(ValueInstantiator.java:229) ~[jackson-databind-2.10.5.1.jar:2.10.5.1]
	at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:198) ~[jackson-databind-2.10.5.1.jar:2.10.5.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:422) ~[jackson-databind-2.10.5.1.jar:2.10.5.1]
	at com.fasterxml.jackson.databind.deser.std.ThrowableDeserializer.deserializeFromObject(ThrowableDeserializer.java:65) ~[jackson-databind-2.10.5.1.jar:2.10.5.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159) ~[jackson-databind-2.10.5.1.jar:2.10.5.1]
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4189) ~[jackson-databind-2.10.5.1.jar:2.10.5.1]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2476) ~[jackson-databind-2.10.5.1.jar:2.10.5.1]
	... 16 more
2021-02-12T05:28:48,994 WARN [ForkJoinPool-1-worker-1] org.apache.druid.client.JsonParserIterator - Query [7f2609f7-8a90-49e2-a8b0-17c48a1dfc3a] to host [1.1.1.1:8083] interrupted
org.apache.druid.query.QueryInterruptedException: Cannot deserialize instance of `java.lang.String` out of VALUE_NULL token
 at [Source: (net.jpountz.lz4.LZ4BlockInputStream); line: -1, column: 114]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_282]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_282]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_282]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_282]
	at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:124) ~[jackson-databind-2.10.5.1.jar:2.10.5.1]
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:283) ~[jackson-databind-2.10.5.1.jar:2.10.5.1]
	at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromObjectWith(ValueInstantiator.java:229) ~[jackson-databind-2.10.5.1.jar:2.10.5.1]
	at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:198) ~[jackson-databind-2.10.5.1.jar:2.10.5.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:422) ~[jackson-databind-2.10.5.1.jar:2.10.5.1]
	at com.fasterxml.jackson.databind.deser.std.ThrowableDeserializer.deserializeFromObject(ThrowableDeserializer.java:65) ~[jackson-databind-2.10.5.1.jar:2.10.5.1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159) ~[jackson-databind-2.10.5.1.jar:2.10.5.1]
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4189) ~[jackson-databind-2.10.5.1.jar:2.10.5.1]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2476) ~[jackson-databind-2.10.5.1.jar:2.10.5.1]
	at org.apache.druid.client.JsonParserIterator.init(JsonParserIterator.java:176) [druid-server-0.20.1.jar:0.20.1]
	at org.apache.druid.client.JsonParserIterator.hasNext(JsonParserIterator.java:89) [druid-server-0.20.1.jar:0.20.1]
	at org.apache.druid.java.util.common.guava.BaseSequence.makeYielder(BaseSequence.java:89) [druid-core-0.20.1.jar:0.20.1]
	at org.apache.druid.java.util.common.guava.BaseSequence.toYielder(BaseSequence.java:69) [druid-core-0.20.1.jar:0.20.1]
	at org.apache.druid.java.util.common.guava.MappedSequence.toYielder(MappedSequence.java:49) [druid-core-0.20.1.jar:0.20.1]
	at org.apache.druid.java.util.common.guava.ParallelMergeCombiningSequence$ResultBatch.fromSequence(ParallelMergeCombiningSequence.java:869) [druid-core-0.20.1.jar:0.20.1]
	at org.apache.druid.java.util.common.guava.ParallelMergeCombiningSequence$SequenceBatcher.block(ParallelMergeCombiningSequence.java:920) [druid-core-0.20.1.jar:0.20.1]
	at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3313) [?:1.8.0_282]
	at org.apache.druid.java.util.common.guava.ParallelMergeCombiningSequence$SequenceBatcher.getBatchYielder(ParallelMergeCombiningSequence.java:909) [druid-core-0.20.1.jar:0.20.1]
	at org.apache.druid.java.util.common.guava.ParallelMergeCombiningSequence$YielderBatchedResultsCursor.initialize(ParallelMergeCombiningSequence.java:1017) [druid-core-0.20.1.jar:0.20.1]
	at org.apache.druid.java.util.common.guava.ParallelMergeCombiningSequence$PrepareMergeCombineInputsAction.compute(ParallelMergeCombiningSequence.java:721) [druid-core-0.20.1.jar:0.20.1]
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189) [?:1.8.0_282]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_282]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_282]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_282]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) [?:1.8.0_282]



```

**Comment by vikramarsid** [comment]
It is failing at this point

https://github.com/apache/druid/blob/b3325c160171f8a91972b5590c481cb121e58eae/core/src/main/java/org/apache/druid/java/util/common/guava/BaseSequence.java#L89

**Comment by vikramarsid** [comment]
@jihoonson  @clintropolis Please let us know if there is any workaround for this issue. Thank you in advance.

**Comment by xiaoDjun** [comment]
@jihoonson @clintropolis hi, any update on this issue? Please let us know : ). Thanks.
