### ISSUE TITLE
Kafka indexing of Avro topic fails with java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by AndriiSushko** [apache/incubator-druid#7702]
### Affected Version
0.14.1, 0.13.0

### Description
- Druid is up and running: 
 _./apache-druid-0.14.1-incubating/bin/supervise -c apache-druid-0.14.1-incubating/quickstart/tutorial/conf/tutorial-cluster.conf_

- druid-avro-extensions is included as an extension. 

- Supervisor submitted:  
_curl -X POST -H 'Content-Type: application/json' -d @configKafka.json http://localhost:8090/druid/indexer/v1/supervisor_

with following configKafka.json:

`{
	"type": "kafka",
	"dataSchema": {
		"dataSource": "teststream",
		"parser": {
			"type": "avro_stream",
			"avroBytesDecoder": {
				"type": "schema_inline",
				"schema": {
					"namespace": "io.druid.data",
					"name": "User",
					"type": "record",
					"fields": [
                        {
							"name": "f1",
							"type": "string"
						},
						{
							"name": "timestamp",
							"type": "long"
						},
						{
							"name": "f2",
							"type": "int"
						}
					]
				}
			},
			"parseSpec": {
				"format": "timeAndDims",
				"timestampSpec": {
					"column": "timestamp",
					"format": "auto"
				},
				"dimensionsSpec": {
					"dimensions": [
						"f1",
                        "f2"
					]
				}
			}
		},
		"metricsSpec": [],
		"granularitySpec": {
			"type": "uniform",
			"segmentGranularity": "HOUR",
			"queryGranularity": "NONE"
		}
	},
	"tuningConfig": {
		"type": "kafka",
		"maxRowsPerSegment": 5000000
	},
	"ioConfig": {
		"topic": "avroTest0",
		"consumerProperties": {
			"bootstrap.servers": "http://xxxx:9092"
		},
		"taskCount": 1,
		"replicas": 1,
		"taskDuration": "PT1M"
	}
}`

**Expected:** 
Kafka topic avtoTest0 being indexed to Druid table teststream.

**Actual:** 
I can see the supervisor (http://xxxx:8090/console.html) and failed tasks with following exceptions: 

_2019-05-20T17:58:23,412 ERROR [task-runner-0-priority-0] org.apache.druid.indexing.kafka.IncrementalPublishingKafkaIndexTaskRunner - Encountered exception in run() before persisting.
java.lang.UnsupportedOperationException: not supported
	at org.apache.druid.data.input.impl.TimeAndDimsParseSpec$1.parseToMap(TimeAndDimsParseSpec.java:53) ~[druid-api-0.13.0-incubating.jar:0.13.0-incubating]
	at org.apache.druid.data.input.impl.StringInputRowParser.parseString(StringInputRowParser.java:155) ~[druid-api-0.13.0-incubating.jar:0.13.0-incubating]
	at org.apache.druid.data.input.impl.StringInputRowParser.buildStringKeyMap(StringInputRowParser.java:119) ~[druid-api-0.13.0-incubating.jar:0.13.0-incubating]
	at org.apache.druid.data.input.impl.StringInputRowParser.parseBatch(StringInputRowParser.java:80) ~[druid-api-0.13.0-incubating.jar:0.13.0-incubating]
	at org.apache.druid.segment.transform.TransformingStringInputRowParser.parseBatch(TransformingStringInputRowParser.java:50) ~[druid-processing-0.13.0-incubating.jar:0.13.0-incubating]
	at org.apache.druid.segment.transform.TransformingStringInputRowParser.parseBatch(TransformingStringInputRowParser.java:31) ~[druid-processing-0.13.0-incubating.jar:0.13.0-incubating]
	at org.apache.druid.indexing.kafka.IncrementalPublishingKafkaIndexTaskRunner.runInternal(IncrementalPublishingKafkaIndexTaskRunner.java:493) [druid-kafka-indexing-service-0.13.0-incubating.jar:0.13.0-incubating]
	at org.apache.druid.indexing.kafka.IncrementalPublishingKafkaIndexTaskRunner.run(IncrementalPublishingKafkaIndexTaskRunner.java:232) [druid-kafka-indexing-service-0.13.0-incubating.jar:0.13.0-incubating]
	at org.apache.druid.indexing.kafka.KafkaIndexTask.run(KafkaIndexTask.java:210) [druid-kafka-indexing-service-0.13.0-incubating.jar:0.13.0-incubating]
	at org.apache.druid.indexing.overlord.SingleTaskBackgroundRunner$SingleTaskBackgroundRunnerCallable.call(SingleTaskBackgroundRunner.java:421) [druid-indexing-service-0.13.0-incubating.jar:0.13.0-incubating]
	at org.apache.druid.indexing.overlord.SingleTaskBackgroundRunner$SingleTaskBackgroundRunnerCallable.call(SingleTaskBackgroundRunner.java:393) [druid-indexing-service-0.13.0-incubating.jar:0.13.0-incubating]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_141]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_141]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_141]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]_

**Comment by jihoonson** [comment]
Hi, it looks that your `parseSpec` is wrong. It should be `avro`. Please check http://druid.io/docs/latest/development/extensions-core/avro.html for details.

I'm closing this since it looks not an issue. Please feel free to reopen if you still have this issue.
