### ISSUE TITLE
Regression: Coordinator startup fails with exception

### ISSUE THREAD

**Issue by pdeva** [apache/incubator-druid#7762]
### Affected Version
0.14.0-iap10

### Last working version

0.14.0-iap8

### Description

No configuration changes were made when upgrading versions

```
Exception in thread "main" com.google.inject.CreationException: Unable to create injector, see the following errors:
1) A binding to com.google.common.base.Supplier<org.apache.druid.query.lookup.LookupConfig> was already configured at org.apache.druid.guice.JsonConfigProvider.bind(JsonConfigProvider.java:151) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.query.lookup.LookupSerdeModule).
  at org.apache.druid.guice.JsonConfigProvider.bind(JsonConfigProvider.java:151) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.query.lookup.LookupSerdeModule)
2) A binding to org.apache.druid.query.lookup.LookupConfig was already configured at org.apache.druid.guice.JsonConfigProvider.bind(JsonConfigProvider.java:152) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.query.lookup.LookupSerdeModule).
  at org.apache.druid.guice.JsonConfigProvider.bind(JsonConfigProvider.java:152) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.query.lookup.LookupSerdeModule)
2 errors
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
	at com.google.inject.Guice.createInjector(Guice.java:99)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at org.apache.druid.initialization.Initialization.makeInjectorWithModules(Initialization.java:422)
	at org.apache.druid.cli.GuiceRunnable.makeInjector(GuiceRunnable.java:69)
	at org.apache.druid.cli.ServerRunnable.run(ServerRunnable.java:57)
	at org.apache.druid.cli.Main.main(Main.java:118)
```

**Comment by gianm** [comment]
This happens when `druid.coordinator.asOverlord.enabled` is true and is a regression since #7752, which adds LookupSerdeModule to CliCoordinator. Therefore, it should be a 0.15.0 blocker. I'm not sure what the best way is to fix this yet but I'll take a look.

**Comment by pdeva** [comment]
i can confirm that druid.coordinator.asOverlord.enabled is indeed set to true in my config

**Comment by gianm** [comment]
I think the simplest thing is to skip loading LookupSerdeModule in CliCoordinator if it's in beOverlord mode. This patch does that: https://github.com/apache/incubator-druid/pull/7765

**Comment by vogievetsky** [comment]
Note: this is fixed as part of 0.14.0-iap12

**Comment by pdeva** [comment]
so something weird is happening with version numbers.
in installed imply 2.9.11 but i see version numbers everywhere as 0.14.0-iap12 instead of 0.14.0-iap11....
not sure if you introduced an off by one bug in your versioning...

**Comment by gianm** [comment]
They aren't supposed to match.

**Comment by pdeva** [comment]
i see.
confirming that fix does work and coordinator starts up

**Comment by meniluca** [comment]
Same here. Testing 0.19.0 with bin/start-micro-quickstart. The only changed: the port in ``conf/druid/single-server/micro-quickstart/coordinator-overlord/runtime.properties`` (see below). Any suggestion?

```
druid.plaintextPort=7999 #was 8081
```
