### ISSUE TITLE
Druid 0.12.3 - Middle Managers - NullPointerException Jackson

### ISSUE THREAD

**Issue by hellobabygogo** [apache/incubator-druid#7763]
Hi, all
We are running Druid 0.12.3 on production. Every hour we run approximately 2000 tasks on middle managers.

Every few hours one or two real time index tasks are failing with the same error:
2019-05-23T16:23:52,414 ERROR [main] io.druid.cli.CliPeon - Error when starting up.  Failing.
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_77]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_77]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_77]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_77]
	at io.druid.java.util.common.lifecycle.Lifecycle$AnnotationBasedHandler.start(Lifecycle.java:421) ~[java-util-0.12.3-111.jar:0.12.3-111]
	at io.druid.java.util.common.lifecycle.Lifecycle.start(Lifecycle.java:319) ~[java-util-0.12.3-111.jar:0.12.3-111]
	at io.druid.guice.LifecycleModule$2.start(LifecycleModule.java:134) ~[druid-api-0.12.3-111.jar:0.12.3-111]
	at io.druid.cli.GuiceRunnable.initLifecycle(GuiceRunnable.java:101) [druid-services-0.12.3-111.jar:0.12.3-111]
	at io.druid.cli.CliPeon.run(CliPeon.java:301) [druid-services-0.12.3-111.jar:0.12.3-111]
	at io.druid.cli.Main.main(Main.java:117) [druid-services-0.12.3-111.jar:0.12.3-111]
Caused by: java.lang.NullPointerException
	at org.codehaus.jackson.JsonFactory.createJsonParser(JsonFactory.java:604) ~[jackson-core-asl-1.9.13.jar:1.9.13]
	at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1973) ~[jackson-mapper-asl-1.9.13.jar:1.9.13]
	at org.apache.curator.x.discovery.details.JsonInstanceSerializer.deserialize(JsonInstanceSerializer.java:86) ~[curator-x-discovery-4.0.0.jar:?]
	at org.apache.curator.x.discovery.details.ServiceCacheImpl.addInstance(ServiceCacheImpl.java:193) ~[curator-x-discovery-4.0.0.jar:?]
	at org.apache.curator.x.discovery.details.ServiceCacheImpl.start(ServiceCacheImpl.java:96) ~[curator-x-discovery-4.0.0.jar:?]
	at org.apache.curator.x.discovery.details.ServiceProviderImpl.start(ServiceProviderImpl.java:75) ~[curator-x-discovery-4.0.0.jar:?]
	at io.druid.curator.discovery.ServerDiscoverySelector.start(ServerDiscoverySelector.java:138) ~[druid-server-0.12.3-111.jar:0.12.3-111]
	... 10 more

I see someone also meet this problem and He thought this is is a issue of curator : https://github.com/apache/curator/commit/cc30b67c8dbe24babd31ed654e9536fe776b8a18.
how about merge this patch or replace our curator version?

**Comment by gianm** [comment]
That commit is marked as https://issues.apache.org/jira/browse/CURATOR-452, which says it was fixed in 4.1.0. We updated to this version in 0.14: https://github.com/apache/incubator-druid/pull/6862, so we should have this update already. If you still see this issue in the latest release (0.14.2) please let us know.

**Comment by hellobabygogo** [comment]
> That commit is marked as https://issues.apache.org/jira/browse/CURATOR-452, which says it was fixed in 4.1.0. We updated to this version in 0.14: #6862, so we should have this update already. If you still see this issue in the latest release (0.14.2) please let us know.

ok, thank you!
