### ISSUE TITLE
First Time Launching Druid Tasks fail

### ISSUE THREAD

**Issue by CalvinSchulze** [apache/incubator-druid#7835]
Hello,

I set up an Ubuntu 19.04 Virtual Machine using VMWare Workstation.
Java JRE build 11.0.3+7-Ubuntu-1ubuntu219.04.1 and Python 2.7 are installed. 

All starting Tasks fail, whenever I try to execute the single machine quicklaunch. 
Here's the log: 

```

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/home/myadmin/apache-druid-0.14.2-incubating/lib/guice-4.1.0.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2019-06-05T11:27:47,578 INFO [main] org.apache.druid.guice.PropertiesModule - Loading properties from common.runtime.properties
2019-06-05T11:27:47,583 INFO [main] org.apache.druid.guice.PropertiesModule - Loading properties from runtime.properties
2019-06-05T11:27:47,768 INFO [main] org.hibernate.validator.internal.util.Version - HV000001: Hibernate Validator 5.1.3.Final
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/ValidationException
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:802)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:700)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:623)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at org.hibernate.validator.internal.engine.ConfigurationImpl.<init>(ConfigurationImpl.java:110)
	at org.hibernate.validator.internal.engine.ConfigurationImpl.<init>(ConfigurationImpl.java:86)
	at org.hibernate.validator.HibernateValidator.createGenericConfiguration(HibernateValidator.java:41)
	at javax.validation.Validation$GenericBootstrapImpl.configure(Validation.java:276)
	at javax.validation.Validation.buildDefaultValidatorFactory(Validation.java:110)
	at org.apache.druid.guice.ConfigModule.configure(ConfigModule.java:39)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
	at com.google.inject.Guice.createInjector(Guice.java:99)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at org.apache.druid.guice.GuiceInjectors.makeStartupInjector(GuiceInjectors.java:56)
	at org.apache.druid.cli.Main.main(Main.java:101)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.ValidationException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 23 more

```

Is this a Java incompatibility?

I use Druid 0.14.2 incubating and I tried Zookeeper 3.5.5. , 3.4.11 and 3.4.14

Best Regards,
Calvin

**Comment by justinborromeo** [comment]
Hi Calvin,

Afaik, Druid doesn't support Java 11; you'll have to use Java 8 (as mentioned in the [quickstart doc](http://druid.io/docs/latest/tutorials/index.html)).  There's an initiative to support Java 11 compatibility (see #5589) but I don't think it's been completed.

**Comment by CalvinSchulze** [comment]
Thank you! Java 8 works.
