### ISSUE TITLE
Indexing task was killed after start

### ISSUE THREAD

**Issue by duanxuelin** [apache/incubator-druid#7929]
Task was killed after abort 6 second when post a kafka supervisor
### Affected Version

0.14.0-incubator

### Description

here is supervisor:
``` json
{
  "type": "kafka",
  "dataSchema": {
    "dataSource": "alpha_station_txack_record",
    "parser": {
      "type": "string",
      "parseSpec": {
        "format": "json",
        "timestampSpec": {
          "column": "@timestamp",
          "format": "iso"
        },
        "dimensionsSpec": {
          "dimensions": [
            "msgId",
            "gwEUI",
            "devEUI",
            "downTx"
          ]
        }
      }
    },
    "metricsSpec" : [],
    "granularitySpec": {
      "type": "uniform",
      "segmentGranularity": "DAY",
      "queryGranularity": "NONE",
      "rollup": false
    }
  },
  "tuningConfig": {
    "type": "kafka",
    "logParseExceptions": true,
    "maxRowsInMemory": 500000,
    "intermediateHandoffPeriod": "P1D"
  },
  "ioConfig": {
    "topic": "alpha-station-txack-record",
    "replicas": 1,
    "taskDuration": "PT12H",
    "completionTimeout": "PT30M",
    "consumerProperties": {
      "bootstrap.servers": "192.168.102.18:9092,192.168.102.19:9092,192.168.102.20:9092",
      "group.id": "alpha-druid"
    }
  }
}
```

overlord log:
`2019-06-20T02:56:11,132 ERROR [KafkaSupervisor-alpha_station_txack_record-Worker-0] org.apache.druid.indexing.seekablestream.supervisor.SeekableStreamSupervisor - Problem while getting checkpoints for task [index_kafka_alpha_station_txack_record_7084b4cf7bfd7a7_bebmfiod], killing the task
java.util.concurrent.ExecutionException: org.apache.druid.indexing.common.IndexTaskClient$TaskNotRunnableException: Aborting request because task [index_kafka_alpha_station_txack_record_7084b4cf7bfd7a7_bebmfiod] is not runnable
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_212]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_212]
	at org.apache.druid.indexing.seekablestream.supervisor.SeekableStreamSupervisor.verifyAndMergeCheckpoints(SeekableStreamSupervisor.java:1444) ~[druid-indexing-service-0.14.0-incubating.jar:0.14.0-incubating]
	at org.apache.druid.indexing.seekablestream.supervisor.SeekableStreamSupervisor.lambda$verifyAndMergeCheckpoints$16(SeekableStreamSupervisor.java:1402) ~[druid-indexing-service-0.14.0-incubating.jar:0.14.0-incubating]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: org.apache.druid.indexing.common.IndexTaskClient$TaskNotRunnableException: Aborting request because task [index_kafka_alpha_station_txack_record_7084b4cf7bfd7a7_bebmfiod] is not runnable
	at org.apache.druid.indexing.common.IndexTaskClient.submitRequest(IndexTaskClient.java:322) ~[druid-indexing-service-0.14.0-incubating.jar:0.14.0-incubating]
	at org.apache.druid.indexing.common.IndexTaskClient.submitRequestWithEmptyContent(IndexTaskClient.java:220) ~[druid-indexing-service-0.14.0-incubating.jar:0.14.0-incubating]
	at org.apache.druid.indexing.seekablestream.SeekableStreamIndexTaskClient.getCheckpoints(SeekableStreamIndexTaskClient.java:253) ~[druid-indexing-service-0.14.0-incubating.jar:0.14.0-incubating]
	at org.apache.druid.indexing.seekablestream.SeekableStreamIndexTaskClient.lambda$getCheckpointsAsync$0(SeekableStreamIndexTaskClient.java:276) ~[druid-indexing-service-0.14.0-incubating.jar:0.14.0-incubating]
	... 4 more`

**Comment by oriontl** [comment]
@duanxuelin any resolution on this?

**Comment by zhuchaoyang1** [comment]
I have this problem, too
Have you solved it?

**Comment by robophil** [comment]
What was the solution to this? @duanxuelin ?
