### ISSUE TITLE
Trying to load extensions with 'druid.extensions.localRepository' raises NullPointerException if permission denied

### ISSUE THREAD

**Issue by swistakm** [apache/incubator-druid#807]
For example this runtime.properties:

```
druid.extensions.coordinates=["io.druid.extensions:druid-s3-extensions:0.6.160"]
druid.extensions.localRepository=/usr/local/druid/repository
```

with `/usr/local/druid/repository` owned by user `root` and druid node run by user `druid`

gives:

```
2014-10-23 14:11:04,150 INFO [main] io.druid.guice.JsonConfigurator - Loaded class[class io.druid.guice.ExtensionsConfig] from props[druid.extensions.] as [ExtensionsConfig{searchCurrentClassloader=true, coordinates=[io.druid.extensions:druid-rabbitmq:0.6.160, io.druid.extensions:druid-s3-extensions:0.6.158], localRepository='/usr/local/druid/lib', remoteRepositories=[http://repo1.maven.org/maven2/, https://metamx.artifactoryonline.com/metamx/pub-libs-releases-local]}]
2014-10-23 14:11:04,331 INFO [main] io.druid.initialization.Initialization - Loading extension[io.druid.extensions:druid-rabbitmq:0.6.160] for class[io.druid.cli.CliCommandCreator]
2014-10-23 14:11:04,399 ERROR [main] io.druid.initialization.Initialization - Unable to resolve artifacts for [io.druid.extensions:druid-rabbitmq:jar:0.6.160 (runtime) -> [] < [central (http://repo1.maven.org/maven2/, releases+snapshots),  (https://metamx.artifactoryonline.com/metamx/pub-libs-releases-local, releases+snapshots)]].
java.lang.NullPointerException
    at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:361)
    at io.tesla.aether.internal.DefaultTeslaAether.resolveArtifacts(DefaultTeslaAether.java:289)
    at io.druid.initialization.Initialization.getClassLoaderForCoordinates(Initialization.java:200)
    at io.druid.initialization.Initialization.getFromExtensions(Initialization.java:142)
    at io.druid.cli.Main.main(Main.java:78)
Exception in thread "main" java.lang.NullPointerException
    at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:361)
    at io.tesla.aether.internal.DefaultTeslaAether.resolveArtifacts(DefaultTeslaAether.java:289)
    at io.druid.initialization.Initialization.getClassLoaderForCoordinates(Initialization.java:200)
    at io.druid.initialization.Initialization.getFromExtensions(Initialization.java:142)
    at io.druid.cli.Main.main(Main.java:78)
```

IMO error messages should be more meaningful than this.

**Comment by xvrl** [comment]
@swistakm the library we use for dependency resolution does not provide much error handling, if any.
We should probably catch those exceptions and try to offer pointers for resolution, but it's not going to be perfect.
