### ISSUE TITLE
historical node crashes on startup in 0.15.0

### ISSUE THREAD

**Issue by pdeva** [apache/incubator-druid#8077]
### Affected Version

0.15.0

### Description
Upgrading from 0.14.2 with no configuration change.
Running into this error on startup:

```
Exception in thread "main" java.lang.RuntimeException: com.google.inject.CreationException: Unable to create injector, see the following errors:

1) No implementation for org.apache.druid.client.TimelineServerView was bound.
  while locating org.apache.druid.client.TimelineServerView
    for the 1st parameter of org.apache.druid.query.materializedview.DataSourceOptimizer.<init>(DataSourceOptimizer.java:60)
  at org.apache.druid.query.materializedview.MaterializedViewSelectionDruidModule.configure(MaterializedViewSelectionDruidModule.java:55) (via modules: com.google.inject.util.Modules$OverrideModule -> org.apache.druid.query.materializedview.MaterializedViewSelectionDruidModule)

2) A binding to com.google.common.base.Supplier<org.apache.druid.server.audit.SQLAuditManagerConfig> was already configured at org.apache.druid.guice.JsonConfigProvider.bind(JsonConfigProvider.java:151) (via modules: com.google.inject.util.Modules$OverrideModule -> org.apache.druid.metadata.storage.mysql.MySQLMetadataStorageModule).
  at org.apache.druid.guice.JsonConfigProvider.bind(JsonConfigProvider.java:151) (via modules: com.google.inject.util.Modules$OverrideModule -> org.apache.druid.metadata.storage.postgresql.PostgreSQLMetadataStorageModule)                                                                                                             
3) A binding to org.apache.druid.server.audit.SQLAuditManagerConfig was already configured at org.apache.druid.guice.JsonConfigProvider.bind(JsonConfigProvider.java:152) (via modules: com.google.inject.util.Modules$OverrideModule -> org.apache.druid.metadata.storage.mysql.MySQLMetadataStorageModule).
  at org.apache.druid.guice.JsonConfigProvider.bind(JsonConfigProvider.java:152) (via modules: com.google.inject.util.Modules$OverrideModule -> org.apache.druid.metadata.storage.postgresql.PostgreSQLMetadataStorageModule)

3 errors
        at org.apache.druid.cli.GuiceRunnable.makeInjector(GuiceRunnable.java:71)
        at org.apache.druid.cli.ServerRunnable.run(ServerRunnable.java:56)
        at org.apache.druid.cli.Main.main(Main.java:118)
Caused by: com.google.inject.CreationException: Unable to create injector, see the following errors:

1) No implementation for org.apache.druid.client.TimelineServerView was bound.
  while locating org.apache.druid.client.TimelineServerView
    for the 1st parameter of org.apache.druid.query.materializedview.DataSourceOptimizer.<init>(DataSourceOptimizer.java:60)
  at org.apache.druid.query.materializedview.MaterializedViewSelectionDruidModule.configure(MaterializedViewSelectionDruidModule.java:55) (via modules: com.google.inject.util.Modules$OverrideModule -> org.apache.druid.query.materializedview.MaterializedViewSelectionDruidModule)


2) A binding to com.google.common.base.Supplier<org.apache.druid.server.audit.SQLAuditManagerConfig> was already configured 
at org.apache.druid.guice.JsonConfigProvider.bind(JsonConfigProvider.java:151) 
(via modules: com.google.inject.util.Modules$OverrideModule -> org.apache.druid.metadata.storage.mysql.MySQLMetadataStorageModule).                                                                                                                                                                   at org.apache.druid.guice.JsonConfigProvider.bind(JsonConfigProvider.java:151) (via modules: com.google.inject.util.Modules$OverrideModule -> org.apache.druid.metadata.storage.postgresql.PostgreSQLMetadataStorageModule)

3) A binding to org.apache.druid.server.audit.SQLAuditManagerConfig was already configured at org.apache.druid.guice.JsonConfigProvider.bind(JsonConfigProvider.java:152) (via modules: com.google.inject.util.Modules$OverrideModule -> org.apache.druid.metadata.storage.mysql.MySQLMetadataStorageModule).
  at org.apache.druid.guice.JsonConfigProvider.bind(JsonConfigProvider.java:152) (via modules: com.google.inject.util.Modules$OverrideModule -> org.apache.druid.metadata.storage.postgresql.PostgreSQLMetadataStorageModule)

3 errors
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
        at com.google.inject.Guice.createInjector(Guice.java:99)                                                                                                             at com.google.inject.Guice.createInjector(Guice.java:73)
        at com.google.inject.Guice.createInjector(Guice.java:62)
        at org.apache.druid.initialization.Initialization.makeInjectorWithModules(Initialization.java:419)                                                                   at org.apache.druid.cli.GuiceRunnable.makeInjector(GuiceRunnable.java:68)                                                                                            ... 2 more
		
```

**Comment by pdeva** [comment]
this could be related to something silly that i am probably doing.
let me investigate further and i will reopen with details.
