### ISSUE TITLE
Protobuf config file setting timestampSpec column not as "timestamp" will encounter exception

### ISSUE THREAD

**Issue by yycncom** [apache/incubator-druid#8102]
### Affected Version
druid-0.14.2-incubating

### Description
part config file:
{
  "type": "kafka",
  "dataSchema": {
    "dataSource": "autopilot_kafka",
    "parser": {
      "type": "protobuf",
      "descriptor": "file:///tmp/allevent.desc",
      "parseSpec": {
        "format": "json",
        "timestampSpec": {
          "column": "local_timestamp",
          "format": "millis"
        },
It will get exception. if changing the "local_timestamp" into "timestamp" ,it will work well.

Exception info:
2019-07-18T03:20:22,858 ERROR [task-runner-0-priority-0] org.apache.druid.indexing.seekablestream.SeekableStreamIndexTaskRunner - Encountered exception in run() before persisting.
java.lang.NullPointerException: timestamp
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:229) ~[guava-16.0.1.jar:?]
	at org.apache.druid.indexing.common.actions.SegmentAllocateAction.<init>(SegmentAllocateAction.java:84) ~[druid-indexing-service-0.14.2-incubating.jar:0.14.2-incubating]
	at org.apache.druid.indexing.seekablestream.SeekableStreamIndexTask.lambda$newDriver$1(SeekableStreamIndexTask.java:229) ~[druid-indexing-service-0.14.2-incubating.jar:0.14.2-incubating]
	at org.apache.druid.indexing.appenderator.ActionBasedSegmentAllocator.allocate(ActionBasedSegmentAllocator.java:56) ~[druid-indexing-service-0.14.2-incubating.jar:0.14.2-incubating]
	at org.apache.druid.segment.realtime.appenderator.BaseAppenderatorDriver.getSegment(BaseAppenderatorDriver.java:331) ~[druid-server-0.14.2-incubating.jar:0.14.2-incubating]
	at org.apache.druid.segment.realtime.appenderator.BaseAppenderatorDriver.append(BaseAppenderatorDriver.java:399) ~[druid-server-0.14.2-incubating.jar:0.14.2-incubating]
	at org.apache.druid.segment.realtime.appenderator.StreamAppenderatorDriver.add(StreamAppenderatorDriver.java:180) ~[druid-server-0.14.2-incubating.jar:0.14.2-incubating]
	at org.apache.druid.indexing.seekablestream.SeekableStreamIndexTaskRunner.runInternal(SeekableStreamIndexTaskRunner.java:584) [druid-indexing-service-0.14.2-incubating.jar:0.14.2-incubating]
	at org.apache.druid.indexing.seekablestream.SeekableStreamIndexTaskRunner.run(SeekableStreamIndexTaskRunner.java:246) [druid-indexing-service-0.14.2-incubating.jar:0.14.2-incubating]
	at org.apache.druid.indexing.seekablestream.SeekableStreamIndexTask.run(SeekableStreamIndexTask.java:166) [druid-indexing-service-0.14.2-incubating.jar:0.14.2-incubating]
	at org.apache.druid.indexing.overlord.SingleTaskBackgroundRunner$SingleTaskBackgroundRunnerCallable.call(SingleTaskBackgroundRunner.java:419) [druid-indexing-service-0.14.2-incubating.jar:0.14.2-incubating]
	at org.apache.druid.indexing.overlord.SingleTaskBackgroundRunner$SingleTaskBackgroundRunnerCallable.call(SingleTaskBackgroundRunner.java:391) [druid-indexing-service-0.14.2-incubating.jar:0.14.2-incubating]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by yycncom** [comment]
There are some "null" and "None" in local_timestamp.
