### ISSUE TITLE
ReferenceCountedSegment is acquired too many times

### ISSUE THREAD

**Issue by leventov** [apache/incubator-druid#8291]
A error when a timeseries query is sent to Druid with high concurrency.

### Affected Version

0.14.0-incubating

### Description

```
org.apache.druid.query.ChainedExecutionQueryRunner - Exception with one of the sequences!

java.lang.IllegalStateException: Attempt to register more than 65535 parties for org.apache.druid.segment.ReferenceCountingSegment$1@50149526[phase = 0 parties = 65535 arrived = 0]

       at java.util.concurrent.Phaser.doRegister(Phaser.java:438) ~[?:1.8.0_151]

       at java.util.concurrent.Phaser.register(Phaser.java:591) ~[?:1.8.0_151]

       at org.apache.druid.segment.ReferenceCountingSegment.increment(ReferenceCountingSegment.java:124) ~[druid-processing-0.14.0-incubating.jar:0.14.0-incubating]

       at org.apache.druid.segment.realtime.FireHydrant.getIncrementedSegment(FireHydrant.java:76) ~[druid-server-0.14.0-incubating.jar:0.14.0-incubating]

       at org.apache.druid.segment.realtime.FireHydrant.getAndIncrementSegment(FireHydrant.java:136) ~[druid-server-0.14.0-incubating.jar:0.14.0-incubating]

       at org.apache.druid.segment.realtime.appenderator.SinkQuerySegmentWalker$3$1.apply(SinkQuerySegmentWalker.java:227) ~[druid-server-0.14.0-incubating.jar:0.14.0-incubating]

       at org.apache.druid.segment.realtime.appenderator.SinkQuerySegmentWalker$3$1.apply(SinkQuerySegmentWalker.java:214) ~[druid-server-0.14.0-incubating.jar:0.14.0-incubating]

       at com.google.common.collect.Iterators$8.transform(Iterators.java:794) ~[guava-16.0.1.jar:?]

       at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48) ~[guava-16.0.1.jar:?]

       at com.google.common.collect.Iterators$3.next(Iterators.java:163) ~[guava-16.0.1.jar:?]

       at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48) ~[guava-16.0.1.jar:?]

       at com.google.common.collect.Iterators.addAll(Iterators.java:357) ~[guava-16.0.1.jar:?]

       at com.google.common.collect.Lists.newArrayList(Lists.java:147) ~[guava-16.0.1.jar:?]

       at com.google.common.collect.Lists.newArrayList(Lists.java:129) ~[guava-16.0.1.jar:?]

       at org.apache.druid.query.ChainedExecutionQueryRunner$1.make(ChainedExecutionQueryRunner.java:104) ~[druid-processing-0.14.0-incubating.jar:0.14.0-incubating]

       at org.apache.druid.java.util.common.guava.BaseSequence.accumulate(BaseSequence.java:42) ~[druid-core-0.14.0-incubating.jar:0.14.0-incubating]

       at org.apache.druid.java.util.common.guava.LazySequence.accumulate(LazySequence.java:40) ~[druid-core-0.14.0-incubating.jar:0.14.0-incubating]

       at org.apache.druid.java.util.common.guava.WrappingSequence$1.get(WrappingSequence.java:50) ~[druid-core-0.14.0-incubating.jar:0.14.0-incubating]

       at org.apache.druid.java.util.common.guava.SequenceWrapper.wrap(SequenceWrapper.java:55) ~[druid-core-0.14.0-incubating.jar:0.14.0-incubating]

       at org.apache.druid.java.util.common.guava.WrappingSequence.accumulate(WrappingSequence.java:45) ~[druid-core-0.14.0-incubating.jar:0.14.0-incubating]

       at org.apache.druid.java.util.common.guava.LazySequence.accumulate(LazySequence.java:40) ~[druid-core-0.14.0-incubating.jar:0.14.0-incubating]

       at org.apache.druid.java.util.common.guava.WrappingSequence$1.get(WrappingSequence.java:50) ~[druid-core-0.14.0-incubating.jar:0.14.0-incubating]

       at org.apache.druid.java.util.common.guava.SequenceWrapper.wrap(SequenceWrapper.java:55) ~[druid-core-0.14.0-incubating.jar:0.14.0-incubating]

       at org.apache.druid.java.util.common.guava.WrappingSequence.accumulate(WrappingSequence.java:45) ~[druid-core-0.14.0-incubating.jar:0.14.0-incubating]

       at org.apache.druid.java.util.common.guava.WrappingSequence$1.get(WrappingSequence.java:50) ~[druid-core-0.14.0-incubating.jar:0.14.0-incubating]

       at org.apache.druid.query.CPUTimeMetricQueryRunner$1.wrap(CPUTimeMetricQueryRunner.java:74) ~[druid-processing-0.14.0-incubating.jar:0.14.0-incubating]

       at org.apache.druid.java.util.common.guava.WrappingSequence.accumulate(WrappingSequence.java:45) ~[druid-core-0.14.0-incubating.jar:0.14.0-incubating]

       at org.apache.druid.query.spec.SpecificSegmentQueryRunner$1.accumulate(SpecificSegmentQueryRunner.java:82) ~[druid-processing-0.14.0-incubating.jar:0.14.0-incubating]

       at org.apache.druid.java.util.common.guava.WrappingSequence$1.get(WrappingSequence.java:50) ~[druid-core-0.14.0-incubating.jar:0.14.0-incubating]

       at org.apache.druid.query.spec.SpecificSegmentQueryRunner.doNamed(SpecificSegmentQueryRunner.java:168) ~[druid-processing-0.14.0-incubating.jar:0.14.0-incubating]

       at org.apache.druid.query.spec.SpecificSegmentQueryRunner.access$100(SpecificSegmentQueryRunner.java:45) ~[druid-processing-0.14.0-incubating.jar:0.14.0-incubating]

       at org.apache.druid.query.spec.SpecificSegmentQueryRunner$2.wrap(SpecificSegmentQueryRunner.java:148) ~[druid-processing-0.14.0-incubating.jar:0.14.0-incubating]

       at org.apache.druid.java.util.common.guava.WrappingSequence.accumulate(WrappingSequence.java:45) ~[druid-core-0.14.0-incubating.jar:0.14.0-incubating]

       at org.apache.druid.java.util.common.guava.Sequence.toList(Sequence.java:76) ~[druid-core-0.14.0-incubating.jar:0.14.0-incubating]

       at org.apache.druid.query.ChainedExecutionQueryRunner$1$1.call(ChainedExecutionQueryRunner.java:124) [druid-processing-0.14.0-incubating.jar:0.14.0-incubating]

       at org.apache.druid.query.ChainedExecutionQueryRunner$1$1.call(ChainedExecutionQueryRunner.java:114) [druid-processing-0.14.0-incubating.jar:0.14.0-incubating]

       at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]

       at org.apache.druid.query.PrioritizedListenableFutureTask.run(PrioritizedExecutorService.java:247) [druid-processing-0.14.0-incubating.jar:0.14.0-incubating]

       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]

       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]

       at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
```

**Comment by leventov** [comment]
Reported by shaoxiankai@jd.com

**Comment by mh-boy** [comment]
I encountered the same issue : it occured when peon task immediately persisted data to local file system generated smoosh files,after that, concurrent queries aquire these smoosh files as ReferenceCountingSegment, made their **_referents_**(Phaser) register too many parties and didn't deregister them timely, eventually lead to throw above error; we add log in method _**increment()**_ and _**decrement()**_  in ReferenceCountingSegment to print _**referents registerParties**_ use _**getNumReferences()**_, and find out the _**registerParties**_ keep increasing.

**Comment by pphust** [comment]
I submit https://github.com/apache/incubator-druid/pull/8316 to fix the problem
