### ISSUE TITLE
SegmentLoadingException from AWS S3

### ISSUE THREAD

**Issue by xuejiaqing** [apache/incubator-druid#8706]
I got a exception in my historical node.

```
Oct 21 08:35:47 druid-historical-01.local.com java[14448]: 2019-10-21T08:35:47,416 WARN [ZKCoordinator--5] org.apache.druid.server.coordination.SegmentLoadDropHandler - Unable to delete segmentInfoCacheFile[/data/druid/segment-cache/info_dir/adx-xyz-json-t7_2019-10-20T14:00:00.000Z_2019-10-20T15:00:00.000Z_2019-10-20T14:00:01.460Z_43]
Oct 21 08:35:47 druid-historical-01.local.com java[14448]: 2019-10-21T08:35:47,416 ERROR [ZKCoordinator--5] org.apache.druid.server.coordination.SegmentLoadDropHandler - Failed to load segment for dataSource: {class=org.apache.druid.server.coordination.SegmentLoadDropHandler, exceptionType=class org.apache.druid.segment.loading.SegmentLoadingException, exceptionMessage=Exception loading segment[adx-xyz-json-t7_2019-10-20T14:00:00.000Z_2019-10-20T15:00:00.000Z_2019-10-20T14:00:01.460Z_43], segment=DataSegment{size=16853728, shardSpec=NumberedShardSpec{partitionNum=43, partitions=0}, metrics=[request, response, impression, click, win], dimensions=[seller_id, api, seat, seller_name, inventory_type, platform, ad_type, country, app_bundle_id, app_name, brand, model, os_version, buyer_id, buyer_name, seller_bid_floor, bid_floor, buyer_cpm, cpm, auction_cpm, server_region, adomain, agency_name, advertiser_name, cid, crid, buyer_gross_cpm, seller_gross_cpm], version='2019-10-20T14:00:01.460Z', loadSpec={type=>s3_zip, bucket=>use.logs.druid, key=>druid/segments/adx-xyz-json-t7/2019-10-20T14:00:00.000Z_2019-10-20T15:00:00.000Z/2019-10-20T14:00:01.460Z/43/1af44bba-29f6-48de-8ed1-a558c244f57f/index.zip, S3Schema=>s3n}, interval=2019-10-20T14:00:00.000Z/2019-10-20T15:00:00.000Z, dataSource='adx-xyz-json-t7', binaryVersion='9'}}
Oct 21 08:35:47 druid-historical-01.local.com java[14448]: org.apache.druid.segment.loading.SegmentLoadingException: Exception loading segment[adx-xyz-json-t7_2019-10-20T14:00:00.000Z_2019-10-20T15:00:00.000Z_2019-10-20T14:00:01.460Z_43]
Oct 21 08:35:47 druid-historical-01.local.com java[14448]: at org.apache.druid.server.coordination.SegmentLoadDropHandler.loadSegment(SegmentLoadDropHandler.java:268) ~[druid-server-0.15.1-incubating.jar:0.15.1-incubating]
Oct 21 08:35:47 druid-historical-01.local.com java[14448]: at org.apache.druid.server.coordination.SegmentLoadDropHandler.addSegment(SegmentLoadDropHandler.java:312) ~[druid-server-0.15.1-incubating.jar:0.15.1-incubating]
Oct 21 08:35:47 druid-historical-01.local.com java[14448]: at org.apache.druid.server.coordination.SegmentChangeRequestLoad.go(SegmentChangeRequestLoad.java:47) ~[druid-server-0.15.1-incubating.jar:0.15.1-incubating]
Oct 21 08:35:47 druid-historical-01.local.com java[14448]: at org.apache.druid.server.coordination.ZkCoordinator.lambda$childAdded$0(ZkCoordinator.java:152) ~[druid-server-0.15.1-incubating.jar:0.15.1-incubating]
Oct 21 08:35:47 druid-historical-01.local.com java[14448]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_202-ea]
Oct 21 08:35:47 druid-historical-01.local.com java[14448]: at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_202-ea]
Oct 21 08:35:47 druid-historical-01.local.com java[14448]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_202-ea]
Oct 21 08:35:47 druid-historical-01.local.com java[14448]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_202-ea]
Oct 21 08:35:47 druid-historical-01.local.com java[14448]: at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202-ea]
Oct 21 08:35:47 druid-historical-01.local.com java[14448]: Caused by: org.apache.druid.segment.loading.SegmentLoadingException: Failed to load segment adx-xyz-json-t7_2019-10-20T14:00:00.000Z_2019-10-20T15:00:00.000Z_2019-10-20T14:00:01.460Z_43 in all locations.
Oct 21 08:35:47 druid-historical-01.local.com java[14448]: at org.apache.druid.segment.loading.SegmentLoaderLocalCacheManager.loadSegmentWithRetry(SegmentLoaderLocalCacheManager.java:203) ~[druid-server-0.15.1-incubating.jar:0.15.1-incubating]
Oct 21 08:35:47 druid-historical-01.local.com java[14448]: at org.apache.druid.segment.loading.SegmentLoaderLocalCacheManager.getSegmentFiles(SegmentLoaderLocalCacheManager.java:164) ~[druid-server-0.15.1-incubating.jar:0.15.1-incubating]
Oct 21 08:35:47 druid-historical-01.local.com java[14448]: at org.apache.druid.segment.loading.SegmentLoaderLocalCacheManager.getSegment(SegmentLoaderLocalCacheManager.java:131) ~[druid-server-0.15.1-incubating.jar:0.15.1-incubating]
Oct 21 08:35:47 druid-historical-01.local.com java[14448]: at org.apache.druid.server.SegmentManager.getAdapter(SegmentManager.java:196) ~[druid-server-0.15.1-incubating.jar:0.15.1-incubating]
Oct 21 08:35:47 druid-historical-01.local.com java[14448]: at org.apache.druid.server.SegmentManager.loadSegment(SegmentManager.java:157) ~[druid-server-0.15.1-incubating.jar:0.15.1-incubating]
Oct 21 08:35:47 druid-historical-01.local.com java[14448]: at org.apache.druid.server.coordination.SegmentLoadDropHandler.loadSegment(SegmentLoadDropHandler.java:264) ~[druid-server-0.15.1-incubating.jar:0.15.1-incubating]
Oct 21 08:35:47 druid-historical-01.local.com java[14448]: ... 8 more
Oct 21 08:35:47 druid-historical-01.local.com java[14448]: 2019-10-21T08:35:47,417 INFO [ZKCoordinator--5] org.apache.druid.server.coordination.ZkCoordinator - Completed request [LOAD: adx-xyz-json-t7_2019-10-20T14:00:00.000Z_2019-10-20T15:00:00.000Z_2019-10-20T14:00:01.460Z_43]
Oct 21 08:35:47 druid-historical-01.local.com java[14448]: 2019-10-21T08:35:47,417 INFO [ZkCoordinator] org.apache.druid.server.coordination.ZkCoordinator - zNode[/druid/loadQueue/druid-historical-01.local.com:18083/adx-xyz-json-t7_2019-10-20T14:00:00.000Z_2019-10-20T15:00:00.000Z_2019-10-20T14:00:01.460Z_43] was removed
```

I confirm that my s3 access key has sufficient permissions. and how can I fixed it?

**Comment by xuejiaqing** [comment]
I run druid in amazon ec2 instance, and I confirm clock is right

**Comment by xuejiaqing** [comment]
I set too small `maxSize` in `druid.segmentCache.locations`, closed.

**Comment by gopakr** [comment]
@alphaxo before you hit the above error did you notice below error in the same historical log.	
	
	
	at org.apache.druid.segment.loading.SegmentLoaderLocalCacheManager.loadSegmentWithRetry(SegmentLoaderLocalCacheManager.java:190) ~[druid-server-0.20.0.jar:0.20.0]
	at org.apache.druid.segment.loading.SegmentLoaderLocalCacheManager.getSegmentFiles(SegmentLoaderLocalCacheManager.java:162) ~[druid-server-0.20.0.jar:0.20.0]
	at org.apache.druid.segment.loading.SegmentLoaderLocalCacheManager.getSegment(SegmentLoaderLocalCacheManager.java:129) ~[druid-server-0.20.0.jar:0.20.0]
	at org.apache.druid.server.SegmentManager.getAdapter(SegmentManager.java:278) ~[druid-server-0.20.0.jar:0.20.0]
	at org.apache.druid.server.SegmentManager.loadSegment(SegmentManager.java:224) ~[druid-server-0.20.0.jar:0.20.0]
	at org.apache.druid.server.coordination.SegmentLoadDropHandler.loadSegment(SegmentLoadDropHandler.java:265) ~[druid-server-0.20.0.jar:0.20.0]
	at org.apache.druid.server.coordination.SegmentLoadDropHandler.addSegment(SegmentLoadDropHandler.java:313) ~[druid-server-0.20.0.jar:0.20.0]
	at org.apache.druid.server.coordination.SegmentChangeRequestLoad.go(SegmentChangeRequestLoad.java:61) ~[druid-server-0.20.0.jar:0.20.0]
	at org.apache.druid.server.coordination.ZkCoordinator.lambda$childAdded$2(ZkCoordinator.java:147) ~[druid-server-0.20.0.jar:0.20.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_201]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
	Caused by: java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:213) ~[guava-16.0.1.jar:?]
	at org.apache.druid.data.input.impl.CloudObjectLocation.<init>(CloudObjectLocation.java:63) ~[druid-core-0.20.0.jar:0.20.0]
	at org.apache.druid.data.input.impl.CloudObjectLocation.<init>(CloudObjectLocation.java:73) ~[druid-core-0.20.0.jar:0.20.0]
	at org.apache.druid.storage.s3.S3DataSegmentPuller.buildFileObject(S3DataSegmentPuller.java:152) ~[?:?]
	at org.apache.druid.storage.s3.S3DataSegmentPuller.access$000(S3DataSegmentPuller.java:57) ~[?:?]
	at org.apache.druid.storage.s3.S3DataSegmentPuller$1.openStream(S3DataSegmentPuller.java:91) ~[?:?]
	at org.apache.druid.utils.CompressionUtils.lambda$unzip$1(CompressionUtils.java:182) ~[druid-core-0.20.0.jar:0.20.0]
	at org.apache.druid.java.util.common.RetryUtils.retry(RetryUtils.java:87) ~[druid-core-0.20.0.jar:0.20.0]
	at org.apache.druid.java.util.common.RetryUtils.retry(RetryUtils.java:115) ~[druid-core-0.20.0.jar:0.20.0]
	at org.apache.druid.java.util.common.RetryUtils.retry(RetryUtils.java:105) ~[druid-core-0.20.0.jar:0.20.0]
	at org.apache.druid.utils.CompressionUtils.unzip(CompressionUtils.java:181) ~[druid-core-0.20.0.jar:0.20.0]
	at org.apache.druid.storage.s3.S3DataSegmentPuller.getSegmentFiles(S3DataSegmentPuller.java:104) ~[?:?]
