### ISSUE TITLE
No match found for function signature STDDEV_POP(<NUMERIC>)

### ISSUE THREAD

**Issue by wch661** [apache/incubator-druid#8971]
I'm using apache druid 0.15.1. 
This exception occurs when using the std function to aggregate data.
```
Unknown exception / org.apache.calcite.runtime.CalciteContextException: From line 3, column 5 to line 3, column 33: No match found for function signature STDDEV_POP(<NUMERIC>) / org.apache.calcite.tools.ValidationException
```

Sql：
```
SELECT 
    TIME_FLOOR("__time", 'PT1M') AS "dt_1min",
    STDDEV_POP ("XXXXXXXX_Speed")            AS std_1min
FROM "test"
GROUP BY TIME_FLOOR("__time", 'PT1M')
ORDER BY TIME_FLOOR("__time", 'PT1M')
```

I have read about this page: https://druid.apache.org/docs/latest/development/extensions-core/stats.html. 
Added the extension `druid-stats`.
![image](https://user-images.githubusercontent.com/8898158/69841697-3a907d00-129b-11ea-95e8-0fd684b40063.png)

Extensions are loaded in all nodes.
![image](https://user-images.githubusercontent.com/8898158/69841759-7b889180-129b-11ea-8c34-94fdfae004c7.png)

But this exception still occurs when using the std function.

Can anyone help me?

**Comment by wch661** [comment]
Error log in broker.log

```
2019-11-29T03:21:43,832 ERROR [sql[5ae76b0a-f08a-404a-b922-b4da93970830]] org.apache.calcite.runtime.CalciteException - org.apache.calcite.sql.validate.SqlValidatorException: No match found for function signature STDDEV_POP(<NUMERIC>)
2019-11-29T03:21:43,833 ERROR [sql[5ae76b0a-f08a-404a-b922-b4da93970830]] org.apache.calcite.runtime.CalciteException - org.apache.calcite.runtime.CalciteContextException: From line 3, column 5 to line 3, column 33: No match found for function signature STDDEV_POP(<NUMERIC>)
2019-11-29T03:21:43,833 WARN [sql[5ae76b0a-f08a-404a-b922-b4da93970830]] org.apache.druid.sql.http.SqlResource - Failed to handle query: SqlQuery{query='SELECT * FROM (SELECT ^M
    TIME_FLOOR("__time", 'PT1M') AS "dt_1min",^M
    STDDEV_POP ("XXXXXXXX_Speed")            AS std_1min^M
FROM "test"^M
GROUP BY TIME_FLOOR("__time", 'PT1M')^M
ORDER BY TIME_FLOOR("__time", 'PT1M')) LIMIT 5000', resultFormat=ARRAY, header=true, context={}}
org.apache.calcite.tools.ValidationException: org.apache.calcite.runtime.CalciteContextException: From line 3, column 5 to line 3, column 33: No match found for function signature STDDEV_POP(<NUMERIC>)
    at org.apache.calcite.prepare.PlannerImpl.validate(PlannerImpl.java:190) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.druid.sql.calcite.planner.DruidPlanner.plan(DruidPlanner.java:85) ~[druid-sql-0.15.1-incubating.jar:0.15.1-incubating]
    at org.apache.druid.sql.SqlLifecycle.plan(SqlLifecycle.java:143) ~[druid-sql-0.15.1-incubating.jar:0.15.1-incubating]
    at org.apache.druid.sql.SqlLifecycle.plan(SqlLifecycle.java:154) ~[druid-sql-0.15.1-incubating.jar:0.15.1-incubating]
    at org.apache.druid.sql.SqlLifecycle.planAndAuthorize(SqlLifecycle.java:220) ~[druid-sql-0.15.1-incubating.jar:0.15.1-incubating]
    at org.apache.druid.sql.http.SqlResource.doPost(SqlResource.java:91) [druid-sql-0.15.1-incubating.jar:0.15.1-incubating]
    at sun.reflect.GeneratedMethodAccessor61.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
    at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60) [jersey-server-1.19.3.jar:1.19.3]
    at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205) [jersey-server-1.19.3.jar:1.19.3]
    at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75) [jersey-server-1.19.3.jar:1.19.3]
    at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302) [jersey-server-1.19.3.jar:1.19.3]
    at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108) [jersey-server-1.19.3.jar:1.19.3]
    at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) [jersey-server-1.19.3.jar:1.19.3]
    at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84) [jersey-server-1.19.3.jar:1.19.3]
    at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542) [jersey-server-1.19.3.jar:1.19.3]
    at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473) [jersey-server-1.19.3.jar:1.19.3]
    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419) [jersey-server-1.19.3.jar:1.19.3]
    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409) [jersey-server-1.19.3.jar:1.19.3]
    at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409) [jersey-servlet-1.19.3.jar:1.19.3]
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558) [jersey-servlet-1.19.3.jar:1.19.3]
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733) [jersey-servlet-1.19.3.jar:1.19.3]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [javax.servlet-api-3.1.0.jar:3.1.0]
    at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:286) [guice-servlet-4.1.0.jar:?]
    at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:276) [guice-servlet-4.1.0.jar:?]
    at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:181) [guice-servlet-4.1.0.jar:?]
    at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91) [guice-servlet-4.1.0.jar:?]
    at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85) [guice-servlet-4.1.0.jar:?]
    at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120) [guice-servlet-4.1.0.jar:?]
    at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135) [guice-servlet-4.1.0.jar:?]
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642) [jetty-servlet-9.4.10.v20180503.jar:9.4.10.v20180503]
    at org.apache.druid.server.security.PreResponseAuthorizationCheckFilter.doFilter(PreResponseAuthorizationCheckFilter.java:82) [druid-server-0.15.1-incubating.jar:0.15.1-incubating]
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642) [jetty-servlet-9.4.10.v20180503.jar:9.4.10.v20180503]
    at org.apache.druid.server.security.AllowOptionsResourceFilter.doFilter(AllowOptionsResourceFilter.java:75) [druid-server-0.15.1-incubating.jar:0.15.1-incubating]
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642) [jetty-servlet-9.4.10.v20180503.jar:9.4.10.v20180503]
    at org.apache.druid.server.security.AllowAllAuthenticator$1.doFilter(AllowAllAuthenticator.java:84) [druid-server-0.15.1-incubating.jar:0.15.1-incubating]
    at org.apache.druid.server.security.AuthenticationWrappingFilter.doFilter(AuthenticationWrappingFilter.java:59) [druid-server-0.15.1-incubating.jar:0.15.1-incubating]
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642) [jetty-servlet-9.4.10.v20180503.jar:9.4.10.v20180503]
    at org.apache.druid.server.security.SecuritySanityCheckFilter.doFilter(SecuritySanityCheckFilter.java:86) [druid-server-0.15.1-incubating.jar:0.15.1-incubating]
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642) [jetty-servlet-9.4.10.v20180503.jar:9.4.10.v20180503]
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533) [jetty-servlet-9.4.10.v20180503.jar:9.4.10.v20180503]
    at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
    at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
    at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473) [jetty-servlet-9.4.10.v20180503.jar:9.4.10.v20180503]
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
    at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
    at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:724) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
    at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:169) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
    at org.eclipse.jetty.server.Server.handle(Server.java:531) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260) [jetty-server-9.4.10.v20180503.jar:9.4.10.v20180503]
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281) [jetty-io-9.4.10.v20180503.jar:9.4.10.v20180503]
    at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102) [jetty-io-9.4.10.v20180503.jar:9.4.10.v20180503]
    at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118) [jetty-io-9.4.10.v20180503.jar:9.4.10.v20180503]
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
    at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:760) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:678) [jetty-util-9.4.10.v20180503.jar:9.4.10.v20180503]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: org.apache.calcite.runtime.CalciteContextException: From line 3, column 5 to line 3, column 33: No match found for function signature STDDEV_POP(<NUMERIC>)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_181]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_181]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_181]
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_181]
    at org.apache.calcite.runtime.Resources$ExInstWithCause.ex(Resources.java:463) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:783) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:768) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.validate.SqlValidatorImpl.newValidationError(SqlValidatorImpl.java:4759) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.validate.SqlValidatorImpl.handleUnresolvedFunction(SqlValidatorImpl.java:1711) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.SqlFunction.deriveType(SqlFunction.java:270) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.SqlFunction.deriveType(SqlFunction.java:215) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.validate.SqlValidatorImpl$DeriveTypeVisitor.visit(SqlValidatorImpl.java:5483) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.validate.SqlValidatorImpl$DeriveTypeVisitor.visit(SqlValidatorImpl.java:5470) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.SqlCall.accept(SqlCall.java:138) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.validate.SqlValidatorImpl.deriveTypeImpl(SqlValidatorImpl.java:1629) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.validate.SqlValidatorImpl.deriveType(SqlValidatorImpl.java:1614) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.SqlAsOperator.deriveType(SqlAsOperator.java:133) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.validate.SqlValidatorImpl$DeriveTypeVisitor.visit(SqlValidatorImpl.java:5483) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.validate.SqlValidatorImpl$DeriveTypeVisitor.visit(SqlValidatorImpl.java:5470) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.SqlCall.accept(SqlCall.java:138) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.validate.SqlValidatorImpl.deriveTypeImpl(SqlValidatorImpl.java:1629) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.validate.SqlValidatorImpl.deriveType(SqlValidatorImpl.java:1614) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.validate.SqlValidatorImpl.expandSelectItem(SqlValidatorImpl.java:457) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.validate.SqlValidatorImpl.validateSelectList(SqlValidatorImpl.java:4023) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.validate.SqlValidatorImpl.validateSelect(SqlValidatorImpl.java:3286) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.validate.SelectNamespace.validateImpl(SelectNamespace.java:60) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.validate.AbstractNamespace.validate(AbstractNamespace.java:84) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.validate.SqlValidatorImpl.validateNamespace(SqlValidatorImpl.java:967) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.validate.SqlValidatorImpl.validateQuery(SqlValidatorImpl.java:943) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.validate.SqlValidatorImpl.validateFrom(SqlValidatorImpl.java:3029) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.validate.SqlValidatorImpl.validateFrom(SqlValidatorImpl.java:3014) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.validate.SqlValidatorImpl.validateSelect(SqlValidatorImpl.java:3273) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.validate.SelectNamespace.validateImpl(SelectNamespace.java:60) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.validate.AbstractNamespace.validate(AbstractNamespace.java:84) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.validate.SqlValidatorImpl.validateNamespace(SqlValidatorImpl.java:967) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.validate.SqlValidatorImpl.validateQuery(SqlValidatorImpl.java:943) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.SqlSelect.validate(SqlSelect.java:225) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.validate.SqlValidatorImpl.validateScopedExpression(SqlValidatorImpl.java:918) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.validate.SqlValidatorImpl.validate(SqlValidatorImpl.java:628) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.prepare.PlannerImpl.validate(PlannerImpl.java:188) ~[calcite-core-1.17.0.jar:1.17.0]
    ... 69 more
Caused by: org.apache.calcite.sql.validate.SqlValidatorException: No match found for function signature STDDEV_POP(<NUMERIC>)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_181]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_181]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_181]
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_181]
    at org.apache.calcite.runtime.Resources$ExInstWithCause.ex(Resources.java:463) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.runtime.Resources$ExInst.ex(Resources.java:572) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:783) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:768) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.validate.SqlValidatorImpl.newValidationError(SqlValidatorImpl.java:4759) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.validate.SqlValidatorImpl.handleUnresolvedFunction(SqlValidatorImpl.java:1711) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.SqlFunction.deriveType(SqlFunction.java:270) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.SqlFunction.deriveType(SqlFunction.java:215) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.validate.SqlValidatorImpl$DeriveTypeVisitor.visit(SqlValidatorImpl.java:5483) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.validate.SqlValidatorImpl$DeriveTypeVisitor.visit(SqlValidatorImpl.java:5470) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.SqlCall.accept(SqlCall.java:138) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.validate.SqlValidatorImpl.deriveTypeImpl(SqlValidatorImpl.java:1629) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.validate.SqlValidatorImpl.deriveType(SqlValidatorImpl.java:1614) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.SqlAsOperator.deriveType(SqlAsOperator.java:133) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.validate.SqlValidatorImpl$DeriveTypeVisitor.visit(SqlValidatorImpl.java:5483) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.validate.SqlValidatorImpl$DeriveTypeVisitor.visit(SqlValidatorImpl.java:5470) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.SqlCall.accept(SqlCall.java:138) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.validate.SqlValidatorImpl.deriveTypeImpl(SqlValidatorImpl.java:1629) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.validate.SqlValidatorImpl.deriveType(SqlValidatorImpl.java:1614) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.validate.SqlValidatorImpl.expandSelectItem(SqlValidatorImpl.java:457) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.validate.SqlValidatorImpl.validateSelectList(SqlValidatorImpl.java:4023) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.validate.SqlValidatorImpl.validateSelect(SqlValidatorImpl.java:3286) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.validate.SelectNamespace.validateImpl(SelectNamespace.java:60) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.validate.AbstractNamespace.validate(AbstractNamespace.java:84) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.validate.SqlValidatorImpl.validateNamespace(SqlValidatorImpl.java:967) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.validate.SqlValidatorImpl.validateQuery(SqlValidatorImpl.java:943) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.validate.SqlValidatorImpl.validateFrom(SqlValidatorImpl.java:3029) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.validate.SqlValidatorImpl.validateFrom(SqlValidatorImpl.java:3014) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.validate.SqlValidatorImpl.validateSelect(SqlValidatorImpl.java:3273) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.validate.SelectNamespace.validateImpl(SelectNamespace.java:60) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.validate.AbstractNamespace.validate(AbstractNamespace.java:84) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.validate.SqlValidatorImpl.validateNamespace(SqlValidatorImpl.java:967) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.validate.SqlValidatorImpl.validateQuery(SqlValidatorImpl.java:943) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.SqlSelect.validate(SqlSelect.java:225) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.validate.SqlValidatorImpl.validateScopedExpression(SqlValidatorImpl.java:918) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.sql.validate.SqlValidatorImpl.validate(SqlValidatorImpl.java:628) ~[calcite-core-1.17.0.jar:1.17.0]
    at org.apache.calcite.prepare.PlannerImpl.validate(PlannerImpl.java:188) ~[calcite-core-1.17.0.jar:1.17.0]
    ... 69 more
```

**Comment by wch661** [comment]
I found out why：
https://github.com/apache/incubator-druid/releases#stats
