### ISSUE TITLE
Could not able to use segment-dump tool - SQLAuditManagerConfig was already configured error

### ISSUE THREAD

**Issue by shadeeka** [apache/incubator-druid#8997]
### Affected Version
druid 0.13.0

### Description
Unable to use druid **tools dump-segment** to dump the segment data

- Cluster size - dev environment
- Configurations in use - default configurations
- Steps to reproduce the problem - run following command 

java -classpath "./lib/*" org.apache.druid.cli.Main tools dump-segment --directory /opt/apache-druid-0.15/var/druid/segments/ds1_analytics --out ~/output.txt

```
2019-12-06T14:30:00,140 WARN [main] org.apache.hadoop.util.NativeCodeLoader - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Exception in thread "main" com.google.inject.CreationException: Unable to create injector, see the following errors:

1) A binding to com.google.common.base.Supplier<org.apache.druid.server.audit.SQLAuditManagerConfig> was already configured at org.apache.druid.guice.JsonConfigProvider.bind(JsonConfigProvider.java:133) (via modules: com.google.inject.util.Modules$OverrideModule -> org.apache.druid.metadata.storage.mysql.MySQLMetadataStorageModule).
  at org.apache.druid.guice.JsonConfigProvider.bind(JsonConfigProvider.java:133) (via modules: com.google.inject.util.Modules$OverrideModule -> org.apache.druid.metadata.storage.postgresql.PostgreSQLMetadataStorageModule)

2) A binding to org.apache.druid.server.audit.SQLAuditManagerConfig was already configured at org.apache.druid.guice.JsonConfigProvider.bind(JsonConfigProvider.java:134) (via modules: com.google.inject.util.Modules$OverrideModule -> org.apache.druid.metadata.storage.mysql.MySQLMetadataStorageModule).
  at org.apache.druid.guice.JsonConfigProvider.bind(JsonConfigProvider.java:134) (via modules: com.google.inject.util.Modules$OverrideModule -> org.apache.druid.metadata.storage.postgresql.PostgreSQLMetadataStorageModule)

2 errors
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
	at com.google.inject.Guice.createInjector(Guice.java:99)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at org.apache.druid.initialization.Initialization.makeInjectorWithModules(Initialization.java:419)
	at org.apache.druid.cli.GuiceRunnable.makeInjector(GuiceRunnable.java:68)
	at org.apache.druid.cli.DumpSegment.run(DumpSegment.java:169)
	at org.apache.druid.cli.Main.main(Main.java:118)
```

**Comment by ccaominh** [comment]
Can you try explicitly specifying the extension load list? For example:
```
java -classpath "lib/*" -Ddruid.extensions.loadList="[]" org.apache.druid.cli.Main tools dump-segment --directory /opt/apache-druid-0.15/var/druid/segments/ds1_analytics --out ~/output.txt
```
