### ISSUE TITLE
Broken master because of duplicate injection

### ISSUE THREAD

**Issue by jihoonson** [apache/incubator-druid#9002]
### Affected Version

Current master

### Description

Here is the error on start up. Maybe it only happens with coordinator + overlord mode.

```
1) A binding to org.apache.druid.discovery.NodeRole annotated with interface org.apache.druid.guice.annotations.Self was already configured at org.apache.druid.cli.CliCoordinator$1.configure(CliCoordinator.java:242) (via modules: com.google.inject.util.Modules$Override
Module -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.cli.CliCoordinator$1).
  at org.apache.druid.cli.CliOverlord$1.configure(CliOverlord.java:251) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.cli.CliOverlord$1)

1 error
        at org.apache.druid.cli.GuiceRunnable.makeInjector(GuiceRunnable.java:72)
        at org.apache.druid.cli.ServerRunnable.run(ServerRunnable.java:56)
        at org.apache.druid.cli.Main.main(Main.java:113)
Caused by: com.google.inject.CreationException: Unable to create injector, see the following errors:

1) A binding to org.apache.druid.discovery.NodeRole annotated with interface org.apache.druid.guice.annotations.Self was already configured at org.apache.druid.cli.CliCoordinator$1.configure(CliCoordinator.java:242) (via modules: com.google.inject.util.Modules$Override
Module -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.cli.CliCoordinator$1).
  at org.apache.druid.cli.CliOverlord$1.configure(CliOverlord.java:251) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.cli.CliOverlord$1)

1 error
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
        at com.google.inject.Guice.createInjector(Guice.java:99)
        at com.google.inject.Guice.createInjector(Guice.java:73)
        at com.google.inject.Guice.createInjector(Guice.java:62)
        at org.apache.druid.initialization.Initialization.makeInjectorWithModules(Initialization.java:431)
        at org.apache.druid.cli.GuiceRunnable.makeInjector(GuiceRunnable.java:69)
        ... 2 more
```

**Comment by jihoonson** [comment]
Looks like this was caused by https://github.com/apache/incubator-druid/pull/6702/files#diff-8306af8ad09532617fa5a47941bc81b8R242. Should it be the multibinding?
